-- Generated by bloomery — do not edit.
-- fingerprint: blm1:2b6372ca8b47ba0246a75ad73d731f63e525b4dd7b4879016523384377857a62
MODEL (
  name gold.dim_date,
  kind FULL,
  grain (date_day)
);

SELECT
  CAST(date_day AS DATE) AS date_day,
  CAST(DATE_TRUNC(date_day, MONTH) AS DATE) AS date_month,
  CAST(DATE_TRUNC(date_day, QUARTER) AS DATE) AS date_quarter,
  CAST(DATE_TRUNC(date_day, WEEK) AS DATE) AS date_week,
  CAST(DATE_TRUNC(date_day, YEAR) AS DATE) AS date_year
FROM UNNEST(
  GENERATE_DATE_ARRAY(CAST('2020-01-01' AS DATE), CAST('2030-12-31' AS DATE), INTERVAL 1 DAY)
) AS date_day
