-- Generated by bloomery — do not edit.
-- fingerprint: blm1:095f45236eac5adb4dcdb8940d1d623dd69b6dd84b6ed894f94bfd42626ceb6e
AUDIT (
  name item_net_price_reconcile
);

SELECT * FROM @this_model WHERE net_price IS DISTINCT FROM net_price__direct
