-- Generated by bloomery — do not edit.
-- fingerprint: blm1:a4f1ad14b1ec3576132d7c2306b05977dc784ec5af768eb474c0f8e9ad45010f
AUDIT (
  name item_net_price_reconcile
);

SELECT * FROM @this_model WHERE net_price IS DISTINCT FROM net_price__direct
