-- Generated by bloomery — do not edit.
-- fingerprint: blm1:20ba2742b0ffb14ed00bc3fbf1ba32c635694ef7d6e885d396f715f2df8ea644
AUDIT (
  name item_net_price_reconcile
);

SELECT * FROM @this_model WHERE net_price IS DISTINCT FROM net_price__direct
