-- Generated by bloomery — do not edit.
-- fingerprint: blm1:db71c82c730ada3d407064906b3bb39332c2809d5465152dd4598a36e9b4f0b2
AUDIT (
  name item_key_unique
);

SELECT
  _entity.order_id,
  _entity.line_no,
  COUNT(*) AS key_rows
FROM @this_model AS _entity
GROUP BY
  _entity.order_id,
  _entity.line_no
HAVING
  COUNT(*) > 1
