-- Generated by bloomery — do not edit.
-- fingerprint: blm1:d92aab877db7d27b81247c668f2119a5def5f9dda65e17959abfcdb686f67513
AUDIT (
  name item_key_unique
);

SELECT
  _entity.order_id,
  _entity.line_no,
  COUNT(*) AS key_rows
FROM @this_model AS _entity
GROUP BY
  _entity.order_id,
  _entity.line_no
HAVING
  COUNT(*) > 1
