-- Generated by bloomery — do not edit.
-- fingerprint: blm1:20ba2742b0ffb14ed00bc3fbf1ba32c635694ef7d6e885d396f715f2df8ea644
AUDIT (
  name item_key_unique
);

SELECT
  _entity.order_id,
  _entity.line_no,
  COUNT(*) AS key_rows
FROM @this_model AS _entity
GROUP BY
  _entity.order_id,
  _entity.line_no
HAVING
  COUNT(*) > 1
