-- Generated by bloomery — do not edit.
-- fingerprint: blm1:ac52aca8f8d8dc43a35455b7d4af96f435769aae7c2ff86798b2b269a2ac0f8f
-- The disjointness law (S-0041/what-is-refused-at-run-time) as a runtime audit: a union merge
-- requires the sources' key sets to be disjoint, and the compiler has no data
-- to establish it with. Blocking, and not configurable to a weaker
-- disposition (D5) — a key in two sources is either genuine duplication or a
-- shared key space by accident, and both are refusals. Flagging it would let a
-- double-counted entity into the warehouse marked merely suspect.
AUDIT (
  name item_source_collision
);

SELECT
  order_id,
  line_no,
  COUNT(DISTINCT _source) AS sources
FROM (
  SELECT
    CAST(position AS BIGINT) AS line_no,
    CAST(total / quantity AS DECIMAL(12, 4)) AS net_price,
    CAST(price AS DECIMAL(12, 4)) AS net_price__direct,
    CAST(order_ref AS TEXT) AS order_id,
    CAST(quantity AS BIGINT) AS quantity,
    'shopify__items' AS _source
  FROM bronze.shopify__items
  UNION ALL
  SELECT
    CAST(item_index AS BIGINT) AS line_no,
    CAST(line_gross / qty AS DECIMAL(12, 4)) AS net_price,
    CAST(unit_amount AS DECIMAL(12, 4)) AS net_price__direct,
    CAST(order_number AS TEXT) AS order_id,
    CAST(qty AS BIGINT) AS quantity,
    'woo__items' AS _source
  FROM bronze.woo__items
) AS _entity
GROUP BY
  order_id,
  line_no
HAVING
  COUNT(DISTINCT _source) > 1
