-- Generated by bloomery — do not edit.
-- fingerprint: blm1:c8ce09807a3a09504ca62810d0adf4bc290ee856e56a34dbbb2e0b4735703ede
{{ config(severity='warn') }}

SELECT
  COUNT(_mart.amount) AS value
FROM {{ ref('mart_lines') }} AS _mart
HAVING
  COUNT(_mart.amount) < 1
