-- Generated by bloomery — do not edit.
-- fingerprint: blm1:8c7f4ff4be9cf5560c876e4592768a1024e5f8d389022966beedc556625f397f
{{ config(severity='warn') }}

SELECT
  *
FROM {{ ref('line_amount_matches_row__reconcile') }}
WHERE
  NOT within_tolerance
