-- Generated by bloomery — do not edit.
-- fingerprint: blm1:2800e6f1e8f5e39e12898fc2abc06df1f66919228ef6df297c9dbdee7420fd53
{{ config(severity='warn') }}

SELECT
  *
FROM {{ ref('line_amount_matches_row__reconcile') }}
WHERE
  NOT within_tolerance
