-- Generated by bloomery — do not edit.
-- fingerprint: blm1:00cb4f3ae310113de186acdcbd34966cb33af65e1696b7e5c476dd363ed4bd97
{{ config(severity='warn') }}

SELECT
  *
FROM {{ ref('line_amount_matches_row__reconcile') }}
WHERE
  NOT within_tolerance
