-- Generated by bloomery — do not edit.
-- fingerprint: blm1:a36b238f2199ee250aec2b50bb59065021a032604f5b62100ca31d6f611049ad
{{ config(severity='error') }}

SELECT
  *
FROM {{ ref('line_amount_matches_row_blocking__reconcile') }}
WHERE
  NOT within_tolerance
