-- Generated by bloomery — do not edit.
-- fingerprint: blm1:b5bf2fa542b0b18f51126e0eb175da99d6abaf964d79e6634a7a4d57439d08e2
{{ config(severity='error') }}

SELECT
  _mart.ordered_month,
  SUM(_mart.amount) AS value
FROM {{ ref('mart_lines') }} AS _mart
GROUP BY
  _mart.ordered_month
HAVING
  SUM(_mart.amount) < 0.000000001
