-- Generated by bloomery — do not edit.
-- fingerprint: blm1:00cb4f3ae310113de186acdcbd34966cb33af65e1696b7e5c476dd363ed4bd97
{{ config(severity='warn') }}

SELECT
  COUNT(_mart.amount) AS value
FROM {{ ref('mart_lines') }} AS _mart
HAVING
  COUNT(_mart.amount) < 1
