-- Generated by bloomery — do not edit.
-- fingerprint: blm1:b4add99c38382c6751d4a778a027591302424af4ec91a386cf7803d507b57719
{{ config(severity='error') }}

SELECT
  _mart.ordered_month,
  SUM(_mart.amount) AS value
FROM {{ ref('mart_lines') }} AS _mart
GROUP BY
  _mart.ordered_month
HAVING
  SUM(_mart.amount) < 0.000000001
