-- Generated by bloomery — do not edit.
-- fingerprint: blm1:67d84e8a9daea9f3c76f94d0fb6bb21d0ca6ea29389524c152b66a910f51418f
{{ config(severity='error') }}

SELECT
  *
FROM {{ ref('line_amount_matches_row_blocking__reconcile') }}
WHERE
  NOT within_tolerance
