-- Generated by bloomery — do not edit.
-- fingerprint: blm1:b7a7f4c151717de912753ea1a222889d35d1486e8d740edb7348e55b8f4bd96a
{{ config(severity='error') }}

SELECT
  _mart.ordered_month,
  SUM(_mart.amount) AS value
FROM {{ ref('mart_lines') }} AS _mart
GROUP BY
  _mart.ordered_month
HAVING
  SUM(_mart.amount) < 0.000000001
