-- Generated by bloomery — do not edit.
-- fingerprint: blm1:4a9d76c9acea051e3af977607fe19312545a656c041515d11d437495532c42e6
{{ config(severity='warn') }}

SELECT
  COUNT(_mart.amount) AS value
FROM {{ ref('mart_lines') }} AS _mart
HAVING
  COUNT(_mart.amount) < 1
