-- Generated by bloomery — do not edit.
-- fingerprint: blm1:b4add99c38382c6751d4a778a027591302424af4ec91a386cf7803d507b57719
{{ config(severity='error') }}

SELECT
  _entity.code_id,
  COUNT(*) AS key_rows
FROM {{ ref('q_code') }} AS _entity
GROUP BY
  _entity.code_id
HAVING
  COUNT(*) > 1
