-- Generated by bloomery — do not edit.
-- fingerprint: blm1:9a4b81ebd2a91fc32c1ca72c41d825c8fbae9ebdb85d83d00b020b96a280b9b3
{{ config(severity='error') }}

WITH _survivors AS (
  SELECT
    CASE WHEN PG_INPUT_IS_VALID(group_id, 'TEXT') THEN CAST(group_id AS TEXT) END AS group_id,
    CASE WHEN PG_INPUT_IS_VALID(note, 'TEXT') THEN CAST(note AS TEXT) END AS note,
    CASE WHEN PG_INPUT_IS_VALID(status, 'TEXT') THEN CAST(status AS TEXT) END AS status,
    _ingested_at,
    _load_id,
    _source_row_id,
    CASE WHEN PG_INPUT_IS_VALID(group_id, 'TEXT') THEN CAST(group_id AS TEXT) END IS NULL
    AND (
      NOT group_id IS NULL
    ) AS _branch_group_id_coercible,
    CASE WHEN PG_INPUT_IS_VALID(note, 'TEXT') THEN CAST(note AS TEXT) END IS NULL
    AND (
      NOT note IS NULL
    ) AS _branch_note_coercible,
    CASE WHEN PG_INPUT_IS_VALID(status, 'TEXT') THEN CAST(status AS TEXT) END IS NULL
    AND (
      NOT status IS NULL
    ) AS _branch_status_coercible
  FROM {{ source('bronze', 'q__dups') }}
)
SELECT
  *
FROM (
  SELECT
    COUNT(*) AS surviving_rows,
    SUM(
      CASE
        WHEN COALESCE(
          (
            _survivors._branch_group_id_coercible
            OR _survivors._branch_status_coercible
            OR (
              NOT _survivors.status IN ('open', 'closed')
            )
          ),
          FALSE
        )
        THEN 1
        ELSE 0
      END
    ) AS diverted_rows,
    (
      SELECT
        COUNT(*)
      FROM {{ source('bronze', 'q__dups') }}
    ) AS bronze_rows,
    (
      SELECT
        COUNT(*)
      FROM {{ ref('q_dup') }} AS _entity
      WHERE
        _entity._source_row_id IN (
          SELECT
            _source_row_id
          FROM _survivors
        )
    ) AS entity_rows
  FROM _survivors
) AS _conservation
WHERE
  entity_rows + diverted_rows <> surviving_rows
