-- Generated by bloomery — do not edit.
-- fingerprint: blm1:b5bf2fa542b0b18f51126e0eb175da99d6abaf964d79e6634a7a4d57439d08e2
{{ config(severity='error') }}

SELECT
  *
FROM (
  SELECT
    *,
    COUNT(*) OVER (PARTITION BY _source_row_id) AS _row_id_count
  FROM {{ ref('q_line') }}
) AS _metadata
WHERE
  _ingested_at IS NULL
  OR _load_id IS NULL
  OR _source_row_id IS NULL
  OR _row_id_count > 1
  OR (
    (
      NOT _ingested_at IS NULL
    )
    AND CASE
      WHEN PG_INPUT_IS_VALID(
        CASE
          WHEN SUBSTRING(CAST(_ingested_at AS VARCHAR) FROM 11) LIKE '%+%'
          OR SUBSTRING(CAST(_ingested_at AS VARCHAR) FROM 11) LIKE '%-%'
          THEN NULL
          ELSE _ingested_at
        END,
        'TIMESTAMP'
      )
      AND NOT LOWER(
        CASE
          WHEN SUBSTRING(CAST(_ingested_at AS VARCHAR) FROM 11) LIKE '%+%'
          OR SUBSTRING(CAST(_ingested_at AS VARCHAR) FROM 11) LIKE '%-%'
          THEN NULL
          ELSE _ingested_at
        END
      ) ~ '^[[:space:]]*(now|today|tomorrow|yesterday)[[:space:]]*$'
      THEN CAST(CASE
        WHEN SUBSTRING(CAST(_ingested_at AS VARCHAR) FROM 11) LIKE '%+%'
        OR SUBSTRING(CAST(_ingested_at AS VARCHAR) FROM 11) LIKE '%-%'
        THEN NULL
        ELSE _ingested_at
      END AS TIMESTAMP)
    END IS NULL
  )
