-- Generated by bloomery — do not edit.
-- fingerprint: blm1:098fa50992c83bcbc383225902ba829aef87359d914a966a7790e11c5bf886ab
{{ config(materialized='table') }}

SELECT
  CAST(id AS TEXT) AS address_id,
  CAST(city AS TEXT) AS city,
  CAST(state AS TEXT) AS state,
  CAST(ARRAY[] AS TEXT[]) AS _quality_flags,
  TRUE AS _quality_ok
FROM {{ source('bronze', 'src__addresses') }}
