-- Generated by bloomery — do not edit.
-- fingerprint: blm1:29108e9e9b438ef664c0babbc7aab37d5963b2d2d1f3799b48c6e9ce579917cb
{{ config(materialized='table') }}

SELECT
  CAST(id AS TEXT) AS address_id,
  CAST(city AS TEXT) AS city,
  CAST(state AS TEXT) AS state,
  CAST(ARRAY[] AS TEXT[]) AS _quality_flags,
  TRUE AS _quality_ok
FROM {{ source('bronze', 'src__addresses') }}
