-- Generated by bloomery — do not edit.
-- fingerprint: blm1:7246c36935034179235dd882752046760be5363a8df12afb8b64127989d42389
{{ config(materialized='table') }}

SELECT
  CAST(id AS TEXT) AS address_id,
  CAST(city AS TEXT) AS city,
  CAST(state AS TEXT) AS state,
  CAST(ARRAY[] AS TEXT[]) AS _quality_flags,
  TRUE AS _quality_ok
FROM {{ source('bronze', 'src__addresses') }}
