-- Generated by bloomery — do not edit.
-- fingerprint: blm1:4aa879a0d07f7796fc657c3a13953f682a63ca425f542567961a29fe86887f96
{{ config(materialized='table') }}

SELECT
  CAST(amount AS DECIMAL(12, 4)) AS amount,
  CAST(bill AS TEXT) AS bill_to_id,
  CAST(od AS DATE) AS order_date,
  CAST(id AS TEXT) AS order_id,
  CAST(ship AS TEXT) AS ship_to_id,
  CAST(ARRAY[] AS TEXT[]) AS _quality_flags,
  TRUE AS _quality_ok
FROM {{ source('bronze', 'src__orders') }}
