-- Generated by bloomery — do not edit.
-- fingerprint: blm1:7490943b15797cd5baeb85396fef60a08a90295e30e831513965e189e2fbe114
{{ config(severity='error') }}

SELECT
  order_id,
  line_no,
  COUNT(DISTINCT _source) AS sources
FROM {{ ref('order_line') }} AS _entity
GROUP BY
  order_id,
  line_no
HAVING
  COUNT(DISTINCT _source) > 1
