-- Generated by bloomery — do not edit.
-- fingerprint: blm1:312a029cdfe71aaa59431815ce7393aebc6de8e212cc9dc3ebcbb5ec24a81535
{{ config(severity='error') }}

SELECT
  _entity.order_id,
  _entity.line_no,
  COUNT(*) AS key_rows
FROM {{ ref('order_line') }} AS _entity
GROUP BY
  _entity.order_id,
  _entity.line_no
HAVING
  COUNT(*) > 1
