-- Generated by bloomery — do not edit.
-- fingerprint: blm1:be67e6f17b9d2d709e6c53bb2dfd4898aebd3c335890baaaed083a735595bd37
{{ config(severity='error') }}

SELECT
  order_id,
  line_no,
  COUNT(DISTINCT _source) AS sources
FROM {{ ref('order_line') }} AS _entity
GROUP BY
  order_id,
  line_no
HAVING
  COUNT(DISTINCT _source) > 1
