-- Generated by bloomery — do not edit.
-- fingerprint: blm1:4498353cb377f6bf0a96dc71428260f08d44ea7eafaa307ebc949837153fa87b
AUDIT (
  name order_line_ingestion_metadata
);

SELECT
  *
FROM (
  SELECT
    *,
    COUNT(*) OVER (PARTITION BY _source, _source_row_id) AS _row_id_count
  FROM @this_model
) AS _metadata
WHERE
  _ingested_at IS NULL
  OR _load_id IS NULL
  OR _source_row_id IS NULL
  OR _row_id_count > 1
  OR (
    (
      NOT _ingested_at IS NULL
    )
    AND TRY_CAST(CASE
      WHEN SUBSTRING(CAST(_ingested_at AS TEXT), 11) LIKE '%+%'
      OR SUBSTRING(CAST(_ingested_at AS TEXT), 11) LIKE '%-%'
      THEN NULL
      ELSE REPLACE(REPLACE(CAST(_ingested_at AS TEXT), 'T', ' '), 't', ' ')
    END AS TIMESTAMP) IS NULL
  )
