-- Generated by bloomery — do not edit.
-- fingerprint: blm1:58a6195ae0c81f71e97bb9f469bc9cbc1dfed8462b51297838ef5093af565158
-- The conservation law (RFC 0016 §6) as a runtime audit: every bronze row
-- lands in exactly one of the entity, an unresolved reject, or the deduped
-- count. Blocking — a row in neither side of the split has been silently
-- dropped, which is the failure this package exists to make impossible.
AUDIT (
  name order_line_conservation
);

WITH _survivors AS (
  SELECT
    *
  FROM (
    SELECT
      TRY_CAST(properties ->> '$.gift_note' AS TEXT) AS gift_note,
      TRY_CAST(position AS BIGINT) AS line_no,
      TRY_CAST("order" ->> '$.id' AS TEXT) AS order_id,
      TRY_CAST(created_at AS TIMESTAMP) AS placed_at,
      TRY_CAST(quantity AS BIGINT) AS quantity,
      TRY_CAST(variant ->> '$.sku' AS TEXT) AS sku,
      CASE TRY_CAST(financial_status AS TEXT)
        WHEN 'pending'
        THEN 'open'
        WHEN 'paid'
        THEN 'closed'
        WHEN 'refunded'
        THEN 'reversed'
        ELSE TRY_CAST(financial_status AS TEXT)
      END AS status,
      _ingested_at,
      _load_id,
      _source_row_id,
      TRY_CAST(properties ->> '$.gift_note' AS TEXT) IS NULL
      AND (
        NOT (
          properties ->> '$.gift_note'
        ) IS NULL
      ) AS _branch_gift_note_coercible,
      TRY_CAST(position AS BIGINT) IS NULL AND (
        NOT position IS NULL
      ) AS _branch_line_no_coercible,
      TRY_CAST("order" ->> '$.id' AS TEXT) IS NULL
      AND (
        NOT (
          "order" ->> '$.id'
        ) IS NULL
      ) AS _branch_order_id_coercible,
      TRY_CAST(created_at AS TIMESTAMP) IS NULL AND (
        NOT created_at IS NULL
      ) AS _branch_placed_at_coercible,
      TRY_CAST(quantity AS BIGINT) IS NULL AND (
        NOT quantity IS NULL
      ) AS _branch_quantity_coercible,
      TRY_CAST(variant ->> '$.sku' AS TEXT) IS NULL
      AND (
        NOT (
          variant ->> '$.sku'
        ) IS NULL
      ) AS _branch_sku_coercible,
      CASE TRY_CAST(financial_status AS TEXT)
        WHEN 'pending'
        THEN 'open'
        WHEN 'paid'
        THEN 'closed'
        WHEN 'refunded'
        THEN 'reversed'
        ELSE TRY_CAST(financial_status AS TEXT)
      END IS NULL
      AND (
        NOT financial_status IS NULL
      ) AS _branch_status_coercible,
      NOT CASE TRY_CAST(financial_status AS TEXT)
        WHEN 'pending'
        THEN 'open'
        WHEN 'paid'
        THEN 'closed'
        WHEN 'refunded'
        THEN 'reversed'
        ELSE TRY_CAST(financial_status AS TEXT)
      END IN ('closed', 'open', 'reversed') AS _branch_status_in_enum,
      'shopify__order_lines' AS _source
    FROM bronze.shopify__order_lines
    UNION ALL
    SELECT
      CAST(NULL AS TEXT) AS gift_note,
      TRY_CAST(item_index AS BIGINT) AS line_no,
      TRY_CAST(order_number AS TEXT) AS order_id,
      TRY_CAST(created AS TIMESTAMP) AS placed_at,
      TRY_CAST(qty AS BIGINT) AS quantity,
      TRY_CAST(product_sku AS TEXT) AS sku,
      CASE TRY_CAST(state AS TEXT)
        WHEN 'PROCESSING'
        THEN 'open'
        WHEN 'COMPLETE'
        THEN 'closed'
        ELSE TRY_CAST(state AS TEXT)
      END AS status,
      _ingested_at,
      _load_id,
      _source_row_id,
      FALSE AS _branch_gift_note_coercible,
      TRY_CAST(item_index AS BIGINT) IS NULL AND (
        NOT item_index IS NULL
      ) AS _branch_line_no_coercible,
      TRY_CAST(order_number AS TEXT) IS NULL AND (
        NOT order_number IS NULL
      ) AS _branch_order_id_coercible,
      TRY_CAST(created AS TIMESTAMP) IS NULL AND (
        NOT created IS NULL
      ) AS _branch_placed_at_coercible,
      TRY_CAST(qty AS BIGINT) IS NULL AND (
        NOT qty IS NULL
      ) AS _branch_quantity_coercible,
      TRY_CAST(product_sku AS TEXT) IS NULL AND (
        NOT product_sku IS NULL
      ) AS _branch_sku_coercible,
      CASE TRY_CAST(state AS TEXT)
        WHEN 'PROCESSING'
        THEN 'open'
        WHEN 'COMPLETE'
        THEN 'closed'
        ELSE TRY_CAST(state AS TEXT)
      END IS NULL
      AND (
        NOT state IS NULL
      ) AS _branch_status_coercible,
      NOT CASE TRY_CAST(state AS TEXT)
        WHEN 'PROCESSING'
        THEN 'open'
        WHEN 'COMPLETE'
        THEN 'closed'
        ELSE TRY_CAST(state AS TEXT)
      END IN ('closed', 'open') AS _branch_status_in_enum,
      'woo__order_lines' AS _source
    FROM bronze.woo__order_lines
  ) AS _extract
  QUALIFY
    ROW_NUMBER() OVER (
      PARTITION BY order_id, line_no
      ORDER BY placed_at DESC, line_no DESC, _source DESC, _source_row_id DESC
    ) = 1
)
SELECT
  *
FROM (
  SELECT
    COUNT(*) AS surviving_rows,
    SUM(
      CASE
        WHEN COALESCE(
          (
            _survivors._branch_gift_note_coercible
            OR _survivors._branch_order_id_coercible
            OR _survivors._branch_quantity_coercible
            OR _survivors._branch_sku_coercible
            OR _survivors._branch_status_coercible
            OR _survivors._branch_status_in_enum
          ),
          FALSE
        )
        THEN 1
        ELSE 0
      END
    ) AS diverted_rows,
    (
      SELECT
        COUNT(*)
      FROM bronze.shopify__order_lines
    ) + (
      SELECT
        COUNT(*)
      FROM bronze.woo__order_lines
    ) AS bronze_rows,
    (
      SELECT
        COUNT(*)
      FROM @this_model AS _entity
      WHERE
        (_entity._source, _entity._source_row_id) IN (
          SELECT
            _source,
            _source_row_id
          FROM _survivors
        )
    ) AS entity_rows
  FROM _survivors
) AS _conservation
WHERE
  entity_rows + diverted_rows <> surviving_rows
