-- Generated by bloomery — do not edit.
-- fingerprint: blm1:7e13158538dc1cca9c8cccd1a62fbe39b95f5edf7ea8bae3b7ef1d9facb8c7f7
MODEL (
  name gold.mart_data_quality,
  kind FULL,
  grain (entity, rule)
);

WITH _quality_rows_order_line AS (
  SELECT
    _quality_flags AS _flags,
    FALSE AS _quarantined
  FROM silver.order_line
  UNION ALL
  SELECT
    failed_rules AS _flags,
    TRUE AS _quarantined
  FROM silver.order_line__reject
  WHERE
    resolved_at IS NULL
)
SELECT
  _stamped.disposition,
  _stamped.entity,
  _stamped.mapping,
  _stamped.rows_deduped,
  _stamped.rows_evaluated,
  _stamped.rows_failed,
  _stamped.rows_quarantined,
  _stamped.rule,
  _stamped.run_date,
  CAST(DATE_TRUNC('DAY', _stamped.run_date) AS DATE) AS run_day,
  _stamped.run_id,
  CAST(DATE_TRUNC('MONTH', _stamped.run_date) AS DATE) AS run_month,
  CAST(DATE_TRUNC('QUARTER', _stamped.run_date) AS DATE) AS run_quarter,
  CAST(DATE_TRUNC('WEEK', _stamped.run_date) AS DATE) AS run_week,
  CAST(DATE_TRUNC('YEAR', _stamped.run_date) AS DATE) AS run_year
FROM (
  SELECT
    _evaluations.entity,
    _evaluations.mapping,
    _evaluations.rule,
    _evaluations.disposition,
    _evaluations.rows_evaluated,
    _evaluations.rows_failed,
    _evaluations.rows_quarantined,
    _evaluations.rows_deduped,
    CAST(NULL AS TEXT) AS run_id, /* run_id: supplied by the executing engine's run context (RFC 0016 §5.8); the pinned target exposes no macro for it — fill this column in your runner */
    CAST(@execution_ds AS DATE) AS run_date
  FROM (
    SELECT
      'order_line' AS entity,
      'shopify__order_lines+woo__order_lines->order_line' AS mapping,
      '(entity)' AS rule,
      '(entity)' AS disposition,
      COUNT(*) AS rows_evaluated,
      0 AS rows_failed,
      COALESCE(SUM(CASE WHEN _quarantined THEN 1 ELSE 0 END), 0) AS rows_quarantined,
      (
        SELECT
          COUNT(*)
        FROM (
          SELECT
            TRY_CAST(properties ->> '$.gift_note' AS TEXT) AS gift_note,
            TRY_CAST(position AS BIGINT) AS line_no,
            TRY_CAST("order" ->> '$.id' AS TEXT) AS order_id,
            TRY_CAST(created_at AS TIMESTAMP) AS placed_at,
            TRY_CAST(quantity AS BIGINT) AS quantity,
            TRY_CAST(variant ->> '$.sku' AS TEXT) AS sku,
            CASE TRY_CAST(financial_status AS TEXT)
              WHEN 'pending'
              THEN 'open'
              WHEN 'paid'
              THEN 'closed'
              ELSE TRY_CAST(financial_status AS TEXT)
            END AS status,
            _ingested_at,
            _load_id,
            _source_row_id,
            TRY_CAST(properties ->> '$.gift_note' AS TEXT) IS NULL
            AND (
              NOT (
                properties ->> '$.gift_note'
              ) IS NULL
            ) AS _branch_gift_note_coercible,
            TRY_CAST(position AS BIGINT) IS NULL AND (
              NOT position IS NULL
            ) AS _branch_line_no_coercible,
            TRY_CAST("order" ->> '$.id' AS TEXT) IS NULL
            AND (
              NOT (
                "order" ->> '$.id'
              ) IS NULL
            ) AS _branch_order_id_coercible,
            TRY_CAST(created_at AS TIMESTAMP) IS NULL AND (
              NOT created_at IS NULL
            ) AS _branch_placed_at_coercible,
            TRY_CAST(quantity AS BIGINT) IS NULL AND (
              NOT quantity IS NULL
            ) AS _branch_quantity_coercible,
            TRY_CAST(variant ->> '$.sku' AS TEXT) IS NULL
            AND (
              NOT (
                variant ->> '$.sku'
              ) IS NULL
            ) AS _branch_sku_coercible,
            CASE TRY_CAST(financial_status AS TEXT)
              WHEN 'pending'
              THEN 'open'
              WHEN 'paid'
              THEN 'closed'
              ELSE TRY_CAST(financial_status AS TEXT)
            END IS NULL
            AND (
              NOT financial_status IS NULL
            ) AS _branch_status_coercible,
            NOT CASE TRY_CAST(financial_status AS TEXT)
              WHEN 'pending'
              THEN 'open'
              WHEN 'paid'
              THEN 'closed'
              ELSE TRY_CAST(financial_status AS TEXT)
            END IN ('closed', 'open') AS _branch_status_in_enum,
            'shopify__order_lines' AS _source,
            SHA256(
              'S20:shopify__order_lines' || 'S' || CAST(LENGTH(_source_row_id) AS TEXT) || ':' || _source_row_id
            ) AS reject_id,
            'shopify__order_lines' AS source_relation,
            'shopify__order_lines->order_line' AS mapping,
            1 AS mapping_version
          FROM bronze.shopify__order_lines
          UNION ALL
          SELECT
            CAST(NULL AS TEXT) AS gift_note,
            TRY_CAST(item_index AS BIGINT) AS line_no,
            TRY_CAST(order_number AS TEXT) AS order_id,
            TRY_CAST(created AS TIMESTAMP) AS placed_at,
            TRY_CAST(qty AS BIGINT) AS quantity,
            TRY_CAST(product_sku AS TEXT) AS sku,
            CASE TRY_CAST(state AS TEXT)
              WHEN 'PROCESSING'
              THEN 'open'
              WHEN 'COMPLETE'
              THEN 'closed'
              ELSE TRY_CAST(state AS TEXT)
            END AS status,
            _ingested_at,
            _load_id,
            _source_row_id,
            FALSE AS _branch_gift_note_coercible,
            TRY_CAST(item_index AS BIGINT) IS NULL AND (
              NOT item_index IS NULL
            ) AS _branch_line_no_coercible,
            TRY_CAST(order_number AS TEXT) IS NULL AND (
              NOT order_number IS NULL
            ) AS _branch_order_id_coercible,
            TRY_CAST(created AS TIMESTAMP) IS NULL AND (
              NOT created IS NULL
            ) AS _branch_placed_at_coercible,
            TRY_CAST(qty AS BIGINT) IS NULL AND (
              NOT qty IS NULL
            ) AS _branch_quantity_coercible,
            TRY_CAST(product_sku AS TEXT) IS NULL AND (
              NOT product_sku IS NULL
            ) AS _branch_sku_coercible,
            CASE TRY_CAST(state AS TEXT)
              WHEN 'PROCESSING'
              THEN 'open'
              WHEN 'COMPLETE'
              THEN 'closed'
              ELSE TRY_CAST(state AS TEXT)
            END IS NULL
            AND (
              NOT state IS NULL
            ) AS _branch_status_coercible,
            NOT CASE TRY_CAST(state AS TEXT)
              WHEN 'PROCESSING'
              THEN 'open'
              WHEN 'COMPLETE'
              THEN 'closed'
              ELSE TRY_CAST(state AS TEXT)
            END IN ('closed', 'open') AS _branch_status_in_enum,
            'woo__order_lines' AS _source,
            SHA256(
              'S16:woo__order_lines' || 'S' || CAST(LENGTH(_source_row_id) AS TEXT) || ':' || _source_row_id
            ) AS reject_id,
            'woo__order_lines' AS source_relation,
            'woo__order_lines->order_line' AS mapping,
            1 AS mapping_version
          FROM bronze.woo__order_lines
        ) AS _bronze
      ) - (
        SELECT
          COUNT(*)
        FROM (
          SELECT
            *
          FROM (
            SELECT
              TRY_CAST(properties ->> '$.gift_note' AS TEXT) AS gift_note,
              TRY_CAST(position AS BIGINT) AS line_no,
              TRY_CAST("order" ->> '$.id' AS TEXT) AS order_id,
              TRY_CAST(created_at AS TIMESTAMP) AS placed_at,
              TRY_CAST(quantity AS BIGINT) AS quantity,
              TRY_CAST(variant ->> '$.sku' AS TEXT) AS sku,
              CASE TRY_CAST(financial_status AS TEXT)
                WHEN 'pending'
                THEN 'open'
                WHEN 'paid'
                THEN 'closed'
                ELSE TRY_CAST(financial_status AS TEXT)
              END AS status,
              _ingested_at,
              _load_id,
              _source_row_id,
              TRY_CAST(properties ->> '$.gift_note' AS TEXT) IS NULL
              AND (
                NOT (
                  properties ->> '$.gift_note'
                ) IS NULL
              ) AS _branch_gift_note_coercible,
              TRY_CAST(position AS BIGINT) IS NULL AND (
                NOT position IS NULL
              ) AS _branch_line_no_coercible,
              TRY_CAST("order" ->> '$.id' AS TEXT) IS NULL
              AND (
                NOT (
                  "order" ->> '$.id'
                ) IS NULL
              ) AS _branch_order_id_coercible,
              TRY_CAST(created_at AS TIMESTAMP) IS NULL AND (
                NOT created_at IS NULL
              ) AS _branch_placed_at_coercible,
              TRY_CAST(quantity AS BIGINT) IS NULL AND (
                NOT quantity IS NULL
              ) AS _branch_quantity_coercible,
              TRY_CAST(variant ->> '$.sku' AS TEXT) IS NULL
              AND (
                NOT (
                  variant ->> '$.sku'
                ) IS NULL
              ) AS _branch_sku_coercible,
              CASE TRY_CAST(financial_status AS TEXT)
                WHEN 'pending'
                THEN 'open'
                WHEN 'paid'
                THEN 'closed'
                ELSE TRY_CAST(financial_status AS TEXT)
              END IS NULL
              AND (
                NOT financial_status IS NULL
              ) AS _branch_status_coercible,
              NOT CASE TRY_CAST(financial_status AS TEXT)
                WHEN 'pending'
                THEN 'open'
                WHEN 'paid'
                THEN 'closed'
                ELSE TRY_CAST(financial_status AS TEXT)
              END IN ('closed', 'open') AS _branch_status_in_enum,
              'shopify__order_lines' AS _source,
              SHA256(
                'S20:shopify__order_lines' || 'S' || CAST(LENGTH(_source_row_id) AS TEXT) || ':' || _source_row_id
              ) AS reject_id,
              'shopify__order_lines' AS source_relation,
              'shopify__order_lines->order_line' AS mapping,
              1 AS mapping_version
            FROM bronze.shopify__order_lines
            UNION ALL
            SELECT
              CAST(NULL AS TEXT) AS gift_note,
              TRY_CAST(item_index AS BIGINT) AS line_no,
              TRY_CAST(order_number AS TEXT) AS order_id,
              TRY_CAST(created AS TIMESTAMP) AS placed_at,
              TRY_CAST(qty AS BIGINT) AS quantity,
              TRY_CAST(product_sku AS TEXT) AS sku,
              CASE TRY_CAST(state AS TEXT)
                WHEN 'PROCESSING'
                THEN 'open'
                WHEN 'COMPLETE'
                THEN 'closed'
                ELSE TRY_CAST(state AS TEXT)
              END AS status,
              _ingested_at,
              _load_id,
              _source_row_id,
              FALSE AS _branch_gift_note_coercible,
              TRY_CAST(item_index AS BIGINT) IS NULL AND (
                NOT item_index IS NULL
              ) AS _branch_line_no_coercible,
              TRY_CAST(order_number AS TEXT) IS NULL AND (
                NOT order_number IS NULL
              ) AS _branch_order_id_coercible,
              TRY_CAST(created AS TIMESTAMP) IS NULL AND (
                NOT created IS NULL
              ) AS _branch_placed_at_coercible,
              TRY_CAST(qty AS BIGINT) IS NULL AND (
                NOT qty IS NULL
              ) AS _branch_quantity_coercible,
              TRY_CAST(product_sku AS TEXT) IS NULL AND (
                NOT product_sku IS NULL
              ) AS _branch_sku_coercible,
              CASE TRY_CAST(state AS TEXT)
                WHEN 'PROCESSING'
                THEN 'open'
                WHEN 'COMPLETE'
                THEN 'closed'
                ELSE TRY_CAST(state AS TEXT)
              END IS NULL
              AND (
                NOT state IS NULL
              ) AS _branch_status_coercible,
              NOT CASE TRY_CAST(state AS TEXT)
                WHEN 'PROCESSING'
                THEN 'open'
                WHEN 'COMPLETE'
                THEN 'closed'
                ELSE TRY_CAST(state AS TEXT)
              END IN ('closed', 'open') AS _branch_status_in_enum,
              'woo__order_lines' AS _source,
              SHA256(
                'S16:woo__order_lines' || 'S' || CAST(LENGTH(_source_row_id) AS TEXT) || ':' || _source_row_id
              ) AS reject_id,
              'woo__order_lines' AS source_relation,
              'woo__order_lines->order_line' AS mapping,
              1 AS mapping_version
            FROM bronze.woo__order_lines
          ) AS _extract
          QUALIFY
            ROW_NUMBER() OVER (
              PARTITION BY order_id, line_no
              ORDER BY placed_at DESC, line_no DESC, _source DESC, _source_row_id DESC
            ) = 1
        ) AS _extract
      ) AS rows_deduped
    FROM _quality_rows_order_line
    UNION ALL
    SELECT
      'order_line' AS entity,
      'shopify__order_lines+woo__order_lines->order_line' AS mapping,
      'gift_note_coercible' AS rule,
      'quarantine' AS disposition,
      0 AS rows_evaluated,
      COALESCE(SUM(CASE WHEN ARRAY_CONTAINS(_flags, 'gift_note_coercible') THEN 1 ELSE 0 END), 0) AS rows_failed,
      0 AS rows_quarantined,
      0 AS rows_deduped
    FROM _quality_rows_order_line
    UNION ALL
    SELECT
      'order_line' AS entity,
      'shopify__order_lines+woo__order_lines->order_line' AS mapping,
      'line_no_coercible' AS rule,
      'fail' AS disposition,
      0 AS rows_evaluated,
      COALESCE(SUM(CASE WHEN ARRAY_CONTAINS(_flags, 'line_no_coercible') THEN 1 ELSE 0 END), 0) AS rows_failed,
      0 AS rows_quarantined,
      0 AS rows_deduped
    FROM _quality_rows_order_line
    UNION ALL
    SELECT
      'order_line' AS entity,
      'shopify__order_lines+woo__order_lines->order_line' AS mapping,
      'order_id_coercible' AS rule,
      'quarantine' AS disposition,
      0 AS rows_evaluated,
      COALESCE(SUM(CASE WHEN ARRAY_CONTAINS(_flags, 'order_id_coercible') THEN 1 ELSE 0 END), 0) AS rows_failed,
      0 AS rows_quarantined,
      0 AS rows_deduped
    FROM _quality_rows_order_line
    UNION ALL
    SELECT
      'order_line' AS entity,
      'shopify__order_lines+woo__order_lines->order_line' AS mapping,
      'placed_at_coercible' AS rule,
      'fail' AS disposition,
      0 AS rows_evaluated,
      COALESCE(SUM(CASE WHEN ARRAY_CONTAINS(_flags, 'placed_at_coercible') THEN 1 ELSE 0 END), 0) AS rows_failed,
      0 AS rows_quarantined,
      0 AS rows_deduped
    FROM _quality_rows_order_line
    UNION ALL
    SELECT
      'order_line' AS entity,
      'shopify__order_lines+woo__order_lines->order_line' AS mapping,
      'quantity_coercible' AS rule,
      'quarantine' AS disposition,
      0 AS rows_evaluated,
      COALESCE(SUM(CASE WHEN ARRAY_CONTAINS(_flags, 'quantity_coercible') THEN 1 ELSE 0 END), 0) AS rows_failed,
      0 AS rows_quarantined,
      0 AS rows_deduped
    FROM _quality_rows_order_line
    UNION ALL
    SELECT
      'order_line' AS entity,
      'shopify__order_lines+woo__order_lines->order_line' AS mapping,
      'sku_coercible' AS rule,
      'quarantine' AS disposition,
      0 AS rows_evaluated,
      COALESCE(SUM(CASE WHEN ARRAY_CONTAINS(_flags, 'sku_coercible') THEN 1 ELSE 0 END), 0) AS rows_failed,
      0 AS rows_quarantined,
      0 AS rows_deduped
    FROM _quality_rows_order_line
    UNION ALL
    SELECT
      'order_line' AS entity,
      'shopify__order_lines+woo__order_lines->order_line' AS mapping,
      'status_coercible' AS rule,
      'quarantine' AS disposition,
      0 AS rows_evaluated,
      COALESCE(SUM(CASE WHEN ARRAY_CONTAINS(_flags, 'status_coercible') THEN 1 ELSE 0 END), 0) AS rows_failed,
      0 AS rows_quarantined,
      0 AS rows_deduped
    FROM _quality_rows_order_line
    UNION ALL
    SELECT
      'order_line' AS entity,
      'shopify__order_lines+woo__order_lines->order_line' AS mapping,
      'status_in_enum' AS rule,
      'quarantine' AS disposition,
      0 AS rows_evaluated,
      COALESCE(SUM(CASE WHEN ARRAY_CONTAINS(_flags, 'status_in_enum') THEN 1 ELSE 0 END), 0) AS rows_failed,
      0 AS rows_quarantined,
      0 AS rows_deduped
    FROM _quality_rows_order_line
  ) AS _evaluations
) AS _stamped
