-- Generated by bloomery — do not edit.
-- fingerprint: blm1:c63e5f8d5a9a3ed8654688ca3ae0126803dc498e332e44fa3b493a01cabc3785
MODEL (
  name gold.dim_date,
  kind FULL,
  grain (date_day)
);

SELECT
  CAST(date_day AS DATE) AS date_day,
  CAST(DATE_TRUNC('MONTH', date_day) AS DATE) AS date_month,
  CAST(DATE_TRUNC('QUARTER', date_day) AS DATE) AS date_quarter,
  CAST(DATE_TRUNC('WEEK', date_day) AS DATE) AS date_week,
  CAST(DATE_TRUNC('YEAR', date_day) AS DATE) AS date_year
FROM GENERATE_SERIES(CAST('2020-01-01' AS DATE), CAST('2030-12-31' AS DATE), INTERVAL '1 DAY') AS date_day(date_day)
