-- Generated by bloomery — do not edit.
-- fingerprint: blm1:4003b506211d40a682f8e1d2e46a7931600b4046770843fb4e20ff43b68d6f3e
MODEL (
  name silver.order,
  kind FULL,
  grain (order_id)
);

SELECT
  CAST(amount AS DECIMAL(12, 4)) AS amount,
  CAST(order_date AS DATE) AS order_date,
  CAST(id AS TEXT) AS order_id,
  CAST(ship_date AS DATE) AS ship_date,
  CAST(ARRAY[] AS TEXT[]) AS _quality_flags,
  TRUE AS _quality_ok
FROM bronze.oms__orders
