-- Generated by bloomery — do not edit.
-- fingerprint: blm1:117ea9bea4006da79e6881929e55c2bad2116bc02e1245fda82572bd1f17de3d
MODEL (
  name silver.order,
  kind FULL,
  grain (order_id)
);

SELECT
  CAST(amount AS DECIMAL(12, 4)) AS amount,
  CAST(order_date AS DATE) AS order_date,
  CAST(id AS TEXT) AS order_id,
  CAST(ship_date AS DATE) AS ship_date,
  CAST(ARRAY[] AS TEXT[]) AS _quality_flags,
  TRUE AS _quality_ok
FROM bronze.oms__orders
