-- Generated by bloomery — do not edit.
-- fingerprint: blm1:594ae31595470e666c9b924745023a2828319bc5021c0417be9aeb7a1d9c0f77
MODEL (
  name silver.order,
  kind FULL,
  grain (order_id)
);

SELECT
  CAST(amount AS DECIMAL(12, 4)) AS amount,
  CAST(order_date AS DATE) AS order_date,
  CAST(id AS TEXT) AS order_id,
  CAST(ship_date AS DATE) AS ship_date,
  CAST(ARRAY[] AS TEXT[]) AS _quality_flags,
  TRUE AS _quality_ok
FROM bronze.oms__orders
