-- Generated by bloomery — do not edit.
-- fingerprint: blm1:2b0407511db7b688fffbf442b3f162f4c44f5e49581680834e3db1ef2ae7b4a8
MODEL (
  name silver.item,
  kind FULL,
  grain (item_id),
  audits (item_net_price_reconcile)
);

SELECT
  CAST(id AS TEXT) AS item_id,
  CAST(total / qty AS DECIMAL(12, 4)) AS net_price,
  CAST(price AS DECIMAL(12, 4)) AS net_price__direct,
  CAST(qty AS BIGINT) AS quantity,
  CAST([] AS TEXT[]) AS _quality_flags,
  TRUE AS _quality_ok
FROM bronze.shop__items
