-- Generated by bloomery — do not edit.
-- fingerprint: blm1:4e07e0a0eea5da90640d97b8e0d655ea6b3c0a633824698eb244766f7b7399bf
MODEL (
  name silver.item,
  kind FULL,
  grain (item_id),
  audits (item_key_unique, item_net_price_reconcile)
);

SELECT
  CAST(id AS TEXT) AS item_id,
  CAST(CAST(total AS DECIMAL(33, 4)) / qty AS DECIMAL(12, 4)) AS net_price,
  CAST(price AS DECIMAL(12, 4)) AS net_price__direct,
  CAST(qty AS BIGINT) AS quantity,
  CAST([] AS TEXT[]) AS _quality_flags,
  TRUE AS _quality_ok
FROM bronze.shop__items
