-- Generated by bloomery — do not edit.
-- fingerprint: blm1:2b4af481c63f555c2c3b9b9bd56f2bb69547c4d89ece277ad20afaa9c4218e03
MODEL (
  name silver.item,
  kind FULL,
  grain (item_id),
  audits (item_key_unique, item_net_price_reconcile)
);

SELECT
  CAST(id AS TEXT) AS item_id,
  CAST(CAST(total AS DECIMAL(12, 4)) / qty AS DECIMAL(12, 4)) AS net_price,
  CAST(price AS DECIMAL(12, 4)) AS net_price__direct,
  CAST(qty AS BIGINT) AS quantity,
  CAST([] AS TEXT[]) AS _quality_flags,
  TRUE AS _quality_ok
FROM bronze.shop__items
