-- Generated by bloomery — do not edit.
-- fingerprint: blm1:e6dbe4b79e508dede765a1173a992746bfe5edd9651b767732b94b72b70c204a
MODEL (
  name silver.order,
  kind FULL,
  grain (order_id)
);

SELECT
  CAST(customer_id AS TEXT) AS customer_id,
  CAST(id AS TEXT) AS order_id,
  CAST([] AS TEXT[]) AS _quality_flags,
  TRUE AS _quality_ok
FROM bronze.shop__orders
