-- Generated by bloomery — do not edit.
-- fingerprint: blm1:f08fc2ecdb327ef3d3cb465ef3d694be3071044eb6fc14d986f22e99ba91cf6f
MODEL (
  name silver.order,
  kind FULL,
  grain (order_id),
  audits (order_key_unique)
);

SELECT
  CAST(customer_id AS TEXT) AS customer_id,
  CAST(id AS TEXT) AS order_id,
  CAST([] AS TEXT[]) AS _quality_flags,
  TRUE AS _quality_ok
FROM bronze.shop__orders
