-- Generated by bloomery — do not edit.
-- fingerprint: blm1:bdaf583ef2a2ee6226471ca65bbe82fa77b0bc581fb923ee038cf2543dd8e201
MODEL (
  name silver.order,
  kind FULL,
  grain (order_id)
);

SELECT
  CAST(customer_id AS TEXT) AS customer_id,
  CAST(id AS TEXT) AS order_id,
  CAST([] AS TEXT[]) AS _quality_flags,
  TRUE AS _quality_ok
FROM bronze.shop__orders
