-- Generated by bloomery — do not edit.
-- fingerprint: blm1:09079a16099d256611c868da5d7b85b93da43b1e02d15b8bd4dc36af6056b11a
MODEL (
  name silver.order,
  kind FULL,
  grain (order_id)
);

SELECT
  CAST(customer ->> '$.id' AS TEXT) AS customer_id,
  CAST(id AS TEXT) AS order_id
FROM bronze.shopify__orders
