-- Generated by bloomery — do not edit.
-- fingerprint: blm1:b83989759b62fdb330e65aa39684a4c9bafa92479224459cf42a791535d698d9
MODEL (
  name silver.order_item,
  kind INCREMENTAL_BY_TIME_RANGE (time_column order_date),
  grain (order_id, line_no),
  partitioned_by (days(order_date)),
  audits (not_null(columns := (order_date)))
);

SELECT
  CAST(index AS BIGINT) AS line_no,
  CAST(created_at AS TIMESTAMP) AT TIME ZONE 'Europe/Paris' AS order_date,
  CAST(order_id AS TEXT) AS order_id,
  CAST(qty AS BIGINT) AS quantity,
  CAST(total / qty AS DECIMAL(12, 4)) AS unit_price
FROM bronze.shopify__order_lines
