-- Generated by bloomery — do not edit.
-- fingerprint: blm1:12331bd66d37c46211c9e8d4f1f0a1990e87374826973d906258b17d855b2cf7
MODEL (
  name silver.order,
  kind FULL,
  owner 'commerce-platform@example.com',
  grain (order_id)
);

SELECT
  CAST(customer ->> '$.id' AS TEXT) AS customer_id,
  CAST(id AS TEXT) AS order_id,
  CAST([] AS TEXT[]) AS _quality_flags,
  TRUE AS _quality_ok
FROM bronze.shopify__orders
