-- Generated by bloomery — do not edit.
-- fingerprint: blm1:b466cb8ce46bb2149cba8a536cccc6af94ba1d98cd1437c0455e5f522c357190
{{ config(materialized='table') }}

WITH _left AS (
  SELECT
    order_id,
    line_no,
    SUM(amount) AS left_value
  FROM {{ ref('q_line') }}
  GROUP BY
    order_id,
    line_no
), _right AS (
  SELECT
    order_id,
    line_no,
    amount AS right_value
  FROM {{ ref('q_line') }}
), _keys AS (
  SELECT
    _left.line_no,
    _left.order_id
  FROM _left
  UNION
  SELECT
    _right.line_no,
    _right.order_id
  FROM _right
)
SELECT
  _keys.order_id,
  _keys.line_no,
  _left.left_value,
  _right.right_value,
  ABS(_left.left_value - _right.right_value) AS difference,
  COALESCE(ABS(_left.left_value - _right.right_value) <= 1E-9, FALSE) AS within_tolerance
FROM _keys
LEFT JOIN _left
  ON _keys.line_no IS NOT DISTINCT FROM _left.line_no
  AND _keys.order_id IS NOT DISTINCT FROM _left.order_id
LEFT JOIN _right
  ON _keys.line_no IS NOT DISTINCT FROM _right.line_no
  AND _keys.order_id IS NOT DISTINCT FROM _right.order_id
