-- Generated by bloomery — do not edit.
-- fingerprint: blm1:b5bf2fa542b0b18f51126e0eb175da99d6abaf964d79e6634a7a4d57439d08e2
{{ config(materialized='table') }}

SELECT
  _evaluated.code_fail,
  _evaluated.code_flag,
  _evaluated.code_id,
  _evaluated.code_quar,
  _evaluated._ingested_at,
  _evaluated._load_id,
  _evaluated._source_row_id,
  _evaluated._quality_flags,
  COALESCE(ARRAY_LENGTH(_evaluated._quality_flags, 1), 0) = 0 AS _quality_ok
FROM (
  SELECT
    _extract.code_fail,
    _extract.code_flag,
    _extract.code_id,
    _extract.code_quar,
    _extract._ingested_at,
    _extract._load_id,
    _extract._source_row_id,
    ARRAY_CAT(
      CASE
        WHEN _extract._win_code_fail_unique
        THEN ARRAY['code_fail_unique']
        ELSE CAST(ARRAY[] AS TEXT[])
      END,
      CASE
        WHEN _extract._win_code_flag_unique
        THEN ARRAY['code_flag_unique']
        ELSE CAST(ARRAY[] AS TEXT[])
      END
    ) AS _quality_flags
  FROM (
    SELECT
      *,
      (
        COUNT(*) OVER (PARTITION BY code_fail) > 1 AND (
          NOT code_fail IS NULL
        )
      ) AS _win_code_fail_unique,
      (
        COUNT(*) OVER (PARTITION BY code_flag) > 1 AND (
          NOT code_flag IS NULL
        )
      ) AS _win_code_flag_unique,
      (
        COUNT(*) OVER (PARTITION BY code_quar) > 1 AND (
          NOT code_quar IS NULL
        )
      ) AS _win_code_quar_unique
    FROM (
      SELECT
        CASE WHEN PG_INPUT_IS_VALID(code_fail, 'TEXT') THEN CAST(code_fail AS TEXT) END AS code_fail,
        CASE WHEN PG_INPUT_IS_VALID(code_flag, 'TEXT') THEN CAST(code_flag AS TEXT) END AS code_flag,
        CASE WHEN PG_INPUT_IS_VALID(code_id, 'TEXT') THEN CAST(code_id AS TEXT) END AS code_id,
        CASE WHEN PG_INPUT_IS_VALID(code_quar, 'TEXT') THEN CAST(code_quar AS TEXT) END AS code_quar,
        _ingested_at,
        _load_id,
        _source_row_id,
        CASE WHEN PG_INPUT_IS_VALID(code_fail, 'TEXT') THEN CAST(code_fail AS TEXT) END IS NULL
        AND (
          NOT code_fail IS NULL
        ) AS _branch_code_fail_coercible,
        CASE WHEN PG_INPUT_IS_VALID(code_flag, 'TEXT') THEN CAST(code_flag AS TEXT) END IS NULL
        AND (
          NOT code_flag IS NULL
        ) AS _branch_code_flag_coercible,
        CASE WHEN PG_INPUT_IS_VALID(code_id, 'TEXT') THEN CAST(code_id AS TEXT) END IS NULL
        AND (
          NOT code_id IS NULL
        ) AS _branch_code_id_coercible,
        CASE WHEN PG_INPUT_IS_VALID(code_quar, 'TEXT') THEN CAST(code_quar AS TEXT) END IS NULL
        AND (
          NOT code_quar IS NULL
        ) AS _branch_code_quar_coercible
      FROM {{ source('bronze', 'q__codes') }}
    ) AS _deduped
  ) AS _extract
  WHERE
    NOT COALESCE(
      (
        _extract._branch_code_fail_coercible
        OR _extract._branch_code_flag_coercible
        OR _extract._branch_code_id_coercible
        OR _extract._branch_code_quar_coercible
        OR _extract._win_code_quar_unique
      ),
      FALSE
    )
) AS _evaluated
