-- Generated by bloomery — do not edit.
-- fingerprint: blm1:b5bf2fa542b0b18f51126e0eb175da99d6abaf964d79e6634a7a4d57439d08e2
{{ config(materialized='incremental', unique_key='reject_id', incremental_strategy='delete+insert') }}

{% if is_incremental() %}

SELECT
  arriving.reject_id,
  arriving.source_relation,
  arriving.mapping,
  arriving.mapping_version,
  arriving.failed_rules,
  arriving.key_values,
  arriving.raw,
  arriving._load_id,
  arriving._ingested_at,
  arriving._source_row_id,
  COALESCE(incumbent.first_seen, arriving.first_seen) AS first_seen,
  arriving.last_seen,
  arriving.resolved_at,
  COALESCE(incumbent.last_evaluated_at, arriving.last_evaluated_at) AS last_evaluated_at
FROM (
  SELECT
    _extract.reject_id,
    _extract.source_relation,
    _extract.mapping,
    _extract.mapping_version,
    ARRAY_CAT(
      ARRAY_CAT(
        ARRAY_CAT(
          CASE
            WHEN _extract._branch_group_id_coercible
            THEN ARRAY['group_id_coercible']
            ELSE CAST(ARRAY[] AS TEXT[])
          END,
          CASE
            WHEN _extract._branch_note_coercible
            THEN ARRAY['note_coercible']
            ELSE CAST(ARRAY[] AS TEXT[])
          END
        ),
        CASE
          WHEN _extract._branch_status_coercible
          THEN ARRAY['status_coercible']
          ELSE CAST(ARRAY[] AS TEXT[])
        END
      ),
      CASE
        WHEN NOT _extract.status IN ('open', 'closed')
        THEN ARRAY['status_in_set']
        ELSE CAST(ARRAY[] AS TEXT[])
      END
    ) AS failed_rules,
    JSON_BUILD_OBJECT('group_id', _extract.group_id) AS key_values,
    _extract._raw AS raw,
    _extract._load_id,
    _extract._ingested_at,
    _extract._source_row_id,
    _extract._ingested_at AS first_seen,
    _extract._ingested_at AS last_seen,
    CAST(NULL AS TIMESTAMP) AS resolved_at,
    CAST(NULL AS TIMESTAMP) AS last_evaluated_at
  FROM (
    SELECT
      CASE WHEN PG_INPUT_IS_VALID(group_id, 'TEXT') THEN CAST(group_id AS TEXT) END AS group_id,
      CASE WHEN PG_INPUT_IS_VALID(note, 'TEXT') THEN CAST(note AS TEXT) END AS note,
      CASE WHEN PG_INPUT_IS_VALID(status, 'TEXT') THEN CAST(status AS TEXT) END AS status,
      _ingested_at,
      _load_id,
      _source_row_id,
      CASE WHEN PG_INPUT_IS_VALID(group_id, 'TEXT') THEN CAST(group_id AS TEXT) END IS NULL
      AND (
        NOT group_id IS NULL
      ) AS _branch_group_id_coercible,
      CASE WHEN PG_INPUT_IS_VALID(note, 'TEXT') THEN CAST(note AS TEXT) END IS NULL
      AND (
        NOT note IS NULL
      ) AS _branch_note_coercible,
      CASE WHEN PG_INPUT_IS_VALID(status, 'TEXT') THEN CAST(status AS TEXT) END IS NULL
      AND (
        NOT status IS NULL
      ) AS _branch_status_coercible,
      JSON_BUILD_OBJECT(
        '_ingested_at',
        _ingested_at,
        '_load_id',
        _load_id,
        '_source_row_id',
        _source_row_id,
        'group_id',
        group_id,
        'note',
        note,
        'status',
        status
      ) AS _raw,
      ENCODE(
        SHA256(
          CONVERT_TO(
            'S7:q__dups' || 'S' || CAST(LENGTH(_source_row_id) AS TEXT) || ':' || _source_row_id,
            'UTF8'
          )
        ),
        'hex'
      ) AS reject_id,
      'q__dups' AS source_relation,
      'q__dups->q_dup' AS mapping,
      1 AS mapping_version
    FROM {{ source('bronze', 'q__dups') }}
  ) AS _extract
  WHERE
    COALESCE(
      (
        _extract._branch_group_id_coercible
        OR _extract._branch_status_coercible
        OR (
          NOT _extract.status IN ('open', 'closed')
        )
      ),
      FALSE
    )
) AS arriving
LEFT JOIN {{ this }} AS incumbent
  ON arriving.reject_id = incumbent.reject_id

{% else %}

SELECT
  _extract.reject_id,
  _extract.source_relation,
  _extract.mapping,
  _extract.mapping_version,
  ARRAY_CAT(
    ARRAY_CAT(
      ARRAY_CAT(
        CASE
          WHEN _extract._branch_group_id_coercible
          THEN ARRAY['group_id_coercible']
          ELSE CAST(ARRAY[] AS TEXT[])
        END,
        CASE
          WHEN _extract._branch_note_coercible
          THEN ARRAY['note_coercible']
          ELSE CAST(ARRAY[] AS TEXT[])
        END
      ),
      CASE
        WHEN _extract._branch_status_coercible
        THEN ARRAY['status_coercible']
        ELSE CAST(ARRAY[] AS TEXT[])
      END
    ),
    CASE
      WHEN NOT _extract.status IN ('open', 'closed')
      THEN ARRAY['status_in_set']
      ELSE CAST(ARRAY[] AS TEXT[])
    END
  ) AS failed_rules,
  JSON_BUILD_OBJECT('group_id', _extract.group_id) AS key_values,
  _extract._raw AS raw,
  _extract._load_id,
  _extract._ingested_at,
  _extract._source_row_id,
  _extract._ingested_at AS first_seen,
  _extract._ingested_at AS last_seen,
  CAST(NULL AS TIMESTAMP) AS resolved_at,
  CAST(NULL AS TIMESTAMP) AS last_evaluated_at
FROM (
  SELECT
    CASE WHEN PG_INPUT_IS_VALID(group_id, 'TEXT') THEN CAST(group_id AS TEXT) END AS group_id,
    CASE WHEN PG_INPUT_IS_VALID(note, 'TEXT') THEN CAST(note AS TEXT) END AS note,
    CASE WHEN PG_INPUT_IS_VALID(status, 'TEXT') THEN CAST(status AS TEXT) END AS status,
    _ingested_at,
    _load_id,
    _source_row_id,
    CASE WHEN PG_INPUT_IS_VALID(group_id, 'TEXT') THEN CAST(group_id AS TEXT) END IS NULL
    AND (
      NOT group_id IS NULL
    ) AS _branch_group_id_coercible,
    CASE WHEN PG_INPUT_IS_VALID(note, 'TEXT') THEN CAST(note AS TEXT) END IS NULL
    AND (
      NOT note IS NULL
    ) AS _branch_note_coercible,
    CASE WHEN PG_INPUT_IS_VALID(status, 'TEXT') THEN CAST(status AS TEXT) END IS NULL
    AND (
      NOT status IS NULL
    ) AS _branch_status_coercible,
    JSON_BUILD_OBJECT(
      '_ingested_at',
      _ingested_at,
      '_load_id',
      _load_id,
      '_source_row_id',
      _source_row_id,
      'group_id',
      group_id,
      'note',
      note,
      'status',
      status
    ) AS _raw,
    ENCODE(
      SHA256(
        CONVERT_TO(
          'S7:q__dups' || 'S' || CAST(LENGTH(_source_row_id) AS TEXT) || ':' || _source_row_id,
          'UTF8'
        )
      ),
      'hex'
    ) AS reject_id,
    'q__dups' AS source_relation,
    'q__dups->q_dup' AS mapping,
    1 AS mapping_version
  FROM {{ source('bronze', 'q__dups') }}
) AS _extract
WHERE
  COALESCE(
    (
      _extract._branch_group_id_coercible
      OR _extract._branch_status_coercible
      OR (
        NOT _extract.status IN ('open', 'closed')
      )
    ),
    FALSE
  )

{% endif %}
