-- Generated by bloomery — do not edit.
-- fingerprint: blm1:b5bf2fa542b0b18f51126e0eb175da99d6abaf964d79e6634a7a4d57439d08e2
{{ config(materialized='table') }}

SELECT
  _evaluated.group_id,
  _evaluated.note,
  _evaluated.status,
  _evaluated._ingested_at,
  _evaluated._load_id,
  _evaluated._source_row_id,
  _evaluated._quality_flags,
  COALESCE(ARRAY_LENGTH(_evaluated._quality_flags, 1), 0) = 0 AS _quality_ok
FROM (
  SELECT
    _extract.group_id,
    _extract.note,
    _extract.status,
    _extract._ingested_at,
    _extract._load_id,
    _extract._source_row_id,
    CASE
      WHEN _extract._branch_note_coercible
      THEN ARRAY['note_coercible']
      ELSE CAST(ARRAY[] AS TEXT[])
    END AS _quality_flags
  FROM (
    SELECT
      CASE WHEN PG_INPUT_IS_VALID(group_id, 'TEXT') THEN CAST(group_id AS TEXT) END AS group_id,
      CASE WHEN PG_INPUT_IS_VALID(note, 'TEXT') THEN CAST(note AS TEXT) END AS note,
      CASE WHEN PG_INPUT_IS_VALID(status, 'TEXT') THEN CAST(status AS TEXT) END AS status,
      _ingested_at,
      _load_id,
      _source_row_id,
      CASE WHEN PG_INPUT_IS_VALID(group_id, 'TEXT') THEN CAST(group_id AS TEXT) END IS NULL
      AND (
        NOT group_id IS NULL
      ) AS _branch_group_id_coercible,
      CASE WHEN PG_INPUT_IS_VALID(note, 'TEXT') THEN CAST(note AS TEXT) END IS NULL
      AND (
        NOT note IS NULL
      ) AS _branch_note_coercible,
      CASE WHEN PG_INPUT_IS_VALID(status, 'TEXT') THEN CAST(status AS TEXT) END IS NULL
      AND (
        NOT status IS NULL
      ) AS _branch_status_coercible
    FROM {{ source('bronze', 'q__dups') }}
  ) AS _extract
  WHERE
    NOT COALESCE(
      (
        _extract._branch_group_id_coercible
        OR _extract._branch_status_coercible
        OR (
          NOT _extract.status IN ('open', 'closed')
        )
      ),
      FALSE
    )
) AS _evaluated
