-- Generated by bloomery — do not edit.
-- fingerprint: blm1:b5bf2fa542b0b18f51126e0eb175da99d6abaf964d79e6634a7a4d57439d08e2
{{ config(materialized='table') }}

SELECT
  _evaluated.amount,
  _evaluated.code,
  _evaluated.line_no,
  _evaluated.order_date,
  _evaluated.order_id,
  _evaluated.status,
  _evaluated._ingested_at,
  _evaluated._load_id,
  _evaluated._source_row_id,
  _evaluated._quality_flags,
  COALESCE(ARRAY_LENGTH(_evaluated._quality_flags, 1), 0) = 0 AS _quality_ok
FROM (
  SELECT
    _extract.amount,
    _extract.code,
    _extract.line_no,
    _extract.order_date,
    _extract.order_id,
    _extract.status,
    _extract._ingested_at,
    _extract._load_id,
    _extract._source_row_id,
    CASE
      WHEN _extract.amount < 0
      THEN ARRAY['amount_range_min']
      ELSE CAST(ARRAY[] AS TEXT[])
    END AS _quality_flags
  FROM (
    SELECT
      *,
      (
        COUNT(*) OVER (PARTITION BY code) > 1 AND (
          NOT code IS NULL
        )
      ) AS _win_code_unique
    FROM (
      SELECT
        amount,
        code,
        line_no,
        order_date,
        order_id,
        status,
        _ingested_at,
        _load_id,
        _source_row_id,
        _branch_amount_coercible,
        _branch_code_coercible,
        _branch_line_no_coercible,
        _branch_order_date_coercible,
        _branch_order_id_coercible,
        _branch_status_coercible
      FROM (
        SELECT
          CASE
            WHEN PG_INPUT_IS_VALID(amount, 'DECIMAL(38, 9)')
            THEN CAST(amount AS DECIMAL(38, 9))
          END AS amount,
          CASE WHEN PG_INPUT_IS_VALID(code, 'TEXT') THEN CAST(code AS TEXT) END AS code,
          CASE WHEN PG_INPUT_IS_VALID(line_no, 'BIGINT') THEN CAST(line_no AS BIGINT) END AS line_no,
          CASE
            WHEN PG_INPUT_IS_VALID(order_date, 'DATE')
            AND NOT LOWER(order_date) ~ '^[[:space:]]*(now|today|tomorrow|yesterday)[[:space:]]*$'
            THEN CAST(order_date AS DATE)
          END AS order_date,
          CASE WHEN PG_INPUT_IS_VALID(order_id, 'TEXT') THEN CAST(order_id AS TEXT) END AS order_id,
          CASE WHEN PG_INPUT_IS_VALID(status, 'TEXT') THEN CAST(status AS TEXT) END AS status,
          _ingested_at,
          _load_id,
          _source_row_id,
          CASE
            WHEN PG_INPUT_IS_VALID(amount, 'DECIMAL(38, 9)')
            THEN CAST(amount AS DECIMAL(38, 9))
          END IS NULL
          AND (
            NOT amount IS NULL
          ) AS _branch_amount_coercible,
          CASE WHEN PG_INPUT_IS_VALID(code, 'TEXT') THEN CAST(code AS TEXT) END IS NULL
          AND (
            NOT code IS NULL
          ) AS _branch_code_coercible,
          CASE WHEN PG_INPUT_IS_VALID(line_no, 'BIGINT') THEN CAST(line_no AS BIGINT) END IS NULL
          AND (
            NOT line_no IS NULL
          ) AS _branch_line_no_coercible,
          CASE
            WHEN PG_INPUT_IS_VALID(order_date, 'DATE')
            AND NOT LOWER(order_date) ~ '^[[:space:]]*(now|today|tomorrow|yesterday)[[:space:]]*$'
            THEN CAST(order_date AS DATE)
          END IS NULL
          AND (
            NOT order_date IS NULL
          ) AS _branch_order_date_coercible,
          CASE WHEN PG_INPUT_IS_VALID(order_id, 'TEXT') THEN CAST(order_id AS TEXT) END IS NULL
          AND (
            NOT order_id IS NULL
          ) AS _branch_order_id_coercible,
          CASE WHEN PG_INPUT_IS_VALID(status, 'TEXT') THEN CAST(status AS TEXT) END IS NULL
          AND (
            NOT status IS NULL
          ) AS _branch_status_coercible,
          ROW_NUMBER() OVER (
            PARTITION BY CASE WHEN PG_INPUT_IS_VALID(order_id, 'TEXT') THEN CAST(order_id AS TEXT) END, CASE WHEN PG_INPUT_IS_VALID(line_no, 'BIGINT') THEN CAST(line_no AS BIGINT) END
            ORDER BY _ingested_at DESC NULLS LAST, _load_id DESC NULLS LAST, _source_row_id DESC NULLS LAST
          ) AS _w
        FROM {{ source('bronze', 'q__lines') }}
      ) AS _t
      WHERE
        _w = 1
    ) AS _deduped
  ) AS _extract
  WHERE
    NOT COALESCE(
      (
        _extract._branch_amount_coercible
        OR _extract._branch_code_coercible
        OR _extract._branch_line_no_coercible
        OR _extract._branch_order_date_coercible
        OR _extract._branch_order_id_coercible
        OR _extract._branch_status_coercible
        OR (
          NOT _extract.status IN ('open', 'closed')
        )
        OR _extract._win_code_unique
      ),
      FALSE
    )
) AS _evaluated
