-- Generated by bloomery — do not edit.
-- fingerprint: blm1:58a6195ae0c81f71e97bb9f469bc9cbc1dfed8462b51297838ef5093af565158
-- Quarantine replay for order_line (RFC 0016 §5.6). bloomery emits this
-- artifact and never executes it: run the statements below, in order, as one
-- unit of work — the passers merge, the rows that made it resolve, and the
-- rest have their failed_rules and last_seen re-stamped from the very same
-- evaluation. Winners are decided by the pipeline's own dedupe total order, so
-- re-running replay re-derives identical semantic state (D22). Retention —
-- never replay — deletes reject rows; resolved rows are kept as audit history.

MERGE INTO silver.order_line AS _target
USING (
  SELECT
    gift_note,
    line_no,
    order_id,
    placed_at,
    quantity,
    sku,
    status,
    _source,
    _ingested_at,
    _load_id,
    _source_row_id,
    _quality_flags,
    _quality_ok
  FROM (
    SELECT
      _evaluated.gift_note,
      _evaluated.line_no,
      _evaluated.order_id,
      _evaluated.placed_at,
      _evaluated.quantity,
      _evaluated.sku,
      _evaluated.status,
      _evaluated._source,
      _evaluated._ingested_at,
      _evaluated._load_id,
      _evaluated._source_row_id,
      _evaluated._quality_flags,
      ARRAY_LENGTH(_evaluated._quality_flags, 1) = 0 AS _quality_ok,
      ROW_NUMBER() OVER (
        PARTITION BY order_id, line_no
        ORDER BY placed_at DESC NULLS LAST, line_no DESC NULLS LAST, _source DESC NULLS LAST, _source_row_id DESC NULLS LAST
      ) AS _w
    FROM (
      SELECT
        _extract.gift_note,
        _extract.line_no,
        _extract.order_id,
        _extract.placed_at,
        _extract.quantity,
        _extract.sku,
        _extract.status,
        _extract._source,
        _extract._ingested_at,
        _extract._load_id,
        _extract._source_row_id,
        ARRAY_CAT(
          CASE
            WHEN _extract._branch_line_no_coercible
            THEN ARRAY['line_no_coercible']
            ELSE CAST(ARRAY[] AS TEXT[])
          END,
          CASE
            WHEN _extract._branch_placed_at_coercible
            THEN ARRAY['placed_at_coercible']
            ELSE CAST(ARRAY[] AS TEXT[])
          END
        ) AS _quality_flags
      FROM (
        SELECT
          CASE
            WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.properties') ->> 'gift_note', 'TEXT')
            THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.properties') ->> 'gift_note' AS TEXT)
          END AS gift_note,
          CASE
            WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.position'), 'BIGINT')
            THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.position') AS BIGINT)
          END AS line_no,
          CASE
            WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.order') ->> 'id', 'TEXT')
            THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.order') ->> 'id' AS TEXT)
          END AS order_id,
          CASE
            WHEN PG_INPUT_IS_VALID(
              CASE
                WHEN SUBSTRING(JSON_EXTRACT_PATH_TEXT(raw, '$.created_at') FROM 11) LIKE '%+%'
                OR SUBSTRING(JSON_EXTRACT_PATH_TEXT(raw, '$.created_at') FROM 11) LIKE '%-%'
                THEN NULL
                ELSE JSON_EXTRACT_PATH_TEXT(raw, '$.created_at')
              END,
              'TIMESTAMP'
            )
            AND NOT LOWER(
              CASE
                WHEN SUBSTRING(JSON_EXTRACT_PATH_TEXT(raw, '$.created_at') FROM 11) LIKE '%+%'
                OR SUBSTRING(JSON_EXTRACT_PATH_TEXT(raw, '$.created_at') FROM 11) LIKE '%-%'
                THEN NULL
                ELSE JSON_EXTRACT_PATH_TEXT(raw, '$.created_at')
              END
            ) ~ '^[[:space:]]*(now|today|tomorrow|yesterday)[[:space:]]*$'
            THEN CAST(CASE
              WHEN SUBSTRING(JSON_EXTRACT_PATH_TEXT(raw, '$.created_at') FROM 11) LIKE '%+%'
              OR SUBSTRING(JSON_EXTRACT_PATH_TEXT(raw, '$.created_at') FROM 11) LIKE '%-%'
              THEN NULL
              ELSE JSON_EXTRACT_PATH_TEXT(raw, '$.created_at')
            END AS TIMESTAMP)
          END AS placed_at,
          CASE
            WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.quantity'), 'BIGINT')
            THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.quantity') AS BIGINT)
          END AS quantity,
          CASE
            WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.variant') ->> 'sku', 'TEXT')
            THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.variant') ->> 'sku' AS TEXT)
          END AS sku,
          CASE CASE
              WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.financial_status'), 'TEXT')
              THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.financial_status') AS TEXT)
            END
            WHEN 'pending'
            THEN 'open'
            WHEN 'paid'
            THEN 'closed'
            WHEN 'refunded'
            THEN 'reversed'
            ELSE CASE
              WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.financial_status'), 'TEXT')
              THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.financial_status') AS TEXT)
            END
          END AS status,
          _ingested_at,
          _load_id,
          _source_row_id,
          CASE
            WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.properties') ->> 'gift_note', 'TEXT')
            THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.properties') ->> 'gift_note' AS TEXT)
          END IS NULL
          AND (
            NOT JSON_EXTRACT_PATH_TEXT(raw, '$.properties') ->> 'gift_note' IS NULL
          ) AS _branch_gift_note_coercible,
          CASE
            WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.position'), 'BIGINT')
            THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.position') AS BIGINT)
          END IS NULL
          AND (
            NOT JSON_EXTRACT_PATH_TEXT(raw, '$.position') IS NULL
          ) AS _branch_line_no_coercible,
          CASE
            WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.order') ->> 'id', 'TEXT')
            THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.order') ->> 'id' AS TEXT)
          END IS NULL
          AND (
            NOT JSON_EXTRACT_PATH_TEXT(raw, '$.order') ->> 'id' IS NULL
          ) AS _branch_order_id_coercible,
          CASE
            WHEN PG_INPUT_IS_VALID(
              CASE
                WHEN SUBSTRING(JSON_EXTRACT_PATH_TEXT(raw, '$.created_at') FROM 11) LIKE '%+%'
                OR SUBSTRING(JSON_EXTRACT_PATH_TEXT(raw, '$.created_at') FROM 11) LIKE '%-%'
                THEN NULL
                ELSE JSON_EXTRACT_PATH_TEXT(raw, '$.created_at')
              END,
              'TIMESTAMP'
            )
            AND NOT LOWER(
              CASE
                WHEN SUBSTRING(JSON_EXTRACT_PATH_TEXT(raw, '$.created_at') FROM 11) LIKE '%+%'
                OR SUBSTRING(JSON_EXTRACT_PATH_TEXT(raw, '$.created_at') FROM 11) LIKE '%-%'
                THEN NULL
                ELSE JSON_EXTRACT_PATH_TEXT(raw, '$.created_at')
              END
            ) ~ '^[[:space:]]*(now|today|tomorrow|yesterday)[[:space:]]*$'
            THEN CAST(CASE
              WHEN SUBSTRING(JSON_EXTRACT_PATH_TEXT(raw, '$.created_at') FROM 11) LIKE '%+%'
              OR SUBSTRING(JSON_EXTRACT_PATH_TEXT(raw, '$.created_at') FROM 11) LIKE '%-%'
              THEN NULL
              ELSE JSON_EXTRACT_PATH_TEXT(raw, '$.created_at')
            END AS TIMESTAMP)
          END IS NULL
          AND (
            NOT JSON_EXTRACT_PATH_TEXT(raw, '$.created_at') IS NULL
          ) AS _branch_placed_at_coercible,
          CASE
            WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.quantity'), 'BIGINT')
            THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.quantity') AS BIGINT)
          END IS NULL
          AND (
            NOT JSON_EXTRACT_PATH_TEXT(raw, '$.quantity') IS NULL
          ) AS _branch_quantity_coercible,
          CASE
            WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.variant') ->> 'sku', 'TEXT')
            THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.variant') ->> 'sku' AS TEXT)
          END IS NULL
          AND (
            NOT JSON_EXTRACT_PATH_TEXT(raw, '$.variant') ->> 'sku' IS NULL
          ) AS _branch_sku_coercible,
          CASE CASE
              WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.financial_status'), 'TEXT')
              THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.financial_status') AS TEXT)
            END
            WHEN 'pending'
            THEN 'open'
            WHEN 'paid'
            THEN 'closed'
            WHEN 'refunded'
            THEN 'reversed'
            ELSE CASE
              WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.financial_status'), 'TEXT')
              THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.financial_status') AS TEXT)
            END
          END IS NULL
          AND (
            NOT JSON_EXTRACT_PATH_TEXT(raw, '$.financial_status') IS NULL
          ) AS _branch_status_coercible,
          NOT CASE CASE
              WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.financial_status'), 'TEXT')
              THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.financial_status') AS TEXT)
            END
            WHEN 'pending'
            THEN 'open'
            WHEN 'paid'
            THEN 'closed'
            WHEN 'refunded'
            THEN 'reversed'
            ELSE CASE
              WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.financial_status'), 'TEXT')
              THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.financial_status') AS TEXT)
            END
          END IN ('closed', 'open', 'reversed') AS _branch_status_in_enum,
          'shopify__order_lines' AS _source
        FROM silver.order_line__reject
        WHERE
          resolved_at IS NULL AND source_relation = 'shopify__order_lines'
        UNION ALL
        SELECT
          CAST(NULL AS TEXT) AS gift_note,
          CASE
            WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.item_index'), 'BIGINT')
            THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.item_index') AS BIGINT)
          END AS line_no,
          CASE
            WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.order_number'), 'TEXT')
            THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.order_number') AS TEXT)
          END AS order_id,
          CASE
            WHEN PG_INPUT_IS_VALID(
              CASE
                WHEN SUBSTRING(JSON_EXTRACT_PATH_TEXT(raw, '$.created') FROM 11) LIKE '%+%'
                OR SUBSTRING(JSON_EXTRACT_PATH_TEXT(raw, '$.created') FROM 11) LIKE '%-%'
                THEN NULL
                ELSE JSON_EXTRACT_PATH_TEXT(raw, '$.created')
              END,
              'TIMESTAMP'
            )
            AND NOT LOWER(
              CASE
                WHEN SUBSTRING(JSON_EXTRACT_PATH_TEXT(raw, '$.created') FROM 11) LIKE '%+%'
                OR SUBSTRING(JSON_EXTRACT_PATH_TEXT(raw, '$.created') FROM 11) LIKE '%-%'
                THEN NULL
                ELSE JSON_EXTRACT_PATH_TEXT(raw, '$.created')
              END
            ) ~ '^[[:space:]]*(now|today|tomorrow|yesterday)[[:space:]]*$'
            THEN CAST(CASE
              WHEN SUBSTRING(JSON_EXTRACT_PATH_TEXT(raw, '$.created') FROM 11) LIKE '%+%'
              OR SUBSTRING(JSON_EXTRACT_PATH_TEXT(raw, '$.created') FROM 11) LIKE '%-%'
              THEN NULL
              ELSE JSON_EXTRACT_PATH_TEXT(raw, '$.created')
            END AS TIMESTAMP)
          END AS placed_at,
          CASE
            WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.qty'), 'BIGINT')
            THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.qty') AS BIGINT)
          END AS quantity,
          CASE
            WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.product_sku'), 'TEXT')
            THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.product_sku') AS TEXT)
          END AS sku,
          CASE CASE
              WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.state'), 'TEXT')
              THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.state') AS TEXT)
            END
            WHEN 'PROCESSING'
            THEN 'open'
            WHEN 'COMPLETE'
            THEN 'closed'
            ELSE CASE
              WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.state'), 'TEXT')
              THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.state') AS TEXT)
            END
          END AS status,
          _ingested_at,
          _load_id,
          _source_row_id,
          FALSE AS _branch_gift_note_coercible,
          CASE
            WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.item_index'), 'BIGINT')
            THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.item_index') AS BIGINT)
          END IS NULL
          AND (
            NOT JSON_EXTRACT_PATH_TEXT(raw, '$.item_index') IS NULL
          ) AS _branch_line_no_coercible,
          CASE
            WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.order_number'), 'TEXT')
            THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.order_number') AS TEXT)
          END IS NULL
          AND (
            NOT JSON_EXTRACT_PATH_TEXT(raw, '$.order_number') IS NULL
          ) AS _branch_order_id_coercible,
          CASE
            WHEN PG_INPUT_IS_VALID(
              CASE
                WHEN SUBSTRING(JSON_EXTRACT_PATH_TEXT(raw, '$.created') FROM 11) LIKE '%+%'
                OR SUBSTRING(JSON_EXTRACT_PATH_TEXT(raw, '$.created') FROM 11) LIKE '%-%'
                THEN NULL
                ELSE JSON_EXTRACT_PATH_TEXT(raw, '$.created')
              END,
              'TIMESTAMP'
            )
            AND NOT LOWER(
              CASE
                WHEN SUBSTRING(JSON_EXTRACT_PATH_TEXT(raw, '$.created') FROM 11) LIKE '%+%'
                OR SUBSTRING(JSON_EXTRACT_PATH_TEXT(raw, '$.created') FROM 11) LIKE '%-%'
                THEN NULL
                ELSE JSON_EXTRACT_PATH_TEXT(raw, '$.created')
              END
            ) ~ '^[[:space:]]*(now|today|tomorrow|yesterday)[[:space:]]*$'
            THEN CAST(CASE
              WHEN SUBSTRING(JSON_EXTRACT_PATH_TEXT(raw, '$.created') FROM 11) LIKE '%+%'
              OR SUBSTRING(JSON_EXTRACT_PATH_TEXT(raw, '$.created') FROM 11) LIKE '%-%'
              THEN NULL
              ELSE JSON_EXTRACT_PATH_TEXT(raw, '$.created')
            END AS TIMESTAMP)
          END IS NULL
          AND (
            NOT JSON_EXTRACT_PATH_TEXT(raw, '$.created') IS NULL
          ) AS _branch_placed_at_coercible,
          CASE
            WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.qty'), 'BIGINT')
            THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.qty') AS BIGINT)
          END IS NULL
          AND (
            NOT JSON_EXTRACT_PATH_TEXT(raw, '$.qty') IS NULL
          ) AS _branch_quantity_coercible,
          CASE
            WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.product_sku'), 'TEXT')
            THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.product_sku') AS TEXT)
          END IS NULL
          AND (
            NOT JSON_EXTRACT_PATH_TEXT(raw, '$.product_sku') IS NULL
          ) AS _branch_sku_coercible,
          CASE CASE
              WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.state'), 'TEXT')
              THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.state') AS TEXT)
            END
            WHEN 'PROCESSING'
            THEN 'open'
            WHEN 'COMPLETE'
            THEN 'closed'
            ELSE CASE
              WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.state'), 'TEXT')
              THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.state') AS TEXT)
            END
          END IS NULL
          AND (
            NOT JSON_EXTRACT_PATH_TEXT(raw, '$.state') IS NULL
          ) AS _branch_status_coercible,
          NOT CASE CASE
              WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.state'), 'TEXT')
              THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.state') AS TEXT)
            END
            WHEN 'PROCESSING'
            THEN 'open'
            WHEN 'COMPLETE'
            THEN 'closed'
            ELSE CASE
              WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.state'), 'TEXT')
              THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.state') AS TEXT)
            END
          END IN ('closed', 'open') AS _branch_status_in_enum,
          'woo__order_lines' AS _source
        FROM silver.order_line__reject
        WHERE
          resolved_at IS NULL AND source_relation = 'woo__order_lines'
      ) AS _extract
      WHERE
        NOT COALESCE(
          (
            _extract._branch_gift_note_coercible
            OR _extract._branch_order_id_coercible
            OR _extract._branch_quantity_coercible
            OR _extract._branch_sku_coercible
            OR _extract._branch_status_coercible
            OR _extract._branch_status_in_enum
          ),
          FALSE
        )
    ) AS _evaluated
  ) AS _t
  WHERE
    _w = 1
) AS _replay
ON _target.order_id = _replay.order_id AND _target.line_no = _replay.line_no
WHEN MATCHED AND (
  (
    (
      NOT _replay.placed_at IS NULL AND _target.placed_at IS NULL
    )
    OR (
      NOT _replay.placed_at IS NULL
      AND NOT _target.placed_at IS NULL
      AND _replay.placed_at > _target.placed_at
    )
  )
  OR (
    (
      (
        _replay.placed_at IS NULL AND _target.placed_at IS NULL
      )
      OR _replay.placed_at = _target.placed_at
    )
    AND (
      (
        (
          NOT _replay.line_no IS NULL AND _target.line_no IS NULL
        )
        OR (
          NOT _replay.line_no IS NULL
          AND NOT _target.line_no IS NULL
          AND _replay.line_no > _target.line_no
        )
      )
      OR (
        (
          (
            _replay.line_no IS NULL AND _target.line_no IS NULL
          )
          OR _replay.line_no = _target.line_no
        )
        AND (
          (
            (
              NOT _replay._source IS NULL AND _target._source IS NULL
            )
            OR (
              NOT _replay._source IS NULL
              AND NOT _target._source IS NULL
              AND _replay._source > _target._source
            )
          )
          OR (
            (
              (
                _replay._source IS NULL AND _target._source IS NULL
              )
              OR _replay._source = _target._source
            )
            AND (
              (
                NOT _replay._source_row_id IS NULL AND _target._source_row_id IS NULL
              )
              OR (
                NOT _replay._source_row_id IS NULL
                AND NOT _target._source_row_id IS NULL
                AND _replay._source_row_id > _target._source_row_id
              )
            )
          )
        )
      )
    )
  )
) THEN UPDATE SET
  gift_note = _replay.gift_note,
  placed_at = _replay.placed_at,
  quantity = _replay.quantity,
  sku = _replay.sku,
  status = _replay.status,
  _source = _replay._source,
  _ingested_at = _replay._ingested_at,
  _load_id = _replay._load_id,
  _source_row_id = _replay._source_row_id,
  _quality_flags = _replay._quality_flags,
  _quality_ok = _replay._quality_ok
WHEN NOT MATCHED THEN INSERT (
  gift_note,
  line_no,
  order_id,
  placed_at,
  quantity,
  sku,
  status,
  _source,
  _ingested_at,
  _load_id,
  _source_row_id,
  _quality_flags,
  _quality_ok
) VALUES (
  _replay.gift_note,
  _replay.line_no,
  _replay.order_id,
  _replay.placed_at,
  _replay.quantity,
  _replay.sku,
  _replay.status,
  _replay._source,
  _replay._ingested_at,
  _replay._load_id,
  _replay._source_row_id,
  _replay._quality_flags,
  _replay._quality_ok
);

UPDATE silver.order_line__reject SET resolved_at = CURRENT_TIMESTAMP, last_evaluated_at = CURRENT_TIMESTAMP
WHERE
  resolved_at IS NULL
  AND (source_relation, _source_row_id) IN (
    SELECT
      _target._source,
      _target._source_row_id
    FROM silver.order_line AS _target
  );

MERGE INTO silver.order_line__reject AS _target
USING (
  SELECT
    _extract._source,
    _extract._source_row_id,
    ARRAY_CAT(
      ARRAY_CAT(
        ARRAY_CAT(
          ARRAY_CAT(
            ARRAY_CAT(
              ARRAY_CAT(
                ARRAY_CAT(
                  ARRAY_CAT(
                    CASE
                      WHEN NOT COALESCE(
                        (
                          _extract._branch_gift_note_coercible
                          OR _extract._branch_order_id_coercible
                          OR _extract._branch_quantity_coercible
                          OR _extract._branch_sku_coercible
                          OR _extract._branch_status_coercible
                          OR _extract._branch_status_in_enum
                        ),
                        FALSE
                      )
                      THEN ARRAY['(superseded)']
                      ELSE CAST(ARRAY[] AS TEXT[])
                    END,
                    CASE
                      WHEN _extract._branch_gift_note_coercible
                      THEN ARRAY['gift_note_coercible']
                      ELSE CAST(ARRAY[] AS TEXT[])
                    END
                  ),
                  CASE
                    WHEN _extract._branch_line_no_coercible
                    THEN ARRAY['line_no_coercible']
                    ELSE CAST(ARRAY[] AS TEXT[])
                  END
                ),
                CASE
                  WHEN _extract._branch_order_id_coercible
                  THEN ARRAY['order_id_coercible']
                  ELSE CAST(ARRAY[] AS TEXT[])
                END
              ),
              CASE
                WHEN _extract._branch_placed_at_coercible
                THEN ARRAY['placed_at_coercible']
                ELSE CAST(ARRAY[] AS TEXT[])
              END
            ),
            CASE
              WHEN _extract._branch_quantity_coercible
              THEN ARRAY['quantity_coercible']
              ELSE CAST(ARRAY[] AS TEXT[])
            END
          ),
          CASE
            WHEN _extract._branch_sku_coercible
            THEN ARRAY['sku_coercible']
            ELSE CAST(ARRAY[] AS TEXT[])
          END
        ),
        CASE
          WHEN _extract._branch_status_coercible
          THEN ARRAY['status_coercible']
          ELSE CAST(ARRAY[] AS TEXT[])
        END
      ),
      CASE
        WHEN _extract._branch_status_in_enum
        THEN ARRAY['status_in_enum']
        ELSE CAST(ARRAY[] AS TEXT[])
      END
    ) AS failed_rules
  FROM (
    SELECT
      CASE
        WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.properties') ->> 'gift_note', 'TEXT')
        THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.properties') ->> 'gift_note' AS TEXT)
      END AS gift_note,
      CASE
        WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.position'), 'BIGINT')
        THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.position') AS BIGINT)
      END AS line_no,
      CASE
        WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.order') ->> 'id', 'TEXT')
        THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.order') ->> 'id' AS TEXT)
      END AS order_id,
      CASE
        WHEN PG_INPUT_IS_VALID(
          CASE
            WHEN SUBSTRING(JSON_EXTRACT_PATH_TEXT(raw, '$.created_at') FROM 11) LIKE '%+%'
            OR SUBSTRING(JSON_EXTRACT_PATH_TEXT(raw, '$.created_at') FROM 11) LIKE '%-%'
            THEN NULL
            ELSE JSON_EXTRACT_PATH_TEXT(raw, '$.created_at')
          END,
          'TIMESTAMP'
        )
        AND NOT LOWER(
          CASE
            WHEN SUBSTRING(JSON_EXTRACT_PATH_TEXT(raw, '$.created_at') FROM 11) LIKE '%+%'
            OR SUBSTRING(JSON_EXTRACT_PATH_TEXT(raw, '$.created_at') FROM 11) LIKE '%-%'
            THEN NULL
            ELSE JSON_EXTRACT_PATH_TEXT(raw, '$.created_at')
          END
        ) ~ '^[[:space:]]*(now|today|tomorrow|yesterday)[[:space:]]*$'
        THEN CAST(CASE
          WHEN SUBSTRING(JSON_EXTRACT_PATH_TEXT(raw, '$.created_at') FROM 11) LIKE '%+%'
          OR SUBSTRING(JSON_EXTRACT_PATH_TEXT(raw, '$.created_at') FROM 11) LIKE '%-%'
          THEN NULL
          ELSE JSON_EXTRACT_PATH_TEXT(raw, '$.created_at')
        END AS TIMESTAMP)
      END AS placed_at,
      CASE
        WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.quantity'), 'BIGINT')
        THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.quantity') AS BIGINT)
      END AS quantity,
      CASE
        WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.variant') ->> 'sku', 'TEXT')
        THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.variant') ->> 'sku' AS TEXT)
      END AS sku,
      CASE CASE
          WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.financial_status'), 'TEXT')
          THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.financial_status') AS TEXT)
        END
        WHEN 'pending'
        THEN 'open'
        WHEN 'paid'
        THEN 'closed'
        WHEN 'refunded'
        THEN 'reversed'
        ELSE CASE
          WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.financial_status'), 'TEXT')
          THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.financial_status') AS TEXT)
        END
      END AS status,
      _ingested_at,
      _load_id,
      _source_row_id,
      CASE
        WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.properties') ->> 'gift_note', 'TEXT')
        THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.properties') ->> 'gift_note' AS TEXT)
      END IS NULL
      AND (
        NOT JSON_EXTRACT_PATH_TEXT(raw, '$.properties') ->> 'gift_note' IS NULL
      ) AS _branch_gift_note_coercible,
      CASE
        WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.position'), 'BIGINT')
        THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.position') AS BIGINT)
      END IS NULL
      AND (
        NOT JSON_EXTRACT_PATH_TEXT(raw, '$.position') IS NULL
      ) AS _branch_line_no_coercible,
      CASE
        WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.order') ->> 'id', 'TEXT')
        THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.order') ->> 'id' AS TEXT)
      END IS NULL
      AND (
        NOT JSON_EXTRACT_PATH_TEXT(raw, '$.order') ->> 'id' IS NULL
      ) AS _branch_order_id_coercible,
      CASE
        WHEN PG_INPUT_IS_VALID(
          CASE
            WHEN SUBSTRING(JSON_EXTRACT_PATH_TEXT(raw, '$.created_at') FROM 11) LIKE '%+%'
            OR SUBSTRING(JSON_EXTRACT_PATH_TEXT(raw, '$.created_at') FROM 11) LIKE '%-%'
            THEN NULL
            ELSE JSON_EXTRACT_PATH_TEXT(raw, '$.created_at')
          END,
          'TIMESTAMP'
        )
        AND NOT LOWER(
          CASE
            WHEN SUBSTRING(JSON_EXTRACT_PATH_TEXT(raw, '$.created_at') FROM 11) LIKE '%+%'
            OR SUBSTRING(JSON_EXTRACT_PATH_TEXT(raw, '$.created_at') FROM 11) LIKE '%-%'
            THEN NULL
            ELSE JSON_EXTRACT_PATH_TEXT(raw, '$.created_at')
          END
        ) ~ '^[[:space:]]*(now|today|tomorrow|yesterday)[[:space:]]*$'
        THEN CAST(CASE
          WHEN SUBSTRING(JSON_EXTRACT_PATH_TEXT(raw, '$.created_at') FROM 11) LIKE '%+%'
          OR SUBSTRING(JSON_EXTRACT_PATH_TEXT(raw, '$.created_at') FROM 11) LIKE '%-%'
          THEN NULL
          ELSE JSON_EXTRACT_PATH_TEXT(raw, '$.created_at')
        END AS TIMESTAMP)
      END IS NULL
      AND (
        NOT JSON_EXTRACT_PATH_TEXT(raw, '$.created_at') IS NULL
      ) AS _branch_placed_at_coercible,
      CASE
        WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.quantity'), 'BIGINT')
        THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.quantity') AS BIGINT)
      END IS NULL
      AND (
        NOT JSON_EXTRACT_PATH_TEXT(raw, '$.quantity') IS NULL
      ) AS _branch_quantity_coercible,
      CASE
        WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.variant') ->> 'sku', 'TEXT')
        THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.variant') ->> 'sku' AS TEXT)
      END IS NULL
      AND (
        NOT JSON_EXTRACT_PATH_TEXT(raw, '$.variant') ->> 'sku' IS NULL
      ) AS _branch_sku_coercible,
      CASE CASE
          WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.financial_status'), 'TEXT')
          THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.financial_status') AS TEXT)
        END
        WHEN 'pending'
        THEN 'open'
        WHEN 'paid'
        THEN 'closed'
        WHEN 'refunded'
        THEN 'reversed'
        ELSE CASE
          WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.financial_status'), 'TEXT')
          THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.financial_status') AS TEXT)
        END
      END IS NULL
      AND (
        NOT JSON_EXTRACT_PATH_TEXT(raw, '$.financial_status') IS NULL
      ) AS _branch_status_coercible,
      NOT CASE CASE
          WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.financial_status'), 'TEXT')
          THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.financial_status') AS TEXT)
        END
        WHEN 'pending'
        THEN 'open'
        WHEN 'paid'
        THEN 'closed'
        WHEN 'refunded'
        THEN 'reversed'
        ELSE CASE
          WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.financial_status'), 'TEXT')
          THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.financial_status') AS TEXT)
        END
      END IN ('closed', 'open', 'reversed') AS _branch_status_in_enum,
      'shopify__order_lines' AS _source
    FROM silver.order_line__reject
    WHERE
      resolved_at IS NULL AND source_relation = 'shopify__order_lines'
    UNION ALL
    SELECT
      CAST(NULL AS TEXT) AS gift_note,
      CASE
        WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.item_index'), 'BIGINT')
        THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.item_index') AS BIGINT)
      END AS line_no,
      CASE
        WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.order_number'), 'TEXT')
        THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.order_number') AS TEXT)
      END AS order_id,
      CASE
        WHEN PG_INPUT_IS_VALID(
          CASE
            WHEN SUBSTRING(JSON_EXTRACT_PATH_TEXT(raw, '$.created') FROM 11) LIKE '%+%'
            OR SUBSTRING(JSON_EXTRACT_PATH_TEXT(raw, '$.created') FROM 11) LIKE '%-%'
            THEN NULL
            ELSE JSON_EXTRACT_PATH_TEXT(raw, '$.created')
          END,
          'TIMESTAMP'
        )
        AND NOT LOWER(
          CASE
            WHEN SUBSTRING(JSON_EXTRACT_PATH_TEXT(raw, '$.created') FROM 11) LIKE '%+%'
            OR SUBSTRING(JSON_EXTRACT_PATH_TEXT(raw, '$.created') FROM 11) LIKE '%-%'
            THEN NULL
            ELSE JSON_EXTRACT_PATH_TEXT(raw, '$.created')
          END
        ) ~ '^[[:space:]]*(now|today|tomorrow|yesterday)[[:space:]]*$'
        THEN CAST(CASE
          WHEN SUBSTRING(JSON_EXTRACT_PATH_TEXT(raw, '$.created') FROM 11) LIKE '%+%'
          OR SUBSTRING(JSON_EXTRACT_PATH_TEXT(raw, '$.created') FROM 11) LIKE '%-%'
          THEN NULL
          ELSE JSON_EXTRACT_PATH_TEXT(raw, '$.created')
        END AS TIMESTAMP)
      END AS placed_at,
      CASE
        WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.qty'), 'BIGINT')
        THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.qty') AS BIGINT)
      END AS quantity,
      CASE
        WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.product_sku'), 'TEXT')
        THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.product_sku') AS TEXT)
      END AS sku,
      CASE CASE
          WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.state'), 'TEXT')
          THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.state') AS TEXT)
        END
        WHEN 'PROCESSING'
        THEN 'open'
        WHEN 'COMPLETE'
        THEN 'closed'
        ELSE CASE
          WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.state'), 'TEXT')
          THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.state') AS TEXT)
        END
      END AS status,
      _ingested_at,
      _load_id,
      _source_row_id,
      FALSE AS _branch_gift_note_coercible,
      CASE
        WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.item_index'), 'BIGINT')
        THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.item_index') AS BIGINT)
      END IS NULL
      AND (
        NOT JSON_EXTRACT_PATH_TEXT(raw, '$.item_index') IS NULL
      ) AS _branch_line_no_coercible,
      CASE
        WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.order_number'), 'TEXT')
        THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.order_number') AS TEXT)
      END IS NULL
      AND (
        NOT JSON_EXTRACT_PATH_TEXT(raw, '$.order_number') IS NULL
      ) AS _branch_order_id_coercible,
      CASE
        WHEN PG_INPUT_IS_VALID(
          CASE
            WHEN SUBSTRING(JSON_EXTRACT_PATH_TEXT(raw, '$.created') FROM 11) LIKE '%+%'
            OR SUBSTRING(JSON_EXTRACT_PATH_TEXT(raw, '$.created') FROM 11) LIKE '%-%'
            THEN NULL
            ELSE JSON_EXTRACT_PATH_TEXT(raw, '$.created')
          END,
          'TIMESTAMP'
        )
        AND NOT LOWER(
          CASE
            WHEN SUBSTRING(JSON_EXTRACT_PATH_TEXT(raw, '$.created') FROM 11) LIKE '%+%'
            OR SUBSTRING(JSON_EXTRACT_PATH_TEXT(raw, '$.created') FROM 11) LIKE '%-%'
            THEN NULL
            ELSE JSON_EXTRACT_PATH_TEXT(raw, '$.created')
          END
        ) ~ '^[[:space:]]*(now|today|tomorrow|yesterday)[[:space:]]*$'
        THEN CAST(CASE
          WHEN SUBSTRING(JSON_EXTRACT_PATH_TEXT(raw, '$.created') FROM 11) LIKE '%+%'
          OR SUBSTRING(JSON_EXTRACT_PATH_TEXT(raw, '$.created') FROM 11) LIKE '%-%'
          THEN NULL
          ELSE JSON_EXTRACT_PATH_TEXT(raw, '$.created')
        END AS TIMESTAMP)
      END IS NULL
      AND (
        NOT JSON_EXTRACT_PATH_TEXT(raw, '$.created') IS NULL
      ) AS _branch_placed_at_coercible,
      CASE
        WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.qty'), 'BIGINT')
        THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.qty') AS BIGINT)
      END IS NULL
      AND (
        NOT JSON_EXTRACT_PATH_TEXT(raw, '$.qty') IS NULL
      ) AS _branch_quantity_coercible,
      CASE
        WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.product_sku'), 'TEXT')
        THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.product_sku') AS TEXT)
      END IS NULL
      AND (
        NOT JSON_EXTRACT_PATH_TEXT(raw, '$.product_sku') IS NULL
      ) AS _branch_sku_coercible,
      CASE CASE
          WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.state'), 'TEXT')
          THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.state') AS TEXT)
        END
        WHEN 'PROCESSING'
        THEN 'open'
        WHEN 'COMPLETE'
        THEN 'closed'
        ELSE CASE
          WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.state'), 'TEXT')
          THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.state') AS TEXT)
        END
      END IS NULL
      AND (
        NOT JSON_EXTRACT_PATH_TEXT(raw, '$.state') IS NULL
      ) AS _branch_status_coercible,
      NOT CASE CASE
          WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.state'), 'TEXT')
          THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.state') AS TEXT)
        END
        WHEN 'PROCESSING'
        THEN 'open'
        WHEN 'COMPLETE'
        THEN 'closed'
        ELSE CASE
          WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.state'), 'TEXT')
          THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.state') AS TEXT)
        END
      END IN ('closed', 'open') AS _branch_status_in_enum,
      'woo__order_lines' AS _source
    FROM silver.order_line__reject
    WHERE
      resolved_at IS NULL AND source_relation = 'woo__order_lines'
  ) AS _extract
) AS _replay
ON _target.source_relation = _replay._source
AND _target._source_row_id = _replay._source_row_id
WHEN MATCHED AND _target.resolved_at IS NULL THEN UPDATE SET
  failed_rules = _replay.failed_rules,
  last_evaluated_at = CURRENT_TIMESTAMP;
