-- Generated by bloomery — do not edit.
-- fingerprint: blm1:12f24ef0ee9349a0c213ad0a747d3e89d894aaca8bd02d0aae9bddcd7927f090
MODEL (
  name silver.event,
  kind FULL,
  grain (event_id)
);

SELECT
  CAST(id AS VARCHAR) AS event_id,
  CAST(kind AS VARCHAR) AS kind,
  CAST(ts AS TIMESTAMP) AS occurred_at,
  CAST(ARRAY[] AS ARRAY(VARCHAR)) AS _quality_flags,
  TRUE AS _quality_ok
FROM bronze.raw__events
