-- Generated by bloomery — do not edit.
-- fingerprint: blm1:d16cecfce8dd8acb2c0fda3815b6657828d4ae347d4b20d2664cc179df2a0b3d
MODEL (
  name silver.event,
  kind FULL,
  grants ("select" = ('analyst', 'reverse_etl')),
  grain (event_id)
);

SELECT
  CAST(id AS VARCHAR) AS event_id,
  CAST(kind AS VARCHAR) AS kind,
  CAST(ts AS TIMESTAMP) AS occurred_at,
  CAST(ARRAY[] AS ARRAY(VARCHAR)) AS _quality_flags,
  TRUE AS _quality_ok
FROM bronze.raw__events
