-- Generated by bloomery — do not edit.
-- fingerprint: blm1:edadf55caee808168900ee2857b158c85eaf139b5770e5e648b3ec5fff7a2710
MODEL (
  name silver.event,
  kind FULL,
  grain (event_id)
);

SELECT
  CAST(id AS VARCHAR) AS event_id,
  CAST(kind AS VARCHAR) AS kind,
  CAST(ts AS TIMESTAMP) AS occurred_at
FROM bronze.raw__events
