-- Generated by bloomery — do not edit.
-- fingerprint: blm1:8838774fca49b03229bd13e4225e708124d15423d7b47bf4e262f99fc41708fe
MODEL (
  name gold.mart_orders,
  kind FULL,
  grain (order_id)
);

SELECT
  `order`.amount AS amount,
  `order`.order_date AS order_date,
  `order`.order_id AS order_id,
  CAST(DATE_TRUNC(`order`.order_date, DAY) AS DATE) AS ordered_day,
  CAST(DATE_TRUNC(`order`.order_date, MONTH) AS DATE) AS ordered_month,
  CAST(DATE_TRUNC(`order`.order_date, QUARTER) AS DATE) AS ordered_quarter,
  CAST(DATE_TRUNC(`order`.order_date, WEEK) AS DATE) AS ordered_week,
  CAST(DATE_TRUNC(`order`.order_date, YEAR) AS DATE) AS ordered_year,
  `order`.ship_date AS ship_date,
  CAST(DATE_TRUNC(`order`.ship_date, DAY) AS DATE) AS shipped_day,
  CAST(DATE_TRUNC(`order`.ship_date, MONTH) AS DATE) AS shipped_month,
  CAST(DATE_TRUNC(`order`.ship_date, QUARTER) AS DATE) AS shipped_quarter,
  CAST(DATE_TRUNC(`order`.ship_date, WEEK) AS DATE) AS shipped_week,
  CAST(DATE_TRUNC(`order`.ship_date, YEAR) AS DATE) AS shipped_year
FROM silver.`order` AS `order`
