-- Generated by bloomery — do not edit.
-- fingerprint: blm1:afea927a0ed16abe7254c8b0b720fd8a99347ee3a3a00e3939e2c92a13ec9f18
MODEL (
  name silver.customer_crm,
  kind FULL,
  grain (source_system, source_id)
);

SELECT
  TRIM(LOWER(CAST(email AS TEXT))) AS email,
  TRIM(CAST(full_name AS TEXT)) AS name,
  CAST(id AS TEXT) AS source_id,
  CAST(system AS TEXT) AS source_system,
  CAST([] AS TEXT[]) AS _quality_flags,
  TRUE AS _quality_ok
FROM bronze.crm__customers
