-- Generated by bloomery — do not edit.
-- fingerprint: blm1:4aad8ab751b4ca51c6fba6b770f71335fd99abd84ffed225037d0f89753016b5
MODEL (
  name silver.customer_billing,
  kind FULL,
  grain (source_system, source_id)
);

SELECT
  TRIM(LOWER(CAST(billing_email AS TEXT))) AS email,
  TRIM(CAST(account_name AS TEXT)) AS name,
  CAST(account_ref AS TEXT) AS source_id,
  CAST(origin AS TEXT) AS source_system,
  CAST([] AS TEXT[]) AS _quality_flags,
  TRUE AS _quality_ok
FROM bronze.billing__accounts
