-- Generated by bloomery — do not edit.
-- fingerprint: blm1:e5366eb4e310ebc4c57fd707032719595f3674fc652cf3d482e59b3b203fb3fd
MODEL (
  name silver.customer_billing,
  kind FULL,
  grain (source_system, source_id)
);

SELECT
  TRIM(LOWER(CAST(billing_email AS TEXT))) AS email,
  TRIM(CAST(account_name AS TEXT)) AS name,
  CAST(account_ref AS TEXT) AS source_id,
  CAST(origin AS TEXT) AS source_system,
  CAST([] AS TEXT[]) AS _quality_flags,
  TRUE AS _quality_ok
FROM bronze.billing__accounts
