-- Generated by bloomery — do not edit.
-- fingerprint: blm1:b0bcbe3e06020e11c469b1b24cfa46c48f8f4e093ea3aaa6d9520480418f6f95
MODEL (
  name silver.customer_billing,
  kind FULL,
  grain (source_system, source_id)
);

SELECT
  TRIM(LOWER(CAST(billing_email AS TEXT))) AS email,
  TRIM(CAST(account_name AS TEXT)) AS name,
  CAST(account_ref AS TEXT) AS source_id,
  CAST(origin AS TEXT) AS source_system,
  CAST([] AS TEXT[]) AS _quality_flags,
  TRUE AS _quality_ok
FROM bronze.billing__accounts
