-- Generated by bloomery — do not edit.
-- fingerprint: blm1:6929420a8a4ea1fed35d9d931178129415704626d72876ae85cb5d2e06f8520e
MODEL (
  name silver.customer_crm,
  kind FULL,
  grain (source_system, source_id)
);

SELECT
  TRIM(LOWER(CAST(email AS TEXT))) AS email,
  TRIM(CAST(full_name AS TEXT)) AS name,
  CAST(id AS TEXT) AS source_id,
  CAST(system AS TEXT) AS source_system,
  CAST([] AS TEXT[]) AS _quality_flags,
  TRUE AS _quality_ok
FROM bronze.crm__customers
