-- Generated by bloomery — do not edit.
-- fingerprint: blm1:9dc573d44f843f3b591dbf9f685f751b7d3a1264120fb8bfd4ac4ff920cc2971
MODEL (
  name silver.customer_crm,
  kind FULL,
  grain (source_system, source_id)
);

SELECT
  TRIM(LOWER(CAST(email AS TEXT))) AS email,
  TRIM(CAST(full_name AS TEXT)) AS name,
  CAST(id AS TEXT) AS source_id,
  CAST(system AS TEXT) AS source_system,
  CAST([] AS TEXT[]) AS _quality_flags,
  TRUE AS _quality_ok
FROM bronze.crm__customers
