-- Generated by bloomery — do not edit.
-- fingerprint: blm1:161e0fe2c0cb8a1aece5f7fdf00fdc7350d36da6bce4c4bde896257aa6034335
{{ config(severity='error') }}

SELECT
  _entity.order_id,
  _entity.line_no,
  COUNT(*) AS key_rows
FROM {{ ref('order_item') }} AS _entity
GROUP BY
  _entity.order_id,
  _entity.line_no
HAVING
  COUNT(*) > 1
