-- Generated by bloomery — do not edit.
-- fingerprint: blm1:186f5850bc442e331162b3d82d5d5a63202059fddfe4b0d0a840410f7f84fd41
{{ config(severity='error') }}

SELECT
  _entity.order_id,
  _entity.line_no,
  COUNT(*) AS key_rows
FROM {{ ref('order_item') }} AS _entity
GROUP BY
  _entity.order_id,
  _entity.line_no
HAVING
  COUNT(*) > 1
