-- Generated by bloomery — do not edit.
-- fingerprint: blm1:053088bdbcb28a99adaa45be6671004431861b7ed332b6e29b911d2edbc61659
{{ config(severity='error') }}

SELECT
  _entity.order_id,
  _entity.line_no,
  COUNT(*) AS key_rows
FROM {{ ref('order_item') }} AS _entity
GROUP BY
  _entity.order_id,
  _entity.line_no
HAVING
  COUNT(*) > 1
