-- Generated by bloomery — do not edit.
-- fingerprint: blm1:27d74d9ec84f7fb3275d59be3456f34dc78125a2575ea14766ecbdce0ba9805f
{{ config(severity='error') }}

SELECT
  _entity.order_id,
  COUNT(*) AS key_rows
FROM {{ ref('order') }} AS _entity
GROUP BY
  _entity.order_id
HAVING
  COUNT(*) > 1
