-- Generated by bloomery — do not edit.
-- fingerprint: blm1:85868b90fb2c8058fae372853f795640688a50f36856ecadca960e559cf20854
{{ config(severity='error') }}

SELECT
  _entity.order_id,
  COUNT(*) AS key_rows
FROM {{ ref('order') }} AS _entity
GROUP BY
  _entity.order_id
HAVING
  COUNT(*) > 1
