-- Generated by bloomery — do not edit.
-- fingerprint: blm1:6eed00192a15eca28ee64740ba4833ecba07734b54d00704321965617c3a82c4
AUDIT (
  name order_line_key_unique
);

SELECT
  _entity.order_id,
  _entity.line_no,
  COUNT(*) AS key_rows
FROM @this_model AS _entity
GROUP BY
  _entity.order_id,
  _entity.line_no
HAVING
  COUNT(*) > 1
