-- Generated by bloomery — do not edit.
-- fingerprint: blm1:ccef11b2488f2bd592c740e5c1603cd9c2b54d803cd8a8e4bb47c7ebc94407ce
{{ config(materialized='table') }}

SELECT
  CAST(date_day AS DATE) AS date_day,
  CAST(DATE_TRUNC('MONTH', date_day) AS DATE) AS date_month,
  CAST(DATE_TRUNC('QUARTER', date_day) AS DATE) AS date_quarter,
  CAST(DATE_TRUNC('WEEK', date_day) AS DATE) AS date_week,
  CAST(DATE_TRUNC('YEAR', date_day) AS DATE) AS date_year
FROM GENERATE_SERIES(CAST('2020-01-01' AS DATE), CAST('2030-12-31' AS DATE), INTERVAL '1 DAY') AS date_day(date_day)
