-- Generated by bloomery — do not edit.
-- fingerprint: blm1:d74b550cabc17d419b7c3b416b571d727f2be318e4a15f7410cfafa6bf58f3d9
{{ config(materialized='table') }}

SELECT
  order_customer_id,
  ordered_month,
  SUM(unit_price * quantity) AS gross_revenue
FROM {{ ref('mart_order_items') }}
GROUP BY
  order_customer_id,
  ordered_month
