-- Generated by bloomery — do not edit.
-- fingerprint: blm1:f02114f747f249f12fe7d8789848381d91e90a8a8d1174229fed2c1a8bfea5b3
{{ config(materialized='table') }}

SELECT
  order_customer_id,
  ordered_month,
  SUM(unit_price * quantity) AS gross_revenue
FROM {{ ref('mart_order_items') }}
GROUP BY
  order_customer_id,
  ordered_month
