-- Generated by bloomery — do not edit.
-- fingerprint: blm1:56f22928b5698ffa438e6b9ddcf3d998f3608d772bdd2e58af5623ab8a12595b
{{ config(materialized='table') }}

SELECT
  order_customer_id,
  ordered_month,
  SUM(unit_price * quantity) AS gross_revenue
FROM {{ ref('mart_order_items') }}
GROUP BY
  order_customer_id,
  ordered_month
