-- Generated by bloomery — do not edit.
-- fingerprint: blm1:2443d13159586215c7bef200bb1944c16ebd5cdfb9b1c3a685ce5f6248edaec9
MODEL (
  name gold.mart_order_items,
  kind INCREMENTAL_BY_TIME_RANGE (time_column ordered_day),
  grain (order_id, line_no),
  partitioned_by (days(ordered_day))
);

SELECT
  order_item.line_no AS line_no,
  order_.customer_id AS order_customer_id,
  order_item.order_date AS order_date,
  order_item.order_id AS order_id,
  order_.order_id AS order_order_id,
  CAST(DATE_TRUNC('DAY', order_item.order_date) AS DATE) AS ordered_day,
  CAST(DATE_TRUNC('MONTH', order_item.order_date) AS DATE) AS ordered_month,
  CAST(DATE_TRUNC('QUARTER', order_item.order_date) AS DATE) AS ordered_quarter,
  CAST(DATE_TRUNC('WEEK', order_item.order_date) AS DATE) AS ordered_week,
  CAST(DATE_TRUNC('YEAR', order_item.order_date) AS DATE) AS ordered_year,
  order_item.quantity AS quantity,
  order_item.unit_price AS unit_price
FROM silver.order_item AS order_item
LEFT JOIN silver."order" AS order_
  ON order_item.order_id = order_.order_id
