-- Generated by bloomery — do not edit.
-- fingerprint: blm1:06223627d00172ce699d307312c3b3edd4618ced869b1811e804b89ee8026086
{% macro generate_schema_name(custom_schema_name, node) -%}
{%- if custom_schema_name is none -%}
{{ target.schema }}
{%- else -%}
{{ custom_schema_name | trim }}
{%- endif -%}
{%- endmacro %}
