-- Generated by bloomery — do not edit.
-- fingerprint: blm1:f80667e9ac1d9e8a7ba07e6905baadedb2e105ad1d52daa10f4102efd42183f2
{% macro generate_schema_name(custom_schema_name, node) -%}
{%- if custom_schema_name is none -%}
{{ target.schema }}
{%- else -%}
{{ custom_schema_name | trim }}
{%- endif -%}
{%- endmacro %}
