-- Generated by bloomery — do not edit.
-- fingerprint: blm1:829dd7421f8ee44890c21dd7eaf4941ec0d3b1f2ab8f4473fa0c6a84d4303fa5
{% macro generate_schema_name(custom_schema_name, node) -%}
{%- if custom_schema_name is none -%}
{{ target.schema }}
{%- else -%}
{{ custom_schema_name | trim }}
{%- endif -%}
{%- endmacro %}
