-- Generated by bloomery — do not edit.
-- fingerprint: blm1:9b09dfd3b4023aaf496bbd9aaa08abbc99b88f1775a988bfe7dc977d825c46ad
AUDIT (
  name order_key_unique
);

SELECT
  _entity.order_id,
  COUNT(*) AS key_rows
FROM @this_model AS _entity
GROUP BY
  _entity.order_id
HAVING
  COUNT(*) > 1
