-- Generated by bloomery — do not edit.
-- fingerprint: blm1:b4aac00dd6c4b7c04b241b6929551d3f848886216e3a4adf1efecd43d49fdcf2
AUDIT (
  name customer_billing_key_unique
);

SELECT
  _entity.source_system,
  _entity.source_id,
  COUNT(*) AS key_rows
FROM @this_model AS _entity
GROUP BY
  _entity.source_system,
  _entity.source_id
HAVING
  COUNT(*) > 1
