-- Generated by bloomery — do not edit.
-- fingerprint: blm1:157c7f804d52e4952377421dcc3b36045bc97599bc01eab5d8b7f51d80c9a05a
AUDIT (
  name step_customer_xref_canonical_id_references_customer
);

SELECT
  _child.canonical_id
FROM silver.customer_xref AS _child
WHERE
  NOT _child.canonical_id IS NULL
  AND NOT EXISTS(
    SELECT
      1
    FROM silver.customer AS _parent
    WHERE
      _parent.canonical_id = _child.canonical_id
  )
