-- Generated by bloomery — do not edit.
-- fingerprint: blm1:cfd7da096cdaa99720b36237f5c6f8649cb095b79130324e4b63eaf996d94d41
AUDIT (
  name step_customer_confidence_is_high
);

SELECT
  *
FROM @this_model AS _output
WHERE
  NOT (
    _output.confidence >= 0.8
  )
