-- Generated by bloomery — do not edit.
-- fingerprint: blm1:4aad8ab751b4ca51c6fba6b770f71335fd99abd84ffed225037d0f89753016b5
AUDIT (
  name step_customer_xref_canonical_id_references_customer
);

SELECT
  _child.canonical_id
FROM silver.customer_xref AS _child
WHERE
  NOT _child.canonical_id IS NULL
  AND NOT EXISTS(
    SELECT
      1
    FROM silver.customer AS _parent
    WHERE
      _parent.canonical_id = _child.canonical_id
  )
