-- Generated by bloomery — do not edit.
-- fingerprint: blm1:b0bcbe3e06020e11c469b1b24cfa46c48f8f4e093ea3aaa6d9520480418f6f95
AUDIT (
  name step_customer_confidence_is_high
);

SELECT
  *
FROM @this_model AS _output
WHERE
  NOT (
    _output.confidence >= 0.8
  )
