-- Generated by bloomery — do not edit.
-- fingerprint: blm1:75222c5667cfc36c68519fda9d3cbf345c0a548e6157d0943b675211391baf8e
AUDIT (
  name step_customer_xref_canonical_id_references_customer
);

SELECT
  _child.canonical_id
FROM silver.customer_xref AS _child
WHERE
  NOT _child.canonical_id IS NULL
  AND NOT EXISTS(
    SELECT
      1
    FROM silver.customer AS _parent
    WHERE
      _parent.canonical_id = _child.canonical_id
  )
