-- Generated by bloomery — do not edit.
-- fingerprint: blm1:2a3692de409c6ed955fc0b7235772dacf2124e27f7107aa7addcee7a27af9a19
AUDIT (
  name step_customer_confidence_is_high
);

SELECT
  *
FROM @this_model AS _output
WHERE
  NOT (
    _output.confidence >= 0.8
  )
