-- Generated by bloomery — do not edit.
-- fingerprint: blm1:9af922d2e91172363d391a8f5f2f76300d56e88d95cc5afa8629740bb9f28fb2
{{ config(materialized='table') }}

SELECT
  CAST(date_day AS DATE) AS date_day,
  CAST(DATE_TRUNC('MONTH', date_day) AS DATE) AS date_month,
  CAST(DATE_TRUNC('QUARTER', date_day) AS DATE) AS date_quarter,
  CAST(DATE_TRUNC('WEEK', date_day) AS DATE) AS date_week,
  CAST(DATE_TRUNC('YEAR', date_day) AS DATE) AS date_year
FROM GENERATE_SERIES(CAST('2020-01-01' AS DATE), CAST('2030-12-31' AS DATE), INTERVAL '1 DAY') AS date_day(date_day)
