-- Generated by bloomery — do not edit.
-- fingerprint: blm1:c63e5f8d5a9a3ed8654688ca3ae0126803dc498e332e44fa3b493a01cabc3785
{{ config(materialized='incremental', unique_key=['order_id', 'line_no']) }}

SELECT
  order_item.line_no AS line_no,
  order_.customer_id AS order_customer_id,
  order_item.order_date AS order_date,
  order_item.order_id AS order_id,
  order_.order_id AS order_order_id,
  CAST(DATE_TRUNC('DAY', order_item.order_date) AS DATE) AS ordered_day,
  CAST(DATE_TRUNC('MONTH', order_item.order_date) AS DATE) AS ordered_month,
  CAST(DATE_TRUNC('QUARTER', order_item.order_date) AS DATE) AS ordered_quarter,
  CAST(DATE_TRUNC('WEEK', order_item.order_date) AS DATE) AS ordered_week,
  CAST(DATE_TRUNC('YEAR', order_item.order_date) AS DATE) AS ordered_year,
  order_item.quantity AS quantity,
  order_item.unit_price AS unit_price
FROM {{ ref('order_item') }} AS order_item
LEFT JOIN {{ ref('order') }} AS order_
  ON order_item.order_id = order_.order_id
