-- Generated by bloomery — do not edit.
-- fingerprint: blm1:9ab6be02fbdc8c44dc85b4acb03bfde7131aed81671d88c9e0ead7071f90020b
{{ config(materialized='incremental', unique_key=['order_id', 'line_no']) }}

SELECT
  order_item.line_no AS line_no,
  order_.customer_id AS order_customer_id,
  order_item.order_date AS order_date,
  order_item.order_id AS order_id,
  order_.order_id AS order_order_id,
  CAST(DATE_TRUNC('DAY', order_item.order_date) AS DATE) AS ordered_day,
  CAST(DATE_TRUNC('MONTH', order_item.order_date) AS DATE) AS ordered_month,
  CAST(DATE_TRUNC('QUARTER', order_item.order_date) AS DATE) AS ordered_quarter,
  CAST(DATE_TRUNC('WEEK', order_item.order_date) AS DATE) AS ordered_week,
  CAST(DATE_TRUNC('YEAR', order_item.order_date) AS DATE) AS ordered_year,
  order_item.quantity AS quantity,
  order_item.unit_price AS unit_price
FROM silver.order_item AS order_item
LEFT JOIN silver."order" AS order_
  ON order_item.order_id = order_.order_id
