-- Generated by bloomery — do not edit.
-- fingerprint: blm1:3ca3bdb45f0e3d383f8fac41a8b92cc43113edd4f7f2ebb38938f576997b5a5e
MODEL (
  name gold.mart_orders,
  kind FULL,
  grain (order_id)
);

SELECT
  "order".amount AS amount,
  "order".order_date AS order_date,
  "order".order_id AS order_id,
  CAST(DATE_TRUNC('DAY', "order".order_date) AS DATE) AS ordered_day,
  CAST(DATE_TRUNC('MONTH', "order".order_date) AS DATE) AS ordered_month,
  CAST(DATE_TRUNC('QUARTER', "order".order_date) AS DATE) AS ordered_quarter,
  CAST(DATE_TRUNC('WEEK', "order".order_date) AS DATE) AS ordered_week,
  CAST(DATE_TRUNC('YEAR', "order".order_date) AS DATE) AS ordered_year,
  "order".ship_date AS ship_date,
  CAST(DATE_TRUNC('DAY', "order".ship_date) AS DATE) AS shipped_day,
  CAST(DATE_TRUNC('MONTH', "order".ship_date) AS DATE) AS shipped_month,
  CAST(DATE_TRUNC('QUARTER', "order".ship_date) AS DATE) AS shipped_quarter,
  CAST(DATE_TRUNC('WEEK', "order".ship_date) AS DATE) AS shipped_week,
  CAST(DATE_TRUNC('YEAR', "order".ship_date) AS DATE) AS shipped_year
FROM silver."order" AS "order"
