-- Generated by bloomery — do not edit.
-- fingerprint: blm1:6b311122fca27bf8b9672aef95684e2d474ca4e0ac206d79a8b36155c96edd30
AUDIT (
  name customer_raw_key_unique
);

SELECT
  _entity.source_system,
  _entity.source_id,
  COUNT(*) AS key_rows
FROM @this_model AS _entity
GROUP BY
  _entity.source_system,
  _entity.source_id
HAVING
  COUNT(*) > 1
