-- Generated by bloomery — do not edit.
-- fingerprint: blm1:8d07eac24436516a78a4b38c072d9af467d703cdfc1b7a62d7e94d25f2390f71
AUDIT (
  name step_customer_xref_canonical_id_references_customer
);

SELECT
  _child.canonical_id
FROM silver.customer_xref AS _child
WHERE
  NOT _child.canonical_id IS NULL
  AND NOT EXISTS(
    SELECT
      1
    FROM silver.customer AS _parent
    WHERE
      _parent.canonical_id = _child.canonical_id
  )
