-- Generated by bloomery — do not edit.
-- fingerprint: blm1:e41b653769a44e197569facbcb4723799ad545b7c1135b3bd5d8dc99242b5adf
AUDIT (
  name step_customer_xref_canonical_id_references_customer
);

SELECT
  _child.canonical_id
FROM silver.customer_xref AS _child
WHERE
  NOT _child.canonical_id IS NULL
  AND NOT EXISTS(
    SELECT
      1
    FROM silver.customer AS _parent
    WHERE
      _parent.canonical_id = _child.canonical_id
  )
