-- Generated by bloomery — do not edit.
-- fingerprint: blm1:d834c2a33c1db3db169d69127f74ad50b4483bf6135c8ea28e4f861959cd9471
AUDIT (
  name step_customer_xref_canonical_id_references_customer
);

SELECT
  _child.canonical_id
FROM silver.customer_xref AS _child
WHERE
  NOT _child.canonical_id IS NULL
  AND NOT EXISTS(
    SELECT
      1
    FROM silver.customer AS _parent
    WHERE
      _parent.canonical_id = _child.canonical_id
  )
