-- Generated by bloomery — do not edit.
-- fingerprint: blm1:0f95b26be3ed644490b0c9d8d1de857f301064e2748ec082fc49f8cfba140e9a
{{ config(materialized='incremental', unique_key=['order_id', 'line_no']) }}

SELECT
  CAST(index AS BIGINT) AS line_no,
  CAST(CASE
    WHEN SUBSTRING(CAST(created_at AS VARCHAR) FROM 11) LIKE '%+%'
    OR SUBSTRING(CAST(created_at AS VARCHAR) FROM 11) LIKE '%-%'
    THEN NULL
    ELSE created_at
  END AS TIMESTAMP) AT TIME ZONE 'Europe/Paris' AT TIME ZONE 'UTC' AS order_date,
  CAST(order_id AS TEXT) AS order_id,
  CAST(qty AS BIGINT) AS quantity,
  CAST(CAST(total AS DOUBLE PRECISION) / qty AS DECIMAL(12, 4)) AS unit_price,
  CAST(ARRAY[] AS TEXT[]) AS _quality_flags,
  TRUE AS _quality_ok
FROM {{ source('bronze', 'shopify__order_lines') }}
