-- Generated by bloomery — do not edit.
-- fingerprint: blm1:0f95b26be3ed644490b0c9d8d1de857f301064e2748ec082fc49f8cfba140e9a
{{ config(materialized='table') }}

SELECT
  CAST(customer ->> 'id' AS TEXT) AS customer_id,
  CAST(id AS TEXT) AS order_id,
  CAST(ARRAY[] AS TEXT[]) AS _quality_flags,
  TRUE AS _quality_ok
FROM {{ source('bronze', 'shopify__orders') }}
