-- Generated by bloomery — do not edit.
-- fingerprint: blm1:27d74d9ec84f7fb3275d59be3456f34dc78125a2575ea14766ecbdce0ba9805f
{{ config(materialized='table') }}

SELECT
  CAST(customer ->> 'id' AS TEXT) AS customer_id,
  CAST(id AS TEXT) AS order_id,
  CAST(ARRAY[] AS TEXT[]) AS _quality_flags,
  TRUE AS _quality_ok
FROM {{ source('bronze', 'shopify__orders') }}
