-- Generated by bloomery — do not edit.
-- fingerprint: blm1:186f5850bc442e331162b3d82d5d5a63202059fddfe4b0d0a840410f7f84fd41
{{ config(materialized='table') }}

SELECT
  CAST(customer ->> 'id' AS TEXT) AS customer_id,
  CAST(id AS TEXT) AS order_id,
  CAST(ARRAY[] AS TEXT[]) AS _quality_flags,
  TRUE AS _quality_ok
FROM {{ source('bronze', 'shopify__orders') }}
