-- Generated by bloomery — do not edit.
-- fingerprint: blm1:c418eb69054fe59e9854583719a1921b90685f43d5405b5455a5c8da570860d1
{{ config(materialized='incremental', unique_key=['order_id', 'line_no']) }}

SELECT
  CAST(index AS BIGINT) AS line_no,
  CAST(created_at AS TIMESTAMP) AT TIME ZONE 'Europe/Paris' AS order_date,
  CAST(order_id AS TEXT) AS order_id,
  CAST(qty AS BIGINT) AS quantity,
  CAST(CAST(total AS DOUBLE PRECISION) / qty AS DECIMAL(12, 4)) AS unit_price,
  CAST(ARRAY[] AS TEXT[]) AS _quality_flags,
  TRUE AS _quality_ok
FROM {{ source('bronze', 'shopify__order_lines') }}
