-- Generated by bloomery — do not edit.
-- fingerprint: blm1:c5a47c89f5524efe557e1c860a3cd54b7ba8ca8dd51396796a547b15e7449c06
MODEL (
  name gold.mart_revenue_by_state_monthly,
  kind FULL,
  grain (billing_state, ordered_month)
);

SELECT
  billing_state,
  ordered_month,
  SUM(amount) AS revenue
FROM gold.mart_orders
GROUP BY
  billing_state,
  ordered_month
