-- Generated by bloomery — do not edit.
-- fingerprint: blm1:4eef78a6fc50bed1084282bbc309bde8f6af4488d3136789a92e0c8a0c6f8d8b
MODEL (
  name gold.mart_revenue_by_state_monthly,
  kind FULL,
  grain (billing_state, ordered_month)
);

SELECT
  billing_state,
  ordered_month,
  SUM(amount) AS revenue
FROM gold.mart_orders
GROUP BY
  billing_state,
  ordered_month
