-- Generated by bloomery — do not edit.
-- fingerprint: blm1:098fa50992c83bcbc383225902ba829aef87359d914a966a7790e11c5bf886ab
MODEL (
  name gold.mart_revenue_by_state_monthly,
  kind FULL,
  grain (billing_state, ordered_month)
);

SELECT
  billing_state,
  ordered_month,
  SUM(amount) AS revenue
FROM gold.mart_orders
GROUP BY
  billing_state,
  ordered_month
