-- Generated by bloomery — do not edit.
-- fingerprint: blm1:982094f9016d3e8d8226756b5820284154fe0ca94e78f48231634abea9405a9d
MODEL (
  name silver.event,
  kind FULL,
  grants ("select" = ('analyst', 'reverse_etl')),
  grain (event_id),
  audits (event_key_unique)
);

SELECT
  CAST(id AS STRING) AS event_id,
  CAST(kind AS STRING) AS kind,
  CAST(ts AS DATETIME) AS occurred_at,
  ARRAY<STRING>[] AS _quality_flags,
  TRUE AS _quality_ok
FROM bronze.raw__events
