"""Step artifacts (RFC 0017 §5.8, D8/D16).

Three kinds, one per tier above the DSL:

- **``sql_macro``** splices into the consuming entity's SELECT and emits no
  artifact of its own — the model stays one query and column-level lineage
  sees straight through it (§5.1). :func:`macro_expression` is that splice.
- **``sql_model``** emits an ordinary model artifact from the registry body,
  which reached the IR canonicalized at lowering.
- **``python_model``** emits a generated SQLMesh Python-model ``.py``
  artifact — file-shaped text like every other artifact (RFC 0008 D2) —
  importing the manifest ``entrypoint`` at run time and wrapping it with the
  §5.4 contract assertion.

**One wrapper per declared output** (D16), each executing the step and
returning its own output. The RFC records the cost honestly and so does this
module: N outputs means N executions. That is safe for a *correctly declared*
step — nondeterministic ones are compile-refused and seeded ones re-execute
with the same recorded seed — and the residual risk is a step misdeclared as
pure producing disagreeing sibling outputs within one run, which behavioral
gates (run-to-run) do not catch. Accepted for v1 with the mitigation named in
the RFC, not built here.

Every wrapper asserts **all** declared outputs, not just the one it returns:
a step that lies about one output should be caught wherever the run starts.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Final, cast

import jinja2
from sqlglot import exp

from bloomery.emit.base import ArtifactKind, EmittedArtifact
from bloomery.ir import Layer, StepKind
from bloomery.quality import is_not_null
from bloomery.typing import render_type

if TYPE_CHECKING:
    from collections.abc import Sequence

    from sqlglot.expressions.core import Expression

    from bloomery.emit.base import EmitContext
    from bloomery.ir import ProjectIR, StepIR, StepOutputIR, StepParameterIR

__all__ = [
    "consistency_audits",
    "macro_expression",
    "step_artifacts",
]

# The wrapper is Python, so the envelope interpolates *pre-rendered* strings
# exactly as the SQL envelopes do (RFC 0008 D4) — the manifest arrives as a
# JSON literal built by json.dumps, never as template-formatted values.
_WRAPPER = jinja2.Template(  # nosec B701
    '''\
# Generated by bloomery — do not edit.
# fingerprint: {{ fingerprint }}
"""SQLMesh Python model for step {{ ref }}@{{ version }}, output {{ output_name }}.

bloomery emits this wrapper; it never executes the step (RFC 0003). The
contract assertion below is generated and non-optional by construction — see
RFC 0017 §5.4.
"""

from __future__ import annotations

import typing

from sqlmesh import model


@model(
    {{ relation }},
    kind="FULL",
    columns={{ columns }},{% if audits %}
    audits={{ audits }},{% endif %}
)
def execute(context: typing.Any, **kwargs: typing.Any) -> typing.Any:
    # Every name this function needs is bound *inside* it, deliberately.
    # SQLMesh computes a Python model's dependencies by serializing the module
    # globals the function references and rebuilding them in a fresh
    # environment; a global holding a non-literal value — a Decimal parameter,
    # say — fails to reconstruct there, and the model does not load at all
    # ("name 'Decimal' is not defined", before anything runs). Local state has
    # nothing to serialize.
    from datetime import date, datetime  # noqa: F401
    from decimal import Decimal  # noqa: F401

    from bloomery.steps.contract import assert_step_contract

    from {{ module }} import {{ function }}

    manifest = {{ manifest }}
    parameters = {{ parameters }}
    inputs = { {%- for name, relation in inputs %}
        {{ name }}: context.fetchdf(
            f"SELECT * FROM {context.table({{ relation }})}"
        ),{% endfor %}
    }
    outputs = {{ function }}(**inputs, **parameters)
    assert_step_contract(outputs, manifest)
    return outputs[{{ output }}]
''',
    autoescape=False,
)


# A whole-query audit body: the SELECT returns violating rows and the audit
# passes when there are none — the same shape RFC 0016's blocking audits use,
# and the SQL arrives pre-rendered through the dialect port (RFC 0008 D4).
_AUDIT = jinja2.Template(  # nosec B701
    """\
-- Generated by bloomery — do not edit.
-- fingerprint: {{ fingerprint }}
AUDIT (
  name {{ name }}
);

{{ select }}
""",
    autoescape=False,
)


def _python_literal(value: object) -> str:
    """A deterministic Python literal for the wrapper.

    ``repr`` over canonically sorted structures. The obvious alternative —
    ``json.dumps`` then patching ``true``/``false``/``null`` back to Python's
    spelling — is what this used to do, and it edited *string contents* too:
    a column named ``id, null`` came out as ``id, None``, so the embedded
    manifest and the SQLMesh ``columns=`` named a column that does not exist
    and a *correct* step failed its own contract at run time. The wrapper
    still parsed, so no ``ast``-based test noticed.

    ``repr`` is also the escaping boundary. Nothing here interpolates a spec
    value into source text by hand: values arrive from an authored spec, and
    §5.3/D3's promise is that such a spec can never become an
    arbitrary-code-execution surface.
    """
    if isinstance(value, dict):
        pairs = cast("dict[object, object]", value)
        items = ", ".join(
            f"{_python_literal(key)}: {_python_literal(item)}"
            for key, item in sorted(pairs.items(), key=lambda pair: str(pair[0]))
        )
        return "{" + items + "}"
    if isinstance(value, (list, tuple)):
        members: Sequence[object] = cast("Sequence[object]", value)
        return "[" + ", ".join(_python_literal(item) for item in members) + "]"
    if isinstance(value, (str, bool, int)) or value is None:
        return repr(value)
    msg = f"unsupported value in a generated wrapper literal: {type(value).__name__}"
    raise TypeError(msg)


def _manifest_literal(step: StepIR) -> str:
    """The manifest as plain data the wrapper embeds.

    Plain data rather than a re-parsed :class:`StepManifest` so the step
    runtime needs neither pydantic nor bloomery's spec layer to verify a
    contract (D12). Only what the assertion reads is carried — outputs, their
    keys and their produced columns — because anything else would be a second
    copy of the manifest going stale in a generated file.
    """
    return _python_literal(
        {
            "ref": step.ref,
            "version": step.version,
            "outputs": {
                output.name: {
                    "key": list(output.key),
                    "produces": {
                        column.name: {
                            "type": render_type(column.type),
                            "required": column.required,
                        }
                        for column in output.columns
                    },
                }
                for output in step.outputs
            },
        }
    )


def _columns_literal(output: StepOutputIR, ctx: EmitContext) -> str:
    """The SQLMesh ``columns=`` mapping — physical types through the dialect
    port, so a step model declares its schema the same way every other model
    does."""
    return _python_literal(
        {column.name: ctx.dialect.physical_type(column.type) for column in output.columns}
    )


#: How each declared parameter type is reconstructed in the wrapper. The IR
#: holds values as text (canon bytes never meet a float, RFC 0003 D5), but a
#: step body must be *called* with the real thing — a ``threshold`` declared
#: ``decimal`` has to arrive as ``Decimal("0.9")``, not as the string
#: ``"0.9"``, or every comparison inside the step is a type error waiting for
#: the first run.
#:
#: Every entry wraps a ``repr``-produced literal, never a raw value. Building
#: these by string interpolation let an authored parameter close the quote and
#: append an expression — ``PARAMETERS = {"label": "ACME" + __import__("os")…}``
#: parsed and ran. §5.3/D3's promise is that a spec cannot become an
#: arbitrary-code-execution surface, and it is only true if this function
#: holds it.
_PARAMETER_CTORS: Final[dict[str, str]] = {
    "decimal": "Decimal({literal})",
    "date": "date.fromisoformat({literal})",
    "timestamp": "datetime.fromisoformat({literal})",
}


def _parameter_expression(parameter: StepParameterIR) -> str:
    base = parameter.type.split("(", 1)[0].strip()
    if base == "bool":
        return repr(parameter.value.strip().lower() in {"true", "1"})
    if base == "int":
        # Validated at lowering; repr of the parsed int rather than the text,
        # so nothing an author wrote reaches the source unquoted.
        return repr(int(parameter.value))
    template = _PARAMETER_CTORS.get(base)
    if template is None:
        return repr(parameter.value)
    return template.format(literal=repr(parameter.value))


def _parameters_literal(step: StepIR) -> str:
    """Resolved parameters as a Python dict *expression*, typed per the
    manifest.

    The seed is passed as an ordinary parameter because that is what it is:
    the step draws from it, and every wrapper for the step passes the same
    recorded value — which is precisely what makes N executions of a seeded
    step agree (D16).
    """
    entries = [f"{_python_literal(p.name)}: {_parameter_expression(p)}" for p in step.parameters]
    if step.seed is not None:
        entries.append(f"{_python_literal('seed')}: {step.seed:d}")
    return "{" + ", ".join(entries) + "}"


def macro_expression(step: StepIR, arguments: dict[str, Expression]) -> Expression:
    """A Tier 1 body as an expression, with its named parameters substituted.

    The body reached the IR parsed and canonicalized (RFC 0017 §5.8), so this
    is a substitution over an AST rather than string interpolation — which is
    what keeps the splice inside the SQLGlot-only discipline (RFC 0004 D7) and
    lets the resulting model stay one query.

    Placeholders are SQLGlot ``:name`` parameters. An argument the body does
    not mention is ignored rather than refused: the caller supplies the
    columns in scope, and a macro is entitled to use fewer than it is offered.
    """
    if step.body is None:  # pragma: no cover — lowering guarantees a Tier 1 body
        msg = f"step {step.ref}@{step.version} is a sql_macro with no body"
        raise ValueError(msg)
    tree = step.body.ast()

    def _substitute(node: Expression) -> Expression:
        if isinstance(node, exp.Placeholder) and isinstance(node.this, str):
            replacement = arguments.get(node.this)
            if replacement is not None:
                return replacement.copy()
        return node

    return tree.transform(_substitute)


def _wrapper_artifact(
    step: StepIR,
    output: StepOutputIR,
    ir: ProjectIR,
    ctx: EmitContext,
    audits: tuple[str, ...] = (),
) -> EmittedArtifact:
    del ir
    namespace, relation = ctx.naming.relation(_relation_name(output), Layer.SILVER)
    module, function = (step.entrypoint or ":").split(":", 1)
    content = _WRAPPER.render(
        fingerprint=ctx.fingerprint,
        ref=step.ref,
        version=step.version,
        output=_python_literal(output.name),
        # The docstring is prose, so it carries the *name*; every other use is
        # escaped. Both are safe only because the manifest validator forbids a
        # non-identifier output name — belt and braces, since this file writes
        # executable text (D25).
        output_name=output.name,
        relation=_python_literal(f"{namespace}.{relation}"),
        manifest=_manifest_literal(step),
        parameters=_parameters_literal(step),
        columns=_columns_literal(output, ctx),
        # An audit nothing references never runs: SQLMesh loads a bare AUDIT
        # as a *model* audit, executed only where a model's `audits` names it.
        audits=_python_literal(list(audits)) if audits else "",
        module=module,
        function=function,
        inputs=tuple(
            (_python_literal(name), _python_literal(_bound(bound, ctx)))
            for name, bound in step.inputs
        ),
    )
    return EmittedArtifact.create(
        path=f"models/{namespace}/{relation}.py",
        content=content.rstrip("\n") + "\n",
        kind=ArtifactKind.MODEL,
    )


def _bound(relation: str, ctx: EmitContext) -> str:
    """An input binding as the naming policy spells it.

    The output side has always gone through the policy; the input side did
    not, so under a scoping policy a wrapper wrote ``acme_silver.customer``
    and read plain ``silver.customer_raw`` — two different relations, one of
    which may not exist.
    """
    namespace, name = ctx.naming.relation(relation.rsplit(".", 1)[-1], Layer.SILVER)
    return f"{namespace}.{name}"


def _relation_name(output: StepOutputIR) -> str:
    """The bare relation a bound output writes to.

    The wiring binds a qualified name (``silver.customer``); the naming policy
    owns the namespace, so only the last segment is handed to it — otherwise
    a policy that prefixes namespaces would produce ``silver.silver_customer``.
    """
    return output.relation.rsplit(".", 1)[-1]


def _sql_model_artifact(
    step: StepIR,
    output: StepOutputIR,
    ctx: EmitContext,
    envelope: jinja2.Template,
    audits: tuple[str, ...] = (),
) -> EmittedArtifact:
    namespace, relation = ctx.naming.relation(_relation_name(output), Layer.SILVER)
    content = envelope.render(
        fingerprint=ctx.fingerprint,
        name=f"{namespace}.{relation}",  # constrained by RELATION_PATTERN
        kind="FULL",
        grain=", ".join(output.key),
        partitioned_by="",
        audits=", ".join(audits),
        select=ctx.dialect.render(step.body.ast()) if step.body is not None else "",
    )
    return EmittedArtifact.create(
        path=f"models/{namespace}/{relation}.sql",
        content=content.rstrip("\n") + "\n",
        kind=ArtifactKind.MODEL,
    )


#: Aliases for the two sides of a consistency audit. Fixed rather than derived
#: from the output names, which are only identifiers — two outputs could
#: otherwise alias to the same thing.
_PARENT_ALIAS = "_parent"
_CHILD_ALIAS = "_child"


def _audit_relation(output: StepOutputIR, ctx: EmitContext) -> exp.Table:
    """The relation an output writes, as the naming policy spells it.

    Through the policy because every other step path is — the wrapper's
    `@model` name, its `context.table(...)` read, the `sql_model` envelope.
    An audit reading the authored binding instead would query a relation that
    a scoping policy means does not exist, which is the defect D34 fixed on
    the input side and this repeated on the audit side.
    """
    namespace, relation = ctx.naming.relation(_relation_name(output), Layer.SILVER)
    return exp.to_table(f"{namespace}.{relation}")


def _consistency_select(
    parent: StepOutputIR, child: StepOutputIR, column: str, ctx: EmitContext
) -> exp.Select:
    """Rows of ``child`` whose ``column`` has no match in ``parent``'s key —
    the audit passes when there are none.

    NULL references are excluded, the same three-valued discipline RFC 0016
    applies to ``referential``: a row with no reference is not an orphan, it
    is a row that says nothing, and failing a blocking audit on it would
    punish the ordinary case.
    """
    (key,) = parent.key
    exists = (
        exp.Select()
        .select(exp.Literal.number(1))
        .from_(exp.alias_(_audit_relation(parent, ctx), _PARENT_ALIAS))
        .where(
            exp.EQ(
                this=exp.column(key, table=_PARENT_ALIAS),
                expression=exp.column(column, table=_CHILD_ALIAS),
            )
        )
    )
    return (
        exp.Select()
        .select(exp.column(column, table=_CHILD_ALIAS))
        .from_(exp.alias_(_audit_relation(child, ctx), _CHILD_ALIAS))
        .where(
            exp.and_(
                is_not_null(exp.column(column, table=_CHILD_ALIAS)),
                exp.Not(this=exp.Exists(this=exists)),
            )
        )
    )


def _audit_name(child: StepOutputIR, column: str, parent: StepOutputIR) -> str:
    """Namespaced under ``step_`` so it cannot collide with an RFC 0016
    quality audit, whose names are ``<entity>_<rule>`` over author-chosen
    parts. Two audits at one path is the two-writers collision D28 refuses for
    relations, arrived at through the audit namespace."""
    return f"step_{_relation_name(child)}_{column}_references_{_relation_name(parent)}"


def consistency_audits(step: StepIR, ctx: EmitContext) -> tuple[tuple[str, EmittedArtifact], ...]:
    """Blocking audits that sibling outputs of one step agree (RFC 0017 D16),
    returned with the **child output** each one must be attached to.

    D16 accepts a real residual risk: each output gets its own wrapper, so the
    step runs N times, and that is only safe for a *correctly declared* step.
    A step misdeclared as ``pure`` can produce **disagreeing siblings within a
    single run** — a ``customer_xref`` referencing ``canonical_id``s the
    ``customer`` execution never minted. Every behavioural gate compares run
    to run, so none can see it; ``assert_step_contract`` cannot either,
    because each output is individually valid and only their relationship is
    wrong.

    Emitted only for references the manifest **declares**. Inferring them from
    "one output carries another's key columns" fabricates relationships from
    coincidence: two outputs both keyed ``id`` would get a mutual pair of
    audits asserting their id sets are identical, failing every run on correct
    data — the failure that teaches people to ignore audits.

    The name is returned beside the artifact because an audit nothing
    references never runs: SQLMesh loads a bare ``AUDIT`` as a *model* audit,
    executed only when a model's ``audits`` list names it.
    """
    # No `len(outputs) < 2` shortcut: a single output declares no
    # references (the manifest validator refuses a self-reference), so the
    # loop below is already empty for it. The guard was dead code its own
    # test passed without.
    emitted: list[tuple[str, EmittedArtifact]] = []
    by_name = {output.name: output for output in step.outputs}
    for child in step.outputs:
        for column, target in child.references:
            parent = by_name.get(target)
            if parent is None:  # pragma: no cover — the manifest validator refuses this
                continue
            name = _audit_name(child, column, parent)
            content = _AUDIT.render(
                fingerprint=ctx.fingerprint,
                name=name,
                select=ctx.dialect.render(_consistency_select(parent, child, column, ctx)),
            )
            emitted.append(
                (
                    child.name,
                    EmittedArtifact.create(
                        path=f"audits/{name}.sql",
                        content=content.rstrip("\n") + "\n",
                        kind=ArtifactKind.AUDIT,
                    ),
                )
            )
    return tuple(emitted)


def step_artifacts(
    ir: ProjectIR, ctx: EmitContext, envelope: jinja2.Template
) -> tuple[EmittedArtifact, ...]:
    """Every artifact the project's steps contribute, sorted by path.

    ``sql_macro`` contributes none — it lives inside a consuming model's
    SELECT (§5.1), which is the whole point of the tier.
    """
    artifacts: list[EmittedArtifact] = []
    for step in ir.steps:
        if step.kind is StepKind.SQL_MACRO:
            continue
        audits_by_output: dict[str, list[str]] = {}
        for owner, artifact in consistency_audits(step, ctx):
            artifacts.append(artifact)
            # The audit is attached to the *child* — the output holding the
            # reference — because that is the model whose rows it judges.
            audits_by_output.setdefault(owner, []).append(
                artifact.path.removeprefix("audits/").removesuffix(".sql")
            )
        for output in step.outputs:
            attached = tuple(sorted(audits_by_output.get(output.name, ())))
            if step.kind is StepKind.PYTHON_MODEL:
                artifacts.append(_wrapper_artifact(step, output, ir, ctx, attached))
            else:
                artifacts.append(_sql_model_artifact(step, output, ctx, envelope, attached))
    return tuple(sorted(artifacts, key=lambda a: a.path))
