"""Step artifacts (RFC 0017 §5.8, D8/D16).

Three kinds, one per tier above the DSL:

- **``sql_macro``** splices into the consuming entity's SELECT and emits no
  artifact of its own — the model stays one query and column-level lineage
  sees straight through it (§5.1). :func:`macro_expression` is that splice.
- **``sql_model``** emits an ordinary model artifact from the registry body,
  which reached the IR canonicalized at lowering.
- **``python_model``** emits a generated SQLMesh Python-model ``.py``
  artifact — file-shaped text like every other artifact (RFC 0008 D2) —
  importing the manifest ``entrypoint`` at run time and wrapping it with the
  §5.4 contract assertion.

**One wrapper per declared output** (D16), each executing the step and
returning its own output. The RFC records the cost honestly and so does this
module: N outputs means N executions. That is safe for a *correctly declared*
step — nondeterministic ones are compile-refused and seeded ones re-execute
with the same recorded seed — and the residual risk is a step misdeclared as
pure producing disagreeing sibling outputs within one run, which behavioral
gates (run-to-run) do not catch. Accepted for v1 with the mitigation named in
the RFC, not built here.

Every wrapper asserts **all** declared outputs, not just the one it returns:
a step that lies about one output should be caught wherever the run starts.
"""

from __future__ import annotations

import json
from typing import TYPE_CHECKING, Final

import jinja2
from sqlglot import exp

from bloomery.emit.base import ArtifactKind, EmittedArtifact
from bloomery.ir import Layer, StepKind
from bloomery.typing import render_type

if TYPE_CHECKING:
    from sqlglot.expressions.core import Expression

    from bloomery.emit.base import EmitContext
    from bloomery.ir import ProjectIR, StepIR, StepOutputIR, StepParameterIR

__all__ = [
    "macro_expression",
    "step_artifacts",
]

# The wrapper is Python, so the envelope interpolates *pre-rendered* strings
# exactly as the SQL envelopes do (RFC 0008 D4) — the manifest arrives as a
# JSON literal built by json.dumps, never as template-formatted values.
_WRAPPER = jinja2.Template(  # nosec B701
    '''\
# Generated by bloomery — do not edit.
# fingerprint: {{ fingerprint }}
"""SQLMesh Python model for step {{ ref }}@{{ version }}, output {{ output }}.

bloomery emits this wrapper; it never executes the step (RFC 0003). The
contract assertion below is generated and non-optional by construction — see
RFC 0017 §5.4.
"""

from __future__ import annotations

import typing
from datetime import date, datetime
from decimal import Decimal

from sqlmesh import model

from bloomery.steps.contract import assert_step_contract

MANIFEST = {{ manifest }}

PARAMETERS = {{ parameters }}


@model(
    "{{ relation }}",
    kind="FULL",
    columns={{ columns }},
)
def execute(context: typing.Any, **kwargs: typing.Any) -> typing.Any:
    from {{ module }} import {{ function }}

    inputs = { {%- for name, relation in inputs %}
        "{{ name }}": context.fetchdf("SELECT * FROM {{ relation }}"),{% endfor %}
    }
    outputs = {{ function }}(**inputs, **PARAMETERS)
    assert_step_contract(outputs, MANIFEST)
    return outputs["{{ output }}"]
''',
    autoescape=False,
)


def _python_literal(value: object) -> str:
    """A deterministic Python literal for the wrapper.

    ``json.dumps`` with sorted keys, which is valid Python for the shapes used
    here (dicts of strings, bools, ints) and — unlike ``repr`` over a dict —
    is stable regardless of insertion order. ``true``/``false``/``null`` are
    the one divergence, so they are mapped back to Python's spelling.
    """
    rendered = json.dumps(value, sort_keys=True, indent=None)
    for js, py in (("true", "True"), ("false", "False"), ("null", "None")):
        rendered = rendered.replace(f": {js}", f": {py}").replace(f", {js}", f", {py}")
    return rendered


def _manifest_literal(step: StepIR) -> str:
    """The manifest as plain data the wrapper embeds.

    Plain data rather than a re-parsed :class:`StepManifest` so the step
    runtime needs neither pydantic nor bloomery's spec layer to verify a
    contract (D12). Only what the assertion reads is carried — outputs, their
    keys and their produced columns — because anything else would be a second
    copy of the manifest going stale in a generated file.
    """
    return _python_literal(
        {
            "ref": step.ref,
            "version": step.version,
            "outputs": {
                output.name: {
                    "key": list(output.key),
                    "produces": {
                        column.name: {
                            "type": render_type(column.type),
                            "required": column.required,
                        }
                        for column in output.columns
                    },
                }
                for output in step.outputs
            },
        }
    )


def _columns_literal(output: StepOutputIR, ctx: EmitContext) -> str:
    """The SQLMesh ``columns=`` mapping — physical types through the dialect
    port, so a step model declares its schema the same way every other model
    does."""
    return _python_literal(
        {column.name: ctx.dialect.physical_type(column.type) for column in output.columns}
    )


#: How each declared parameter type is reconstructed in the wrapper. The IR
#: holds values as text (canon bytes never meet a float, RFC 0003 D5), but a
#: step body must be *called* with the real thing — a ``threshold`` declared
#: ``decimal`` has to arrive as ``Decimal("0.9")``, not as the string
#: ``"0.9"``, or every comparison inside the step is a type error waiting for
#: the first run.
_PARAMETER_CTORS: Final[dict[str, str]] = {
    "decimal": 'Decimal("{value}")',
    "int": "{value}",
    "bool": "{value}",
    "string": '"{value}"',
    "date": 'date.fromisoformat("{value}")',
    "timestamp": 'datetime.fromisoformat("{value}")',
}


def _parameter_expression(parameter: StepParameterIR) -> str:
    base = parameter.type.split("(", 1)[0].strip()
    template = _PARAMETER_CTORS.get(base, '"{value}"')
    if base == "bool":
        return "True" if parameter.value.lower() in {"true", "1"} else "False"
    return template.format(value=parameter.value)


def _parameters_literal(step: StepIR) -> str:
    """Resolved parameters as a Python dict *expression*, typed per the
    manifest.

    The seed is passed as an ordinary parameter because that is what it is:
    the step draws from it, and every wrapper for the step passes the same
    recorded value — which is precisely what makes N executions of a seeded
    step agree (D16).
    """
    entries = [f'"{p.name}": {_parameter_expression(p)}' for p in step.parameters]
    if step.seed is not None:
        entries.append(f'"seed": {step.seed}')
    return "{" + ", ".join(entries) + "}"


def macro_expression(step: StepIR, arguments: dict[str, Expression]) -> Expression:
    """A Tier 1 body as an expression, with its named parameters substituted.

    The body reached the IR parsed and canonicalized (RFC 0017 §5.8), so this
    is a substitution over an AST rather than string interpolation — which is
    what keeps the splice inside the SQLGlot-only discipline (RFC 0004 D7) and
    lets the resulting model stay one query.

    Placeholders are SQLGlot ``:name`` parameters. An argument the body does
    not mention is ignored rather than refused: the caller supplies the
    columns in scope, and a macro is entitled to use fewer than it is offered.
    """
    if step.body is None:  # pragma: no cover — lowering guarantees a Tier 1 body
        msg = f"step {step.ref}@{step.version} is a sql_macro with no body"
        raise ValueError(msg)
    tree = step.body.ast()

    def _substitute(node: Expression) -> Expression:
        if isinstance(node, exp.Placeholder) and isinstance(node.this, str):
            replacement = arguments.get(node.this)
            if replacement is not None:
                return replacement.copy()
        return node

    return tree.transform(_substitute)


def _wrapper_artifact(
    step: StepIR, output: StepOutputIR, ir: ProjectIR, ctx: EmitContext
) -> EmittedArtifact:
    del ir
    namespace, relation = ctx.naming.relation(_relation_name(output), Layer.SILVER)
    module, function = (step.entrypoint or ":").split(":", 1)
    content = _WRAPPER.render(
        fingerprint=ctx.fingerprint,
        ref=step.ref,
        version=step.version,
        output=output.name,
        relation=f"{namespace}.{relation}",
        manifest=_manifest_literal(step),
        parameters=_parameters_literal(step),
        columns=_columns_literal(output, ctx),
        module=module,
        function=function,
        inputs=step.inputs,
    )
    return EmittedArtifact.create(
        path=f"models/{namespace}/{relation}.py",
        content=content.rstrip("\n") + "\n",
        kind=ArtifactKind.MODEL,
    )


def _relation_name(output: StepOutputIR) -> str:
    """The bare relation a bound output writes to.

    The wiring binds a qualified name (``silver.customer``); the naming policy
    owns the namespace, so only the last segment is handed to it — otherwise
    a policy that prefixes namespaces would produce ``silver.silver_customer``.
    """
    return output.relation.rsplit(".", 1)[-1]


def _sql_model_artifact(
    step: StepIR, output: StepOutputIR, ctx: EmitContext, envelope: jinja2.Template
) -> EmittedArtifact:
    namespace, relation = ctx.naming.relation(_relation_name(output), Layer.SILVER)
    content = envelope.render(
        fingerprint=ctx.fingerprint,
        name=f"{namespace}.{relation}",
        kind="FULL",
        grain=", ".join(output.key),
        partitioned_by="",
        audits="",
        select=ctx.dialect.render(step.body.ast()) if step.body is not None else "",
    )
    return EmittedArtifact.create(
        path=f"models/{namespace}/{relation}.sql",
        content=content.rstrip("\n") + "\n",
        kind=ArtifactKind.MODEL,
    )


def step_artifacts(
    ir: ProjectIR, ctx: EmitContext, envelope: jinja2.Template
) -> tuple[EmittedArtifact, ...]:
    """Every artifact the project's steps contribute, sorted by path.

    ``sql_macro`` contributes none — it lives inside a consuming model's
    SELECT (§5.1), which is the whole point of the tier.
    """
    artifacts: list[EmittedArtifact] = []
    for step in ir.steps:
        if step.kind is StepKind.SQL_MACRO:
            continue
        for output in step.outputs:
            if step.kind is StepKind.PYTHON_MODEL:
                artifacts.append(_wrapper_artifact(step, output, ir, ctx))
            else:
                artifacts.append(_sql_model_artifact(step, output, ctx, envelope))
    return tuple(sorted(artifacts, key=lambda a: a.path))
