-- Generated by bloomery — do not edit.
-- fingerprint: blm1:076caf421b36f60cfc0ea6e51b504ff2aef823b3beb1489ab609cc6b396152eb
AUDIT (
  name item_net_price_reconcile
);

SELECT * FROM @this_model WHERE net_price IS DISTINCT FROM net_price__direct
