-- Generated by bloomery — do not edit.
-- fingerprint: blm1:fab30daf3ea7fa67a38af437a5efb11751f1c61a8f72926202e37a828535df77
AUDIT (
  name item_net_price_reconcile
);

SELECT * FROM @this_model WHERE net_price IS DISTINCT FROM net_price__direct
