-- Generated by bloomery — do not edit.
-- fingerprint: blm1:2e41ed19074d7a450e0dda9cacfa623e288a5b862c6689058ad143f5a8bf9049
AUDIT (
  name item_key_unique
);

SELECT
  _entity.item_id,
  COUNT(*) AS key_rows
FROM @this_model AS _entity
GROUP BY
  _entity.item_id
HAVING
  COUNT(*) > 1
