-- Generated by bloomery — do not edit.
-- fingerprint: blm1:0d0350c9a22b0bffaf9a910901c6d999f31bf7ac1c63351453c8e4f8c67c977f
AUDIT (
  name item_net_price_reconcile
);

SELECT * FROM @this_model WHERE net_price IS DISTINCT FROM net_price__direct
