-- Generated by bloomery — do not edit.
-- fingerprint: blm1:1ea9ddef8b0b9d37178a5f398aa181b6c6bd0a986e69e6062b0f9d191a3e73ba
AUDIT (
  name item_key_unique
);

SELECT
  _entity.item_id,
  COUNT(*) AS key_rows
FROM @this_model AS _entity
GROUP BY
  _entity.item_id
HAVING
  COUNT(*) > 1
