-- Generated by bloomery — do not edit.
-- fingerprint: blm1:4e07e0a0eea5da90640d97b8e0d655ea6b3c0a633824698eb244766f7b7399bf
AUDIT (
  name item_key_unique
);

SELECT
  _entity.item_id,
  COUNT(*) AS key_rows
FROM @this_model AS _entity
GROUP BY
  _entity.item_id
HAVING
  COUNT(*) > 1
