"""The dbt emitter (RFC 0008 §5.5) — the compatibility target.

Its real job is proving the port abstraction (RFC 0008 D5, spec §9): it ships
minimal but honest, and every SELECT is the **same** dialect-port-rendered
AST the SQLMesh emitter renders (:mod:`bloomery.emit.lowering`) — only the
envelope differs. Do not read it as production-grade dbt scaffolding.

Artifacts:

- ``dbt_project.yml`` — the scaffold, so ``dbt parse`` has a project.
- ``models/sources.yml`` — every bronze relation the entities read, grouped
  by bronze namespace under the naming policy.
- ``models/<silver_ns>/<entity>.sql`` per SCD type 1 entity, with a
  ``{{ config(...) }}`` header. Materialization maps honestly: ``full`` →
  ``table``; both incremental kinds → ``incremental`` with the entity key as
  ``unique_key`` — dbt has no native time-range kind, and merge-on-key is the
  equivalent that can never silently duplicate rows (RFC 0008 D3: adapt
  loudly-documented, never degrade silently).
- ``snapshots/<entity>_snapshot.sql`` per SCD type 2 entity — dbt's native
  SCD2. Strategy is ``check`` over all columns (``check_cols: all``): the IR
  declares no updated-at marker, so a ``timestamp`` strategy would invent
  one. A composite-key SCD2 entity raises
  :class:`~bloomery.errors.UnsupportedByTarget` — dbt snapshot ``unique_key``
  is a single expression, and concatenating key parts would be a silent
  approximation. The snapshot **replaces** the silver model: dbt builds the
  history table directly at ``<silver_ns>.<entity>_snapshot``.
- ``models/<gold_ns>/<mart>.sql`` per mart and the ``dim_date`` calendar —
  the same gold SELECTs SQLMesh emits.
- ``models/schema.yml`` — audits lowered to schema tests (RFC 0006 →
  RFC 0008 §5.5): ``not_null`` and ``enum``/``accepted_values`` builtin;
  ``min``/``max``/``regex``/``reconcile`` as
  ``dbt_utils.expression_is_true`` tests whose row-level assertion is the
  shared audit predicate rendered through the dialect port. SCD type 2
  entities' tests attach under ``snapshots:``. An audit kind with no honest
  test mapping raises :class:`~bloomery.errors.UnsupportedByTarget` naming
  the entity and kind — fail loud, never approximate (RFC 0008 D3).
"""

from __future__ import annotations

import jinja2
import yaml

from bloomery.emit.base import (
    ArtifactKind,
    EmitContext,
    EmittedArtifact,
    Feature,
    TargetCapabilities,
)
from bloomery.emit.lowering import (
    audit_predicate,
    column_type,
    dim_date_select,
    entity_select,
    mart_select,
)
from bloomery.errors import UnsupportedByTarget
from bloomery.ir import (
    AuditIR,
    DateDimensionIR,
    EntityIR,
    Layer,
    MartIR,
    Materialization,
    ProjectIR,
    SCDKind,
)
from bloomery.quality import is_quality_mart
from bloomery.typing import IntType

__all__ = [
    "DbtEmitter",
]

#: The custom audit kinds that lower to ``dbt_utils.expression_is_true``.
_EXPRESSION_KINDS = frozenset({"min", "max", "regex", "reconcile"})

# The envelope sees pre-rendered strings only (RFC 0008 D4) — the config
# header is built in Python, the SELECT arrives through the dialect port.
# SQL is not HTML: autoescaping would corrupt it (cf. the SQLMesh envelope).
_MODEL_ENVELOPE = jinja2.Template(  # nosec B701
    """\
-- Generated by bloomery — do not edit.
-- fingerprint: {{ fingerprint }}
{{ config_line }}

{{ select }}
""",
    autoescape=False,
)

# The dbt-Jinja block markers are pre-rendered strings too — this template
# never nests Jinja inside Jinja.
_SNAPSHOT_ENVELOPE = jinja2.Template(  # nosec B701
    """\
-- Generated by bloomery — do not edit.
-- fingerprint: {{ fingerprint }}
{{ open_line }}
{{ config_line }}

{{ select }}

{{ close_line }}
""",
    autoescape=False,
)


def _header(ctx: EmitContext) -> str:
    return f"# Generated by bloomery — do not edit.\n# fingerprint: {ctx.fingerprint}\n"


def _yaml(document: dict[str, object]) -> str:
    """Byte-stable YAML: deterministic insertion order (``sort_keys`` would
    shuffle ``name`` below ``schema``), block style, pinned width."""
    return yaml.safe_dump(
        document, sort_keys=False, default_flow_style=False, width=100, allow_unicode=True
    )


def _unique_key(key: tuple[str, ...]) -> str:
    if len(key) == 1:
        return f"unique_key='{key[0]}'"
    members = ", ".join(f"'{part}'" for part in key)
    return f"unique_key=[{members}]"


def _config_line(materialization: Materialization, key: tuple[str, ...]) -> str:
    if materialization is Materialization.FULL:
        return "{{ config(materialized='table') }}"
    return f"{{{{ config(materialized='incremental', {_unique_key(key)}) }}}}"


def _refuse_quarantine(entity: EntityIR) -> None:
    """dbt has no reject/replay lowering in this wave (RFC 0016 §5.4).

    Target coverage is stated honestly rather than approximated: SQLMesh emits
    the full quality set (split models, reject tables, replay merge), and dbt
    raises here for the reject/replay artifacts — the port-proof scope
    (RFC 0008 §5.5, D3: fail loud, never degrade silently). Flag-only quality
    surfaces still emit, because ``_quality_flags`` is the *same* shared
    SELECT both targets render.
    """
    if entity.quarantine is None:
        return
    msg = (
        f"entity {entity.name!r} declares a quarantine policy, which needs the "
        f"{entity.name}__reject model and its replay merge (RFC 0016 §5.6); the dbt "
        "emitter lowers neither in this wave — it is the compatibility target, minimal "
        "but honest (RFC 0008 §5.5). Fix: compile this project for the sqlmesh target, or "
        "reduce the entity's rules to flag dispositions"
    )
    raise UnsupportedByTarget(msg, source_path=f"entity_model: entities.{entity.name}.quarantine")


def _refuse_reconcile(ir: ProjectIR) -> None:
    """dbt lowers no reconcile artifacts in this wave (RFC 0016 D58).

    A second, *separate* claim from ``_refuse_quarantine`` above, and it needed
    its own decision row: §5.4's target-coverage sentence authorized dbt's
    refusal only for the reject/replay artifacts, so refusing ``reconcile:``
    under the same sentence was scope the RFC never granted. D58 grants it, on
    this argument — a reconcile check is a model *and* a **non-blocking** audit,
    and dbt's test surface has no non-blocking equivalent that would not
    silently turn "report the disagreement" into "fail the build" (RFC 0008 D3:
    fail loud, never degrade silently). Refusing names the target that does.
    """
    if not ir.reconcile:
        return
    names = ", ".join(check.name for check in ir.reconcile)
    msg = (
        f"project declares reconcile check(s) {names}, which lower to a model plus a "
        "non-blocking audit (RFC 0016 §5.3); the dbt emitter lowers neither in this wave, "
        "and has no non-blocking test to approximate the audit with — it is the "
        "compatibility target, minimal but honest (RFC 0008 §5.5, RFC 0016 D58). Fix: "
        "compile this project for the sqlmesh target, or drop the reconcile block"
    )
    raise UnsupportedByTarget(msg, source_path="entity_model: reconcile")


def _model_artifact(
    *, path: str, config_line: str, select: str, ctx: EmitContext
) -> EmittedArtifact:
    content = _MODEL_ENVELOPE.render(
        fingerprint=ctx.fingerprint, config_line=config_line, select=select
    )
    return EmittedArtifact.create(
        path=path, content=content.rstrip("\n") + "\n", kind=ArtifactKind.MODEL
    )


def _snapshot_artifact(entity: EntityIR, ctx: EmitContext) -> EmittedArtifact:
    if len(entity.key) != 1:
        msg = (
            f"entity {entity.name!r} is SCD type 2 with composite key "
            f"({', '.join(entity.key)}) — dbt snapshot unique_key takes a single "
            "expression, and concatenating key parts would be a silent approximation "
            "(feature: scd_type_2)"
        )
        raise UnsupportedByTarget(msg)
    namespace, _relation = ctx.naming.relation(entity.name, Layer.SILVER)
    config_line = (
        f"{{{{ config(target_schema='{namespace}', unique_key='{entity.key[0]}', "
        "strategy='check', check_cols='all') }}"
    )
    content = _SNAPSHOT_ENVELOPE.render(
        fingerprint=ctx.fingerprint,
        open_line=f"{{% snapshot {entity.name}_snapshot %}}",
        close_line="{% endsnapshot %}",
        config_line=config_line,
        select=ctx.dialect.render(entity_select(entity, ctx)),
    )
    return EmittedArtifact.create(
        path=f"snapshots/{entity.name}_snapshot.sql",
        content=content.rstrip("\n") + "\n",
        kind=ArtifactKind.MODEL,
    )


def _dim_date_artifact(dim: DateDimensionIR, ctx: EmitContext) -> EmittedArtifact:
    namespace, _mart_relation = ctx.naming.relation(dim.name, Layer.GOLD)
    return _model_artifact(
        path=f"models/{namespace}/{dim.name}.sql",
        config_line="{{ config(materialized='table') }}",
        select=ctx.dialect.render(dim_date_select(dim)),
        ctx=ctx,
    )


def _mart_artifact(mart: MartIR, ir: ProjectIR, ctx: EmitContext) -> EmittedArtifact:
    namespace, relation = ctx.naming.relation(mart.name, Layer.GOLD)
    if is_quality_mart(mart):
        # RFC 0016 §5.4 puts the quality mart in **SQLMesh's** set, and it is
        # built from the surfaces dbt already refuses: the reject tables and
        # the reconcile models. Counting rows in tables this target does not
        # build would be a mart of zeroes — the silent degradation RFC 0008 D3
        # exists to prevent. In practice the two refusals below fire first
        # (the mart cannot exist without quality rules or a reconcile block);
        # this is the branch that keeps that true if either ever narrows.
        msg = (
            "the data-quality mart (RFC 0016 §5.8) counts rule evaluations over the reject "
            "tables and reconcile models, neither of which the dbt emitter lowers in this "
            "wave — it is the compatibility target, minimal but honest (RFC 0008 §5.5). "
            "Fix: compile this project for the sqlmesh target"
        )
        raise UnsupportedByTarget(msg, source_path="entity_model: quality")
    base = next(entity for entity in ir.entities if entity.name == mart.base)
    return _model_artifact(
        path=f"models/{namespace}/{relation}.sql",
        config_line=_config_line(mart.materialization, base.key),
        select=ctx.dialect.render(mart_select(mart, ctx)),
        ctx=ctx,
    )


# ....................... #
# Audit lowering → schema.yml (RFC 0006 → RFC 0008 §5.5)


def _accepted_values(entity: EntityIR, audit: AuditIR) -> dict[str, object]:
    member_type = column_type(entity, audit.column)
    values: list[object] = [
        int(value) if isinstance(member_type, IntType) else value for _name, value in audit.params
    ]
    return {"accepted_values": {"values": values}}


def _entity_tests(
    entity: EntityIR, ctx: EmitContext
) -> tuple[dict[str, list[object]], list[object]]:
    """The per-column tests (column → test list) and the model-level
    expression tests for one entity, in the deterministic ``EntityIR.audits``
    order (sorted by kind, column)."""
    column_tests: dict[str, list[object]] = {}
    model_tests: list[object] = []
    for audit in entity.audits:
        if audit.kind == "not_null":
            column_tests.setdefault(audit.column, []).append("not_null")
        elif audit.kind == "enum":
            column_tests.setdefault(audit.column, []).append(_accepted_values(entity, audit))
        elif audit.kind in _EXPRESSION_KINDS:
            expression = ctx.dialect.render(audit_predicate(entity, audit, violations=False))
            model_tests.append({"dbt_utils.expression_is_true": {"expression": expression}})
        else:
            msg = (
                f"entity {entity.name!r} audit kind {audit.kind!r} on column "
                f"{audit.column!r} has no honest dbt schema-test mapping "
                "(feature: audits) — refusing rather than approximating (RFC 0008 D3)"
            )
            raise UnsupportedByTarget(msg)
    return column_tests, model_tests


def _schema_entry(entity: EntityIR, name: str, ctx: EmitContext) -> dict[str, object]:
    column_tests, model_tests = _entity_tests(entity, ctx)
    entry: dict[str, object] = {"name": name}
    if model_tests:
        entry["data_tests"] = model_tests
    if column_tests:
        entry["columns"] = [
            {"name": column, "data_tests": tests} for column, tests in sorted(column_tests.items())
        ]
    return entry


def _schema_artifact(ir: ProjectIR, ctx: EmitContext) -> EmittedArtifact | None:
    models: list[object] = []
    snapshots: list[object] = []
    for entity in ir.entities:  # sorted by name on ProjectIR
        if not entity.audits:
            continue
        if entity.scd is SCDKind.TYPE2:
            snapshots.append(_schema_entry(entity, f"{entity.name}_snapshot", ctx))
        else:
            _namespace, relation = ctx.naming.relation(entity.name, Layer.SILVER)
            models.append(_schema_entry(entity, relation, ctx))
    if not models and not snapshots:
        return None
    document: dict[str, object] = {"version": 2}
    if models:
        document["models"] = models
    if snapshots:
        document["snapshots"] = snapshots
    return EmittedArtifact.create(
        path="models/schema.yml",
        content=_header(ctx) + _yaml(document),
        kind=ArtifactKind.CONFIG,
    )


def _sources_artifact(ir: ProjectIR, ctx: EmitContext) -> EmittedArtifact | None:
    relations_by_namespace: dict[str, set[str]] = {}
    for entity in ir.entities:
        namespace, relation = ctx.naming.relation(entity.source.relation, Layer.BRONZE)
        relations_by_namespace.setdefault(namespace, set()).add(relation)
    if not relations_by_namespace:
        return None
    document: dict[str, object] = {
        "version": 2,
        "sources": [
            {
                "name": namespace,
                "schema": namespace,
                "tables": [{"name": table} for table in sorted(tables)],
            }
            for namespace, tables in sorted(relations_by_namespace.items())
        ],
    }
    return EmittedArtifact.create(
        path="models/sources.yml",
        content=_header(ctx) + _yaml(document),
        kind=ArtifactKind.CONFIG,
    )


def _project_artifact(ctx: EmitContext) -> EmittedArtifact:
    document: dict[str, object] = {
        "name": "bloomery",
        "version": "1.0.0",
        "profile": "bloomery",
        "model-paths": ["models"],
        "snapshot-paths": ["snapshots"],
    }
    return EmittedArtifact.create(
        path="dbt_project.yml",
        content=_header(ctx) + _yaml(document),
        kind=ArtifactKind.CONFIG,
    )


class DbtEmitter:
    """RFC 0008 §5.5: the port-abstraction proof (RFC 0008 D5) — same
    lowered SELECTs as SQLMesh, dbt envelopes, honest capability answers."""

    name = "dbt"

    def capabilities(self) -> TargetCapabilities:
        """Declared support per RFC 0008 §5.1 (amended D6): dbt builds the
        same silver/gold tables SQLMesh does — SCD type 2 (lowered to a
        snapshot), variant columns, incrementality (merge-on-key), audits
        (schema tests), and all additivity features."""
        return TargetCapabilities(
            supported=frozenset(
                {
                    Feature.SCD_TYPE_2,
                    Feature.VARIANT_COLUMN,
                    Feature.INCREMENTAL,
                    Feature.AUDITS,
                    Feature.SEMI_ADDITIVE,
                    Feature.NON_ADDITIVE,
                    Feature.CUMULATIVE,
                    Feature.DERIVED_METRIC,
                }
            )
        )

    def emit(self, ir: ProjectIR, ctx: EmitContext) -> tuple[EmittedArtifact, ...]:
        """Lower every entity to a model (SCD type 2 → snapshot), every mart
        and the date dimension to gold models, audits to ``schema.yml``, plus
        the project scaffold and bronze sources; artifacts sorted by path,
        content ending in exactly one newline (RFC 0003 §5.5 rule 5)."""
        if ir.steps:
            # RFC 0017 §5.8 emits steps for SQLMesh only. Dropping them here
            # would silently withhold relations downstream models were
            # typechecked against — fail loud, never approximate (RFC 0008 D3).
            msg = (
                f"project wires {len(ir.steps)} step(s), which the dbt target "
                "cannot emit (RFC 0017 §5.8 covers SQLMesh only). Their output "
                "relations would simply be missing. Fix: compile steps for SQLMesh, "
                "or drop the steps: document for this target"
            )
            raise UnsupportedByTarget(msg)

        _refuse_reconcile(ir)
        artifacts: list[EmittedArtifact] = [_project_artifact(ctx)]
        for entity in ir.entities:
            _refuse_quarantine(entity)
            if entity.scd is SCDKind.TYPE2:
                artifacts.append(_snapshot_artifact(entity, ctx))
                continue
            namespace, relation = ctx.naming.relation(entity.name, Layer.SILVER)
            artifacts.append(
                _model_artifact(
                    path=f"models/{namespace}/{relation}.sql",
                    config_line=_config_line(entity.materialization, entity.key),
                    select=ctx.dialect.render(entity_select(entity, ctx)),
                    ctx=ctx,
                )
            )
        artifacts.extend(_mart_artifact(mart, ir, ctx) for mart in ir.marts)
        if ir.date_dimension is not None:
            artifacts.append(_dim_date_artifact(ir.date_dimension, ctx))
        for optional in (_schema_artifact(ir, ctx), _sources_artifact(ir, ctx)):
            if optional is not None:
                artifacts.append(optional)
        return tuple(sorted(artifacts, key=lambda a: a.path))
