-- Generated by bloomery — do not edit.
-- fingerprint: blm1:868b3943fdf842667f94b52c1da1fd0c44142ff28d8e5f54691b9f4775ce1e91
AUDIT (
  name inventory_level_stock_level_not_null
);

SELECT
  _extract.stock_date,
  _extract.stock_level,
  _extract.warehouse_id,
  _extract._ingested_at,
  _extract._load_id,
  _extract._source_row_id
FROM (
  SELECT
    TRY_CAST(day AS DATE) AS stock_date,
    TRY_CAST(on_hand AS BIGINT) AS stock_level,
    TRY_CAST(warehouse AS TEXT) AS warehouse_id,
    _ingested_at,
    _load_id,
    _source_row_id,
    TRY_CAST(day AS DATE) IS NULL AND (
      NOT day IS NULL
    ) AS _branch_stock_date_coercible,
    TRY_CAST(on_hand AS BIGINT) IS NULL AND (
      NOT on_hand IS NULL
    ) AS _branch_stock_level_coercible,
    TRY_CAST(warehouse AS TEXT) IS NULL AND (
      NOT warehouse IS NULL
    ) AS _branch_warehouse_id_coercible
  FROM bronze.wms__stock_levels
  QUALIFY
    ROW_NUMBER() OVER (
      PARTITION BY warehouse_id, stock_date
      ORDER BY _ingested_at DESC, _load_id DESC, _source_row_id DESC
    ) = 1
) AS _extract
WHERE
  _extract.stock_level IS NULL
UNION
SELECT
  _entity.stock_date,
  _entity.stock_level,
  _entity.warehouse_id,
  _entity._ingested_at,
  _entity._load_id,
  _entity._source_row_id
FROM @this_model AS _entity
WHERE
  ARRAY_CONTAINS(_entity._quality_flags, 'stock_level_not_null')
