-- Generated by bloomery — do not edit.
-- fingerprint: blm1:e0ee87ee8f8d770fd966cb8d6fe2631e227ef0f6d4b421904c50d30047bacd92
AUDIT (
  name inventory_level_stock_level_not_null
);

SELECT * FROM @this_model WHERE stock_level IS NULL
