-- Generated by bloomery — do not edit.
-- fingerprint: blm1:82485659bde4bd2ce11ef7d452090ea3269f503620972fcf89d227265785ef1f
AUDIT (
  name inventory_level_stock_level_not_null
);

SELECT
  _extract.stock_date,
  _extract.stock_level,
  _extract.warehouse_id,
  _extract._ingested_at,
  _extract._load_id,
  _extract._source_row_id
FROM (
  SELECT
    TRY_CAST(day AS DATE) AS stock_date,
    TRY_CAST(on_hand AS BIGINT) AS stock_level,
    TRY_CAST(warehouse AS TEXT) AS warehouse_id,
    _ingested_at,
    _load_id,
    _source_row_id,
    day AS _src_stock_date_coercible_0000,
    on_hand AS _src_stock_level_coercible_0000,
    warehouse AS _src_warehouse_id_coercible_0000
  FROM bronze.wms__stock_levels
  QUALIFY
    ROW_NUMBER() OVER (
      PARTITION BY warehouse_id, stock_date
      ORDER BY _ingested_at DESC, _load_id DESC, _source_row_id DESC
    ) = 1
) AS _extract
WHERE
  _extract.stock_level IS NULL
UNION
SELECT
  _entity.stock_date,
  _entity.stock_level,
  _entity.warehouse_id,
  _entity._ingested_at,
  _entity._load_id,
  _entity._source_row_id
FROM @this_model AS _entity
WHERE
  ARRAY_CONTAINS(_entity._quality_flags, 'stock_level_not_null')
