-- Generated by bloomery — do not edit.
-- fingerprint: blm1:739174102166e213d90e6919eb33e8126a0c8967dfd8a633e3fa20205377afc2
AUDIT (
  name inventory_level_ingestion_metadata
);

SELECT * FROM (
  SELECT *, COUNT(*) OVER (PARTITION BY _source_row_id) AS _row_id_count FROM @this_model
) AS _metadata WHERE _ingested_at IS NULL
OR _load_id IS NULL
OR _source_row_id IS NULL
OR _row_id_count > 1
