-- Generated by bloomery — do not edit.
-- fingerprint: blm1:18f1c282fa11dd1922493abefa33c3f255df2d3e19acc8fb16f654ae847cfedd
-- The conservation law (RFC 0016 §6) as a runtime audit: every bronze row
-- lands in exactly one of the entity, an unresolved reject, or the deduped
-- count. Blocking — a row in neither side of the split has been silently
-- dropped, which is the failure this package exists to make impossible.
AUDIT (
  name inventory_level_conservation
);

WITH _survivors AS (
  SELECT
    TRY_CAST(day AS DATE) AS stock_date,
    TRY_CAST(on_hand AS BIGINT) AS stock_level,
    TRY_CAST(warehouse AS TEXT) AS warehouse_id,
    _ingested_at,
    _load_id,
    _source_row_id,
    day AS _src_stock_date_coercible_0000,
    on_hand AS _src_stock_level_coercible_0000,
    warehouse AS _src_warehouse_id_coercible_0000
  FROM bronze.wms__stock_levels
  QUALIFY
    ROW_NUMBER() OVER (
      PARTITION BY warehouse_id, stock_date
      ORDER BY _ingested_at DESC, _load_id DESC, _source_row_id DESC
    ) = 1
)
SELECT
  *
FROM (
  SELECT
    COUNT(*) AS surviving_rows,
    SUM(
      CASE
        WHEN COALESCE(
          (
            (
              _survivors.stock_date IS NULL
              AND (
                NOT _survivors._src_stock_date_coercible_0000 IS NULL
              )
            )
            OR (
              _survivors.stock_level IS NULL
              AND (
                NOT _survivors._src_stock_level_coercible_0000 IS NULL
              )
            )
            OR (
              _survivors.warehouse_id IS NULL
              AND (
                NOT _survivors._src_warehouse_id_coercible_0000 IS NULL
              )
            )
            OR _survivors.stock_level < 0
          ),
          FALSE
        )
        THEN 1
        ELSE 0
      END
    ) AS diverted_rows,
    (
      SELECT
        COUNT(*)
      FROM bronze.wms__stock_levels
    ) AS bronze_rows,
    (
      SELECT
        COUNT(*)
      FROM @this_model AS _entity
      WHERE
        _entity._source_row_id IN (
          SELECT
            _source_row_id
          FROM _survivors
        )
    ) AS entity_rows
  FROM _survivors
) AS _conservation
WHERE
  entity_rows + diverted_rows <> surviving_rows
