-- Generated by bloomery — do not edit.
-- fingerprint: blm1:84e5ab99fd452b4e62e1dfa703136183fe8f1a457dff57cacc79bc23dfab26cd
AUDIT (
  name inventory_level_ingestion_metadata
);

SELECT
  *
FROM (
  SELECT
    *,
    COUNT(*) OVER (PARTITION BY _source_row_id) AS _row_id_count
  FROM @this_model
) AS _metadata
WHERE
  _ingested_at IS NULL
  OR _load_id IS NULL
  OR _source_row_id IS NULL
  OR _row_id_count > 1
  OR (
    (
      NOT _ingested_at IS NULL
    )
    AND TRY_CAST(CASE
      WHEN SUBSTRING(CAST(_ingested_at AS TEXT), 11) LIKE '%+%'
      OR SUBSTRING(CAST(_ingested_at AS TEXT), 11) LIKE '%-%'
      THEN NULL
      ELSE REPLACE(REPLACE(CAST(_ingested_at AS TEXT), 'T', ' '), 't', ' ')
    END AS TIMESTAMP) IS NULL
  )
