-- Generated by bloomery — do not edit.
-- fingerprint: blm1:bd1c364f80ffebd4c63689c254a58de541d9de0eba4a421b27767f3372efea38
AUDIT (
  name inventory_level_ingestion_metadata
);

SELECT * FROM (
  SELECT *, COUNT(*) OVER (PARTITION BY _source_row_id) AS _row_id_count FROM @this_model
) AS _metadata WHERE _ingested_at IS NULL
OR _load_id IS NULL
OR _source_row_id IS NULL
OR _row_id_count > 1
OR (
  (
    NOT _ingested_at IS NULL
  ) AND TRY_CAST(_ingested_at AS TIMESTAMP) IS NULL
)
