-- Generated by bloomery — do not edit.
-- fingerprint: blm1:4d0cf5081ce6cf3d24c290466fe937860127b2d7fb4f78c1261b16ed42e30141
AUDIT (
  name stock_level_matches_snapshot_reconcile,
  blocking false
);

SELECT * FROM @this_model WHERE NOT within_tolerance
