-- Generated by bloomery — do not edit.
-- fingerprint: blm1:08dd4597923e8023692dde403c6dee821a9a0af449113b6090c2855e74674711
AUDIT (
  name stock_level_matches_snapshot_reconcile,
  blocking false
);

SELECT * FROM @this_model WHERE NOT within_tolerance
