-- Generated by bloomery — do not edit.
-- fingerprint: blm1:f595fb0e6f7c091f44b28531b060a9cb8a7feff22f5f2fe62dcc5d7d83cb3702
AUDIT (
  name stock_level_matches_snapshot_reconcile,
  blocking false
);

SELECT * FROM @this_model WHERE NOT within_tolerance
