-- Generated by bloomery — do not edit.
-- fingerprint: blm1:f123d3719f329791c37b128839f1802f9da33eccecaeb9535e5c7938a40c007d
MODEL (
  name silver.order_line__reject,
  kind INCREMENTAL_BY_UNIQUE_KEY (unique_key (reject_id), when_matched (WHEN MATCHED THEN UPDATE SET target.source_relation = source.source_relation, target.mapping = source.mapping, target.mapping_version = source.mapping_version, target.failed_rules = source.failed_rules, target.key_values = source.key_values, target.raw = source.raw, target._load_id = source._load_id, target._ingested_at = source._ingested_at, target._source_row_id = source._source_row_id, target.first_seen = COALESCE(target.first_seen, source.first_seen), target.last_seen = source.last_seen, target.resolved_at = source.resolved_at, target.last_evaluated_at = COALESCE(target.last_evaluated_at, source.last_evaluated_at))),
  grain (reject_id)
);

SELECT
  _extract.reject_id,
  _extract.source_relation,
  _extract.mapping,
  _extract.mapping_version,
  CONCAT(
    CONCAT(
      CONCAT(
        CONCAT(
          CONCAT(
            CONCAT(
              CONCAT(
                CASE
                  WHEN _extract._branch_gift_note_coercible
                  THEN ARRAY('gift_note_coercible')
                  ELSE CAST(ARRAY() AS ARRAY<STRING>)
                END,
                CASE
                  WHEN _extract._branch_line_no_coercible
                  THEN ARRAY('line_no_coercible')
                  ELSE CAST(ARRAY() AS ARRAY<STRING>)
                END
              ),
              CASE
                WHEN _extract._branch_order_id_coercible
                THEN ARRAY('order_id_coercible')
                ELSE CAST(ARRAY() AS ARRAY<STRING>)
              END
            ),
            CASE
              WHEN _extract._branch_placed_at_coercible
              THEN ARRAY('placed_at_coercible')
              ELSE CAST(ARRAY() AS ARRAY<STRING>)
            END
          ),
          CASE
            WHEN _extract._branch_quantity_coercible
            THEN ARRAY('quantity_coercible')
            ELSE CAST(ARRAY() AS ARRAY<STRING>)
          END
        ),
        CASE
          WHEN _extract._branch_sku_coercible
          THEN ARRAY('sku_coercible')
          ELSE CAST(ARRAY() AS ARRAY<STRING>)
        END
      ),
      CASE
        WHEN _extract._branch_status_coercible
        THEN ARRAY('status_coercible')
        ELSE CAST(ARRAY() AS ARRAY<STRING>)
      END
    ),
    CASE
      WHEN _extract._branch_status_in_enum
      THEN ARRAY('status_in_enum')
      ELSE CAST(ARRAY() AS ARRAY<STRING>)
    END
  ) AS failed_rules,
  TO_JSON(NAMED_STRUCT('line_no', _extract.line_no, 'order_id', _extract.order_id)) AS key_values,
  _extract._raw AS raw,
  _extract._load_id,
  _extract._ingested_at,
  _extract._source_row_id,
  _extract._ingested_at AS first_seen,
  _extract._ingested_at AS last_seen,
  CAST(NULL AS TIMESTAMP_NTZ) AS resolved_at,
  CAST(NULL AS TIMESTAMP_NTZ) AS last_evaluated_at
FROM (
  SELECT
    *
  FROM (
    SELECT
      TRY_CAST(properties:gift_note AS STRING) AS gift_note,
      TRY_CAST(position AS BIGINT) AS line_no,
      TRY_CAST(`order`:id AS STRING) AS order_id,
      TRY_CAST(CASE
        WHEN SUBSTRING(CAST(created_at AS STRING), 11) LIKE '%+%'
        OR SUBSTRING(CAST(created_at AS STRING), 11) LIKE '%-%'
        THEN NULL
        ELSE REPLACE(REPLACE(CAST(created_at AS STRING), 'T', ' '), 't', ' ')
      END AS TIMESTAMP_NTZ) AS placed_at,
      TRY_CAST(quantity AS BIGINT) AS quantity,
      TRY_CAST(variant:sku AS STRING) AS sku,
      CASE TRY_CAST(financial_status AS STRING)
        WHEN 'pending'
        THEN 'open'
        WHEN 'paid'
        THEN 'closed'
        WHEN 'refunded'
        THEN 'reversed'
        ELSE TRY_CAST(financial_status AS STRING)
      END AS status,
      _ingested_at,
      _load_id,
      _source_row_id,
      TRY_CAST(properties:gift_note AS STRING) IS NULL
      AND (
        NOT properties:gift_note IS NULL
      ) AS _branch_gift_note_coercible,
      TRY_CAST(position AS BIGINT) IS NULL AND (
        NOT position IS NULL
      ) AS _branch_line_no_coercible,
      TRY_CAST(`order`:id AS STRING) IS NULL AND (
        NOT `order`:id IS NULL
      ) AS _branch_order_id_coercible,
      TRY_CAST(CASE
        WHEN SUBSTRING(CAST(created_at AS STRING), 11) LIKE '%+%'
        OR SUBSTRING(CAST(created_at AS STRING), 11) LIKE '%-%'
        THEN NULL
        ELSE REPLACE(REPLACE(CAST(created_at AS STRING), 'T', ' '), 't', ' ')
      END AS TIMESTAMP_NTZ) IS NULL
      AND (
        NOT created_at IS NULL
      ) AS _branch_placed_at_coercible,
      TRY_CAST(quantity AS BIGINT) IS NULL AND (
        NOT quantity IS NULL
      ) AS _branch_quantity_coercible,
      TRY_CAST(variant:sku AS STRING) IS NULL AND (
        NOT variant:sku IS NULL
      ) AS _branch_sku_coercible,
      CASE TRY_CAST(financial_status AS STRING)
        WHEN 'pending'
        THEN 'open'
        WHEN 'paid'
        THEN 'closed'
        WHEN 'refunded'
        THEN 'reversed'
        ELSE TRY_CAST(financial_status AS STRING)
      END IS NULL
      AND (
        NOT financial_status IS NULL
      ) AS _branch_status_coercible,
      NOT CASE TRY_CAST(financial_status AS STRING)
        WHEN 'pending'
        THEN 'open'
        WHEN 'paid'
        THEN 'closed'
        WHEN 'refunded'
        THEN 'reversed'
        ELSE TRY_CAST(financial_status AS STRING)
      END IN ('closed', 'open', 'reversed') AS _branch_status_in_enum,
      TO_JSON(
        NAMED_STRUCT(
          '_ingested_at',
          _ingested_at,
          '_load_id',
          _load_id,
          '_source_row_id',
          _source_row_id,
          'created_at',
          created_at,
          'financial_status',
          financial_status,
          'order',
          `order`,
          'position',
          position,
          'properties',
          properties,
          'quantity',
          quantity,
          'variant',
          variant
        )
      ) AS _raw,
      'shopify__order_lines' AS _source,
      SHA2(
        CONCAT(
          'S20:shopify__order_lines',
          'S',
          CAST(LENGTH(_source_row_id) AS STRING),
          ':',
          _source_row_id
        ),
        256
      ) AS reject_id,
      'shopify__order_lines' AS source_relation,
      'shopify__order_lines->order_line' AS mapping,
      1 AS mapping_version
    FROM bronze.shopify__order_lines
    UNION ALL
    SELECT
      CAST(NULL AS STRING) AS gift_note,
      TRY_CAST(item_index AS BIGINT) AS line_no,
      TRY_CAST(order_number AS STRING) AS order_id,
      TRY_CAST(CASE
        WHEN SUBSTRING(CAST(created AS STRING), 11) LIKE '%+%'
        OR SUBSTRING(CAST(created AS STRING), 11) LIKE '%-%'
        THEN NULL
        ELSE REPLACE(REPLACE(CAST(created AS STRING), 'T', ' '), 't', ' ')
      END AS TIMESTAMP_NTZ) AS placed_at,
      TRY_CAST(qty AS BIGINT) AS quantity,
      TRY_CAST(product_sku AS STRING) AS sku,
      CASE TRY_CAST(state AS STRING)
        WHEN 'PROCESSING'
        THEN 'open'
        WHEN 'COMPLETE'
        THEN 'closed'
        ELSE TRY_CAST(state AS STRING)
      END AS status,
      _ingested_at,
      _load_id,
      _source_row_id,
      FALSE AS _branch_gift_note_coercible,
      TRY_CAST(item_index AS BIGINT) IS NULL AND (
        NOT item_index IS NULL
      ) AS _branch_line_no_coercible,
      TRY_CAST(order_number AS STRING) IS NULL AND (
        NOT order_number IS NULL
      ) AS _branch_order_id_coercible,
      TRY_CAST(CASE
        WHEN SUBSTRING(CAST(created AS STRING), 11) LIKE '%+%'
        OR SUBSTRING(CAST(created AS STRING), 11) LIKE '%-%'
        THEN NULL
        ELSE REPLACE(REPLACE(CAST(created AS STRING), 'T', ' '), 't', ' ')
      END AS TIMESTAMP_NTZ) IS NULL
      AND (
        NOT created IS NULL
      ) AS _branch_placed_at_coercible,
      TRY_CAST(qty AS BIGINT) IS NULL AND (
        NOT qty IS NULL
      ) AS _branch_quantity_coercible,
      TRY_CAST(product_sku AS STRING) IS NULL AND (
        NOT product_sku IS NULL
      ) AS _branch_sku_coercible,
      CASE TRY_CAST(state AS STRING)
        WHEN 'PROCESSING'
        THEN 'open'
        WHEN 'COMPLETE'
        THEN 'closed'
        ELSE TRY_CAST(state AS STRING)
      END IS NULL
      AND (
        NOT state IS NULL
      ) AS _branch_status_coercible,
      NOT CASE TRY_CAST(state AS STRING)
        WHEN 'PROCESSING'
        THEN 'open'
        WHEN 'COMPLETE'
        THEN 'closed'
        ELSE TRY_CAST(state AS STRING)
      END IN ('closed', 'open') AS _branch_status_in_enum,
      TO_JSON(
        NAMED_STRUCT(
          '_ingested_at',
          _ingested_at,
          '_load_id',
          _load_id,
          '_source_row_id',
          _source_row_id,
          'created',
          created,
          'item_index',
          item_index,
          'order_number',
          order_number,
          'product_sku',
          product_sku,
          'qty',
          qty,
          'state',
          state
        )
      ) AS _raw,
      'woo__order_lines' AS _source,
      SHA2(
        CONCAT('S16:woo__order_lines', 'S', CAST(LENGTH(_source_row_id) AS STRING), ':', _source_row_id),
        256
      ) AS reject_id,
      'woo__order_lines' AS source_relation,
      'woo__order_lines->order_line' AS mapping,
      1 AS mapping_version
    FROM bronze.woo__order_lines
  ) AS _extract
  QUALIFY
    ROW_NUMBER() OVER (
      PARTITION BY order_id, line_no
      ORDER BY placed_at DESC, line_no DESC, _source DESC, _source_row_id DESC
    ) = 1
) AS _extract
WHERE
  COALESCE(
    (
      _extract._branch_gift_note_coercible
      OR _extract._branch_order_id_coercible
      OR _extract._branch_quantity_coercible
      OR _extract._branch_sku_coercible
      OR _extract._branch_status_coercible
      OR _extract._branch_status_in_enum
    ),
    FALSE
  )
