-- Generated by bloomery — do not edit.
-- fingerprint: blm1:4bbad191a61dccb442835e67992d617af3d6077b80515a275a91481c92ba089c
MODEL (
  name gold.mart_data_quality,
  kind FULL,
  grain (entity, rule)
);

WITH _quality_rows_order_line AS (
  SELECT
    _quality_flags AS _flags,
    FALSE AS _quarantined
  FROM silver.order_line
  UNION ALL
  SELECT
    failed_rules AS _flags,
    TRUE AS _quarantined
  FROM silver.order_line__reject
  WHERE
    resolved_at IS NULL
)
SELECT
  _stamped.disposition,
  _stamped.entity,
  _stamped.mapping,
  _stamped.rows_deduped,
  _stamped.rows_evaluated,
  _stamped.rows_failed,
  _stamped.rows_quarantined,
  _stamped.rule,
  _stamped.run_date,
  CAST(DATE_TRUNC(_stamped.run_date, DAY) AS DATE) AS run_day,
  _stamped.run_id,
  CAST(DATE_TRUNC(_stamped.run_date, MONTH) AS DATE) AS run_month,
  CAST(DATE_TRUNC(_stamped.run_date, QUARTER) AS DATE) AS run_quarter,
  CAST(DATE_TRUNC(_stamped.run_date, WEEK) AS DATE) AS run_week,
  CAST(DATE_TRUNC(_stamped.run_date, YEAR) AS DATE) AS run_year
FROM (
  SELECT
    _evaluations.entity,
    _evaluations.mapping,
    _evaluations.rule,
    _evaluations.disposition,
    _evaluations.rows_evaluated,
    _evaluations.rows_failed,
    _evaluations.rows_quarantined,
    _evaluations.rows_deduped,
    CAST(NULL AS STRING) AS run_id, /* run_id: supplied by the executing engine's run context (S-0033/the-quality-mart); the pinned target exposes no macro for it — fill this column in your runner */
    CAST(@execution_ds AS DATE) AS run_date
  FROM (
    SELECT
      'order_line' AS entity,
      'shopify__order_lines+woo__order_lines->order_line' AS mapping,
      '(entity)' AS rule,
      '(entity)' AS disposition,
      COUNT(*) AS rows_evaluated,
      0 AS rows_failed,
      COALESCE(SUM(CASE WHEN _quarantined THEN 1 ELSE 0 END), 0) AS rows_quarantined,
      (
        SELECT
          COUNT(*)
        FROM (
          SELECT
            SAFE_CAST(JSON_EXTRACT_SCALAR(properties, '$.gift_note') AS STRING) AS gift_note,
            SAFE_CAST(position AS INT64) AS line_no,
            SAFE_CAST(JSON_EXTRACT_SCALAR(`order`, '$.id') AS STRING) AS order_id,
            SAFE_CAST(CASE
              WHEN SUBSTR(CAST(created_at AS STRING), 11) LIKE '%+%'
              OR SUBSTR(CAST(created_at AS STRING), 11) LIKE '%-%'
              THEN NULL
              ELSE RTRIM(REPLACE(REPLACE(CAST(created_at AS STRING), 'T', ' '), 't', ' '), 'Zz')
            END AS DATETIME) AS placed_at,
            SAFE_CAST(quantity AS INT64) AS quantity,
            SAFE_CAST(JSON_EXTRACT_SCALAR(variant, '$.sku') AS STRING) AS sku,
            CASE SAFE_CAST(financial_status AS STRING)
              WHEN 'pending'
              THEN 'open'
              WHEN 'paid'
              THEN 'closed'
              WHEN 'refunded'
              THEN 'reversed'
              ELSE SAFE_CAST(financial_status AS STRING)
            END AS status,
            _ingested_at,
            _load_id,
            _source_row_id,
            SAFE_CAST(JSON_EXTRACT_SCALAR(properties, '$.gift_note') AS STRING) IS NULL
            AND (
              NOT JSON_EXTRACT_SCALAR(properties, '$.gift_note') IS NULL
            ) AS _branch_gift_note_coercible,
            SAFE_CAST(position AS INT64) IS NULL AND (
              NOT position IS NULL
            ) AS _branch_line_no_coercible,
            SAFE_CAST(JSON_EXTRACT_SCALAR(`order`, '$.id') AS STRING) IS NULL
            AND (
              NOT JSON_EXTRACT_SCALAR(`order`, '$.id') IS NULL
            ) AS _branch_order_id_coercible,
            SAFE_CAST(CASE
              WHEN SUBSTR(CAST(created_at AS STRING), 11) LIKE '%+%'
              OR SUBSTR(CAST(created_at AS STRING), 11) LIKE '%-%'
              THEN NULL
              ELSE RTRIM(REPLACE(REPLACE(CAST(created_at AS STRING), 'T', ' '), 't', ' '), 'Zz')
            END AS DATETIME) IS NULL
            AND (
              NOT created_at IS NULL
            ) AS _branch_placed_at_coercible,
            SAFE_CAST(quantity AS INT64) IS NULL AND (
              NOT quantity IS NULL
            ) AS _branch_quantity_coercible,
            SAFE_CAST(JSON_EXTRACT_SCALAR(variant, '$.sku') AS STRING) IS NULL
            AND (
              NOT JSON_EXTRACT_SCALAR(variant, '$.sku') IS NULL
            ) AS _branch_sku_coercible,
            CASE SAFE_CAST(financial_status AS STRING)
              WHEN 'pending'
              THEN 'open'
              WHEN 'paid'
              THEN 'closed'
              WHEN 'refunded'
              THEN 'reversed'
              ELSE SAFE_CAST(financial_status AS STRING)
            END IS NULL
            AND (
              NOT financial_status IS NULL
            ) AS _branch_status_coercible,
            NOT CASE SAFE_CAST(financial_status AS STRING)
              WHEN 'pending'
              THEN 'open'
              WHEN 'paid'
              THEN 'closed'
              WHEN 'refunded'
              THEN 'reversed'
              ELSE SAFE_CAST(financial_status AS STRING)
            END IN ('closed', 'open', 'reversed') AS _branch_status_in_enum,
            'shopify__order_lines' AS _source
          FROM bronze.shopify__order_lines
          UNION ALL
          SELECT
            CAST(NULL AS STRING) AS gift_note,
            SAFE_CAST(item_index AS INT64) AS line_no,
            SAFE_CAST(order_number AS STRING) AS order_id,
            SAFE_CAST(CASE
              WHEN SUBSTR(CAST(created AS STRING), 11) LIKE '%+%'
              OR SUBSTR(CAST(created AS STRING), 11) LIKE '%-%'
              THEN NULL
              ELSE RTRIM(REPLACE(REPLACE(CAST(created AS STRING), 'T', ' '), 't', ' '), 'Zz')
            END AS DATETIME) AS placed_at,
            SAFE_CAST(qty AS INT64) AS quantity,
            SAFE_CAST(product_sku AS STRING) AS sku,
            CASE SAFE_CAST(state AS STRING)
              WHEN 'PROCESSING'
              THEN 'open'
              WHEN 'COMPLETE'
              THEN 'closed'
              ELSE SAFE_CAST(state AS STRING)
            END AS status,
            _ingested_at,
            _load_id,
            _source_row_id,
            FALSE AS _branch_gift_note_coercible,
            SAFE_CAST(item_index AS INT64) IS NULL AND (
              NOT item_index IS NULL
            ) AS _branch_line_no_coercible,
            SAFE_CAST(order_number AS STRING) IS NULL AND (
              NOT order_number IS NULL
            ) AS _branch_order_id_coercible,
            SAFE_CAST(CASE
              WHEN SUBSTR(CAST(created AS STRING), 11) LIKE '%+%'
              OR SUBSTR(CAST(created AS STRING), 11) LIKE '%-%'
              THEN NULL
              ELSE RTRIM(REPLACE(REPLACE(CAST(created AS STRING), 'T', ' '), 't', ' '), 'Zz')
            END AS DATETIME) IS NULL
            AND (
              NOT created IS NULL
            ) AS _branch_placed_at_coercible,
            SAFE_CAST(qty AS INT64) IS NULL AND (
              NOT qty IS NULL
            ) AS _branch_quantity_coercible,
            SAFE_CAST(product_sku AS STRING) IS NULL AND (
              NOT product_sku IS NULL
            ) AS _branch_sku_coercible,
            CASE SAFE_CAST(state AS STRING)
              WHEN 'PROCESSING'
              THEN 'open'
              WHEN 'COMPLETE'
              THEN 'closed'
              ELSE SAFE_CAST(state AS STRING)
            END IS NULL
            AND (
              NOT state IS NULL
            ) AS _branch_status_coercible,
            NOT CASE SAFE_CAST(state AS STRING)
              WHEN 'PROCESSING'
              THEN 'open'
              WHEN 'COMPLETE'
              THEN 'closed'
              ELSE SAFE_CAST(state AS STRING)
            END IN ('closed', 'open') AS _branch_status_in_enum,
            'woo__order_lines' AS _source
          FROM bronze.woo__order_lines
        ) AS _bronze
      ) - (
        SELECT
          COUNT(*)
        FROM (
          SELECT
            *
          FROM (
            SELECT
              SAFE_CAST(JSON_EXTRACT_SCALAR(properties, '$.gift_note') AS STRING) AS gift_note,
              SAFE_CAST(position AS INT64) AS line_no,
              SAFE_CAST(JSON_EXTRACT_SCALAR(`order`, '$.id') AS STRING) AS order_id,
              SAFE_CAST(CASE
                WHEN SUBSTR(CAST(created_at AS STRING), 11) LIKE '%+%'
                OR SUBSTR(CAST(created_at AS STRING), 11) LIKE '%-%'
                THEN NULL
                ELSE RTRIM(REPLACE(REPLACE(CAST(created_at AS STRING), 'T', ' '), 't', ' '), 'Zz')
              END AS DATETIME) AS placed_at,
              SAFE_CAST(quantity AS INT64) AS quantity,
              SAFE_CAST(JSON_EXTRACT_SCALAR(variant, '$.sku') AS STRING) AS sku,
              CASE SAFE_CAST(financial_status AS STRING)
                WHEN 'pending'
                THEN 'open'
                WHEN 'paid'
                THEN 'closed'
                WHEN 'refunded'
                THEN 'reversed'
                ELSE SAFE_CAST(financial_status AS STRING)
              END AS status,
              _ingested_at,
              _load_id,
              _source_row_id,
              SAFE_CAST(JSON_EXTRACT_SCALAR(properties, '$.gift_note') AS STRING) IS NULL
              AND (
                NOT JSON_EXTRACT_SCALAR(properties, '$.gift_note') IS NULL
              ) AS _branch_gift_note_coercible,
              SAFE_CAST(position AS INT64) IS NULL AND (
                NOT position IS NULL
              ) AS _branch_line_no_coercible,
              SAFE_CAST(JSON_EXTRACT_SCALAR(`order`, '$.id') AS STRING) IS NULL
              AND (
                NOT JSON_EXTRACT_SCALAR(`order`, '$.id') IS NULL
              ) AS _branch_order_id_coercible,
              SAFE_CAST(CASE
                WHEN SUBSTR(CAST(created_at AS STRING), 11) LIKE '%+%'
                OR SUBSTR(CAST(created_at AS STRING), 11) LIKE '%-%'
                THEN NULL
                ELSE RTRIM(REPLACE(REPLACE(CAST(created_at AS STRING), 'T', ' '), 't', ' '), 'Zz')
              END AS DATETIME) IS NULL
              AND (
                NOT created_at IS NULL
              ) AS _branch_placed_at_coercible,
              SAFE_CAST(quantity AS INT64) IS NULL AND (
                NOT quantity IS NULL
              ) AS _branch_quantity_coercible,
              SAFE_CAST(JSON_EXTRACT_SCALAR(variant, '$.sku') AS STRING) IS NULL
              AND (
                NOT JSON_EXTRACT_SCALAR(variant, '$.sku') IS NULL
              ) AS _branch_sku_coercible,
              CASE SAFE_CAST(financial_status AS STRING)
                WHEN 'pending'
                THEN 'open'
                WHEN 'paid'
                THEN 'closed'
                WHEN 'refunded'
                THEN 'reversed'
                ELSE SAFE_CAST(financial_status AS STRING)
              END IS NULL
              AND (
                NOT financial_status IS NULL
              ) AS _branch_status_coercible,
              NOT CASE SAFE_CAST(financial_status AS STRING)
                WHEN 'pending'
                THEN 'open'
                WHEN 'paid'
                THEN 'closed'
                WHEN 'refunded'
                THEN 'reversed'
                ELSE SAFE_CAST(financial_status AS STRING)
              END IN ('closed', 'open', 'reversed') AS _branch_status_in_enum,
              'shopify__order_lines' AS _source
            FROM bronze.shopify__order_lines
            UNION ALL
            SELECT
              CAST(NULL AS STRING) AS gift_note,
              SAFE_CAST(item_index AS INT64) AS line_no,
              SAFE_CAST(order_number AS STRING) AS order_id,
              SAFE_CAST(CASE
                WHEN SUBSTR(CAST(created AS STRING), 11) LIKE '%+%'
                OR SUBSTR(CAST(created AS STRING), 11) LIKE '%-%'
                THEN NULL
                ELSE RTRIM(REPLACE(REPLACE(CAST(created AS STRING), 'T', ' '), 't', ' '), 'Zz')
              END AS DATETIME) AS placed_at,
              SAFE_CAST(qty AS INT64) AS quantity,
              SAFE_CAST(product_sku AS STRING) AS sku,
              CASE SAFE_CAST(state AS STRING)
                WHEN 'PROCESSING'
                THEN 'open'
                WHEN 'COMPLETE'
                THEN 'closed'
                ELSE SAFE_CAST(state AS STRING)
              END AS status,
              _ingested_at,
              _load_id,
              _source_row_id,
              FALSE AS _branch_gift_note_coercible,
              SAFE_CAST(item_index AS INT64) IS NULL AND (
                NOT item_index IS NULL
              ) AS _branch_line_no_coercible,
              SAFE_CAST(order_number AS STRING) IS NULL AND (
                NOT order_number IS NULL
              ) AS _branch_order_id_coercible,
              SAFE_CAST(CASE
                WHEN SUBSTR(CAST(created AS STRING), 11) LIKE '%+%'
                OR SUBSTR(CAST(created AS STRING), 11) LIKE '%-%'
                THEN NULL
                ELSE RTRIM(REPLACE(REPLACE(CAST(created AS STRING), 'T', ' '), 't', ' '), 'Zz')
              END AS DATETIME) IS NULL
              AND (
                NOT created IS NULL
              ) AS _branch_placed_at_coercible,
              SAFE_CAST(qty AS INT64) IS NULL AND (
                NOT qty IS NULL
              ) AS _branch_quantity_coercible,
              SAFE_CAST(product_sku AS STRING) IS NULL AND (
                NOT product_sku IS NULL
              ) AS _branch_sku_coercible,
              CASE SAFE_CAST(state AS STRING)
                WHEN 'PROCESSING'
                THEN 'open'
                WHEN 'COMPLETE'
                THEN 'closed'
                ELSE SAFE_CAST(state AS STRING)
              END IS NULL
              AND (
                NOT state IS NULL
              ) AS _branch_status_coercible,
              NOT CASE SAFE_CAST(state AS STRING)
                WHEN 'PROCESSING'
                THEN 'open'
                WHEN 'COMPLETE'
                THEN 'closed'
                ELSE SAFE_CAST(state AS STRING)
              END IN ('closed', 'open') AS _branch_status_in_enum,
              'woo__order_lines' AS _source
            FROM bronze.woo__order_lines
          ) AS _extract
          QUALIFY
            ROW_NUMBER() OVER (
              PARTITION BY order_id, line_no
              ORDER BY placed_at DESC, line_no DESC, _source DESC, _source_row_id DESC
            ) = 1
        ) AS _extract
      ) AS rows_deduped
    FROM _quality_rows_order_line
    UNION ALL
    SELECT
      'order_line' AS entity,
      'shopify__order_lines+woo__order_lines->order_line' AS mapping,
      'gift_note_coercible' AS rule,
      'quarantine' AS disposition,
      0 AS rows_evaluated,
      COALESCE(
        SUM(
          CASE
            WHEN EXISTS(
              SELECT
                1
              FROM UNNEST(_flags) AS _col
              WHERE
                _col = 'gift_note_coercible'
            )
            THEN 1
            ELSE 0
          END
        ),
        0
      ) AS rows_failed,
      0 AS rows_quarantined,
      0 AS rows_deduped
    FROM _quality_rows_order_line
    UNION ALL
    SELECT
      'order_line' AS entity,
      'shopify__order_lines+woo__order_lines->order_line' AS mapping,
      'line_no_coercible' AS rule,
      'fail' AS disposition,
      0 AS rows_evaluated,
      COALESCE(
        SUM(
          CASE
            WHEN EXISTS(
              SELECT
                1
              FROM UNNEST(_flags) AS _col
              WHERE
                _col = 'line_no_coercible'
            )
            THEN 1
            ELSE 0
          END
        ),
        0
      ) AS rows_failed,
      0 AS rows_quarantined,
      0 AS rows_deduped
    FROM _quality_rows_order_line
    UNION ALL
    SELECT
      'order_line' AS entity,
      'shopify__order_lines+woo__order_lines->order_line' AS mapping,
      'order_id_coercible' AS rule,
      'quarantine' AS disposition,
      0 AS rows_evaluated,
      COALESCE(
        SUM(
          CASE
            WHEN EXISTS(
              SELECT
                1
              FROM UNNEST(_flags) AS _col
              WHERE
                _col = 'order_id_coercible'
            )
            THEN 1
            ELSE 0
          END
        ),
        0
      ) AS rows_failed,
      0 AS rows_quarantined,
      0 AS rows_deduped
    FROM _quality_rows_order_line
    UNION ALL
    SELECT
      'order_line' AS entity,
      'shopify__order_lines+woo__order_lines->order_line' AS mapping,
      'placed_at_coercible' AS rule,
      'fail' AS disposition,
      0 AS rows_evaluated,
      COALESCE(
        SUM(
          CASE
            WHEN EXISTS(
              SELECT
                1
              FROM UNNEST(_flags) AS _col
              WHERE
                _col = 'placed_at_coercible'
            )
            THEN 1
            ELSE 0
          END
        ),
        0
      ) AS rows_failed,
      0 AS rows_quarantined,
      0 AS rows_deduped
    FROM _quality_rows_order_line
    UNION ALL
    SELECT
      'order_line' AS entity,
      'shopify__order_lines+woo__order_lines->order_line' AS mapping,
      'quantity_coercible' AS rule,
      'quarantine' AS disposition,
      0 AS rows_evaluated,
      COALESCE(
        SUM(
          CASE
            WHEN EXISTS(
              SELECT
                1
              FROM UNNEST(_flags) AS _col
              WHERE
                _col = 'quantity_coercible'
            )
            THEN 1
            ELSE 0
          END
        ),
        0
      ) AS rows_failed,
      0 AS rows_quarantined,
      0 AS rows_deduped
    FROM _quality_rows_order_line
    UNION ALL
    SELECT
      'order_line' AS entity,
      'shopify__order_lines+woo__order_lines->order_line' AS mapping,
      'sku_coercible' AS rule,
      'quarantine' AS disposition,
      0 AS rows_evaluated,
      COALESCE(
        SUM(
          CASE
            WHEN EXISTS(
              SELECT
                1
              FROM UNNEST(_flags) AS _col
              WHERE
                _col = 'sku_coercible'
            )
            THEN 1
            ELSE 0
          END
        ),
        0
      ) AS rows_failed,
      0 AS rows_quarantined,
      0 AS rows_deduped
    FROM _quality_rows_order_line
    UNION ALL
    SELECT
      'order_line' AS entity,
      'shopify__order_lines+woo__order_lines->order_line' AS mapping,
      'status_coercible' AS rule,
      'quarantine' AS disposition,
      0 AS rows_evaluated,
      COALESCE(
        SUM(
          CASE
            WHEN EXISTS(
              SELECT
                1
              FROM UNNEST(_flags) AS _col
              WHERE
                _col = 'status_coercible'
            )
            THEN 1
            ELSE 0
          END
        ),
        0
      ) AS rows_failed,
      0 AS rows_quarantined,
      0 AS rows_deduped
    FROM _quality_rows_order_line
    UNION ALL
    SELECT
      'order_line' AS entity,
      'shopify__order_lines+woo__order_lines->order_line' AS mapping,
      'status_in_enum' AS rule,
      'quarantine' AS disposition,
      0 AS rows_evaluated,
      COALESCE(
        SUM(
          CASE
            WHEN EXISTS(
              SELECT
                1
              FROM UNNEST(_flags) AS _col
              WHERE
                _col = 'status_in_enum'
            )
            THEN 1
            ELSE 0
          END
        ),
        0
      ) AS rows_failed,
      0 AS rows_quarantined,
      0 AS rows_deduped
    FROM _quality_rows_order_line
  ) AS _evaluations
) AS _stamped
