-- Generated by bloomery — do not edit.
-- fingerprint: blm1:c63e5f8d5a9a3ed8654688ca3ae0126803dc498e332e44fa3b493a01cabc3785
{% macro generate_schema_name(custom_schema_name, node) -%}
{%- if custom_schema_name is none -%}
{{ target.schema }}
{%- else -%}
{{ custom_schema_name | trim }}
{%- endif -%}
{%- endmacro %}
