-- Generated by bloomery — do not edit.
-- fingerprint: blm1:9defeb39a846329c3930cb3eae6e6149372231f8188f7060359d112d69f52762
{% macro generate_schema_name(custom_schema_name, node) -%}
{%- if custom_schema_name is none -%}
{{ target.schema }}
{%- else -%}
{{ custom_schema_name | trim }}
{%- endif -%}
{%- endmacro %}
