-- Generated by bloomery — do not edit.
-- fingerprint: blm1:85868b90fb2c8058fae372853f795640688a50f36856ecadca960e559cf20854
{% macro generate_schema_name(custom_schema_name, node) -%}
{%- if custom_schema_name is none -%}
{{ target.schema }}
{%- else -%}
{{ custom_schema_name | trim }}
{%- endif -%}
{%- endmacro %}
