-- Generated by bloomery — do not edit.
-- fingerprint: blm1:5ae38717919da8d2dfe08487325ec8b5f487d4419d8d1d813a2daf86c7886a44
{{ config(severity='error') }}

SELECT
  _entity.order_id,
  _entity.line_no,
  COUNT(*) AS key_rows
FROM {{ ref('order_item') }} AS _entity
GROUP BY
  _entity.order_id,
  _entity.line_no
HAVING
  COUNT(*) > 1
