-- Generated by bloomery — do not edit.
-- fingerprint: blm1:f08fc2ecdb327ef3d3cb465ef3d694be3071044eb6fc14d986f22e99ba91cf6f
{{ config(severity='error') }}

SELECT
  _entity.order_id,
  _entity.line_no,
  COUNT(*) AS key_rows
FROM {{ ref('order_item') }} AS _entity
GROUP BY
  _entity.order_id,
  _entity.line_no
HAVING
  COUNT(*) > 1
