-- Generated by bloomery — do not edit.
-- fingerprint: blm1:161e0fe2c0cb8a1aece5f7fdf00fdc7350d36da6bce4c4bde896257aa6034335
MODEL (
  name silver.order_item,
  kind INCREMENTAL_BY_TIME_RANGE (time_column order_date),
  grain (order_id, line_no),
  partitioned_by (days(order_date)),
  audits (order_item_key_unique, not_null(columns := (order_date)))
);

SELECT
  CAST(index AS INT64) AS line_no,
  DATETIME(
    TIMESTAMP(
      CAST(CASE
        WHEN (
          SUBSTR(CAST(created_at AS STRING), 11) LIKE '%+%'
          OR SUBSTR(CAST(created_at AS STRING), 11) LIKE '%-%'
        )
        OR UPPER(SUBSTR(CAST(created_at AS STRING), 11)) LIKE '%Z%'
        THEN NULL
        ELSE RTRIM(REPLACE(REPLACE(CAST(created_at AS STRING), 'T', ' '), 't', ' '), 'Zz')
      END AS DATETIME),
      'Europe/Paris'
    ),
    'UTC'
  ) AS order_date,
  CAST(order_id AS STRING) AS order_id,
  CAST(qty AS INT64) AS quantity,
  CAST(CAST(total AS NUMERIC) / qty AS NUMERIC) AS unit_price,
  ARRAY<STRING>[] AS _quality_flags,
  TRUE AS _quality_ok
FROM bronze.shopify__order_lines
