-- Generated by bloomery — do not edit.
-- fingerprint: blm1:0f1cacfbce48b9897b7c2a9480e7e0688c86e725d1311728307754adaf469942
MODEL (
  name silver.order,
  kind FULL,
  owner 'commerce-platform@example.com',
  grain (order_id)
);

SELECT
  CAST(JSON_EXTRACT_SCALAR(customer, '$.id') AS STRING) AS customer_id,
  CAST(id AS STRING) AS order_id,
  ARRAY<STRING>[] AS _quality_flags,
  TRUE AS _quality_ok
FROM bronze.shopify__orders
