-- Generated by bloomery — do not edit.
-- fingerprint: blm1:2b6372ca8b47ba0246a75ad73d731f63e525b4dd7b4879016523384377857a62
MODEL (
  name silver.order_item,
  kind INCREMENTAL_BY_TIME_RANGE (time_column order_date),
  grain (order_id, line_no),
  partitioned_by (days(order_date)),
  audits (not_null(columns := (order_date)))
);

SELECT
  CAST(index AS INT64) AS line_no,
  DATETIME(
    TIMESTAMP(
      CAST(CASE
        WHEN SUBSTR(CAST(created_at AS STRING), 11) LIKE '%+%'
        OR SUBSTR(CAST(created_at AS STRING), 11) LIKE '%-%'
        THEN NULL
        ELSE REPLACE(REPLACE(CAST(created_at AS STRING), 'T', ' '), 't', ' ')
      END AS DATETIME),
      'Europe/Paris'
    ),
    'UTC'
  ) AS order_date,
  CAST(order_id AS STRING) AS order_id,
  CAST(qty AS INT64) AS quantity,
  CAST(total / qty AS NUMERIC) AS unit_price,
  ARRAY<STRING>[] AS _quality_flags,
  TRUE AS _quality_ok
FROM bronze.shopify__order_lines
