-- Generated by bloomery — do not edit.
-- fingerprint: blm1:e2bece50e61da1d660b60e35f05ae575ab24ee1d2e194f6ab58afed8dda3c3b7
MODEL (
  name silver.order,
  kind FULL,
  owner 'commerce-platform@example.com',
  grain (order_id)
);

SELECT
  CAST(JSON_EXTRACT_SCALAR(customer, '$.id') AS STRING) AS customer_id,
  CAST(id AS STRING) AS order_id,
  ARRAY<STRING>[] AS _quality_flags,
  TRUE AS _quality_ok
FROM bronze.shopify__orders
