-- Generated by bloomery — do not edit.
-- fingerprint: blm1:773eb32bb4549a48391efb186c0fc40e5f5ec081728ba304dd668e5c73a2b6fa
MODEL (
  name silver.order_line,
  kind FULL,
  grain (order_id, line_no),
  audits (order_line_source_collision)
);

SELECT
  *,
  CAST(ARRAY[] AS TEXT[]) AS _quality_flags,
  TRUE AS _quality_ok
FROM (
  SELECT
    CAST(properties ->> 'gift_note' AS TEXT) AS gift_note,
    CAST(position AS BIGINT) AS line_no,
    CAST("order" ->> 'id' AS TEXT) AS order_id,
    CAST(quantity AS BIGINT) AS quantity,
    CAST(variant ->> 'sku' AS TEXT) AS sku,
    'shopify__order_lines' AS _source
  FROM bronze.shopify__order_lines
  UNION ALL
  SELECT
    CAST(NULL AS TEXT) AS gift_note,
    CAST(item_index AS BIGINT) AS line_no,
    CAST(order_number AS TEXT) AS order_id,
    CAST(qty AS BIGINT) AS quantity,
    CAST(product_sku AS TEXT) AS sku,
    'woo__order_lines' AS _source
  FROM bronze.woo__order_lines
) AS _extract
