-- Generated by bloomery — do not edit.
-- fingerprint: blm1:161e0fe2c0cb8a1aece5f7fdf00fdc7350d36da6bce4c4bde896257aa6034335
AUDIT (
  name order_key_unique
);

SELECT
  _entity.order_id,
  COUNT(*) AS key_rows
FROM @this_model AS _entity
GROUP BY
  _entity.order_id
HAVING
  COUNT(*) > 1
