-- Generated by bloomery — do not edit.
-- fingerprint: blm1:053088bdbcb28a99adaa45be6671004431861b7ed332b6e29b911d2edbc61659
AUDIT (
  name order_key_unique
);

SELECT
  _entity.order_id,
  COUNT(*) AS key_rows
FROM @this_model AS _entity
GROUP BY
  _entity.order_id
HAVING
  COUNT(*) > 1
