-- Generated by bloomery — do not edit.
-- fingerprint: blm1:143f2bec68e18cb8f8cf9f8fe87ccd4f92f1e9cdaf64386c14cd393aa426597a
MODEL (
  name gold.mart_order_items_monthly,
  kind FULL,
  grain (order_customer_id, ordered_month)
);

SELECT
  order_customer_id,
  ordered_month,
  SUM(unit_price * quantity) AS gross_revenue
FROM gold.mart_order_items
GROUP BY
  order_customer_id,
  ordered_month
