-- Generated by bloomery — do not edit.
-- fingerprint: blm1:3d36f01f35658564a01395122f446f4a816bcca7dbc64f8dfd77554336dcc284
MODEL (
  name gold.mart_order_items_monthly,
  kind FULL,
  grain (order_customer_id, ordered_month)
);

SELECT
  order_customer_id,
  ordered_month,
  SUM(unit_price * quantity) AS gross_revenue
FROM gold.mart_order_items
GROUP BY
  order_customer_id,
  ordered_month
