-- Generated by bloomery — do not edit.
-- fingerprint: blm1:7e8d92ec1e27f7f4e1ea551b2ae205bdfdc17841d5310c440b11f683be2527f6
MODEL (
  name gold.mart_order_items_monthly,
  kind FULL,
  grain (order_customer_id, ordered_month)
);

SELECT
  order_customer_id,
  ordered_month,
  SUM(unit_price * quantity) AS gross_revenue
FROM gold.mart_order_items
GROUP BY
  order_customer_id,
  ordered_month
