-- Generated by bloomery — do not edit.
-- fingerprint: blm1:4c7cd2d870c6bfd7bc8858ac646d6b4b94301995878fcdec1476dcf3b89de144
MODEL (
  name gold.mart_order_items,
  kind FULL,
  grain (order_id, line_no)
);

SELECT
  order_item.line_no AS line_no,
  order_.customer_id AS order_customer_id,
  order_item.order_date AS order_date,
  order_item.order_id AS order_id,
  order_.order_id AS order_order_id,
  CAST(DATE_TRUNC('DAY', order_item.order_date) AS DATE) AS ordered_day,
  CAST(DATE_TRUNC('MONTH', order_item.order_date) AS DATE) AS ordered_month,
  CAST(DATE_TRUNC('QUARTER', order_item.order_date) AS DATE) AS ordered_quarter,
  CAST(DATE_TRUNC('WEEK', order_item.order_date) AS DATE) AS ordered_week,
  CAST(DATE_TRUNC('YEAR', order_item.order_date) AS DATE) AS ordered_year,
  order_item.quantity AS quantity,
  order_item.unit_price AS unit_price
FROM silver.order_item AS order_item
LEFT JOIN silver."order" AS order_
  ON order_item.order_id = order_.order_id
