-- Generated by bloomery — do not edit.
-- fingerprint: blm1:bae1d63a2f6c90390eba56ad1c3551d56c783422f79e57c5584f81d03b3b8c74
MODEL (
  name silver.order,
  kind FULL,
  grain (order_id)
);

SELECT
  CAST(amount AS DECIMAL(12, 4)) AS amount,
  CAST(order_date AS DATE) AS order_date,
  CAST(id AS VARCHAR) AS order_id,
  CAST(ship_date AS DATE) AS ship_date,
  CAST(ARRAY[] AS ARRAY(VARCHAR)) AS _quality_flags,
  TRUE AS _quality_ok
FROM bronze.oms__orders
