-- Generated by bloomery — do not edit.
-- fingerprint: blm1:3ca3bdb45f0e3d383f8fac41a8b92cc43113edd4f7f2ebb38938f576997b5a5e
MODEL (
  name silver.order,
  kind FULL,
  grain (order_id)
);

SELECT
  CAST(amount AS DECIMAL(12, 4)) AS amount,
  CAST(order_date AS DATE) AS order_date,
  CAST(id AS VARCHAR) AS order_id,
  CAST(ship_date AS DATE) AS ship_date,
  CAST(ARRAY[] AS ARRAY(VARCHAR)) AS _quality_flags,
  TRUE AS _quality_ok
FROM bronze.oms__orders
