-- Generated by bloomery — do not edit.
-- fingerprint: blm1:00cb4f3ae310113de186acdcbd34966cb33af65e1696b7e5c476dd363ed4bd97
{{ config(materialized='table') }}

SELECT
  CAST(date_day AS DATE) AS date_day,
  CAST(DATE_TRUNC('MONTH', date_day) AS DATE) AS date_month,
  CAST(DATE_TRUNC('QUARTER', date_day) AS DATE) AS date_quarter,
  CAST(DATE_TRUNC('WEEK', date_day) AS DATE) AS date_week,
  CAST(DATE_TRUNC('YEAR', date_day) AS DATE) AS date_year
FROM GENERATE_SERIES(CAST('2023-01-01' AS DATE), CAST('2027-12-31' AS DATE), INTERVAL '1 DAY') AS date_day(date_day)
