-- Generated by bloomery — do not edit.
-- fingerprint: blm1:b466cb8ce46bb2149cba8a536cccc6af94ba1d98cd1437c0455e5f522c357190
{{ config(materialized='table') }}

SELECT
  CAST(date_day AS DATE) AS date_day,
  CAST(DATE_TRUNC('MONTH', date_day) AS DATE) AS date_month,
  CAST(DATE_TRUNC('QUARTER', date_day) AS DATE) AS date_quarter,
  CAST(DATE_TRUNC('WEEK', date_day) AS DATE) AS date_week,
  CAST(DATE_TRUNC('YEAR', date_day) AS DATE) AS date_year
FROM GENERATE_SERIES(CAST('2023-01-01' AS DATE), CAST('2027-12-31' AS DATE), INTERVAL '1 DAY') AS date_day(date_day)
