-- Generated by bloomery — do not edit.
-- fingerprint: blm1:d32b82ce79b586c4e1900987bff83e7c4bfc77a2d0f52af62fdec07b0d63568f
{{ config(materialized='table') }}

SELECT
  q_line.amount AS amount,
  q_line.code AS code,
  NOT q_line._quality_ok AS has_quality_flags,
  q_line.line_no AS line_no,
  q_line.order_date AS order_date,
  q_line.order_id AS order_id,
  CAST(DATE_TRUNC('DAY', q_line.order_date) AS DATE) AS ordered_day,
  CAST(DATE_TRUNC('MONTH', q_line.order_date) AS DATE) AS ordered_month,
  CAST(DATE_TRUNC('QUARTER', q_line.order_date) AS DATE) AS ordered_quarter,
  CAST(DATE_TRUNC('WEEK', q_line.order_date) AS DATE) AS ordered_week,
  CAST(DATE_TRUNC('YEAR', q_line.order_date) AS DATE) AS ordered_year,
  q_line.status AS status
FROM {{ ref('q_line') }} AS q_line
