-- Generated by bloomery — do not edit.
-- fingerprint: blm1:b5bf2fa542b0b18f51126e0eb175da99d6abaf964d79e6634a7a4d57439d08e2
{{ config(materialized='table') }}

WITH _quality_rows_q_code AS (
  SELECT
    _quality_flags AS _flags,
    FALSE AS _quarantined
  FROM {{ ref('q_code') }}
  UNION ALL
  SELECT
    failed_rules AS _flags,
    TRUE AS _quarantined
  FROM {{ ref('q_code__reject') }}
  WHERE
    resolved_at IS NULL
), _quality_rows_q_dup AS (
  SELECT
    _quality_flags AS _flags,
    FALSE AS _quarantined
  FROM {{ ref('q_dup') }}
  UNION ALL
  SELECT
    failed_rules AS _flags,
    TRUE AS _quarantined
  FROM {{ ref('q_dup__reject') }}
  WHERE
    resolved_at IS NULL
), _quality_rows_q_line AS (
  SELECT
    _quality_flags AS _flags,
    FALSE AS _quarantined
  FROM {{ ref('q_line') }}
  UNION ALL
  SELECT
    failed_rules AS _flags,
    TRUE AS _quarantined
  FROM {{ ref('q_line__reject') }}
  WHERE
    resolved_at IS NULL
)
SELECT
  _stamped.disposition,
  _stamped.entity,
  _stamped.mapping,
  _stamped.rows_deduped,
  _stamped.rows_evaluated,
  _stamped.rows_failed,
  _stamped.rows_quarantined,
  _stamped.rule,
  _stamped.run_date,
  CAST(DATE_TRUNC('DAY', _stamped.run_date) AS DATE) AS run_day,
  _stamped.run_id,
  CAST(DATE_TRUNC('MONTH', _stamped.run_date) AS DATE) AS run_month,
  CAST(DATE_TRUNC('QUARTER', _stamped.run_date) AS DATE) AS run_quarter,
  CAST(DATE_TRUNC('WEEK', _stamped.run_date) AS DATE) AS run_week,
  CAST(DATE_TRUNC('YEAR', _stamped.run_date) AS DATE) AS run_year
FROM (
  SELECT
    _evaluations.entity,
    _evaluations.mapping,
    _evaluations.rule,
    _evaluations.disposition,
    _evaluations.rows_evaluated,
    _evaluations.rows_failed,
    _evaluations.rows_quarantined,
    _evaluations.rows_deduped,
    CAST('{{ invocation_id }}' AS TEXT) AS run_id,
    CAST('{{ run_started_at.strftime("%Y-%m-%d") }}' AS DATE) AS run_date
  FROM (
    SELECT
      'q_code' AS entity,
      'q__codes->q_code' AS mapping,
      '(entity)' AS rule,
      '(entity)' AS disposition,
      COUNT(*) AS rows_evaluated,
      0 AS rows_failed,
      COALESCE(SUM(CASE WHEN _quarantined THEN 1 ELSE 0 END), 0) AS rows_quarantined,
      0 AS rows_deduped
    FROM _quality_rows_q_code
    UNION ALL
    SELECT
      'q_code' AS entity,
      'q__codes->q_code' AS mapping,
      'code_fail_coercible' AS rule,
      'quarantine' AS disposition,
      0 AS rows_evaluated,
      COALESCE(
        SUM(
          CASE
            WHEN CASE
              WHEN 'code_fail_coercible' IS NULL
              THEN NULL
              ELSE COALESCE('code_fail_coercible' = ANY(
                _flags
              ), FALSE)
            END
            THEN 1
            ELSE 0
          END
        ),
        0
      ) AS rows_failed,
      0 AS rows_quarantined,
      0 AS rows_deduped
    FROM _quality_rows_q_code
    UNION ALL
    SELECT
      'q_code' AS entity,
      'q__codes->q_code' AS mapping,
      'code_flag_coercible' AS rule,
      'quarantine' AS disposition,
      0 AS rows_evaluated,
      COALESCE(
        SUM(
          CASE
            WHEN CASE
              WHEN 'code_flag_coercible' IS NULL
              THEN NULL
              ELSE COALESCE('code_flag_coercible' = ANY(
                _flags
              ), FALSE)
            END
            THEN 1
            ELSE 0
          END
        ),
        0
      ) AS rows_failed,
      0 AS rows_quarantined,
      0 AS rows_deduped
    FROM _quality_rows_q_code
    UNION ALL
    SELECT
      'q_code' AS entity,
      'q__codes->q_code' AS mapping,
      'code_id_coercible' AS rule,
      'quarantine' AS disposition,
      0 AS rows_evaluated,
      COALESCE(
        SUM(
          CASE
            WHEN CASE
              WHEN 'code_id_coercible' IS NULL
              THEN NULL
              ELSE COALESCE('code_id_coercible' = ANY(
                _flags
              ), FALSE)
            END
            THEN 1
            ELSE 0
          END
        ),
        0
      ) AS rows_failed,
      0 AS rows_quarantined,
      0 AS rows_deduped
    FROM _quality_rows_q_code
    UNION ALL
    SELECT
      'q_code' AS entity,
      'q__codes->q_code' AS mapping,
      'code_quar_coercible' AS rule,
      'quarantine' AS disposition,
      0 AS rows_evaluated,
      COALESCE(
        SUM(
          CASE
            WHEN CASE
              WHEN 'code_quar_coercible' IS NULL
              THEN NULL
              ELSE COALESCE('code_quar_coercible' = ANY(
                _flags
              ), FALSE)
            END
            THEN 1
            ELSE 0
          END
        ),
        0
      ) AS rows_failed,
      0 AS rows_quarantined,
      0 AS rows_deduped
    FROM _quality_rows_q_code
    UNION ALL
    SELECT
      'q_code' AS entity,
      'q__codes->q_code' AS mapping,
      'code_fail_unique' AS rule,
      'fail' AS disposition,
      0 AS rows_evaluated,
      COALESCE(
        SUM(
          CASE
            WHEN CASE
              WHEN 'code_fail_unique' IS NULL
              THEN NULL
              ELSE COALESCE('code_fail_unique' = ANY(
                _flags
              ), FALSE)
            END
            THEN 1
            ELSE 0
          END
        ),
        0
      ) AS rows_failed,
      0 AS rows_quarantined,
      0 AS rows_deduped
    FROM _quality_rows_q_code
    UNION ALL
    SELECT
      'q_code' AS entity,
      'q__codes->q_code' AS mapping,
      'code_flag_unique' AS rule,
      'flag' AS disposition,
      0 AS rows_evaluated,
      COALESCE(
        SUM(
          CASE
            WHEN CASE
              WHEN 'code_flag_unique' IS NULL
              THEN NULL
              ELSE COALESCE('code_flag_unique' = ANY(
                _flags
              ), FALSE)
            END
            THEN 1
            ELSE 0
          END
        ),
        0
      ) AS rows_failed,
      0 AS rows_quarantined,
      0 AS rows_deduped
    FROM _quality_rows_q_code
    UNION ALL
    SELECT
      'q_code' AS entity,
      'q__codes->q_code' AS mapping,
      'code_quar_unique' AS rule,
      'quarantine' AS disposition,
      0 AS rows_evaluated,
      COALESCE(
        SUM(
          CASE
            WHEN CASE
              WHEN 'code_quar_unique' IS NULL
              THEN NULL
              ELSE COALESCE('code_quar_unique' = ANY(
                _flags
              ), FALSE)
            END
            THEN 1
            ELSE 0
          END
        ),
        0
      ) AS rows_failed,
      0 AS rows_quarantined,
      0 AS rows_deduped
    FROM _quality_rows_q_code
    UNION ALL
    SELECT
      'q_dup' AS entity,
      'q__dups->q_dup' AS mapping,
      '(entity)' AS rule,
      '(entity)' AS disposition,
      COUNT(*) AS rows_evaluated,
      0 AS rows_failed,
      COALESCE(SUM(CASE WHEN _quarantined THEN 1 ELSE 0 END), 0) AS rows_quarantined,
      0 AS rows_deduped
    FROM _quality_rows_q_dup
    UNION ALL
    SELECT
      'q_dup' AS entity,
      'q__dups->q_dup' AS mapping,
      'group_id_coercible' AS rule,
      'quarantine' AS disposition,
      0 AS rows_evaluated,
      COALESCE(
        SUM(
          CASE
            WHEN CASE
              WHEN 'group_id_coercible' IS NULL
              THEN NULL
              ELSE COALESCE('group_id_coercible' = ANY(
                _flags
              ), FALSE)
            END
            THEN 1
            ELSE 0
          END
        ),
        0
      ) AS rows_failed,
      0 AS rows_quarantined,
      0 AS rows_deduped
    FROM _quality_rows_q_dup
    UNION ALL
    SELECT
      'q_dup' AS entity,
      'q__dups->q_dup' AS mapping,
      'note_coercible' AS rule,
      'fail' AS disposition,
      0 AS rows_evaluated,
      COALESCE(
        SUM(
          CASE
            WHEN CASE
              WHEN 'note_coercible' IS NULL
              THEN NULL
              ELSE COALESCE('note_coercible' = ANY(
                _flags
              ), FALSE)
            END
            THEN 1
            ELSE 0
          END
        ),
        0
      ) AS rows_failed,
      0 AS rows_quarantined,
      0 AS rows_deduped
    FROM _quality_rows_q_dup
    UNION ALL
    SELECT
      'q_dup' AS entity,
      'q__dups->q_dup' AS mapping,
      'status_coercible' AS rule,
      'quarantine' AS disposition,
      0 AS rows_evaluated,
      COALESCE(
        SUM(
          CASE
            WHEN CASE
              WHEN 'status_coercible' IS NULL
              THEN NULL
              ELSE COALESCE('status_coercible' = ANY(
                _flags
              ), FALSE)
            END
            THEN 1
            ELSE 0
          END
        ),
        0
      ) AS rows_failed,
      0 AS rows_quarantined,
      0 AS rows_deduped
    FROM _quality_rows_q_dup
    UNION ALL
    SELECT
      'q_dup' AS entity,
      'q__dups->q_dup' AS mapping,
      'status_in_set' AS rule,
      'quarantine' AS disposition,
      0 AS rows_evaluated,
      COALESCE(
        SUM(
          CASE
            WHEN CASE
              WHEN 'status_in_set' IS NULL
              THEN NULL
              ELSE COALESCE('status_in_set' = ANY(
                _flags
              ), FALSE)
            END
            THEN 1
            ELSE 0
          END
        ),
        0
      ) AS rows_failed,
      0 AS rows_quarantined,
      0 AS rows_deduped
    FROM _quality_rows_q_dup
    UNION ALL
    SELECT
      'q_line' AS entity,
      'q__lines->q_line' AS mapping,
      '(entity)' AS rule,
      '(entity)' AS disposition,
      COUNT(*) AS rows_evaluated,
      0 AS rows_failed,
      COALESCE(SUM(CASE WHEN _quarantined THEN 1 ELSE 0 END), 0) AS rows_quarantined,
      (
        SELECT
          COUNT(*)
        FROM (
          SELECT
            CASE
              WHEN PG_INPUT_IS_VALID(amount, 'DECIMAL(38, 9)')
              THEN CAST(amount AS DECIMAL(38, 9))
            END AS amount,
            CASE WHEN PG_INPUT_IS_VALID(code, 'TEXT') THEN CAST(code AS TEXT) END AS code,
            CASE WHEN PG_INPUT_IS_VALID(line_no, 'BIGINT') THEN CAST(line_no AS BIGINT) END AS line_no,
            CASE
              WHEN PG_INPUT_IS_VALID(order_date, 'DATE')
              AND NOT LOWER(order_date) ~ '^[[:space:]]*(now|today|tomorrow|yesterday)[[:space:]]*$'
              THEN CAST(order_date AS DATE)
            END AS order_date,
            CASE WHEN PG_INPUT_IS_VALID(order_id, 'TEXT') THEN CAST(order_id AS TEXT) END AS order_id,
            CASE WHEN PG_INPUT_IS_VALID(status, 'TEXT') THEN CAST(status AS TEXT) END AS status,
            _ingested_at,
            _load_id,
            _source_row_id,
            CASE
              WHEN PG_INPUT_IS_VALID(amount, 'DECIMAL(38, 9)')
              THEN CAST(amount AS DECIMAL(38, 9))
            END IS NULL
            AND (
              NOT amount IS NULL
            ) AS _branch_amount_coercible,
            CASE WHEN PG_INPUT_IS_VALID(code, 'TEXT') THEN CAST(code AS TEXT) END IS NULL
            AND (
              NOT code IS NULL
            ) AS _branch_code_coercible,
            CASE WHEN PG_INPUT_IS_VALID(line_no, 'BIGINT') THEN CAST(line_no AS BIGINT) END IS NULL
            AND (
              NOT line_no IS NULL
            ) AS _branch_line_no_coercible,
            CASE
              WHEN PG_INPUT_IS_VALID(order_date, 'DATE')
              AND NOT LOWER(order_date) ~ '^[[:space:]]*(now|today|tomorrow|yesterday)[[:space:]]*$'
              THEN CAST(order_date AS DATE)
            END IS NULL
            AND (
              NOT order_date IS NULL
            ) AS _branch_order_date_coercible,
            CASE WHEN PG_INPUT_IS_VALID(order_id, 'TEXT') THEN CAST(order_id AS TEXT) END IS NULL
            AND (
              NOT order_id IS NULL
            ) AS _branch_order_id_coercible,
            CASE WHEN PG_INPUT_IS_VALID(status, 'TEXT') THEN CAST(status AS TEXT) END IS NULL
            AND (
              NOT status IS NULL
            ) AS _branch_status_coercible
          FROM {{ source('bronze', 'q__lines') }}
        ) AS _bronze
      ) - (
        SELECT
          COUNT(*)
        FROM (
          SELECT
            *,
            (
              COUNT(*) OVER (PARTITION BY code) > 1 AND (
                NOT code IS NULL
              )
            ) AS _win_code_unique
          FROM (
            SELECT
              amount,
              code,
              line_no,
              order_date,
              order_id,
              status,
              _ingested_at,
              _load_id,
              _source_row_id,
              _branch_amount_coercible,
              _branch_code_coercible,
              _branch_line_no_coercible,
              _branch_order_date_coercible,
              _branch_order_id_coercible,
              _branch_status_coercible
            FROM (
              SELECT
                CASE
                  WHEN PG_INPUT_IS_VALID(amount, 'DECIMAL(38, 9)')
                  THEN CAST(amount AS DECIMAL(38, 9))
                END AS amount,
                CASE WHEN PG_INPUT_IS_VALID(code, 'TEXT') THEN CAST(code AS TEXT) END AS code,
                CASE WHEN PG_INPUT_IS_VALID(line_no, 'BIGINT') THEN CAST(line_no AS BIGINT) END AS line_no,
                CASE
                  WHEN PG_INPUT_IS_VALID(order_date, 'DATE')
                  AND NOT LOWER(order_date) ~ '^[[:space:]]*(now|today|tomorrow|yesterday)[[:space:]]*$'
                  THEN CAST(order_date AS DATE)
                END AS order_date,
                CASE WHEN PG_INPUT_IS_VALID(order_id, 'TEXT') THEN CAST(order_id AS TEXT) END AS order_id,
                CASE WHEN PG_INPUT_IS_VALID(status, 'TEXT') THEN CAST(status AS TEXT) END AS status,
                _ingested_at,
                _load_id,
                _source_row_id,
                CASE
                  WHEN PG_INPUT_IS_VALID(amount, 'DECIMAL(38, 9)')
                  THEN CAST(amount AS DECIMAL(38, 9))
                END IS NULL
                AND (
                  NOT amount IS NULL
                ) AS _branch_amount_coercible,
                CASE WHEN PG_INPUT_IS_VALID(code, 'TEXT') THEN CAST(code AS TEXT) END IS NULL
                AND (
                  NOT code IS NULL
                ) AS _branch_code_coercible,
                CASE WHEN PG_INPUT_IS_VALID(line_no, 'BIGINT') THEN CAST(line_no AS BIGINT) END IS NULL
                AND (
                  NOT line_no IS NULL
                ) AS _branch_line_no_coercible,
                CASE
                  WHEN PG_INPUT_IS_VALID(order_date, 'DATE')
                  AND NOT LOWER(order_date) ~ '^[[:space:]]*(now|today|tomorrow|yesterday)[[:space:]]*$'
                  THEN CAST(order_date AS DATE)
                END IS NULL
                AND (
                  NOT order_date IS NULL
                ) AS _branch_order_date_coercible,
                CASE WHEN PG_INPUT_IS_VALID(order_id, 'TEXT') THEN CAST(order_id AS TEXT) END IS NULL
                AND (
                  NOT order_id IS NULL
                ) AS _branch_order_id_coercible,
                CASE WHEN PG_INPUT_IS_VALID(status, 'TEXT') THEN CAST(status AS TEXT) END IS NULL
                AND (
                  NOT status IS NULL
                ) AS _branch_status_coercible,
                ROW_NUMBER() OVER (
                  PARTITION BY CASE WHEN PG_INPUT_IS_VALID(order_id, 'TEXT') THEN CAST(order_id AS TEXT) END, CASE WHEN PG_INPUT_IS_VALID(line_no, 'BIGINT') THEN CAST(line_no AS BIGINT) END
                  ORDER BY _ingested_at DESC NULLS LAST, _load_id DESC NULLS LAST, _source_row_id DESC NULLS LAST
                ) AS _w
              FROM {{ source('bronze', 'q__lines') }}
            ) AS _t
            WHERE
              _w = 1
          ) AS _deduped
        ) AS _extract
      ) AS rows_deduped
    FROM _quality_rows_q_line
    UNION ALL
    SELECT
      'q_line' AS entity,
      'q__lines->q_line' AS mapping,
      'amount_coercible' AS rule,
      'quarantine' AS disposition,
      0 AS rows_evaluated,
      COALESCE(
        SUM(
          CASE
            WHEN CASE
              WHEN 'amount_coercible' IS NULL
              THEN NULL
              ELSE COALESCE('amount_coercible' = ANY(
                _flags
              ), FALSE)
            END
            THEN 1
            ELSE 0
          END
        ),
        0
      ) AS rows_failed,
      0 AS rows_quarantined,
      0 AS rows_deduped
    FROM _quality_rows_q_line
    UNION ALL
    SELECT
      'q_line' AS entity,
      'q__lines->q_line' AS mapping,
      'code_coercible' AS rule,
      'quarantine' AS disposition,
      0 AS rows_evaluated,
      COALESCE(
        SUM(
          CASE
            WHEN CASE
              WHEN 'code_coercible' IS NULL
              THEN NULL
              ELSE COALESCE('code_coercible' = ANY(
                _flags
              ), FALSE)
            END
            THEN 1
            ELSE 0
          END
        ),
        0
      ) AS rows_failed,
      0 AS rows_quarantined,
      0 AS rows_deduped
    FROM _quality_rows_q_line
    UNION ALL
    SELECT
      'q_line' AS entity,
      'q__lines->q_line' AS mapping,
      'line_no_coercible' AS rule,
      'quarantine' AS disposition,
      0 AS rows_evaluated,
      COALESCE(
        SUM(
          CASE
            WHEN CASE
              WHEN 'line_no_coercible' IS NULL
              THEN NULL
              ELSE COALESCE('line_no_coercible' = ANY(
                _flags
              ), FALSE)
            END
            THEN 1
            ELSE 0
          END
        ),
        0
      ) AS rows_failed,
      0 AS rows_quarantined,
      0 AS rows_deduped
    FROM _quality_rows_q_line
    UNION ALL
    SELECT
      'q_line' AS entity,
      'q__lines->q_line' AS mapping,
      'order_date_coercible' AS rule,
      'quarantine' AS disposition,
      0 AS rows_evaluated,
      COALESCE(
        SUM(
          CASE
            WHEN CASE
              WHEN 'order_date_coercible' IS NULL
              THEN NULL
              ELSE COALESCE('order_date_coercible' = ANY(
                _flags
              ), FALSE)
            END
            THEN 1
            ELSE 0
          END
        ),
        0
      ) AS rows_failed,
      0 AS rows_quarantined,
      0 AS rows_deduped
    FROM _quality_rows_q_line
    UNION ALL
    SELECT
      'q_line' AS entity,
      'q__lines->q_line' AS mapping,
      'order_id_coercible' AS rule,
      'quarantine' AS disposition,
      0 AS rows_evaluated,
      COALESCE(
        SUM(
          CASE
            WHEN CASE
              WHEN 'order_id_coercible' IS NULL
              THEN NULL
              ELSE COALESCE('order_id_coercible' = ANY(
                _flags
              ), FALSE)
            END
            THEN 1
            ELSE 0
          END
        ),
        0
      ) AS rows_failed,
      0 AS rows_quarantined,
      0 AS rows_deduped
    FROM _quality_rows_q_line
    UNION ALL
    SELECT
      'q_line' AS entity,
      'q__lines->q_line' AS mapping,
      'status_coercible' AS rule,
      'quarantine' AS disposition,
      0 AS rows_evaluated,
      COALESCE(
        SUM(
          CASE
            WHEN CASE
              WHEN 'status_coercible' IS NULL
              THEN NULL
              ELSE COALESCE('status_coercible' = ANY(
                _flags
              ), FALSE)
            END
            THEN 1
            ELSE 0
          END
        ),
        0
      ) AS rows_failed,
      0 AS rows_quarantined,
      0 AS rows_deduped
    FROM _quality_rows_q_line
    UNION ALL
    SELECT
      'q_line' AS entity,
      'q__lines->q_line' AS mapping,
      'status_in_set' AS rule,
      'quarantine' AS disposition,
      0 AS rows_evaluated,
      COALESCE(
        SUM(
          CASE
            WHEN CASE
              WHEN 'status_in_set' IS NULL
              THEN NULL
              ELSE COALESCE('status_in_set' = ANY(
                _flags
              ), FALSE)
            END
            THEN 1
            ELSE 0
          END
        ),
        0
      ) AS rows_failed,
      0 AS rows_quarantined,
      0 AS rows_deduped
    FROM _quality_rows_q_line
    UNION ALL
    SELECT
      'q_line' AS entity,
      'q__lines->q_line' AS mapping,
      'amount_range_min' AS rule,
      'fail' AS disposition,
      0 AS rows_evaluated,
      COALESCE(
        SUM(
          CASE
            WHEN CASE
              WHEN 'amount_range_min' IS NULL
              THEN NULL
              ELSE COALESCE('amount_range_min' = ANY(
                _flags
              ), FALSE)
            END
            THEN 1
            ELSE 0
          END
        ),
        0
      ) AS rows_failed,
      0 AS rows_quarantined,
      0 AS rows_deduped
    FROM _quality_rows_q_line
    UNION ALL
    SELECT
      'q_line' AS entity,
      'q__lines->q_line' AS mapping,
      'code_unique' AS rule,
      'quarantine' AS disposition,
      0 AS rows_evaluated,
      COALESCE(
        SUM(
          CASE
            WHEN CASE
              WHEN 'code_unique' IS NULL
              THEN NULL
              ELSE COALESCE('code_unique' = ANY(
                _flags
              ), FALSE)
            END
            THEN 1
            ELSE 0
          END
        ),
        0
      ) AS rows_failed,
      0 AS rows_quarantined,
      0 AS rows_deduped
    FROM _quality_rows_q_line
    UNION ALL
    SELECT
      'q_line' AS entity,
      'q__lines->q_line' AS mapping,
      'line_amount_matches_row' AS rule,
      'flag' AS disposition,
      0 AS rows_evaluated,
      COALESCE(SUM(CASE WHEN NOT within_tolerance THEN 1 ELSE 0 END), 0) AS rows_failed,
      0 AS rows_quarantined,
      0 AS rows_deduped
    FROM {{ ref('line_amount_matches_row__reconcile') }}
    UNION ALL
    SELECT
      'q_line' AS entity,
      'q__lines->q_line' AS mapping,
      'line_amount_matches_row_blocking' AS rule,
      'fail' AS disposition,
      0 AS rows_evaluated,
      COALESCE(SUM(CASE WHEN NOT within_tolerance THEN 1 ELSE 0 END), 0) AS rows_failed,
      0 AS rows_quarantined,
      0 AS rows_deduped
    FROM {{ ref('line_amount_matches_row_blocking__reconcile') }}
  ) AS _evaluations
) AS _stamped
