-- Generated by bloomery — do not edit.
-- fingerprint: blm1:9b2080daeff4d3e8cc1f27505c5a6c929299be94ce15d21a835919317d4c4b08
-- The disjointness law (S-0041/what-is-refused-at-run-time) as a runtime audit: a union merge
-- requires the sources' key sets to be disjoint, and the compiler has no data
-- to establish it with. Blocking, and not configurable to a weaker
-- disposition (D5) — a key in two sources is either genuine duplication or a
-- shared key space by accident, and both are refusals. Flagging it would let a
-- double-counted entity into the warehouse marked merely suspect.
AUDIT (
  name order_line_source_collision
);

SELECT
  order_id,
  line_no,
  COUNT(DISTINCT _source) AS sources
FROM (
  SELECT
    CAST(properties ->> '$.gift_note' AS TEXT) AS gift_note,
    CAST(position AS BIGINT) AS line_no,
    CAST("order" ->> '$.id' AS TEXT) AS order_id,
    CAST(quantity AS BIGINT) AS quantity,
    CAST(variant ->> '$.sku' AS TEXT) AS sku,
    'shopify__order_lines' AS _source
  FROM bronze.shopify__order_lines
  UNION ALL
  SELECT
    CAST(NULL AS TEXT) AS gift_note,
    CAST(item_index AS BIGINT) AS line_no,
    CAST(order_number AS TEXT) AS order_id,
    CAST(qty AS BIGINT) AS quantity,
    CAST(product_sku AS TEXT) AS sku,
    'woo__order_lines' AS _source
  FROM bronze.woo__order_lines
) AS _entity
GROUP BY
  order_id,
  line_no
HAVING
  COUNT(DISTINCT _source) > 1
