-- Generated by bloomery — do not edit.
-- fingerprint: blm1:7e13158538dc1cca9c8cccd1a62fbe39b95f5edf7ea8bae3b7ef1d9facb8c7f7
AUDIT (
  name order_line_ingestion_metadata
);

SELECT * FROM (
  SELECT *, COUNT(*) OVER (PARTITION BY _source_row_id) AS _row_id_count FROM @this_model
) AS _metadata WHERE _ingested_at IS NULL
OR _load_id IS NULL
OR _source_row_id IS NULL
OR _row_id_count > 1
OR (
  (
    NOT _ingested_at IS NULL
  ) AND TRY_CAST(_ingested_at AS TIMESTAMP) IS NULL
)
