-- Generated by bloomery — do not edit.
-- fingerprint: blm1:24f1416de6768bcc5570d9b26bde59c137272e4c44af84b7dc3034e683f49c21
{{ config(materialized='table') }}

SELECT
  billing_state,
  ordered_month,
  SUM(amount) AS revenue
FROM {{ ref('mart_orders') }}
GROUP BY
  billing_state,
  ordered_month
