-- Generated by bloomery — do not edit.
-- fingerprint: blm1:29108e9e9b438ef664c0babbc7aab37d5963b2d2d1f3799b48c6e9ce579917cb
{{ config(materialized='table') }}

SELECT
  billing_state,
  ordered_month,
  SUM(amount) AS revenue
FROM {{ ref('mart_orders') }}
GROUP BY
  billing_state,
  ordered_month
