-- Generated by bloomery — do not edit.
-- fingerprint: blm1:098fa50992c83bcbc383225902ba829aef87359d914a966a7790e11c5bf886ab
{{ config(materialized='table') }}

SELECT
  billing_state,
  ordered_month,
  SUM(amount) AS revenue
FROM {{ ref('mart_orders') }}
GROUP BY
  billing_state,
  ordered_month
