-- Generated by bloomery — do not edit.
-- fingerprint: blm1:2b6372ca8b47ba0246a75ad73d731f63e525b4dd7b4879016523384377857a62
MODEL (
  name silver.order_item,
  kind INCREMENTAL_BY_TIME_RANGE (time_column order_date),
  grain (order_id, line_no),
  partitioned_by (days(order_date)),
  audits (not_null(columns := (order_date)))
);

SELECT
  CAST(index AS BIGINT) AS line_no,
  CONVERT_TIMEZONE(
    'Europe/Paris',
    'UTC',
    CAST(CASE
      WHEN SUBSTRING(CAST(created_at AS VARCHAR) FROM 11) LIKE '%+%'
      OR SUBSTRING(CAST(created_at AS VARCHAR) FROM 11) LIKE '%-%'
      THEN NULL
      ELSE created_at
    END AS TIMESTAMP)
  ) AS order_date,
  CAST(order_id AS VARCHAR(MAX)) AS order_id,
  CAST(qty AS BIGINT) AS quantity,
  CAST(CAST(total AS DOUBLE PRECISION) / qty AS DECIMAL(12, 4)) AS unit_price,
  '' AS _quality_flags,
  TRUE AS _quality_ok
FROM bronze.shopify__order_lines
