-- Generated by bloomery — do not edit.
-- fingerprint: blm1:8df03dd7c046468e09a96f18bce5f1ec72a035963976ffdd61c46cee4f69bc95
MODEL (
  name silver.order_item,
  kind INCREMENTAL_BY_TIME_RANGE (time_column order_date),
  grain (order_id, line_no),
  partitioned_by (days(order_date)),
  audits (order_item_key_unique, not_null(columns := (order_date)))
);

SELECT
  CAST(index AS BIGINT) AS line_no,
  CONVERT_TIMEZONE(
    'Europe/Paris',
    'UTC',
    CAST(CASE
      WHEN (
        SUBSTRING(CAST(created_at AS VARCHAR) FROM 11) LIKE '%+%'
        OR SUBSTRING(CAST(created_at AS VARCHAR) FROM 11) LIKE '%-%'
      )
      OR UPPER(SUBSTRING(CAST(created_at AS VARCHAR) FROM 11)) LIKE '%Z%'
      THEN NULL
      ELSE created_at
    END AS TIMESTAMP)
  ) AS order_date,
  CAST(order_id AS VARCHAR(MAX)) AS order_id,
  CAST(qty AS BIGINT) AS quantity,
  CAST(CAST(CAST(total AS DECIMAL(12, 4)) AS DECIMAL(38, 9)) / CAST(qty AS BIGINT) AS DECIMAL(12, 4)) AS unit_price,
  '' AS _quality_flags,
  TRUE AS _quality_ok
FROM bronze.shopify__order_lines
