-- Generated by bloomery — do not edit.
-- fingerprint: blm1:186f5850bc442e331162b3d82d5d5a63202059fddfe4b0d0a840410f7f84fd41
AUDIT (
  name order_item_key_unique
);

SELECT
  _entity.order_id,
  _entity.line_no,
  COUNT(*) AS key_rows
FROM @resolve_template('@{catalog_name}.@{schema_name}.@{table_name}', 'table') AS _entity
WHERE
  EXISTS(
    SELECT
      1
    FROM @this_model AS _written
    WHERE
      (
        _written.order_id = _entity.order_id
        OR (
          _written.order_id IS NULL AND _entity.order_id IS NULL
        )
      )
      AND (
        _written.line_no = _entity.line_no
        OR (
          _written.line_no IS NULL AND _entity.line_no IS NULL
        )
      )
  )
GROUP BY
  _entity.order_id,
  _entity.line_no
HAVING
  COUNT(*) > 1
