-- Generated by bloomery — do not edit.
-- fingerprint: blm1:de98a072194c3715088242b0a66bcc0ce387d9b16b1b1733f062d23a35c93bac
MODEL (
  name silver.customer_raw,
  kind FULL,
  grain (source_system, source_id)
);

SELECT
  CAST(email AS TEXT) AS email,
  CAST(name AS TEXT) AS name,
  CAST(id AS TEXT) AS source_id,
  CAST(system AS TEXT) AS source_system,
  CAST([] AS TEXT[]) AS _quality_flags,
  TRUE AS _quality_ok
FROM bronze.crm__customers
