# Generated by bloomery — do not edit.
# fingerprint: blm1:e41b653769a44e197569facbcb4723799ad545b7c1135b3bd5d8dc99242b5adf
"""SQLMesh Python model for step resolve_customers@3, output customer.

bloomery emits this wrapper; it never executes the step (RFC 0003). The
contract assertion below is generated and non-optional by construction — see
RFC 0017 §5.4.
"""

from __future__ import annotations

import typing

from sqlmesh import model


@model(
    'silver.customer',
    kind="FULL",
    columns={'canonical_id': 'VARCHAR', 'confidence': 'DECIMAL(4, 3)'},
)
def execute(context: typing.Any, **kwargs: typing.Any) -> typing.Any:
    # Every name this function needs is bound *inside* it, deliberately.
    # SQLMesh computes a Python model's dependencies by serializing the module
    # globals the function references and rebuilding them in a fresh
    # environment; a global holding a non-literal value — a Decimal parameter,
    # say — fails to reconstruct there, and the model does not load at all
    # ("name 'Decimal' is not defined", before anything runs). Local state has
    # nothing to serialize.
    # Every generated name is `_blm_`-prefixed: the entrypoint is imported into
    # this same scope, and a step function called `parameters` or `Decimal`
    # would otherwise shadow the local the next line needs — `Decimal` silently
    # rebinding a value constructor to caller code is the bad one.
    from datetime import date as _blm_date  # noqa: F401
    from datetime import datetime as _blm_datetime  # noqa: F401
    from decimal import Decimal as _blm_Decimal  # noqa: F401, N812

    from bloomery.steps.contract import assert_step_contract as _blm_assert

    from platform_steps.resolve_customers import resolve

    _blm_manifest = {'outputs': {'customer': {'key': ['canonical_id'], 'produces': {'canonical_id': {'required': True, 'type': 'string'}, 'confidence': {'required': False, 'type': 'decimal(4,3)'}}}, 'customer_xref': {'key': ['source_system', 'source_id'], 'produces': {'canonical_id': {'required': True, 'type': 'string'}, 'method': {'required': False, 'type': 'string'}, 'source_id': {'required': True, 'type': 'string'}, 'source_system': {'required': True, 'type': 'string'}}}}, 'ref': 'resolve_customers', 'version': 3}
    _blm_parameters = {'threshold': _blm_Decimal('0.9')}
    _blm_inputs = {
        'raw': context.fetchdf(
            f"SELECT * FROM {context.table('silver.customer_raw')}"
        ),
    }
    _blm_outputs = resolve(**_blm_inputs, **_blm_parameters)
    _blm_assert(_blm_outputs, _blm_manifest)
    return _blm_outputs['customer']
