-- Generated by bloomery — do not edit.
-- fingerprint: blm1:9ca6f16519021fe5d38606c0d2c14c0c80c3217304f92b50de3c0b738cf23138
MODEL (
  name silver.customer_raw,
  kind FULL,
  grain (source_system, source_id)
);

SELECT
  CAST(email AS TEXT) AS email,
  CAST(name AS TEXT) AS name,
  CAST(id AS TEXT) AS source_id,
  CAST(system AS TEXT) AS source_system,
  CAST([] AS TEXT[]) AS _quality_flags,
  TRUE AS _quality_ok
FROM bronze.crm__customers
