-- Generated by bloomery — do not edit.
-- fingerprint: blm1:5a633be49bb0f5c48e9cad102a23940acf319264f168a0c1f3fd7f2bf530463f
MODEL (
  name silver.customer_raw,
  kind FULL,
  grain (source_system, source_id)
);

SELECT
  CAST(email AS TEXT) AS email,
  CAST(name AS TEXT) AS name,
  CAST(id AS TEXT) AS source_id,
  CAST(system AS TEXT) AS source_system,
  CAST([] AS TEXT[]) AS _quality_flags,
  TRUE AS _quality_ok
FROM bronze.crm__customers
