# Generated by bloomery — do not edit.
# fingerprint: blm1:1a4e693a1b3e689c6fafcc58d19512bfe8a603332df539f3576c4d977e313c57
"""SQLMesh Python model for step resolve_customers@3, output customer_xref.

bloomery emits this wrapper; it never executes the step (RFC 0003). The
contract assertion below is generated and non-optional by construction — see
RFC 0017 §5.4.
"""

from __future__ import annotations

import typing
from datetime import date, datetime
from decimal import Decimal

from sqlmesh import model

from bloomery.steps.contract import assert_step_contract

MANIFEST = {'outputs': {'customer': {'key': ['canonical_id'], 'produces': {'canonical_id': {'required': True, 'type': 'string'}, 'confidence': {'required': False, 'type': 'decimal(4,3)'}}}, 'customer_xref': {'key': ['source_system', 'source_id'], 'produces': {'canonical_id': {'required': True, 'type': 'string'}, 'method': {'required': False, 'type': 'string'}, 'source_id': {'required': True, 'type': 'string'}, 'source_system': {'required': True, 'type': 'string'}}}}, 'ref': 'resolve_customers', 'version': 3}

PARAMETERS = {'threshold': Decimal('0.9')}


@model(
    'silver.customer_xref',
    kind="FULL",
    columns={'canonical_id': 'VARCHAR', 'method': 'VARCHAR', 'source_id': 'VARCHAR', 'source_system': 'VARCHAR'},
)
def execute(context: typing.Any, **kwargs: typing.Any) -> typing.Any:
    from platform_steps.resolve_customers import resolve

    inputs = {
        'raw': context.fetchdf(
            f"SELECT * FROM {context.table('silver.customer_raw')}"
        ),
    }
    outputs = resolve(**inputs, **PARAMETERS)
    assert_step_contract(outputs, MANIFEST)
    return outputs['customer_xref']
