-- Generated by bloomery — do not edit.
-- fingerprint: blm1:2c41db232cea5cfcbf2c37059181a7fc7e5295fc72e23fa2c843cc4326429eaf
MODEL (
  name silver.event,
  kind FULL,
  grain (event_id)
);

SELECT
  CAST(id AS TEXT) AS event_id,
  CAST(kind AS TEXT) AS kind,
  CAST(ts AS TIMESTAMP) AS occurred_at,
  CAST(ARRAY[] AS TEXT[]) AS _quality_flags,
  TRUE AS _quality_ok
FROM bronze.raw__events
