-- Generated by bloomery — do not edit.
-- fingerprint: blm1:f7051301a9c312d3d0a486963f2432c2b60bb070400e9bc0c3ad4701027c2c74
MODEL (
  name silver.event,
  kind FULL,
  grain (event_id)
);

SELECT
  CAST(id AS TEXT) AS event_id,
  CAST(kind AS TEXT) AS kind,
  CAST(ts AS TIMESTAMP) AS occurred_at,
  CAST(ARRAY[] AS TEXT[]) AS _quality_flags,
  TRUE AS _quality_ok
FROM bronze.raw__events
