-- Generated by bloomery — do not edit.
-- fingerprint: blm1:24f1416de6768bcc5570d9b26bde59c137272e4c44af84b7dc3034e683f49c21
{{ config(severity='error') }}

SELECT
  _entity.address_id,
  COUNT(*) AS key_rows
FROM {{ ref('address') }} AS _entity
GROUP BY
  _entity.address_id
HAVING
  COUNT(*) > 1
