-- Generated by bloomery — do not edit.
-- fingerprint: blm1:4aa879a0d07f7796fc657c3a13953f682a63ca425f542567961a29fe86887f96
{{ config(severity='error') }}

SELECT
  _entity.address_id,
  COUNT(*) AS key_rows
FROM {{ ref('address') }} AS _entity
GROUP BY
  _entity.address_id
HAVING
  COUNT(*) > 1
