-- Generated by bloomery — do not edit.
-- fingerprint: blm1:098fa50992c83bcbc383225902ba829aef87359d914a966a7790e11c5bf886ab
{{ config(severity='error') }}

SELECT
  _entity.order_id,
  COUNT(*) AS key_rows
FROM {{ ref('order') }} AS _entity
GROUP BY
  _entity.order_id
HAVING
  COUNT(*) > 1
