-- Generated by bloomery — do not edit.
-- fingerprint: blm1:5c0660f42fba56bf8254350a3c297020c406bb5ba955aa80e2a94bd4adc57a1b
{% macro generate_schema_name(custom_schema_name, node) -%}
{%- if custom_schema_name is none -%}
{{ target.schema }}
{%- else -%}
{{ custom_schema_name | trim }}
{%- endif -%}
{%- endmacro %}
