-- Generated by bloomery — do not edit.
-- fingerprint: blm1:708ca222e4abb71ee3b7102304679ccf0616d535294ecd885dafa4ee1fdb2315
{% macro generate_schema_name(custom_schema_name, node) -%}
{%- if custom_schema_name is none -%}
{{ target.schema }}
{%- else -%}
{{ custom_schema_name | trim }}
{%- endif -%}
{%- endmacro %}
