-- Generated by bloomery — do not edit.
-- fingerprint: blm1:773eb32bb4549a48391efb186c0fc40e5f5ec081728ba304dd668e5c73a2b6fa
{% macro generate_schema_name(custom_schema_name, node) -%}
{%- if custom_schema_name is none -%}
{{ target.schema }}
{%- else -%}
{{ custom_schema_name | trim }}
{%- endif -%}
{%- endmacro %}
