-- Generated by bloomery — do not edit.
-- fingerprint: blm1:982094f9016d3e8d8226756b5820284154fe0ca94e78f48231634abea9405a9d
AUDIT (
  name event_key_unique
);

SELECT
  _entity.event_id,
  COUNT(*) AS key_rows
FROM @this_model AS _entity
GROUP BY
  _entity.event_id
HAVING
  COUNT(*) > 1
