-- Generated by bloomery — do not edit.
-- fingerprint: blm1:031822bf07c321da2ee5bd0d5c0da750c2f8383e37d7f25e5382893859451946
{{ config(severity='error') }}

SELECT
  _entity.customer_id,
  COUNT(*) AS key_rows
FROM {{ ref('customer_snapshot') }} AS _entity
WHERE
  _entity.valid_to IS NULL
GROUP BY
  _entity.customer_id
HAVING
  COUNT(*) > 1
