-- Generated by bloomery — do not edit.
-- fingerprint: blm1:fb6c691770b6d0954e2336120ba44cb247b43311773185c59881810f516e5f20
{{ config(severity='error') }}

SELECT
  _entity.customer_id,
  COUNT(*) AS key_rows
FROM {{ ref('customer_snapshot') }} AS _entity
WHERE
  _entity.valid_to IS NULL
GROUP BY
  _entity.customer_id
HAVING
  COUNT(*) > 1
