-- Generated by bloomery — do not edit.
-- fingerprint: blm1:6c171141d0fd8cc12e10e1ada664b48ed095e3d32e4fd12466f144244a1057d1
{% macro generate_schema_name(custom_schema_name, node) -%}
{%- if custom_schema_name is none -%}
{{ target.schema }}
{%- else -%}
{{ custom_schema_name | trim }}
{%- endif -%}
{%- endmacro %}
