-- Generated by bloomery — do not edit.
-- fingerprint: blm1:a36b238f2199ee250aec2b50bb59065021a032604f5b62100ca31d6f611049ad
{% macro generate_schema_name(custom_schema_name, node) -%}
{%- if custom_schema_name is none -%}
{{ target.schema }}
{%- else -%}
{{ custom_schema_name | trim }}
{%- endif -%}
{%- endmacro %}
