-- Generated by bloomery — do not edit.
-- fingerprint: blm1:b7a7f4c151717de912753ea1a222889d35d1486e8d740edb7348e55b8f4bd96a
{% macro generate_schema_name(custom_schema_name, node) -%}
{%- if custom_schema_name is none -%}
{{ target.schema }}
{%- else -%}
{{ custom_schema_name | trim }}
{%- endif -%}
{%- endmacro %}
