-- Generated by bloomery — do not edit.
-- fingerprint: blm1:b4add99c38382c6751d4a778a027591302424af4ec91a386cf7803d507b57719
--
-- Run this with `dbt run-operation replay_q_line`. The three statements below are
-- one unit of work and the macro says so to the engine; bloomery executes
-- nothing — this file is text until you run it.
{% macro replay_q_line() %}
  {% if var('bloomery_fingerprint', none) != 'blm1:b4add99c38382c6751d4a778a027591302424af4ec91a386cf7803d507b57719' %}
    {{ exceptions.raise_compiler_error("replay_q_line was emitted under blm1:b4add99c38382c6751d4a778a027591302424af4ec91a386cf7803d507b57719, but this dbt project carries bloomery_fingerprint " ~ var('bloomery_fingerprint', none) ~ "; compile into a clean directory and rebuild q_line and its reject table from the same checkout before replaying") }}
  {% endif %}
  {% set missing = ['amount', 'code', 'order_date', 'status', '_ingested_at', '_load_id', '_source_row_id', '_quality_flags', '_quality_ok', 'line_no', 'order_id'] | reject('in', adapter.get_columns_in_relation(ref('q_line')) | map(attribute='name') | map('lower') | list) | list %}
  {% if missing %}
    {{ exceptions.raise_compiler_error("replay_q_line writes " ~ missing | join(", ") ~ " into silver.q_line, which does not have them; rebuild it from the checkout this macro was compiled from with `dbt run --select q_line` before replaying") }}
  {% endif %}
  {% set missing = ['resolved_at', 'last_evaluated_at', 'failed_rules'] | reject('in', adapter.get_columns_in_relation(ref('q_line__reject')) | map(attribute='name') | map('lower') | list) | list %}
  {% if missing %}
    {{ exceptions.raise_compiler_error("replay_q_line writes " ~ missing | join(", ") ~ " into silver.q_line__reject, which does not have them; rebuild it from the checkout this macro was compiled from with `dbt run --full-refresh --select q_line__reject` before replaying") }}
  {% endif %}
  {% call statement('replay_q_line_columns', auto_begin=True) %}select 1{% endcall %}
  {% do adapter.commit() %}
  {% do run_query("BEGIN") %}

  {% set statement_0 %}
MERGE INTO {{ ref('q_line') }} AS _target
USING (
  SELECT
    amount,
    code,
    line_no,
    order_date,
    order_id,
    status,
    _ingested_at,
    _load_id,
    _source_row_id,
    _quality_flags,
    _quality_ok
  FROM (
    SELECT
      _evaluated.amount,
      _evaluated.code,
      _evaluated.line_no,
      _evaluated.order_date,
      _evaluated.order_id,
      _evaluated.status,
      _evaluated._ingested_at,
      _evaluated._load_id,
      _evaluated._source_row_id,
      _evaluated._quality_flags,
      COALESCE(ARRAY_LENGTH(_evaluated._quality_flags, 1), 0) = 0 AS _quality_ok,
      ROW_NUMBER() OVER (
        PARTITION BY order_id, line_no
        ORDER BY _ingested_at DESC NULLS LAST, _load_id DESC NULLS LAST, _source_row_id DESC NULLS LAST
      ) AS _w
    FROM (
      SELECT
        _extract.amount,
        _extract.code,
        _extract.line_no,
        _extract.order_date,
        _extract.order_id,
        _extract.status,
        _extract._ingested_at,
        _extract._load_id,
        _extract._source_row_id,
        CASE
          WHEN _extract.amount < 0
          THEN ARRAY['amount_range_min']
          ELSE CAST(ARRAY[] AS TEXT[])
        END AS _quality_flags
      FROM (
        SELECT
          *,
          (
            COUNT(*) OVER (PARTITION BY code) > 1 AND (
              NOT code IS NULL
            )
          ) AS _win_code_unique
        FROM (
          SELECT
            CASE
              WHEN PG_INPUT_IS_VALID(raw ->> 'amount', 'DECIMAL(38, 9)')
              THEN CAST(raw ->> 'amount' AS DECIMAL(38, 9))
            END AS amount,
            CASE
              WHEN PG_INPUT_IS_VALID(raw ->> 'code', 'TEXT')
              THEN CAST(raw ->> 'code' AS TEXT)
            END AS code,
            CASE
              WHEN PG_INPUT_IS_VALID(raw ->> 'line_no', 'BIGINT')
              THEN CAST(raw ->> 'line_no' AS BIGINT)
            END AS line_no,
            CASE
              WHEN PG_INPUT_IS_VALID(raw ->> 'order_date', 'DATE')
              AND NOT LOWER(raw ->> 'order_date') ~ '^[[:space:]]*(now|today|tomorrow|yesterday)[[:space:]]*$'
              THEN CAST(raw ->> 'order_date' AS DATE)
            END AS order_date,
            CASE
              WHEN PG_INPUT_IS_VALID(raw ->> 'order_id', 'TEXT')
              THEN CAST(raw ->> 'order_id' AS TEXT)
            END AS order_id,
            CASE
              WHEN PG_INPUT_IS_VALID(raw ->> 'status', 'TEXT')
              THEN CAST(raw ->> 'status' AS TEXT)
            END AS status,
            _ingested_at,
            _load_id,
            _source_row_id,
            CASE
              WHEN PG_INPUT_IS_VALID(raw ->> 'amount', 'DECIMAL(38, 9)')
              THEN CAST(raw ->> 'amount' AS DECIMAL(38, 9))
            END IS NULL
            AND (
              NOT raw ->> 'amount' IS NULL
            ) AS _branch_amount_coercible,
            CASE
              WHEN PG_INPUT_IS_VALID(raw ->> 'code', 'TEXT')
              THEN CAST(raw ->> 'code' AS TEXT)
            END IS NULL
            AND (
              NOT raw ->> 'code' IS NULL
            ) AS _branch_code_coercible,
            CASE
              WHEN PG_INPUT_IS_VALID(raw ->> 'line_no', 'BIGINT')
              THEN CAST(raw ->> 'line_no' AS BIGINT)
            END IS NULL
            AND (
              NOT raw ->> 'line_no' IS NULL
            ) AS _branch_line_no_coercible,
            CASE
              WHEN PG_INPUT_IS_VALID(raw ->> 'order_date', 'DATE')
              AND NOT LOWER(raw ->> 'order_date') ~ '^[[:space:]]*(now|today|tomorrow|yesterday)[[:space:]]*$'
              THEN CAST(raw ->> 'order_date' AS DATE)
            END IS NULL
            AND (
              NOT raw ->> 'order_date' IS NULL
            ) AS _branch_order_date_coercible,
            CASE
              WHEN PG_INPUT_IS_VALID(raw ->> 'order_id', 'TEXT')
              THEN CAST(raw ->> 'order_id' AS TEXT)
            END IS NULL
            AND (
              NOT raw ->> 'order_id' IS NULL
            ) AS _branch_order_id_coercible,
            CASE
              WHEN PG_INPUT_IS_VALID(raw ->> 'status', 'TEXT')
              THEN CAST(raw ->> 'status' AS TEXT)
            END IS NULL
            AND (
              NOT raw ->> 'status' IS NULL
            ) AS _branch_status_coercible
          FROM {{ ref('q_line__reject') }}
          WHERE
            resolved_at IS NULL
        ) AS _deduped
      ) AS _extract
      WHERE
        NOT COALESCE(
          (
            _extract._branch_amount_coercible
            OR _extract._branch_code_coercible
            OR _extract._branch_line_no_coercible
            OR _extract._branch_order_date_coercible
            OR _extract._branch_order_id_coercible
            OR _extract._branch_status_coercible
            OR (
              NOT _extract.status IN ('open', 'closed')
            )
            OR _extract._win_code_unique
          ),
          FALSE
        )
    ) AS _evaluated
  ) AS _t
  WHERE
    _w = 1
) AS _replay
ON _target.order_id = _replay.order_id AND _target.line_no = _replay.line_no
WHEN MATCHED AND (
  (
    (
      NOT _replay._ingested_at IS NULL AND _target._ingested_at IS NULL
    )
    OR (
      NOT _replay._ingested_at IS NULL
      AND NOT _target._ingested_at IS NULL
      AND _replay._ingested_at > _target._ingested_at
    )
  )
  OR (
    (
      (
        _replay._ingested_at IS NULL AND _target._ingested_at IS NULL
      )
      OR _replay._ingested_at = _target._ingested_at
    )
    AND (
      (
        (
          NOT _replay._load_id IS NULL AND _target._load_id IS NULL
        )
        OR (
          NOT _replay._load_id IS NULL
          AND NOT _target._load_id IS NULL
          AND _replay._load_id > _target._load_id
        )
      )
      OR (
        (
          (
            _replay._load_id IS NULL AND _target._load_id IS NULL
          )
          OR _replay._load_id = _target._load_id
        )
        AND (
          (
            NOT _replay._source_row_id IS NULL AND _target._source_row_id IS NULL
          )
          OR (
            NOT _replay._source_row_id IS NULL
            AND NOT _target._source_row_id IS NULL
            AND _replay._source_row_id > _target._source_row_id
          )
        )
      )
    )
  )
) THEN UPDATE SET
  amount = _replay.amount,
  code = _replay.code,
  order_date = _replay.order_date,
  status = _replay.status,
  _ingested_at = _replay._ingested_at,
  _load_id = _replay._load_id,
  _source_row_id = _replay._source_row_id,
  _quality_flags = _replay._quality_flags,
  _quality_ok = _replay._quality_ok
WHEN NOT MATCHED THEN INSERT (
  amount,
  code,
  line_no,
  order_date,
  order_id,
  status,
  _ingested_at,
  _load_id,
  _source_row_id,
  _quality_flags,
  _quality_ok
) VALUES (
  _replay.amount,
  _replay.code,
  _replay.line_no,
  _replay.order_date,
  _replay.order_id,
  _replay.status,
  _replay._ingested_at,
  _replay._load_id,
  _replay._source_row_id,
  _replay._quality_flags,
  _replay._quality_ok
)
  {% endset %}
  {% do run_query(statement_0) %}
  {% set statement_1 %}
UPDATE {{ ref('q_line__reject') }} SET resolved_at = CURRENT_TIMESTAMP, last_evaluated_at = CURRENT_TIMESTAMP
WHERE
  resolved_at IS NULL
  AND _source_row_id IN (
    SELECT
      _target._source_row_id
    FROM {{ ref('q_line') }} AS _target
  )
  {% endset %}
  {% do run_query(statement_1) %}
  {% set statement_2 %}
MERGE INTO {{ ref('q_line__reject') }} AS _target
USING (
  SELECT
    _extract._source_row_id,
    ARRAY_CAT(
      ARRAY_CAT(
        ARRAY_CAT(
          ARRAY_CAT(
            ARRAY_CAT(
              ARRAY_CAT(
                ARRAY_CAT(
                  ARRAY_CAT(
                    ARRAY_CAT(
                      CASE
                        WHEN NOT COALESCE(
                          (
                            _extract._branch_amount_coercible
                            OR _extract._branch_code_coercible
                            OR _extract._branch_line_no_coercible
                            OR _extract._branch_order_date_coercible
                            OR _extract._branch_order_id_coercible
                            OR _extract._branch_status_coercible
                            OR (
                              NOT _extract.status IN ('open', 'closed')
                            )
                            OR _extract._win_code_unique
                          ),
                          FALSE
                        )
                        THEN ARRAY['(superseded)']
                        ELSE CAST(ARRAY[] AS TEXT[])
                      END,
                      CASE
                        WHEN _extract._branch_amount_coercible
                        THEN ARRAY['amount_coercible']
                        ELSE CAST(ARRAY[] AS TEXT[])
                      END
                    ),
                    CASE
                      WHEN _extract.amount < 0
                      THEN ARRAY['amount_range_min']
                      ELSE CAST(ARRAY[] AS TEXT[])
                    END
                  ),
                  CASE
                    WHEN _extract._branch_code_coercible
                    THEN ARRAY['code_coercible']
                    ELSE CAST(ARRAY[] AS TEXT[])
                  END
                ),
                CASE
                  WHEN _extract._win_code_unique
                  THEN ARRAY['code_unique']
                  ELSE CAST(ARRAY[] AS TEXT[])
                END
              ),
              CASE
                WHEN _extract._branch_line_no_coercible
                THEN ARRAY['line_no_coercible']
                ELSE CAST(ARRAY[] AS TEXT[])
              END
            ),
            CASE
              WHEN _extract._branch_order_date_coercible
              THEN ARRAY['order_date_coercible']
              ELSE CAST(ARRAY[] AS TEXT[])
            END
          ),
          CASE
            WHEN _extract._branch_order_id_coercible
            THEN ARRAY['order_id_coercible']
            ELSE CAST(ARRAY[] AS TEXT[])
          END
        ),
        CASE
          WHEN _extract._branch_status_coercible
          THEN ARRAY['status_coercible']
          ELSE CAST(ARRAY[] AS TEXT[])
        END
      ),
      CASE
        WHEN NOT _extract.status IN ('open', 'closed')
        THEN ARRAY['status_in_set']
        ELSE CAST(ARRAY[] AS TEXT[])
      END
    ) AS failed_rules
  FROM (
    SELECT
      *,
      (
        COUNT(*) OVER (PARTITION BY code) > 1 AND (
          NOT code IS NULL
        )
      ) AS _win_code_unique
    FROM (
      SELECT
        CASE
          WHEN PG_INPUT_IS_VALID(raw ->> 'amount', 'DECIMAL(38, 9)')
          THEN CAST(raw ->> 'amount' AS DECIMAL(38, 9))
        END AS amount,
        CASE
          WHEN PG_INPUT_IS_VALID(raw ->> 'code', 'TEXT')
          THEN CAST(raw ->> 'code' AS TEXT)
        END AS code,
        CASE
          WHEN PG_INPUT_IS_VALID(raw ->> 'line_no', 'BIGINT')
          THEN CAST(raw ->> 'line_no' AS BIGINT)
        END AS line_no,
        CASE
          WHEN PG_INPUT_IS_VALID(raw ->> 'order_date', 'DATE')
          AND NOT LOWER(raw ->> 'order_date') ~ '^[[:space:]]*(now|today|tomorrow|yesterday)[[:space:]]*$'
          THEN CAST(raw ->> 'order_date' AS DATE)
        END AS order_date,
        CASE
          WHEN PG_INPUT_IS_VALID(raw ->> 'order_id', 'TEXT')
          THEN CAST(raw ->> 'order_id' AS TEXT)
        END AS order_id,
        CASE
          WHEN PG_INPUT_IS_VALID(raw ->> 'status', 'TEXT')
          THEN CAST(raw ->> 'status' AS TEXT)
        END AS status,
        _ingested_at,
        _load_id,
        _source_row_id,
        CASE
          WHEN PG_INPUT_IS_VALID(raw ->> 'amount', 'DECIMAL(38, 9)')
          THEN CAST(raw ->> 'amount' AS DECIMAL(38, 9))
        END IS NULL
        AND (
          NOT raw ->> 'amount' IS NULL
        ) AS _branch_amount_coercible,
        CASE
          WHEN PG_INPUT_IS_VALID(raw ->> 'code', 'TEXT')
          THEN CAST(raw ->> 'code' AS TEXT)
        END IS NULL
        AND (
          NOT raw ->> 'code' IS NULL
        ) AS _branch_code_coercible,
        CASE
          WHEN PG_INPUT_IS_VALID(raw ->> 'line_no', 'BIGINT')
          THEN CAST(raw ->> 'line_no' AS BIGINT)
        END IS NULL
        AND (
          NOT raw ->> 'line_no' IS NULL
        ) AS _branch_line_no_coercible,
        CASE
          WHEN PG_INPUT_IS_VALID(raw ->> 'order_date', 'DATE')
          AND NOT LOWER(raw ->> 'order_date') ~ '^[[:space:]]*(now|today|tomorrow|yesterday)[[:space:]]*$'
          THEN CAST(raw ->> 'order_date' AS DATE)
        END IS NULL
        AND (
          NOT raw ->> 'order_date' IS NULL
        ) AS _branch_order_date_coercible,
        CASE
          WHEN PG_INPUT_IS_VALID(raw ->> 'order_id', 'TEXT')
          THEN CAST(raw ->> 'order_id' AS TEXT)
        END IS NULL
        AND (
          NOT raw ->> 'order_id' IS NULL
        ) AS _branch_order_id_coercible,
        CASE
          WHEN PG_INPUT_IS_VALID(raw ->> 'status', 'TEXT')
          THEN CAST(raw ->> 'status' AS TEXT)
        END IS NULL
        AND (
          NOT raw ->> 'status' IS NULL
        ) AS _branch_status_coercible
      FROM {{ ref('q_line__reject') }}
      WHERE
        resolved_at IS NULL
    ) AS _deduped
  ) AS _extract
) AS _replay
ON _target._source_row_id = _replay._source_row_id
WHEN MATCHED AND _target.resolved_at IS NULL THEN UPDATE SET
  failed_rules = _replay.failed_rules,
  last_evaluated_at = CURRENT_TIMESTAMP
  {% endset %}
  {% do run_query(statement_2) %}

  {% do run_query("COMMIT") %}
{% endmacro %}
