-- Generated by bloomery — do not edit.
-- fingerprint: blm1:b5bf2fa542b0b18f51126e0eb175da99d6abaf964d79e6634a7a4d57439d08e2
--
-- Run this with `dbt run-operation replay_q_code`. The three statements below are
-- one unit of work and the macro says so to the engine; bloomery executes
-- nothing — this file is text until you run it.
{% macro replay_q_code() %}
  {% do run_query("BEGIN") %}

  {% set statement_0 %}
MERGE INTO {{ ref('q_code') }} AS _target
USING (
  SELECT
    code_fail,
    code_flag,
    code_id,
    code_quar,
    _ingested_at,
    _load_id,
    _source_row_id,
    _quality_flags,
    _quality_ok
  FROM (
    SELECT
      _evaluated.code_fail,
      _evaluated.code_flag,
      _evaluated.code_id,
      _evaluated.code_quar,
      _evaluated._ingested_at,
      _evaluated._load_id,
      _evaluated._source_row_id,
      _evaluated._quality_flags,
      COALESCE(ARRAY_LENGTH(_evaluated._quality_flags, 1), 0) = 0 AS _quality_ok,
      ROW_NUMBER() OVER (PARTITION BY code_id ORDER BY _source_row_id DESC NULLS LAST) AS _w
    FROM (
      SELECT
        _extract.code_fail,
        _extract.code_flag,
        _extract.code_id,
        _extract.code_quar,
        _extract._ingested_at,
        _extract._load_id,
        _extract._source_row_id,
        ARRAY_CAT(
          CASE
            WHEN _extract._win_code_fail_unique
            THEN ARRAY['code_fail_unique']
            ELSE CAST(ARRAY[] AS TEXT[])
          END,
          CASE
            WHEN _extract._win_code_flag_unique
            THEN ARRAY['code_flag_unique']
            ELSE CAST(ARRAY[] AS TEXT[])
          END
        ) AS _quality_flags
      FROM (
        SELECT
          *,
          (
            COUNT(*) OVER (PARTITION BY code_fail) > 1 AND (
              NOT code_fail IS NULL
            )
          ) AS _win_code_fail_unique,
          (
            COUNT(*) OVER (PARTITION BY code_flag) > 1 AND (
              NOT code_flag IS NULL
            )
          ) AS _win_code_flag_unique,
          (
            COUNT(*) OVER (PARTITION BY code_quar) > 1 AND (
              NOT code_quar IS NULL
            )
          ) AS _win_code_quar_unique
        FROM (
          SELECT
            CASE
              WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.code_fail'), 'TEXT')
              THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.code_fail') AS TEXT)
            END AS code_fail,
            CASE
              WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.code_flag'), 'TEXT')
              THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.code_flag') AS TEXT)
            END AS code_flag,
            CASE
              WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.code_id'), 'TEXT')
              THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.code_id') AS TEXT)
            END AS code_id,
            CASE
              WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.code_quar'), 'TEXT')
              THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.code_quar') AS TEXT)
            END AS code_quar,
            _ingested_at,
            _load_id,
            _source_row_id,
            CASE
              WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.code_fail'), 'TEXT')
              THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.code_fail') AS TEXT)
            END IS NULL
            AND (
              NOT JSON_EXTRACT_PATH_TEXT(raw, '$.code_fail') IS NULL
            ) AS _branch_code_fail_coercible,
            CASE
              WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.code_flag'), 'TEXT')
              THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.code_flag') AS TEXT)
            END IS NULL
            AND (
              NOT JSON_EXTRACT_PATH_TEXT(raw, '$.code_flag') IS NULL
            ) AS _branch_code_flag_coercible,
            CASE
              WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.code_id'), 'TEXT')
              THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.code_id') AS TEXT)
            END IS NULL
            AND (
              NOT JSON_EXTRACT_PATH_TEXT(raw, '$.code_id') IS NULL
            ) AS _branch_code_id_coercible,
            CASE
              WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.code_quar'), 'TEXT')
              THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.code_quar') AS TEXT)
            END IS NULL
            AND (
              NOT JSON_EXTRACT_PATH_TEXT(raw, '$.code_quar') IS NULL
            ) AS _branch_code_quar_coercible
          FROM {{ ref('q_code__reject') }}
          WHERE
            resolved_at IS NULL
        ) AS _deduped
      ) AS _extract
      WHERE
        NOT COALESCE(
          (
            _extract._branch_code_fail_coercible
            OR _extract._branch_code_flag_coercible
            OR _extract._branch_code_id_coercible
            OR _extract._branch_code_quar_coercible
            OR _extract._win_code_quar_unique
          ),
          FALSE
        )
    ) AS _evaluated
  ) AS _t
  WHERE
    _w = 1
) AS _replay
ON _target.code_id = _replay.code_id
WHEN MATCHED AND (
  (
    NOT _replay._source_row_id IS NULL AND _target._source_row_id IS NULL
  )
  OR (
    NOT _replay._source_row_id IS NULL
    AND NOT _target._source_row_id IS NULL
    AND _replay._source_row_id > _target._source_row_id
  )
) THEN UPDATE SET
  code_fail = _replay.code_fail,
  code_flag = _replay.code_flag,
  code_quar = _replay.code_quar,
  _ingested_at = _replay._ingested_at,
  _load_id = _replay._load_id,
  _source_row_id = _replay._source_row_id,
  _quality_flags = _replay._quality_flags,
  _quality_ok = _replay._quality_ok
WHEN NOT MATCHED THEN INSERT (
  code_fail,
  code_flag,
  code_id,
  code_quar,
  _ingested_at,
  _load_id,
  _source_row_id,
  _quality_flags,
  _quality_ok
) VALUES (
  _replay.code_fail,
  _replay.code_flag,
  _replay.code_id,
  _replay.code_quar,
  _replay._ingested_at,
  _replay._load_id,
  _replay._source_row_id,
  _replay._quality_flags,
  _replay._quality_ok
)
  {% endset %}
  {% do run_query(statement_0) %}
  {% set statement_1 %}
UPDATE {{ ref('q_code__reject') }} SET resolved_at = CURRENT_TIMESTAMP, last_evaluated_at = CURRENT_TIMESTAMP
WHERE
  resolved_at IS NULL
  AND _source_row_id IN (
    SELECT
      _target._source_row_id
    FROM {{ ref('q_code') }} AS _target
  )
  {% endset %}
  {% do run_query(statement_1) %}
  {% set statement_2 %}
MERGE INTO {{ ref('q_code__reject') }} AS _target
USING (
  SELECT
    _extract._source_row_id,
    ARRAY_CAT(
      ARRAY_CAT(
        ARRAY_CAT(
          ARRAY_CAT(
            ARRAY_CAT(
              ARRAY_CAT(
                ARRAY_CAT(
                  CASE
                    WHEN NOT COALESCE(
                      (
                        _extract._branch_code_fail_coercible
                        OR _extract._branch_code_flag_coercible
                        OR _extract._branch_code_id_coercible
                        OR _extract._branch_code_quar_coercible
                        OR _extract._win_code_quar_unique
                      ),
                      FALSE
                    )
                    THEN ARRAY['(superseded)']
                    ELSE CAST(ARRAY[] AS TEXT[])
                  END,
                  CASE
                    WHEN _extract._branch_code_fail_coercible
                    THEN ARRAY['code_fail_coercible']
                    ELSE CAST(ARRAY[] AS TEXT[])
                  END
                ),
                CASE
                  WHEN _extract._win_code_fail_unique
                  THEN ARRAY['code_fail_unique']
                  ELSE CAST(ARRAY[] AS TEXT[])
                END
              ),
              CASE
                WHEN _extract._branch_code_flag_coercible
                THEN ARRAY['code_flag_coercible']
                ELSE CAST(ARRAY[] AS TEXT[])
              END
            ),
            CASE
              WHEN _extract._win_code_flag_unique
              THEN ARRAY['code_flag_unique']
              ELSE CAST(ARRAY[] AS TEXT[])
            END
          ),
          CASE
            WHEN _extract._branch_code_id_coercible
            THEN ARRAY['code_id_coercible']
            ELSE CAST(ARRAY[] AS TEXT[])
          END
        ),
        CASE
          WHEN _extract._branch_code_quar_coercible
          THEN ARRAY['code_quar_coercible']
          ELSE CAST(ARRAY[] AS TEXT[])
        END
      ),
      CASE
        WHEN _extract._win_code_quar_unique
        THEN ARRAY['code_quar_unique']
        ELSE CAST(ARRAY[] AS TEXT[])
      END
    ) AS failed_rules
  FROM (
    SELECT
      *,
      (
        COUNT(*) OVER (PARTITION BY code_fail) > 1 AND (
          NOT code_fail IS NULL
        )
      ) AS _win_code_fail_unique,
      (
        COUNT(*) OVER (PARTITION BY code_flag) > 1 AND (
          NOT code_flag IS NULL
        )
      ) AS _win_code_flag_unique,
      (
        COUNT(*) OVER (PARTITION BY code_quar) > 1 AND (
          NOT code_quar IS NULL
        )
      ) AS _win_code_quar_unique
    FROM (
      SELECT
        CASE
          WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.code_fail'), 'TEXT')
          THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.code_fail') AS TEXT)
        END AS code_fail,
        CASE
          WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.code_flag'), 'TEXT')
          THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.code_flag') AS TEXT)
        END AS code_flag,
        CASE
          WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.code_id'), 'TEXT')
          THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.code_id') AS TEXT)
        END AS code_id,
        CASE
          WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.code_quar'), 'TEXT')
          THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.code_quar') AS TEXT)
        END AS code_quar,
        _ingested_at,
        _load_id,
        _source_row_id,
        CASE
          WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.code_fail'), 'TEXT')
          THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.code_fail') AS TEXT)
        END IS NULL
        AND (
          NOT JSON_EXTRACT_PATH_TEXT(raw, '$.code_fail') IS NULL
        ) AS _branch_code_fail_coercible,
        CASE
          WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.code_flag'), 'TEXT')
          THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.code_flag') AS TEXT)
        END IS NULL
        AND (
          NOT JSON_EXTRACT_PATH_TEXT(raw, '$.code_flag') IS NULL
        ) AS _branch_code_flag_coercible,
        CASE
          WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.code_id'), 'TEXT')
          THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.code_id') AS TEXT)
        END IS NULL
        AND (
          NOT JSON_EXTRACT_PATH_TEXT(raw, '$.code_id') IS NULL
        ) AS _branch_code_id_coercible,
        CASE
          WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.code_quar'), 'TEXT')
          THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.code_quar') AS TEXT)
        END IS NULL
        AND (
          NOT JSON_EXTRACT_PATH_TEXT(raw, '$.code_quar') IS NULL
        ) AS _branch_code_quar_coercible
      FROM {{ ref('q_code__reject') }}
      WHERE
        resolved_at IS NULL
    ) AS _deduped
  ) AS _extract
) AS _replay
ON _target._source_row_id = _replay._source_row_id
WHEN MATCHED AND _target.resolved_at IS NULL THEN UPDATE SET
  failed_rules = _replay.failed_rules,
  last_evaluated_at = CURRENT_TIMESTAMP
  {% endset %}
  {% do run_query(statement_2) %}

  {% do run_query("COMMIT") %}
{% endmacro %}
