-- Generated by bloomery — do not edit.
-- fingerprint: blm1:b5bf2fa542b0b18f51126e0eb175da99d6abaf964d79e6634a7a4d57439d08e2
--
-- Run this with `dbt run-operation replay_q_dup`. The three statements below are
-- one unit of work and the macro says so to the engine; bloomery executes
-- nothing — this file is text until you run it.
{% macro replay_q_dup() %}
  {% do run_query("BEGIN") %}

  {% set statement_0 %}
MERGE INTO {{ ref('q_dup') }} AS _target
USING (
  SELECT
    group_id,
    note,
    status,
    _ingested_at,
    _load_id,
    _source_row_id,
    _quality_flags,
    _quality_ok
  FROM (
    SELECT
      _evaluated.group_id,
      _evaluated.note,
      _evaluated.status,
      _evaluated._ingested_at,
      _evaluated._load_id,
      _evaluated._source_row_id,
      _evaluated._quality_flags,
      COALESCE(ARRAY_LENGTH(_evaluated._quality_flags, 1), 0) = 0 AS _quality_ok,
      ROW_NUMBER() OVER (PARTITION BY group_id ORDER BY _source_row_id DESC NULLS LAST) AS _w
    FROM (
      SELECT
        _extract.group_id,
        _extract.note,
        _extract.status,
        _extract._ingested_at,
        _extract._load_id,
        _extract._source_row_id,
        CASE
          WHEN _extract._branch_note_coercible
          THEN ARRAY['note_coercible']
          ELSE CAST(ARRAY[] AS TEXT[])
        END AS _quality_flags
      FROM (
        SELECT
          CASE
            WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.group_id'), 'TEXT')
            THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.group_id') AS TEXT)
          END AS group_id,
          CASE
            WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.note'), 'TEXT')
            THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.note') AS TEXT)
          END AS note,
          CASE
            WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.status'), 'TEXT')
            THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.status') AS TEXT)
          END AS status,
          _ingested_at,
          _load_id,
          _source_row_id,
          CASE
            WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.group_id'), 'TEXT')
            THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.group_id') AS TEXT)
          END IS NULL
          AND (
            NOT JSON_EXTRACT_PATH_TEXT(raw, '$.group_id') IS NULL
          ) AS _branch_group_id_coercible,
          CASE
            WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.note'), 'TEXT')
            THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.note') AS TEXT)
          END IS NULL
          AND (
            NOT JSON_EXTRACT_PATH_TEXT(raw, '$.note') IS NULL
          ) AS _branch_note_coercible,
          CASE
            WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.status'), 'TEXT')
            THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.status') AS TEXT)
          END IS NULL
          AND (
            NOT JSON_EXTRACT_PATH_TEXT(raw, '$.status') IS NULL
          ) AS _branch_status_coercible
        FROM {{ ref('q_dup__reject') }}
        WHERE
          resolved_at IS NULL
      ) AS _extract
      WHERE
        NOT COALESCE(
          (
            _extract._branch_group_id_coercible
            OR _extract._branch_status_coercible
            OR (
              NOT _extract.status IN ('open', 'closed')
            )
          ),
          FALSE
        )
    ) AS _evaluated
  ) AS _t
  WHERE
    _w = 1
) AS _replay
ON _target.group_id = _replay.group_id
WHEN MATCHED AND (
  (
    NOT _replay._source_row_id IS NULL AND _target._source_row_id IS NULL
  )
  OR (
    NOT _replay._source_row_id IS NULL
    AND NOT _target._source_row_id IS NULL
    AND _replay._source_row_id > _target._source_row_id
  )
) THEN UPDATE SET
  note = _replay.note,
  status = _replay.status,
  _ingested_at = _replay._ingested_at,
  _load_id = _replay._load_id,
  _source_row_id = _replay._source_row_id,
  _quality_flags = _replay._quality_flags,
  _quality_ok = _replay._quality_ok
WHEN NOT MATCHED THEN INSERT (
  group_id,
  note,
  status,
  _ingested_at,
  _load_id,
  _source_row_id,
  _quality_flags,
  _quality_ok
) VALUES (
  _replay.group_id,
  _replay.note,
  _replay.status,
  _replay._ingested_at,
  _replay._load_id,
  _replay._source_row_id,
  _replay._quality_flags,
  _replay._quality_ok
)
  {% endset %}
  {% do run_query(statement_0) %}
  {% set statement_1 %}
UPDATE {{ ref('q_dup__reject') }} SET resolved_at = CURRENT_TIMESTAMP, last_evaluated_at = CURRENT_TIMESTAMP
WHERE
  resolved_at IS NULL
  AND _source_row_id IN (
    SELECT
      _target._source_row_id
    FROM {{ ref('q_dup') }} AS _target
  )
  {% endset %}
  {% do run_query(statement_1) %}
  {% set statement_2 %}
MERGE INTO {{ ref('q_dup__reject') }} AS _target
USING (
  SELECT
    _extract._source_row_id,
    ARRAY_CAT(
      ARRAY_CAT(
        ARRAY_CAT(
          ARRAY_CAT(
            CASE
              WHEN NOT COALESCE(
                (
                  _extract._branch_group_id_coercible
                  OR _extract._branch_status_coercible
                  OR (
                    NOT _extract.status IN ('open', 'closed')
                  )
                ),
                FALSE
              )
              THEN ARRAY['(superseded)']
              ELSE CAST(ARRAY[] AS TEXT[])
            END,
            CASE
              WHEN _extract._branch_group_id_coercible
              THEN ARRAY['group_id_coercible']
              ELSE CAST(ARRAY[] AS TEXT[])
            END
          ),
          CASE
            WHEN _extract._branch_note_coercible
            THEN ARRAY['note_coercible']
            ELSE CAST(ARRAY[] AS TEXT[])
          END
        ),
        CASE
          WHEN _extract._branch_status_coercible
          THEN ARRAY['status_coercible']
          ELSE CAST(ARRAY[] AS TEXT[])
        END
      ),
      CASE
        WHEN NOT _extract.status IN ('open', 'closed')
        THEN ARRAY['status_in_set']
        ELSE CAST(ARRAY[] AS TEXT[])
      END
    ) AS failed_rules
  FROM (
    SELECT
      CASE
        WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.group_id'), 'TEXT')
        THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.group_id') AS TEXT)
      END AS group_id,
      CASE
        WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.note'), 'TEXT')
        THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.note') AS TEXT)
      END AS note,
      CASE
        WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.status'), 'TEXT')
        THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.status') AS TEXT)
      END AS status,
      _ingested_at,
      _load_id,
      _source_row_id,
      CASE
        WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.group_id'), 'TEXT')
        THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.group_id') AS TEXT)
      END IS NULL
      AND (
        NOT JSON_EXTRACT_PATH_TEXT(raw, '$.group_id') IS NULL
      ) AS _branch_group_id_coercible,
      CASE
        WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.note'), 'TEXT')
        THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.note') AS TEXT)
      END IS NULL
      AND (
        NOT JSON_EXTRACT_PATH_TEXT(raw, '$.note') IS NULL
      ) AS _branch_note_coercible,
      CASE
        WHEN PG_INPUT_IS_VALID(JSON_EXTRACT_PATH_TEXT(raw, '$.status'), 'TEXT')
        THEN CAST(JSON_EXTRACT_PATH_TEXT(raw, '$.status') AS TEXT)
      END IS NULL
      AND (
        NOT JSON_EXTRACT_PATH_TEXT(raw, '$.status') IS NULL
      ) AS _branch_status_coercible
    FROM {{ ref('q_dup__reject') }}
    WHERE
      resolved_at IS NULL
  ) AS _extract
) AS _replay
ON _target._source_row_id = _replay._source_row_id
WHEN MATCHED AND _target.resolved_at IS NULL THEN UPDATE SET
  failed_rules = _replay.failed_rules,
  last_evaluated_at = CURRENT_TIMESTAMP
  {% endset %}
  {% do run_query(statement_2) %}

  {% do run_query("COMMIT") %}
{% endmacro %}
