-- Generated by bloomery — do not edit.
-- fingerprint: blm1:f123d3719f329791c37b128839f1802f9da33eccecaeb9535e5c7938a40c007d
MODEL (
  name silver.order_line__reject,
  kind INCREMENTAL_BY_UNIQUE_KEY (unique_key (reject_id), when_matched (WHEN MATCHED THEN UPDATE SET target.source_relation = source.source_relation, target.mapping = source.mapping, target.mapping_version = source.mapping_version, target.failed_rules = source.failed_rules, target.key_values = source.key_values, target."raw" = source."raw", target._load_id = source._load_id, target._ingested_at = source._ingested_at, target._source_row_id = source._source_row_id, target.first_seen = COALESCE(target.first_seen, source.first_seen), target.last_seen = source.last_seen, target.resolved_at = source.resolved_at, target.last_evaluated_at = COALESCE(target.last_evaluated_at, source.last_evaluated_at))),
  grain (reject_id)
);

SELECT
  _extract.reject_id,
  _extract.source_relation,
  _extract.mapping,
  _extract.mapping_version,
  TRIM(LEADING ',' FROM CASE
    WHEN _extract._branch_gift_note_coercible
    THEN ',gift_note_coercible'
    ELSE ''
  END || CASE WHEN _extract._branch_line_no_coercible THEN ',line_no_coercible' ELSE '' END || CASE WHEN _extract._branch_order_id_coercible THEN ',order_id_coercible' ELSE '' END || CASE
    WHEN _extract._branch_placed_at_coercible
    THEN ',placed_at_coercible'
    ELSE ''
  END || CASE WHEN _extract._branch_quantity_coercible THEN ',quantity_coercible' ELSE '' END || CASE WHEN _extract._branch_sku_coercible THEN ',sku_coercible' ELSE '' END || CASE WHEN _extract._branch_status_coercible THEN ',status_coercible' ELSE '' END || CASE WHEN _extract._branch_status_in_enum THEN ',status_in_enum' ELSE '' END) AS failed_rules,
  OBJECT('line_no', _extract.line_no, 'order_id', _extract.order_id) AS key_values,
  _extract._raw AS "raw",
  _extract._load_id,
  _extract._ingested_at,
  _extract._source_row_id,
  _extract._ingested_at AS first_seen,
  _extract._ingested_at AS last_seen,
  CAST(NULL AS TIMESTAMP) AS resolved_at,
  CAST(NULL AS TIMESTAMP) AS last_evaluated_at
FROM (
  SELECT
    *
  FROM (
    SELECT
      TRY_CAST(JSON_EXTRACT_PATH_TEXT(properties, 'gift_note') AS VARCHAR(MAX)) AS gift_note,
      TRY_CAST(position AS BIGINT) AS line_no,
      TRY_CAST(JSON_EXTRACT_PATH_TEXT("order", 'id') AS VARCHAR(MAX)) AS order_id,
      TRY_CAST(CASE
        WHEN SUBSTRING(CAST(created_at AS VARCHAR) FROM 11) LIKE '%+%'
        OR SUBSTRING(CAST(created_at AS VARCHAR) FROM 11) LIKE '%-%'
        THEN NULL
        ELSE created_at
      END AS TIMESTAMP) AS placed_at,
      TRY_CAST(quantity AS BIGINT) AS quantity,
      TRY_CAST(JSON_EXTRACT_PATH_TEXT(variant, 'sku') AS VARCHAR(MAX)) AS sku,
      CASE TRY_CAST(financial_status AS VARCHAR(MAX))
        WHEN 'pending'
        THEN 'open'
        WHEN 'paid'
        THEN 'closed'
        WHEN 'refunded'
        THEN 'reversed'
        ELSE TRY_CAST(financial_status AS VARCHAR(MAX))
      END AS status,
      _ingested_at,
      _load_id,
      _source_row_id,
      TRY_CAST(JSON_EXTRACT_PATH_TEXT(properties, 'gift_note') AS VARCHAR(MAX)) IS NULL
      AND (
        NOT JSON_EXTRACT_PATH_TEXT(properties, 'gift_note') IS NULL
      ) AS _branch_gift_note_coercible,
      TRY_CAST(position AS BIGINT) IS NULL AND (
        NOT position IS NULL
      ) AS _branch_line_no_coercible,
      TRY_CAST(JSON_EXTRACT_PATH_TEXT("order", 'id') AS VARCHAR(MAX)) IS NULL
      AND (
        NOT JSON_EXTRACT_PATH_TEXT("order", 'id') IS NULL
      ) AS _branch_order_id_coercible,
      TRY_CAST(CASE
        WHEN SUBSTRING(CAST(created_at AS VARCHAR) FROM 11) LIKE '%+%'
        OR SUBSTRING(CAST(created_at AS VARCHAR) FROM 11) LIKE '%-%'
        THEN NULL
        ELSE created_at
      END AS TIMESTAMP) IS NULL
      AND (
        NOT created_at IS NULL
      ) AS _branch_placed_at_coercible,
      TRY_CAST(quantity AS BIGINT) IS NULL AND (
        NOT quantity IS NULL
      ) AS _branch_quantity_coercible,
      TRY_CAST(JSON_EXTRACT_PATH_TEXT(variant, 'sku') AS VARCHAR(MAX)) IS NULL
      AND (
        NOT JSON_EXTRACT_PATH_TEXT(variant, 'sku') IS NULL
      ) AS _branch_sku_coercible,
      CASE TRY_CAST(financial_status AS VARCHAR(MAX))
        WHEN 'pending'
        THEN 'open'
        WHEN 'paid'
        THEN 'closed'
        WHEN 'refunded'
        THEN 'reversed'
        ELSE TRY_CAST(financial_status AS VARCHAR(MAX))
      END IS NULL
      AND (
        NOT financial_status IS NULL
      ) AS _branch_status_coercible,
      NOT CASE TRY_CAST(financial_status AS VARCHAR(MAX))
        WHEN 'pending'
        THEN 'open'
        WHEN 'paid'
        THEN 'closed'
        WHEN 'refunded'
        THEN 'reversed'
        ELSE TRY_CAST(financial_status AS VARCHAR(MAX))
      END IN ('closed', 'open', 'reversed') AS _branch_status_in_enum,
      OBJECT(
        '_ingested_at',
        _ingested_at,
        '_load_id',
        _load_id,
        '_source_row_id',
        _source_row_id,
        'created_at',
        created_at,
        'financial_status',
        financial_status,
        'order',
        "order",
        'position',
        position,
        'properties',
        properties,
        'quantity',
        quantity,
        'variant',
        variant
      ) AS _raw,
      'shopify__order_lines' AS _source,
      SHA2(
        'S20:shopify__order_lines' || 'S' || CAST(LENGTH(_source_row_id) AS VARCHAR(MAX)) || ':' || _source_row_id,
        256
      ) AS reject_id,
      'shopify__order_lines' AS source_relation,
      'shopify__order_lines->order_line' AS mapping,
      1 AS mapping_version
    FROM bronze.shopify__order_lines
    UNION ALL
    SELECT
      CAST(NULL AS VARCHAR(MAX)) AS gift_note,
      TRY_CAST(item_index AS BIGINT) AS line_no,
      TRY_CAST(order_number AS VARCHAR(MAX)) AS order_id,
      TRY_CAST(CASE
        WHEN SUBSTRING(CAST(created AS VARCHAR) FROM 11) LIKE '%+%'
        OR SUBSTRING(CAST(created AS VARCHAR) FROM 11) LIKE '%-%'
        THEN NULL
        ELSE created
      END AS TIMESTAMP) AS placed_at,
      TRY_CAST(qty AS BIGINT) AS quantity,
      TRY_CAST(product_sku AS VARCHAR(MAX)) AS sku,
      CASE TRY_CAST(state AS VARCHAR(MAX))
        WHEN 'PROCESSING'
        THEN 'open'
        WHEN 'COMPLETE'
        THEN 'closed'
        ELSE TRY_CAST(state AS VARCHAR(MAX))
      END AS status,
      _ingested_at,
      _load_id,
      _source_row_id,
      FALSE AS _branch_gift_note_coercible,
      TRY_CAST(item_index AS BIGINT) IS NULL AND (
        NOT item_index IS NULL
      ) AS _branch_line_no_coercible,
      TRY_CAST(order_number AS VARCHAR(MAX)) IS NULL AND (
        NOT order_number IS NULL
      ) AS _branch_order_id_coercible,
      TRY_CAST(CASE
        WHEN SUBSTRING(CAST(created AS VARCHAR) FROM 11) LIKE '%+%'
        OR SUBSTRING(CAST(created AS VARCHAR) FROM 11) LIKE '%-%'
        THEN NULL
        ELSE created
      END AS TIMESTAMP) IS NULL
      AND (
        NOT created IS NULL
      ) AS _branch_placed_at_coercible,
      TRY_CAST(qty AS BIGINT) IS NULL AND (
        NOT qty IS NULL
      ) AS _branch_quantity_coercible,
      TRY_CAST(product_sku AS VARCHAR(MAX)) IS NULL AND (
        NOT product_sku IS NULL
      ) AS _branch_sku_coercible,
      CASE TRY_CAST(state AS VARCHAR(MAX))
        WHEN 'PROCESSING'
        THEN 'open'
        WHEN 'COMPLETE'
        THEN 'closed'
        ELSE TRY_CAST(state AS VARCHAR(MAX))
      END IS NULL
      AND (
        NOT state IS NULL
      ) AS _branch_status_coercible,
      NOT CASE TRY_CAST(state AS VARCHAR(MAX))
        WHEN 'PROCESSING'
        THEN 'open'
        WHEN 'COMPLETE'
        THEN 'closed'
        ELSE TRY_CAST(state AS VARCHAR(MAX))
      END IN ('closed', 'open') AS _branch_status_in_enum,
      OBJECT(
        '_ingested_at',
        _ingested_at,
        '_load_id',
        _load_id,
        '_source_row_id',
        _source_row_id,
        'created',
        created,
        'item_index',
        item_index,
        'order_number',
        order_number,
        'product_sku',
        product_sku,
        'qty',
        qty,
        'state',
        state
      ) AS _raw,
      'woo__order_lines' AS _source,
      SHA2(
        'S16:woo__order_lines' || 'S' || CAST(LENGTH(_source_row_id) AS VARCHAR(MAX)) || ':' || _source_row_id,
        256
      ) AS reject_id,
      'woo__order_lines' AS source_relation,
      'woo__order_lines->order_line' AS mapping,
      1 AS mapping_version
    FROM bronze.woo__order_lines
  ) AS _extract
  QUALIFY
    ROW_NUMBER() OVER (
      PARTITION BY order_id, line_no
      ORDER BY placed_at DESC NULLS LAST, line_no DESC NULLS LAST, _source DESC NULLS LAST, _source_row_id DESC NULLS LAST
    ) = 1
) AS _extract
WHERE
  COALESCE(
    (
      _extract._branch_gift_note_coercible
      OR _extract._branch_order_id_coercible
      OR _extract._branch_quantity_coercible
      OR _extract._branch_sku_coercible
      OR _extract._branch_status_coercible
      OR _extract._branch_status_in_enum
    ),
    FALSE
  )
