-- Generated by bloomery — do not edit.
-- fingerprint: blm1:954f6bd4bf36632be9fbcfd75582c4b32b51b0d9d7511de05e61dfd0281b1563
{% macro generate_schema_name(custom_schema_name, node) -%}
{%- if custom_schema_name is none -%}
{{ target.schema }}
{%- else -%}
{{ custom_schema_name | trim }}
{%- endif -%}
{%- endmacro %}
