-- Generated by bloomery — do not edit.
-- fingerprint: blm1:f08fc2ecdb327ef3d3cb465ef3d694be3071044eb6fc14d986f22e99ba91cf6f
{% macro generate_schema_name(custom_schema_name, node) -%}
{%- if custom_schema_name is none -%}
{{ target.schema }}
{%- else -%}
{{ custom_schema_name | trim }}
{%- endif -%}
{%- endmacro %}
