-- Generated by bloomery — do not edit.
-- fingerprint: blm1:f02114f747f249f12fe7d8789848381d91e90a8a8d1174229fed2c1a8bfea5b3
{% macro generate_schema_name(custom_schema_name, node) -%}
{%- if custom_schema_name is none -%}
{{ target.schema }}
{%- else -%}
{{ custom_schema_name | trim }}
{%- endif -%}
{%- endmacro %}
