-- Generated by bloomery — do not edit.
-- fingerprint: blm1:230a445d0ee7283d7df0d8e427b9172991624aca40688cf4316cf065f42d84f5
MODEL (
  name silver.customer,
  kind SCD_TYPE_2_BY_COLUMN (unique_key (customer_id), columns *, valid_from_name valid_from, valid_to_name valid_to),
  grain (customer_id),
  audits (accepted_values(column := segment, is_in := ('business', 'consumer')), not_null(columns := (email)))
);

SELECT
  CAST(id AS TEXT) AS customer_id,
  CAST(email AS TEXT) AS email,
  CAST(segment AS TEXT) AS segment,
  CAST([] AS TEXT[]) AS _quality_flags,
  TRUE AS _quality_ok
FROM bronze.crm__customers
