-- Generated by bloomery — do not edit.
-- fingerprint: blm1:2b2d5b22e2a855dc5c31819c5fd4c8ffb46634e5dd1679202d85475640c15487
MODEL (
  name silver.customer,
  kind SCD_TYPE_2_BY_COLUMN (unique_key (customer_id), columns *),
  grain (customer_id),
  audits (accepted_values(column := segment, is_in := ('business', 'consumer')), not_null(columns := (email)))
);

SELECT
  CAST(id AS TEXT) AS customer_id,
  CAST(email AS TEXT) AS email,
  CAST(segment AS TEXT) AS segment,
  CAST([] AS TEXT[]) AS _quality_flags,
  TRUE AS _quality_ok
FROM bronze.crm__customers
