-- Generated by bloomery — do not edit.
-- fingerprint: blm1:f08fc2ecdb327ef3d3cb465ef3d694be3071044eb6fc14d986f22e99ba91cf6f
AUDIT (
  name order_key_unique
);

SELECT
  _entity.order_id,
  COUNT(*) AS key_rows
FROM @this_model AS _entity
GROUP BY
  _entity.order_id
HAVING
  COUNT(*) > 1
