-- Generated by bloomery — do not edit.
-- fingerprint: blm1:d74b550cabc17d419b7c3b416b571d727f2be318e4a15f7410cfafa6bf58f3d9
AUDIT (
  name order_key_unique
);

SELECT
  _entity.order_id,
  COUNT(*) AS key_rows
FROM @this_model AS _entity
GROUP BY
  _entity.order_id
HAVING
  COUNT(*) > 1
