-- Generated by bloomery — do not edit.
-- fingerprint: blm1:b9ce1fafcd7e3d01a0e91407918371c7f45fa9b2cfd1bb734f19d754ffdc304d
{{ config(materialized='table') }}

SELECT
  *,
  CAST(ARRAY[] AS TEXT[]) AS _quality_flags,
  TRUE AS _quality_ok
FROM (
  SELECT
    CAST(properties ->> 'gift_note' AS TEXT) AS gift_note,
    CAST(position AS BIGINT) AS line_no,
    CAST("order" ->> 'id' AS TEXT) AS order_id,
    CAST(quantity AS BIGINT) AS quantity,
    CAST(variant ->> 'sku' AS TEXT) AS sku,
    'shopify__order_lines' AS _source
  FROM {{ source('bronze', 'shopify__order_lines') }}
  UNION ALL
  SELECT
    CAST(NULL AS TEXT) AS gift_note,
    CAST(item_index AS BIGINT) AS line_no,
    CAST(order_number AS TEXT) AS order_id,
    CAST(qty AS BIGINT) AS quantity,
    CAST(product_sku AS TEXT) AS sku,
    'woo__order_lines' AS _source
  FROM {{ source('bronze', 'woo__order_lines') }}
) AS _extract
