-- Generated by bloomery — do not edit.
-- fingerprint: blm1:9b09dfd3b4023aaf496bbd9aaa08abbc99b88f1775a988bfe7dc977d825c46ad
MODEL (
  name gold.dim_date,
  kind FULL,
  grain (date_day)
);

SELECT
  CAST(date_day AS DATE) AS date_day,
  CAST(DATE_TRUNC('MONTH', date_day) AS DATE) AS date_month,
  CAST(DATE_TRUNC('QUARTER', date_day) AS DATE) AS date_quarter,
  CAST(DATE_TRUNC('WEEK', date_day) AS DATE) AS date_week,
  CAST(DATE_TRUNC('YEAR', date_day) AS DATE) AS date_year
FROM (
  SELECT
    CAST('2020-01-01' AS DATE) + n AS date_day
  FROM (
    SELECT
      CAST(ROW_NUMBER() OVER () - 1 AS INTEGER) AS n
    FROM (
      SELECT
        0 AS d
      UNION ALL
      SELECT
        1 AS d
      UNION ALL
      SELECT
        2 AS d
      UNION ALL
      SELECT
        3 AS d
      UNION ALL
      SELECT
        4 AS d
      UNION ALL
      SELECT
        5 AS d
      UNION ALL
      SELECT
        6 AS d
      UNION ALL
      SELECT
        7 AS d
      UNION ALL
      SELECT
        8 AS d
      UNION ALL
      SELECT
        9 AS d
    ) AS d0
    CROSS JOIN (
      SELECT
        0 AS d
      UNION ALL
      SELECT
        1 AS d
      UNION ALL
      SELECT
        2 AS d
      UNION ALL
      SELECT
        3 AS d
      UNION ALL
      SELECT
        4 AS d
      UNION ALL
      SELECT
        5 AS d
      UNION ALL
      SELECT
        6 AS d
      UNION ALL
      SELECT
        7 AS d
      UNION ALL
      SELECT
        8 AS d
      UNION ALL
      SELECT
        9 AS d
    ) AS d1
    CROSS JOIN (
      SELECT
        0 AS d
      UNION ALL
      SELECT
        1 AS d
      UNION ALL
      SELECT
        2 AS d
      UNION ALL
      SELECT
        3 AS d
      UNION ALL
      SELECT
        4 AS d
      UNION ALL
      SELECT
        5 AS d
      UNION ALL
      SELECT
        6 AS d
      UNION ALL
      SELECT
        7 AS d
      UNION ALL
      SELECT
        8 AS d
      UNION ALL
      SELECT
        9 AS d
    ) AS d2
    CROSS JOIN (
      SELECT
        0 AS d
      UNION ALL
      SELECT
        1 AS d
      UNION ALL
      SELECT
        2 AS d
      UNION ALL
      SELECT
        3 AS d
      UNION ALL
      SELECT
        4 AS d
      UNION ALL
      SELECT
        5 AS d
      UNION ALL
      SELECT
        6 AS d
      UNION ALL
      SELECT
        7 AS d
      UNION ALL
      SELECT
        8 AS d
      UNION ALL
      SELECT
        9 AS d
    ) AS d3
  ) AS numbers
  WHERE
    n < 4018
) AS date_day
