-- Generated by bloomery — do not edit.
-- fingerprint: blm1:c5e0c917ca98d591bb55dc407e9eb0ff4fc5335fe70ddfbdb8f09fa5cba0c9b8
AUDIT (
  name order_key_unique
);

SELECT
  _entity.order_id,
  COUNT(*) AS key_rows
FROM @this_model AS _entity
GROUP BY
  _entity.order_id
HAVING
  COUNT(*) > 1
