-- Generated by bloomery — do not edit.
-- fingerprint: blm1:61ce122a301349c2af09efeafde70e4439d3f648ac8e1025db2a3bce680790f0
-- The disjointness law (RFC 0024 §5.4) as a runtime audit: a union merge
-- requires the sources' key sets to be disjoint, and the compiler has no data
-- to establish it with. Blocking, and not configurable to a weaker
-- disposition (D5) — a key in two sources is either genuine duplication or a
-- shared key space by accident, and both are refusals. Flagging it would let a
-- double-counted entity into the warehouse marked merely suspect.
AUDIT (
  name order_line_source_collision
);

SELECT
  order_id,
  line_no,
  COUNT(DISTINCT _source) AS sources
FROM @this_model AS _entity
GROUP BY
  order_id,
  line_no
HAVING
  COUNT(DISTINCT _source) > 1
