-- Generated by bloomery — do not edit.
-- fingerprint: blm1:312a029cdfe71aaa59431815ce7393aebc6de8e212cc9dc3ebcbb5ec24a81535
MODEL (
  name silver.order_line,
  kind FULL,
  grain (order_id, line_no),
  audits (order_line_source_collision, order_line_key_unique)
);

SELECT
  *,
  CAST(ARRAY() AS ARRAY<STRING>) AS _quality_flags,
  TRUE AS _quality_ok
FROM (
  SELECT
    CAST(properties:gift_note AS STRING) AS gift_note,
    CAST(position AS BIGINT) AS line_no,
    CAST(`order`:id AS STRING) AS order_id,
    CAST(quantity AS BIGINT) AS quantity,
    CAST(variant:sku AS STRING) AS sku,
    'shopify__order_lines' AS _source
  FROM bronze.shopify__order_lines
  UNION ALL
  SELECT
    CAST(NULL AS STRING) AS gift_note,
    CAST(item_index AS BIGINT) AS line_no,
    CAST(order_number AS STRING) AS order_id,
    CAST(qty AS BIGINT) AS quantity,
    CAST(product_sku AS STRING) AS sku,
    'woo__order_lines' AS _source
  FROM bronze.woo__order_lines
) AS _extract
