-- Generated by bloomery — do not edit.
-- fingerprint: blm1:4bbad191a61dccb442835e67992d617af3d6077b80515a275a91481c92ba089c
-- Quarantine replay for order_line (S-0033/quarantine-one-reject-table-per-entity). bloomery emits this
-- artifact and never executes it: run the statements below, in order, as one
-- unit of work — the passers merge, the rows that made it resolve, and the
-- rest have their failed_rules re-derived from the very same evaluation.
-- Winners are decided by the pipeline's own dedupe total order, so re-running
-- replay re-derives identical semantic state (D22). Retention — never replay —
-- deletes reject rows; resolved rows are kept as audit history.

MERGE INTO silver.order_line AS _target
USING (
  SELECT
    _evaluated.gift_note,
    _evaluated.line_no,
    _evaluated.order_id,
    _evaluated.placed_at,
    _evaluated.quantity,
    _evaluated.sku,
    _evaluated.status,
    _evaluated._source,
    _evaluated._ingested_at,
    _evaluated._load_id,
    _evaluated._source_row_id,
    _evaluated._quality_flags,
    COALESCE(ARRAY_LENGTH(_evaluated._quality_flags), 0) = 0 AS _quality_ok
  FROM (
    SELECT
      _extract.gift_note,
      _extract.line_no,
      _extract.order_id,
      _extract.placed_at,
      _extract.quantity,
      _extract.sku,
      _extract.status,
      _extract._source,
      _extract._ingested_at,
      _extract._load_id,
      _extract._source_row_id,
      ARRAY_CONCAT(
        CASE
          WHEN _extract._branch_line_no_coercible
          THEN ['line_no_coercible']
          ELSE ARRAY<STRING>[]
        END,
        CASE
          WHEN _extract._branch_placed_at_coercible
          THEN ['placed_at_coercible']
          ELSE ARRAY<STRING>[]
        END
      ) AS _quality_flags
    FROM (
      SELECT
        SAFE_CAST(JSON_EXTRACT_SCALAR(JSON_EXTRACT_SCALAR(raw, '$.properties'), '$.gift_note') AS STRING) AS gift_note,
        SAFE_CAST(JSON_EXTRACT_SCALAR(raw, '$.position') AS INT64) AS line_no,
        SAFE_CAST(JSON_EXTRACT_SCALAR(JSON_EXTRACT_SCALAR(raw, '$.order'), '$.id') AS STRING) AS order_id,
        SAFE_CAST(CASE
          WHEN SUBSTR(CAST(JSON_EXTRACT_SCALAR(raw, '$.created_at') AS STRING), 11) LIKE '%+%'
          OR SUBSTR(CAST(JSON_EXTRACT_SCALAR(raw, '$.created_at') AS STRING), 11) LIKE '%-%'
          THEN NULL
          ELSE RTRIM(
            REPLACE(
              REPLACE(CAST(JSON_EXTRACT_SCALAR(raw, '$.created_at') AS STRING), 'T', ' '),
              't',
              ' '
            ),
            'Zz'
          )
        END AS DATETIME) AS placed_at,
        SAFE_CAST(JSON_EXTRACT_SCALAR(raw, '$.quantity') AS INT64) AS quantity,
        SAFE_CAST(JSON_EXTRACT_SCALAR(JSON_EXTRACT_SCALAR(raw, '$.variant'), '$.sku') AS STRING) AS sku,
        CASE SAFE_CAST(JSON_EXTRACT_SCALAR(raw, '$.financial_status') AS STRING)
          WHEN 'pending'
          THEN 'open'
          WHEN 'paid'
          THEN 'closed'
          WHEN 'refunded'
          THEN 'reversed'
          ELSE SAFE_CAST(JSON_EXTRACT_SCALAR(raw, '$.financial_status') AS STRING)
        END AS status,
        _ingested_at,
        _load_id,
        _source_row_id,
        SAFE_CAST(JSON_EXTRACT_SCALAR(JSON_EXTRACT_SCALAR(raw, '$.properties'), '$.gift_note') AS STRING) IS NULL
        AND (
          NOT JSON_EXTRACT_SCALAR(JSON_EXTRACT_SCALAR(raw, '$.properties'), '$.gift_note') IS NULL
        ) AS _branch_gift_note_coercible,
        SAFE_CAST(JSON_EXTRACT_SCALAR(raw, '$.position') AS INT64) IS NULL
        AND (
          NOT JSON_EXTRACT_SCALAR(raw, '$.position') IS NULL
        ) AS _branch_line_no_coercible,
        SAFE_CAST(JSON_EXTRACT_SCALAR(JSON_EXTRACT_SCALAR(raw, '$.order'), '$.id') AS STRING) IS NULL
        AND (
          NOT JSON_EXTRACT_SCALAR(JSON_EXTRACT_SCALAR(raw, '$.order'), '$.id') IS NULL
        ) AS _branch_order_id_coercible,
        SAFE_CAST(CASE
          WHEN SUBSTR(CAST(JSON_EXTRACT_SCALAR(raw, '$.created_at') AS STRING), 11) LIKE '%+%'
          OR SUBSTR(CAST(JSON_EXTRACT_SCALAR(raw, '$.created_at') AS STRING), 11) LIKE '%-%'
          THEN NULL
          ELSE RTRIM(
            REPLACE(
              REPLACE(CAST(JSON_EXTRACT_SCALAR(raw, '$.created_at') AS STRING), 'T', ' '),
              't',
              ' '
            ),
            'Zz'
          )
        END AS DATETIME) IS NULL
        AND (
          NOT JSON_EXTRACT_SCALAR(raw, '$.created_at') IS NULL
        ) AS _branch_placed_at_coercible,
        SAFE_CAST(JSON_EXTRACT_SCALAR(raw, '$.quantity') AS INT64) IS NULL
        AND (
          NOT JSON_EXTRACT_SCALAR(raw, '$.quantity') IS NULL
        ) AS _branch_quantity_coercible,
        SAFE_CAST(JSON_EXTRACT_SCALAR(JSON_EXTRACT_SCALAR(raw, '$.variant'), '$.sku') AS STRING) IS NULL
        AND (
          NOT JSON_EXTRACT_SCALAR(JSON_EXTRACT_SCALAR(raw, '$.variant'), '$.sku') IS NULL
        ) AS _branch_sku_coercible,
        CASE SAFE_CAST(JSON_EXTRACT_SCALAR(raw, '$.financial_status') AS STRING)
          WHEN 'pending'
          THEN 'open'
          WHEN 'paid'
          THEN 'closed'
          WHEN 'refunded'
          THEN 'reversed'
          ELSE SAFE_CAST(JSON_EXTRACT_SCALAR(raw, '$.financial_status') AS STRING)
        END IS NULL
        AND (
          NOT JSON_EXTRACT_SCALAR(raw, '$.financial_status') IS NULL
        ) AS _branch_status_coercible,
        NOT CASE SAFE_CAST(JSON_EXTRACT_SCALAR(raw, '$.financial_status') AS STRING)
          WHEN 'pending'
          THEN 'open'
          WHEN 'paid'
          THEN 'closed'
          WHEN 'refunded'
          THEN 'reversed'
          ELSE SAFE_CAST(JSON_EXTRACT_SCALAR(raw, '$.financial_status') AS STRING)
        END IN ('closed', 'open', 'reversed') AS _branch_status_in_enum,
        'shopify__order_lines' AS _source
      FROM silver.order_line__reject
      WHERE
        resolved_at IS NULL AND source_relation = 'shopify__order_lines'
      UNION ALL
      SELECT
        CAST(NULL AS STRING) AS gift_note,
        SAFE_CAST(JSON_EXTRACT_SCALAR(raw, '$.item_index') AS INT64) AS line_no,
        SAFE_CAST(JSON_EXTRACT_SCALAR(raw, '$.order_number') AS STRING) AS order_id,
        SAFE_CAST(CASE
          WHEN SUBSTR(CAST(JSON_EXTRACT_SCALAR(raw, '$.created') AS STRING), 11) LIKE '%+%'
          OR SUBSTR(CAST(JSON_EXTRACT_SCALAR(raw, '$.created') AS STRING), 11) LIKE '%-%'
          THEN NULL
          ELSE RTRIM(
            REPLACE(REPLACE(CAST(JSON_EXTRACT_SCALAR(raw, '$.created') AS STRING), 'T', ' '), 't', ' '),
            'Zz'
          )
        END AS DATETIME) AS placed_at,
        SAFE_CAST(JSON_EXTRACT_SCALAR(raw, '$.qty') AS INT64) AS quantity,
        SAFE_CAST(JSON_EXTRACT_SCALAR(raw, '$.product_sku') AS STRING) AS sku,
        CASE SAFE_CAST(JSON_EXTRACT_SCALAR(raw, '$.state') AS STRING)
          WHEN 'PROCESSING'
          THEN 'open'
          WHEN 'COMPLETE'
          THEN 'closed'
          ELSE SAFE_CAST(JSON_EXTRACT_SCALAR(raw, '$.state') AS STRING)
        END AS status,
        _ingested_at,
        _load_id,
        _source_row_id,
        FALSE AS _branch_gift_note_coercible,
        SAFE_CAST(JSON_EXTRACT_SCALAR(raw, '$.item_index') AS INT64) IS NULL
        AND (
          NOT JSON_EXTRACT_SCALAR(raw, '$.item_index') IS NULL
        ) AS _branch_line_no_coercible,
        SAFE_CAST(JSON_EXTRACT_SCALAR(raw, '$.order_number') AS STRING) IS NULL
        AND (
          NOT JSON_EXTRACT_SCALAR(raw, '$.order_number') IS NULL
        ) AS _branch_order_id_coercible,
        SAFE_CAST(CASE
          WHEN SUBSTR(CAST(JSON_EXTRACT_SCALAR(raw, '$.created') AS STRING), 11) LIKE '%+%'
          OR SUBSTR(CAST(JSON_EXTRACT_SCALAR(raw, '$.created') AS STRING), 11) LIKE '%-%'
          THEN NULL
          ELSE RTRIM(
            REPLACE(REPLACE(CAST(JSON_EXTRACT_SCALAR(raw, '$.created') AS STRING), 'T', ' '), 't', ' '),
            'Zz'
          )
        END AS DATETIME) IS NULL
        AND (
          NOT JSON_EXTRACT_SCALAR(raw, '$.created') IS NULL
        ) AS _branch_placed_at_coercible,
        SAFE_CAST(JSON_EXTRACT_SCALAR(raw, '$.qty') AS INT64) IS NULL
        AND (
          NOT JSON_EXTRACT_SCALAR(raw, '$.qty') IS NULL
        ) AS _branch_quantity_coercible,
        SAFE_CAST(JSON_EXTRACT_SCALAR(raw, '$.product_sku') AS STRING) IS NULL
        AND (
          NOT JSON_EXTRACT_SCALAR(raw, '$.product_sku') IS NULL
        ) AS _branch_sku_coercible,
        CASE SAFE_CAST(JSON_EXTRACT_SCALAR(raw, '$.state') AS STRING)
          WHEN 'PROCESSING'
          THEN 'open'
          WHEN 'COMPLETE'
          THEN 'closed'
          ELSE SAFE_CAST(JSON_EXTRACT_SCALAR(raw, '$.state') AS STRING)
        END IS NULL
        AND (
          NOT JSON_EXTRACT_SCALAR(raw, '$.state') IS NULL
        ) AS _branch_status_coercible,
        NOT CASE SAFE_CAST(JSON_EXTRACT_SCALAR(raw, '$.state') AS STRING)
          WHEN 'PROCESSING'
          THEN 'open'
          WHEN 'COMPLETE'
          THEN 'closed'
          ELSE SAFE_CAST(JSON_EXTRACT_SCALAR(raw, '$.state') AS STRING)
        END IN ('closed', 'open') AS _branch_status_in_enum,
        'woo__order_lines' AS _source
      FROM silver.order_line__reject
      WHERE
        resolved_at IS NULL AND source_relation = 'woo__order_lines'
    ) AS _extract
    WHERE
      NOT COALESCE(
        (
          _extract._branch_gift_note_coercible
          OR _extract._branch_order_id_coercible
          OR _extract._branch_quantity_coercible
          OR _extract._branch_sku_coercible
          OR _extract._branch_status_coercible
          OR _extract._branch_status_in_enum
        ),
        FALSE
      )
  ) AS _evaluated
  QUALIFY
    ROW_NUMBER() OVER (
      PARTITION BY order_id, line_no
      ORDER BY placed_at DESC, line_no DESC, _source DESC, _source_row_id DESC
    ) = 1
) AS _replay
ON _target.order_id = _replay.order_id AND _target.line_no = _replay.line_no
WHEN MATCHED AND (
  (
    (
      NOT _replay.placed_at IS NULL AND _target.placed_at IS NULL
    )
    OR (
      NOT _replay.placed_at IS NULL
      AND NOT _target.placed_at IS NULL
      AND _replay.placed_at > _target.placed_at
    )
  )
  OR (
    (
      (
        _replay.placed_at IS NULL AND _target.placed_at IS NULL
      )
      OR _replay.placed_at = _target.placed_at
    )
    AND (
      (
        (
          NOT _replay.line_no IS NULL AND _target.line_no IS NULL
        )
        OR (
          NOT _replay.line_no IS NULL
          AND NOT _target.line_no IS NULL
          AND _replay.line_no > _target.line_no
        )
      )
      OR (
        (
          (
            _replay.line_no IS NULL AND _target.line_no IS NULL
          )
          OR _replay.line_no = _target.line_no
        )
        AND (
          (
            (
              NOT _replay._source IS NULL AND _target._source IS NULL
            )
            OR (
              NOT _replay._source IS NULL
              AND NOT _target._source IS NULL
              AND _replay._source > _target._source
            )
          )
          OR (
            (
              (
                _replay._source IS NULL AND _target._source IS NULL
              )
              OR _replay._source = _target._source
            )
            AND (
              (
                NOT _replay._source_row_id IS NULL AND _target._source_row_id IS NULL
              )
              OR (
                NOT _replay._source_row_id IS NULL
                AND NOT _target._source_row_id IS NULL
                AND _replay._source_row_id > _target._source_row_id
              )
            )
          )
        )
      )
    )
  )
) THEN UPDATE SET
  gift_note = _replay.gift_note,
  placed_at = _replay.placed_at,
  quantity = _replay.quantity,
  sku = _replay.sku,
  status = _replay.status,
  _source = _replay._source,
  _ingested_at = _replay._ingested_at,
  _load_id = _replay._load_id,
  _source_row_id = _replay._source_row_id,
  _quality_flags = _replay._quality_flags,
  _quality_ok = _replay._quality_ok
WHEN NOT MATCHED THEN INSERT (
  gift_note,
  line_no,
  order_id,
  placed_at,
  quantity,
  sku,
  status,
  _source,
  _ingested_at,
  _load_id,
  _source_row_id,
  _quality_flags,
  _quality_ok
) VALUES (
  _replay.gift_note,
  _replay.line_no,
  _replay.order_id,
  _replay.placed_at,
  _replay.quantity,
  _replay.sku,
  _replay.status,
  _replay._source,
  _replay._ingested_at,
  _replay._load_id,
  _replay._source_row_id,
  _replay._quality_flags,
  _replay._quality_ok
);

UPDATE silver.order_line__reject AS _row SET resolved_at = CURRENT_DATETIME('UTC'), last_evaluated_at = CURRENT_DATETIME('UTC')
WHERE
  resolved_at IS NULL
  AND EXISTS(
    SELECT
      _target._source,
      _target._source_row_id
    FROM silver.order_line AS _target
    WHERE
      _target._source = _row.source_relation
      AND _target._source_row_id = _row._source_row_id
  );

MERGE INTO silver.order_line__reject AS _target
USING (
  SELECT
    _extract._source,
    _extract._source_row_id,
    ARRAY_CONCAT(
      ARRAY_CONCAT(
        ARRAY_CONCAT(
          ARRAY_CONCAT(
            ARRAY_CONCAT(
              ARRAY_CONCAT(
                ARRAY_CONCAT(
                  ARRAY_CONCAT(
                    CASE
                      WHEN NOT COALESCE(
                        (
                          _extract._branch_gift_note_coercible
                          OR _extract._branch_order_id_coercible
                          OR _extract._branch_quantity_coercible
                          OR _extract._branch_sku_coercible
                          OR _extract._branch_status_coercible
                          OR _extract._branch_status_in_enum
                        ),
                        FALSE
                      )
                      THEN ['(superseded)']
                      ELSE ARRAY<STRING>[]
                    END,
                    CASE
                      WHEN _extract._branch_gift_note_coercible
                      THEN ['gift_note_coercible']
                      ELSE ARRAY<STRING>[]
                    END
                  ),
                  CASE
                    WHEN _extract._branch_line_no_coercible
                    THEN ['line_no_coercible']
                    ELSE ARRAY<STRING>[]
                  END
                ),
                CASE
                  WHEN _extract._branch_order_id_coercible
                  THEN ['order_id_coercible']
                  ELSE ARRAY<STRING>[]
                END
              ),
              CASE
                WHEN _extract._branch_placed_at_coercible
                THEN ['placed_at_coercible']
                ELSE ARRAY<STRING>[]
              END
            ),
            CASE
              WHEN _extract._branch_quantity_coercible
              THEN ['quantity_coercible']
              ELSE ARRAY<STRING>[]
            END
          ),
          CASE
            WHEN _extract._branch_sku_coercible
            THEN ['sku_coercible']
            ELSE ARRAY<STRING>[]
          END
        ),
        CASE
          WHEN _extract._branch_status_coercible
          THEN ['status_coercible']
          ELSE ARRAY<STRING>[]
        END
      ),
      CASE
        WHEN _extract._branch_status_in_enum
        THEN ['status_in_enum']
        ELSE ARRAY<STRING>[]
      END
    ) AS failed_rules
  FROM (
    SELECT
      SAFE_CAST(JSON_EXTRACT_SCALAR(JSON_EXTRACT_SCALAR(raw, '$.properties'), '$.gift_note') AS STRING) AS gift_note,
      SAFE_CAST(JSON_EXTRACT_SCALAR(raw, '$.position') AS INT64) AS line_no,
      SAFE_CAST(JSON_EXTRACT_SCALAR(JSON_EXTRACT_SCALAR(raw, '$.order'), '$.id') AS STRING) AS order_id,
      SAFE_CAST(CASE
        WHEN SUBSTR(CAST(JSON_EXTRACT_SCALAR(raw, '$.created_at') AS STRING), 11) LIKE '%+%'
        OR SUBSTR(CAST(JSON_EXTRACT_SCALAR(raw, '$.created_at') AS STRING), 11) LIKE '%-%'
        THEN NULL
        ELSE RTRIM(
          REPLACE(
            REPLACE(CAST(JSON_EXTRACT_SCALAR(raw, '$.created_at') AS STRING), 'T', ' '),
            't',
            ' '
          ),
          'Zz'
        )
      END AS DATETIME) AS placed_at,
      SAFE_CAST(JSON_EXTRACT_SCALAR(raw, '$.quantity') AS INT64) AS quantity,
      SAFE_CAST(JSON_EXTRACT_SCALAR(JSON_EXTRACT_SCALAR(raw, '$.variant'), '$.sku') AS STRING) AS sku,
      CASE SAFE_CAST(JSON_EXTRACT_SCALAR(raw, '$.financial_status') AS STRING)
        WHEN 'pending'
        THEN 'open'
        WHEN 'paid'
        THEN 'closed'
        WHEN 'refunded'
        THEN 'reversed'
        ELSE SAFE_CAST(JSON_EXTRACT_SCALAR(raw, '$.financial_status') AS STRING)
      END AS status,
      _ingested_at,
      _load_id,
      _source_row_id,
      SAFE_CAST(JSON_EXTRACT_SCALAR(JSON_EXTRACT_SCALAR(raw, '$.properties'), '$.gift_note') AS STRING) IS NULL
      AND (
        NOT JSON_EXTRACT_SCALAR(JSON_EXTRACT_SCALAR(raw, '$.properties'), '$.gift_note') IS NULL
      ) AS _branch_gift_note_coercible,
      SAFE_CAST(JSON_EXTRACT_SCALAR(raw, '$.position') AS INT64) IS NULL
      AND (
        NOT JSON_EXTRACT_SCALAR(raw, '$.position') IS NULL
      ) AS _branch_line_no_coercible,
      SAFE_CAST(JSON_EXTRACT_SCALAR(JSON_EXTRACT_SCALAR(raw, '$.order'), '$.id') AS STRING) IS NULL
      AND (
        NOT JSON_EXTRACT_SCALAR(JSON_EXTRACT_SCALAR(raw, '$.order'), '$.id') IS NULL
      ) AS _branch_order_id_coercible,
      SAFE_CAST(CASE
        WHEN SUBSTR(CAST(JSON_EXTRACT_SCALAR(raw, '$.created_at') AS STRING), 11) LIKE '%+%'
        OR SUBSTR(CAST(JSON_EXTRACT_SCALAR(raw, '$.created_at') AS STRING), 11) LIKE '%-%'
        THEN NULL
        ELSE RTRIM(
          REPLACE(
            REPLACE(CAST(JSON_EXTRACT_SCALAR(raw, '$.created_at') AS STRING), 'T', ' '),
            't',
            ' '
          ),
          'Zz'
        )
      END AS DATETIME) IS NULL
      AND (
        NOT JSON_EXTRACT_SCALAR(raw, '$.created_at') IS NULL
      ) AS _branch_placed_at_coercible,
      SAFE_CAST(JSON_EXTRACT_SCALAR(raw, '$.quantity') AS INT64) IS NULL
      AND (
        NOT JSON_EXTRACT_SCALAR(raw, '$.quantity') IS NULL
      ) AS _branch_quantity_coercible,
      SAFE_CAST(JSON_EXTRACT_SCALAR(JSON_EXTRACT_SCALAR(raw, '$.variant'), '$.sku') AS STRING) IS NULL
      AND (
        NOT JSON_EXTRACT_SCALAR(JSON_EXTRACT_SCALAR(raw, '$.variant'), '$.sku') IS NULL
      ) AS _branch_sku_coercible,
      CASE SAFE_CAST(JSON_EXTRACT_SCALAR(raw, '$.financial_status') AS STRING)
        WHEN 'pending'
        THEN 'open'
        WHEN 'paid'
        THEN 'closed'
        WHEN 'refunded'
        THEN 'reversed'
        ELSE SAFE_CAST(JSON_EXTRACT_SCALAR(raw, '$.financial_status') AS STRING)
      END IS NULL
      AND (
        NOT JSON_EXTRACT_SCALAR(raw, '$.financial_status') IS NULL
      ) AS _branch_status_coercible,
      NOT CASE SAFE_CAST(JSON_EXTRACT_SCALAR(raw, '$.financial_status') AS STRING)
        WHEN 'pending'
        THEN 'open'
        WHEN 'paid'
        THEN 'closed'
        WHEN 'refunded'
        THEN 'reversed'
        ELSE SAFE_CAST(JSON_EXTRACT_SCALAR(raw, '$.financial_status') AS STRING)
      END IN ('closed', 'open', 'reversed') AS _branch_status_in_enum,
      'shopify__order_lines' AS _source
    FROM silver.order_line__reject
    WHERE
      resolved_at IS NULL AND source_relation = 'shopify__order_lines'
    UNION ALL
    SELECT
      CAST(NULL AS STRING) AS gift_note,
      SAFE_CAST(JSON_EXTRACT_SCALAR(raw, '$.item_index') AS INT64) AS line_no,
      SAFE_CAST(JSON_EXTRACT_SCALAR(raw, '$.order_number') AS STRING) AS order_id,
      SAFE_CAST(CASE
        WHEN SUBSTR(CAST(JSON_EXTRACT_SCALAR(raw, '$.created') AS STRING), 11) LIKE '%+%'
        OR SUBSTR(CAST(JSON_EXTRACT_SCALAR(raw, '$.created') AS STRING), 11) LIKE '%-%'
        THEN NULL
        ELSE RTRIM(
          REPLACE(REPLACE(CAST(JSON_EXTRACT_SCALAR(raw, '$.created') AS STRING), 'T', ' '), 't', ' '),
          'Zz'
        )
      END AS DATETIME) AS placed_at,
      SAFE_CAST(JSON_EXTRACT_SCALAR(raw, '$.qty') AS INT64) AS quantity,
      SAFE_CAST(JSON_EXTRACT_SCALAR(raw, '$.product_sku') AS STRING) AS sku,
      CASE SAFE_CAST(JSON_EXTRACT_SCALAR(raw, '$.state') AS STRING)
        WHEN 'PROCESSING'
        THEN 'open'
        WHEN 'COMPLETE'
        THEN 'closed'
        ELSE SAFE_CAST(JSON_EXTRACT_SCALAR(raw, '$.state') AS STRING)
      END AS status,
      _ingested_at,
      _load_id,
      _source_row_id,
      FALSE AS _branch_gift_note_coercible,
      SAFE_CAST(JSON_EXTRACT_SCALAR(raw, '$.item_index') AS INT64) IS NULL
      AND (
        NOT JSON_EXTRACT_SCALAR(raw, '$.item_index') IS NULL
      ) AS _branch_line_no_coercible,
      SAFE_CAST(JSON_EXTRACT_SCALAR(raw, '$.order_number') AS STRING) IS NULL
      AND (
        NOT JSON_EXTRACT_SCALAR(raw, '$.order_number') IS NULL
      ) AS _branch_order_id_coercible,
      SAFE_CAST(CASE
        WHEN SUBSTR(CAST(JSON_EXTRACT_SCALAR(raw, '$.created') AS STRING), 11) LIKE '%+%'
        OR SUBSTR(CAST(JSON_EXTRACT_SCALAR(raw, '$.created') AS STRING), 11) LIKE '%-%'
        THEN NULL
        ELSE RTRIM(
          REPLACE(REPLACE(CAST(JSON_EXTRACT_SCALAR(raw, '$.created') AS STRING), 'T', ' '), 't', ' '),
          'Zz'
        )
      END AS DATETIME) IS NULL
      AND (
        NOT JSON_EXTRACT_SCALAR(raw, '$.created') IS NULL
      ) AS _branch_placed_at_coercible,
      SAFE_CAST(JSON_EXTRACT_SCALAR(raw, '$.qty') AS INT64) IS NULL
      AND (
        NOT JSON_EXTRACT_SCALAR(raw, '$.qty') IS NULL
      ) AS _branch_quantity_coercible,
      SAFE_CAST(JSON_EXTRACT_SCALAR(raw, '$.product_sku') AS STRING) IS NULL
      AND (
        NOT JSON_EXTRACT_SCALAR(raw, '$.product_sku') IS NULL
      ) AS _branch_sku_coercible,
      CASE SAFE_CAST(JSON_EXTRACT_SCALAR(raw, '$.state') AS STRING)
        WHEN 'PROCESSING'
        THEN 'open'
        WHEN 'COMPLETE'
        THEN 'closed'
        ELSE SAFE_CAST(JSON_EXTRACT_SCALAR(raw, '$.state') AS STRING)
      END IS NULL
      AND (
        NOT JSON_EXTRACT_SCALAR(raw, '$.state') IS NULL
      ) AS _branch_status_coercible,
      NOT CASE SAFE_CAST(JSON_EXTRACT_SCALAR(raw, '$.state') AS STRING)
        WHEN 'PROCESSING'
        THEN 'open'
        WHEN 'COMPLETE'
        THEN 'closed'
        ELSE SAFE_CAST(JSON_EXTRACT_SCALAR(raw, '$.state') AS STRING)
      END IN ('closed', 'open') AS _branch_status_in_enum,
      'woo__order_lines' AS _source
    FROM silver.order_line__reject
    WHERE
      resolved_at IS NULL AND source_relation = 'woo__order_lines'
  ) AS _extract
) AS _replay
ON _target.source_relation = _replay._source
AND _target._source_row_id = _replay._source_row_id
WHEN MATCHED AND _target.resolved_at IS NULL THEN UPDATE SET
  failed_rules = _replay.failed_rules,
  last_evaluated_at = CURRENT_DATETIME('UTC');
