-- Generated by bloomery — do not edit.
-- fingerprint: blm1:8df03dd7c046468e09a96f18bce5f1ec72a035963976ffdd61c46cee4f69bc95
MODEL (
  name gold.dim_date,
  kind FULL,
  grain (date_day)
);

SELECT
  CAST(date_day AS DATE) AS date_day,
  CAST(DATE_TRUNC('MONTH', date_day) AS DATE) AS date_month,
  CAST(DATE_TRUNC('QUARTER', date_day) AS DATE) AS date_quarter,
  CAST(DATE_TRUNC('WEEK', date_day) AS DATE) AS date_week,
  CAST(DATE_TRUNC('YEAR', date_day) AS DATE) AS date_year
FROM (
  SELECT
    DATEADD(DAY, ROW_NUMBER() OVER (ORDER BY SEQ4()) - 1, CAST('2020-01-01' AS DATE)) AS date_day
  FROM TABLE(GENERATOR(ROWCOUNT => 4018))
) AS date_day
