-- Generated by bloomery — do not edit.
-- fingerprint: blm1:4aa879a0d07f7796fc657c3a13953f682a63ca425f542567961a29fe86887f96
MODEL (
  name silver.address,
  kind FULL,
  grain (address_id),
  audits (address_key_unique)
);

SELECT
  CAST(id AS TEXT) AS address_id,
  CAST(city AS TEXT) AS city,
  CAST(state AS TEXT) AS state,
  CAST([] AS TEXT[]) AS _quality_flags,
  TRUE AS _quality_ok
FROM bronze.src__addresses
