-- Generated by bloomery — do not edit.
-- fingerprint: blm1:24f1416de6768bcc5570d9b26bde59c137272e4c44af84b7dc3034e683f49c21
MODEL (
  name silver.address,
  kind FULL,
  grain (address_id)
);

SELECT
  CAST(id AS TEXT) AS address_id,
  CAST(city AS TEXT) AS city,
  CAST(state AS TEXT) AS state,
  CAST([] AS TEXT[]) AS _quality_flags,
  TRUE AS _quality_ok
FROM bronze.src__addresses
