-- Generated by bloomery — do not edit.
-- fingerprint: blm1:4eef78a6fc50bed1084282bbc309bde8f6af4488d3136789a92e0c8a0c6f8d8b
MODEL (
  name silver.address,
  kind FULL,
  grain (address_id)
);

SELECT
  CAST(id AS TEXT) AS address_id,
  CAST(city AS TEXT) AS city,
  CAST(state AS TEXT) AS state,
  CAST([] AS TEXT[]) AS _quality_flags,
  TRUE AS _quality_ok
FROM bronze.src__addresses
