-- Generated by bloomery — do not edit.
-- fingerprint: blm1:24f1416de6768bcc5570d9b26bde59c137272e4c44af84b7dc3034e683f49c21
MODEL (
  name silver.order,
  kind FULL,
  grain (order_id)
);

SELECT
  CAST(amount AS DECIMAL(12, 4)) AS amount,
  CAST(bill AS TEXT) AS bill_to_id,
  CAST(od AS DATE) AS order_date,
  CAST(id AS TEXT) AS order_id,
  CAST(ship AS TEXT) AS ship_to_id,
  CAST([] AS TEXT[]) AS _quality_flags,
  TRUE AS _quality_ok
FROM bronze.src__orders
