-- Generated by bloomery — do not edit.
-- fingerprint: blm1:24a11d56cd5a9e60f2a98acc52ed8dd1a9b739c153ed49572106b2288e244395
MODEL (
  name gold.mart_customers,
  kind FULL,
  grain (canonical_id)
);

SELECT
  customer.canonical_id AS canonical_id,
  customer.confidence AS confidence,
  customer.resolved_at AS resolved_at,
  CAST(DATE_TRUNC('DAY', customer.resolved_at) AS DATE) AS resolved_day,
  CAST(DATE_TRUNC('MONTH', customer.resolved_at) AS DATE) AS resolved_month,
  CAST(DATE_TRUNC('QUARTER', customer.resolved_at) AS DATE) AS resolved_quarter,
  CAST(DATE_TRUNC('WEEK', customer.resolved_at) AS DATE) AS resolved_week,
  CAST(DATE_TRUNC('YEAR', customer.resolved_at) AS DATE) AS resolved_year
FROM silver.customer AS customer
