-- Generated by bloomery — do not edit.
-- fingerprint: blm1:6929420a8a4ea1fed35d9d931178129415704626d72876ae85cb5d2e06f8520e
MODEL (
  name gold.mart_customers,
  kind FULL,
  grain (canonical_id)
);

SELECT
  customer.canonical_id AS canonical_id,
  customer.confidence AS confidence,
  customer.resolved_at AS resolved_at,
  CAST(DATE_TRUNC('DAY', customer.resolved_at) AS DATE) AS resolved_day,
  CAST(DATE_TRUNC('MONTH', customer.resolved_at) AS DATE) AS resolved_month,
  CAST(DATE_TRUNC('QUARTER', customer.resolved_at) AS DATE) AS resolved_quarter,
  CAST(DATE_TRUNC('WEEK', customer.resolved_at) AS DATE) AS resolved_week,
  CAST(DATE_TRUNC('YEAR', customer.resolved_at) AS DATE) AS resolved_year
FROM silver.customer AS customer
