-- Generated by bloomery — do not edit.
-- fingerprint: blm1:f123d3719f329791c37b128839f1802f9da33eccecaeb9535e5c7938a40c007d
MODEL (
  name silver.order_line__reject,
  kind INCREMENTAL_BY_UNIQUE_KEY (unique_key (reject_id), when_matched (WHEN MATCHED THEN UPDATE SET target.source_relation = source.source_relation, target.mapping = source.mapping, target.mapping_version = source.mapping_version, target.failed_rules = source.failed_rules, target.key_values = source.key_values, target.raw = source.raw, target._load_id = source._load_id, target._ingested_at = source._ingested_at, target._source_row_id = source._source_row_id, target.first_seen = COALESCE(target.first_seen, source.first_seen), target.last_seen = source.last_seen, target.resolved_at = source.resolved_at, target.last_evaluated_at = COALESCE(target.last_evaluated_at, source.last_evaluated_at))),
  grain (reject_id)
);

SELECT
  _extract.reject_id,
  _extract.source_relation,
  _extract.mapping,
  _extract.mapping_version,
  ARRAY_CONCAT(
    ARRAY_CONCAT(
      ARRAY_CONCAT(
        ARRAY_CONCAT(
          ARRAY_CONCAT(
            ARRAY_CONCAT(
              ARRAY_CONCAT(
                CASE
                  WHEN _extract._branch_gift_note_coercible
                  THEN ['gift_note_coercible']
                  ELSE ARRAY<STRING>[]
                END,
                CASE
                  WHEN _extract._branch_line_no_coercible
                  THEN ['line_no_coercible']
                  ELSE ARRAY<STRING>[]
                END
              ),
              CASE
                WHEN _extract._branch_order_id_coercible
                THEN ['order_id_coercible']
                ELSE ARRAY<STRING>[]
              END
            ),
            CASE
              WHEN _extract._branch_placed_at_coercible
              THEN ['placed_at_coercible']
              ELSE ARRAY<STRING>[]
            END
          ),
          CASE
            WHEN _extract._branch_quantity_coercible
            THEN ['quantity_coercible']
            ELSE ARRAY<STRING>[]
          END
        ),
        CASE
          WHEN _extract._branch_sku_coercible
          THEN ['sku_coercible']
          ELSE ARRAY<STRING>[]
        END
      ),
      CASE
        WHEN _extract._branch_status_coercible
        THEN ['status_coercible']
        ELSE ARRAY<STRING>[]
      END
    ),
    CASE
      WHEN _extract._branch_status_in_enum
      THEN ['status_in_enum']
      ELSE ARRAY<STRING>[]
    END
  ) AS failed_rules,
  JSON_OBJECT('line_no', _extract.line_no, 'order_id', _extract.order_id) AS key_values,
  _extract._raw AS raw,
  _extract._load_id,
  _extract._ingested_at,
  _extract._source_row_id,
  _extract._ingested_at AS first_seen,
  _extract._ingested_at AS last_seen,
  CAST(NULL AS DATETIME) AS resolved_at,
  CAST(NULL AS DATETIME) AS last_evaluated_at
FROM (
  SELECT
    *
  FROM (
    SELECT
      SAFE_CAST(JSON_EXTRACT_SCALAR(properties, '$.gift_note') AS STRING) AS gift_note,
      SAFE_CAST(position AS INT64) AS line_no,
      SAFE_CAST(JSON_EXTRACT_SCALAR(`order`, '$.id') AS STRING) AS order_id,
      SAFE_CAST(CASE
        WHEN SUBSTR(CAST(created_at AS STRING), 11) LIKE '%+%'
        OR SUBSTR(CAST(created_at AS STRING), 11) LIKE '%-%'
        THEN NULL
        ELSE RTRIM(REPLACE(REPLACE(CAST(created_at AS STRING), 'T', ' '), 't', ' '), 'Zz')
      END AS DATETIME) AS placed_at,
      SAFE_CAST(quantity AS INT64) AS quantity,
      SAFE_CAST(JSON_EXTRACT_SCALAR(variant, '$.sku') AS STRING) AS sku,
      CASE SAFE_CAST(financial_status AS STRING)
        WHEN 'pending'
        THEN 'open'
        WHEN 'paid'
        THEN 'closed'
        WHEN 'refunded'
        THEN 'reversed'
        ELSE SAFE_CAST(financial_status AS STRING)
      END AS status,
      _ingested_at,
      _load_id,
      _source_row_id,
      SAFE_CAST(JSON_EXTRACT_SCALAR(properties, '$.gift_note') AS STRING) IS NULL
      AND (
        NOT JSON_EXTRACT_SCALAR(properties, '$.gift_note') IS NULL
      ) AS _branch_gift_note_coercible,
      SAFE_CAST(position AS INT64) IS NULL AND (
        NOT position IS NULL
      ) AS _branch_line_no_coercible,
      SAFE_CAST(JSON_EXTRACT_SCALAR(`order`, '$.id') AS STRING) IS NULL
      AND (
        NOT JSON_EXTRACT_SCALAR(`order`, '$.id') IS NULL
      ) AS _branch_order_id_coercible,
      SAFE_CAST(CASE
        WHEN SUBSTR(CAST(created_at AS STRING), 11) LIKE '%+%'
        OR SUBSTR(CAST(created_at AS STRING), 11) LIKE '%-%'
        THEN NULL
        ELSE RTRIM(REPLACE(REPLACE(CAST(created_at AS STRING), 'T', ' '), 't', ' '), 'Zz')
      END AS DATETIME) IS NULL
      AND (
        NOT created_at IS NULL
      ) AS _branch_placed_at_coercible,
      SAFE_CAST(quantity AS INT64) IS NULL AND (
        NOT quantity IS NULL
      ) AS _branch_quantity_coercible,
      SAFE_CAST(JSON_EXTRACT_SCALAR(variant, '$.sku') AS STRING) IS NULL
      AND (
        NOT JSON_EXTRACT_SCALAR(variant, '$.sku') IS NULL
      ) AS _branch_sku_coercible,
      CASE SAFE_CAST(financial_status AS STRING)
        WHEN 'pending'
        THEN 'open'
        WHEN 'paid'
        THEN 'closed'
        WHEN 'refunded'
        THEN 'reversed'
        ELSE SAFE_CAST(financial_status AS STRING)
      END IS NULL
      AND (
        NOT financial_status IS NULL
      ) AS _branch_status_coercible,
      NOT CASE SAFE_CAST(financial_status AS STRING)
        WHEN 'pending'
        THEN 'open'
        WHEN 'paid'
        THEN 'closed'
        WHEN 'refunded'
        THEN 'reversed'
        ELSE SAFE_CAST(financial_status AS STRING)
      END IN ('closed', 'open', 'reversed') AS _branch_status_in_enum,
      JSON_OBJECT(
        '_ingested_at',
        _ingested_at,
        '_load_id',
        _load_id,
        '_source_row_id',
        _source_row_id,
        'created_at',
        created_at,
        'financial_status',
        financial_status,
        'order',
        `order`,
        'position',
        position,
        'properties',
        properties,
        'quantity',
        quantity,
        'variant',
        variant
      ) AS _raw,
      'shopify__order_lines' AS _source,
      TO_HEX(
        SHA256(
          CONCAT(
            'S20:shopify__order_lines',
            'S',
            CAST(LENGTH(_source_row_id) AS STRING),
            ':',
            _source_row_id
          )
        )
      ) AS reject_id,
      'shopify__order_lines' AS source_relation,
      'shopify__order_lines->order_line' AS mapping,
      1 AS mapping_version
    FROM bronze.shopify__order_lines
    UNION ALL
    SELECT
      CAST(NULL AS STRING) AS gift_note,
      SAFE_CAST(item_index AS INT64) AS line_no,
      SAFE_CAST(order_number AS STRING) AS order_id,
      SAFE_CAST(CASE
        WHEN SUBSTR(CAST(created AS STRING), 11) LIKE '%+%'
        OR SUBSTR(CAST(created AS STRING), 11) LIKE '%-%'
        THEN NULL
        ELSE RTRIM(REPLACE(REPLACE(CAST(created AS STRING), 'T', ' '), 't', ' '), 'Zz')
      END AS DATETIME) AS placed_at,
      SAFE_CAST(qty AS INT64) AS quantity,
      SAFE_CAST(product_sku AS STRING) AS sku,
      CASE SAFE_CAST(state AS STRING)
        WHEN 'PROCESSING'
        THEN 'open'
        WHEN 'COMPLETE'
        THEN 'closed'
        ELSE SAFE_CAST(state AS STRING)
      END AS status,
      _ingested_at,
      _load_id,
      _source_row_id,
      FALSE AS _branch_gift_note_coercible,
      SAFE_CAST(item_index AS INT64) IS NULL AND (
        NOT item_index IS NULL
      ) AS _branch_line_no_coercible,
      SAFE_CAST(order_number AS STRING) IS NULL AND (
        NOT order_number IS NULL
      ) AS _branch_order_id_coercible,
      SAFE_CAST(CASE
        WHEN SUBSTR(CAST(created AS STRING), 11) LIKE '%+%'
        OR SUBSTR(CAST(created AS STRING), 11) LIKE '%-%'
        THEN NULL
        ELSE RTRIM(REPLACE(REPLACE(CAST(created AS STRING), 'T', ' '), 't', ' '), 'Zz')
      END AS DATETIME) IS NULL
      AND (
        NOT created IS NULL
      ) AS _branch_placed_at_coercible,
      SAFE_CAST(qty AS INT64) IS NULL AND (
        NOT qty IS NULL
      ) AS _branch_quantity_coercible,
      SAFE_CAST(product_sku AS STRING) IS NULL AND (
        NOT product_sku IS NULL
      ) AS _branch_sku_coercible,
      CASE SAFE_CAST(state AS STRING)
        WHEN 'PROCESSING'
        THEN 'open'
        WHEN 'COMPLETE'
        THEN 'closed'
        ELSE SAFE_CAST(state AS STRING)
      END IS NULL
      AND (
        NOT state IS NULL
      ) AS _branch_status_coercible,
      NOT CASE SAFE_CAST(state AS STRING)
        WHEN 'PROCESSING'
        THEN 'open'
        WHEN 'COMPLETE'
        THEN 'closed'
        ELSE SAFE_CAST(state AS STRING)
      END IN ('closed', 'open') AS _branch_status_in_enum,
      JSON_OBJECT(
        '_ingested_at',
        _ingested_at,
        '_load_id',
        _load_id,
        '_source_row_id',
        _source_row_id,
        'created',
        created,
        'item_index',
        item_index,
        'order_number',
        order_number,
        'product_sku',
        product_sku,
        'qty',
        qty,
        'state',
        state
      ) AS _raw,
      'woo__order_lines' AS _source,
      TO_HEX(
        SHA256(
          CONCAT('S16:woo__order_lines', 'S', CAST(LENGTH(_source_row_id) AS STRING), ':', _source_row_id)
        )
      ) AS reject_id,
      'woo__order_lines' AS source_relation,
      'woo__order_lines->order_line' AS mapping,
      1 AS mapping_version
    FROM bronze.woo__order_lines
  ) AS _extract
  QUALIFY
    ROW_NUMBER() OVER (
      PARTITION BY order_id, line_no
      ORDER BY placed_at DESC, line_no DESC, _source DESC, _source_row_id DESC
    ) = 1
) AS _extract
WHERE
  COALESCE(
    (
      _extract._branch_gift_note_coercible
      OR _extract._branch_order_id_coercible
      OR _extract._branch_quantity_coercible
      OR _extract._branch_sku_coercible
      OR _extract._branch_status_coercible
      OR _extract._branch_status_in_enum
    ),
    FALSE
  )
