"""The Cube emitter (RFC 0008 §5.4) — the semantic target.

One ``model/cubes/<mart>.yml`` per mart (``sql_table`` from
``NamingPolicy.relation(mart, Layer.GOLD)`` — the same pair the SQLMesh mart
build uses, so the cube and the built table cannot disagree) plus one
``model/views/<mart>_view.yml`` exposing the mart's members (RFC 0008 §10:
one view per mart, the simplest defensible grouping — the goldens lock it).
The YAML is **dialect-independent**: measure SQL is the metric's canonical
neutral expression and ``ctx.dialect`` is never consulted — Cube renders SQL
against its own configured database.

Deterministic choices pinned here (each golden/unit-tested):

- Dimensions come from ``MartIR.dimensions``. A date-role bucket column
  (``ref.role`` set) is a ``time`` dimension with ``meta.granularity`` naming
  its bucket; every other column maps by logical type (string / number /
  boolean / time) — an int dimension is never declared a string.
- A metric served by several marts lands as a measure on exactly one:
  :func:`bloomery.emit.metricflow.measure_owners` — the same cheapest-mart
  rule the MetricFlow emitter and the planner's coverage precheck apply, so
  the three surfaces cannot disagree.
- Measures carry ``meta.additivity`` / ``meta.grain`` from ``MetricIR``;
  a semi-additive measure additionally carries ``meta.semi_additive``
  (``over``/``rule``). The measure still emits with its declared aggregation:
  RFC 0008 §5.1 gates *trusting* Cube's semi-additive behavior on the
  equivalence suite (RFC 0009 §5.8), not on emission — the meta is what that
  suite (and any consumer) audits against.
- A ``count`` metric emits ``type: count`` with no ``sql``: Cube's ``count``
  counts rows, which at the mart's grain equals counting the non-null key
  expression the metric declares.
- A non-additive ratio is **never a stored aggregate**: it emits as a
  calculated ``number`` measure over its additive components
  (``{num} / NULLIF({den}, 0)`` via Cube's ``{member}`` templating), and only
  on the mart owning both components. A non-additive metric reaching
  ``MartIR.measures`` (a would-be stored non-additive) is refused with
  :class:`~bloomery.errors.UnsupportedByTarget` — the guardrail stage already
  prevents it (RFC 0006 D5); the emitter re-checks, defense in depth.
- Cube has no SCD/incremental concepts — those capabilities are absent and
  *irrelevant rather than errors*: Cube consumes tables SQLMesh maintains
  (RFC 0008 §5.4).
"""

from __future__ import annotations

import yaml

from bloomery.emit.base import (
    ArtifactKind,
    EmitContext,
    EmittedArtifact,
    Feature,
    TargetCapabilities,
)
from bloomery.emit.metricflow import measure_owners
from bloomery.errors import UnsupportedByTarget
from bloomery.ir import (
    Additivity,
    Layer,
    MartIR,
    MetricIR,
    ProjectIR,
)
from bloomery.typing import (
    BoolType,
    DateType,
    DecimalType,
    IntType,
    LogicalType,
    StringType,
    TimestampType,
    VariantType,
)

__all__ = [
    "CubeEmitter",
]

#: Logical type → Cube dimension type. ``variant`` degrades to ``string`` —
#: Cube has no semi-structured dimension type, and string is the widest
#: faithful projection of a JSON value.
_DIMENSION_TYPES: dict[type[LogicalType], str] = {
    StringType: "string",
    IntType: "number",
    DecimalType: "number",
    BoolType: "boolean",
    DateType: "time",
    TimestampType: "time",
    VariantType: "string",
}

#: Metric ``agg`` → Cube measure type (the closed honest set; anything else
#: is ``UnsupportedByTarget``, never approximated).
_MEASURE_TYPES: dict[str, str] = {
    "avg": "avg",
    "count": "count",
    "count_distinct": "count_distinct",
    "max": "max",
    "min": "min",
    "sum": "sum",
}


def _header(ctx: EmitContext) -> str:
    return f"# Generated by bloomery — do not edit.\n# fingerprint: {ctx.fingerprint}\n"


def _yaml(document: dict[str, object]) -> str:
    """Byte-stable YAML: keys keep the deterministic insertion order built
    here (member order is semantic surface; ``sort_keys`` would shuffle
    ``name`` below ``sql_table``), block style, pinned width."""
    return yaml.safe_dump(
        document, sort_keys=False, default_flow_style=False, width=100, allow_unicode=True
    )


def _metric_meta(metric: MetricIR) -> dict[str, object]:
    meta: dict[str, object] = {"additivity": metric.additivity.value}
    if metric.grain:
        # A derived metric (a ratio) has no grain of its own — its components
        # carry theirs; an empty grain entry would be noise, not metadata.
        meta["grain"] = metric.grain
    if metric.semi_additive is not None:
        meta["semi_additive"] = {
            "over": metric.semi_additive.over.qualified,
            "rule": metric.semi_additive.rule.value,
        }
    return meta


def _dimensions(mart: MartIR) -> list[object]:
    types_by_column = {column.name: column.type for column in mart.columns}
    dimensions: list[object] = []
    for dimension in mart.dimensions:  # sorted by column name on MartIR
        entry: dict[str, object] = {"name": dimension.column, "sql": dimension.column}
        if dimension.ref.role is not None:
            # A date-role bucket column (RFC 0010 D4): a time dimension whose
            # bucket is recorded as meta.granularity.
            entry["type"] = "time"
            entry["meta"] = {"granularity": dimension.ref.dimension}
        else:
            entry["type"] = _DIMENSION_TYPES[type(types_by_column[dimension.column])]
        dimensions.append(entry)
    return dimensions


def _stored_measure(metric: MetricIR, mart: MartIR) -> dict[str, object]:
    if metric.additivity is Additivity.NON_ADDITIVE:
        msg = (
            f"mart {mart.name!r} stores non-additive metric {metric.name!r} as a measure — "
            "a non-additive metric is never a stored aggregate (RFC 0006 D5, RFC 0008 §5.4); "
            "the guardrail stage should have refused this upstream"
        )
        raise UnsupportedByTarget(msg)
    measure_type = _MEASURE_TYPES.get(metric.agg) if metric.agg is not None else None
    if measure_type is None:
        msg = (
            f"metric {metric.name!r} uses aggregation {metric.agg!r}, which has no Cube "
            f"measure type mapping; supported: {sorted(_MEASURE_TYPES)}"
        )
        raise UnsupportedByTarget(msg)
    if metric.expr is None:
        msg = (
            f"metric {metric.name!r} has no expression to emit as a Cube measure — only "
            "agg-over-expr metrics lower to stored measures (RFC 0008 §5.4)"
        )
        raise UnsupportedByTarget(msg)
    entry: dict[str, object] = {"name": metric.name, "type": measure_type}
    if measure_type != "count":
        # Cube's ``count`` counts rows and takes no sql (see module docstring).
        entry["sql"] = metric.expr.sql
    entry["meta"] = _metric_meta(metric)
    return entry


def _measures(mart: MartIR, ir: ProjectIR, owners: dict[str, MartIR]) -> list[object]:
    metrics_by_name = {metric.name: metric for metric in ir.metrics}
    owned = [name for name in mart.measures if owners[name] is mart]  # sorted on MartIR
    measures: list[object] = [_stored_measure(metrics_by_name[name], mart) for name in owned]
    owned_set = frozenset(owned)
    for metric in ir.metrics:  # sorted by name on ProjectIR
        ratio = metric.ratio
        if (
            metric.additivity is Additivity.NON_ADDITIVE
            and ratio is not None
            and ratio.numerator in owned_set
            and ratio.denominator in owned_set
        ):
            measures.append(
                {
                    "name": metric.name,
                    "type": "number",
                    "sql": f"{{{ratio.numerator}}} / NULLIF({{{ratio.denominator}}}, 0)",
                    "meta": _metric_meta(metric),
                }
            )
    return measures


def _cube_artifact(
    mart: MartIR, ir: ProjectIR, owners: dict[str, MartIR], ctx: EmitContext
) -> EmittedArtifact:
    namespace, relation = ctx.naming.relation(mart.name, Layer.GOLD)
    document: dict[str, object] = {
        "cubes": [
            {
                "name": mart.name,
                "sql_table": f"{namespace}.{relation}",
                "dimensions": _dimensions(mart),
                "measures": _measures(mart, ir, owners),
            }
        ]
    }
    return EmittedArtifact.create(
        path=f"model/cubes/{mart.name}.yml",
        content=_header(ctx) + _yaml(document),
        kind=ArtifactKind.MODEL,
    )


def _view_artifact(mart: MartIR, ctx: EmitContext) -> EmittedArtifact:
    document: dict[str, object] = {
        "views": [
            {
                "name": f"{mart.name}_view",
                "cubes": [{"join_path": mart.name, "includes": "*"}],
            }
        ]
    }
    return EmittedArtifact.create(
        path=f"model/views/{mart.name}_view.yml",
        content=_header(ctx) + _yaml(document),
        kind=ArtifactKind.MODEL,
    )


class CubeEmitter:
    """RFC 0008 §5.4: one cube per mart, one view per mart — YAML data model
    files, dialect-independent by construction."""

    name = "cube"

    def capabilities(self) -> TargetCapabilities:
        """Declared support per RFC 0008 §5.1 (amended D6): query-time joins,
        multi-fact, row-level security, role-playing dimensions. Semi-additive
        emission carries honest ``meta``; *trusting* it is gated on the
        equivalence suite (RFC 0009 §5.8). SCD2/incremental are irrelevant,
        not errors — Cube consumes tables SQLMesh maintains."""
        return TargetCapabilities(
            supported=frozenset(
                {
                    Feature.QUERY_TIME_JOIN,
                    Feature.MULTI_FACT,
                    Feature.ROW_LEVEL_SECURITY,
                    Feature.ROLE_PLAYING_DIM,
                }
            )
        )

    def emit(self, ir: ProjectIR, ctx: EmitContext) -> tuple[EmittedArtifact, ...]:
        """Lower every mart to a cube and a view; artifacts sorted by path,
        content ending in exactly one newline (RFC 0003 §5.5 rule 5). A
        project without marts emits nothing — Cube has no silver surface."""
        if ir.steps:
            # RFC 0017 §5.8 emits steps for SQLMesh only. Dropping them here
            # would silently withhold relations downstream models were
            # typechecked against — fail loud, never approximate (RFC 0008 D3).
            msg = (
                f"project wires {len(ir.steps)} step(s), which the Cube target "
                "cannot emit (RFC 0017 §5.8 covers SQLMesh only). Their output "
                "relations would simply be missing. Fix: compile steps for SQLMesh, "
                "or drop the steps: document for this target"
            )
            raise UnsupportedByTarget(msg)

        owners = measure_owners(ir)
        artifacts: list[EmittedArtifact] = []
        for mart in ir.marts:  # sorted by name on ProjectIR
            artifacts.append(_cube_artifact(mart, ir, owners, ctx))
            artifacts.append(_view_artifact(mart, ctx))
        return tuple(sorted(artifacts, key=lambda a: a.path))
