-- Generated by bloomery — do not edit.
-- fingerprint: blm1:d6329e15e09de38ca529f1e3baf78f5e81d2d52c862976b3b5d3bcf3ddf1cdb6
MODEL (
  name silver.event,
  kind FULL,
  grain (event_id)
);

SELECT
  CAST(id AS TEXT) AS event_id,
  CAST(kind AS TEXT) AS kind,
  CAST(ts AS TIMESTAMP) AS occurred_at
FROM bronze.raw__events
