-- Generated by bloomery — do not edit.
-- fingerprint: blm1:52e362870abafb3fa6df93c9d800d3ba7803f0ce69756fc19963fce7d8011991
MODEL (
  name silver.event,
  kind FULL,
  grain (event_id)
);

SELECT
  CAST(id AS TEXT) AS event_id,
  CAST(kind AS TEXT) AS kind,
  CAST(ts AS TIMESTAMP) AS occurred_at,
  CAST([] AS TEXT[]) AS _quality_flags,
  TRUE AS _quality_ok
FROM bronze.raw__events
