-- Generated by bloomery — do not edit.
-- fingerprint: blm1:1d170edb0e328f3ce287959584d46345dc507b0624c9d7f38196894f876956f5
MODEL (
  name silver.event,
  kind FULL,
  grants ("select" = ('analyst', 'reverse_etl')),
  grain (event_id)
);

SELECT
  CAST(id AS TEXT) AS event_id,
  CAST(kind AS TEXT) AS kind,
  CAST(ts AS TIMESTAMP) AS occurred_at,
  CAST([] AS TEXT[]) AS _quality_flags,
  TRUE AS _quality_ok
FROM bronze.raw__events
