-- Generated by bloomery — do not edit.
-- fingerprint: blm1:d7c0b402f991ace8163218a0401b823fe48f4865d46855a92ce4e829b5cd5a5b
{{ config(materialized='table') }}

SELECT
  CAST(customer_id AS TEXT) AS customer_id,
  CAST(id AS TEXT) AS order_id,
  CAST(ARRAY[] AS TEXT[]) AS _quality_flags,
  TRUE AS _quality_ok
FROM {{ source('bronze', 'shop__orders') }}
