-- Generated by bloomery — do not edit.
-- fingerprint: blm1:7e8d92ec1e27f7f4e1ea551b2ae205bdfdc17841d5310c440b11f683be2527f6
{{ config(materialized='table') }}

SELECT
  CAST(customer_id AS TEXT) AS customer_id,
  CAST(id AS TEXT) AS order_id,
  CAST(ARRAY[] AS TEXT[]) AS _quality_flags,
  TRUE AS _quality_ok
FROM {{ source('bronze', 'shop__orders') }}
