-- Generated by bloomery — do not edit.
-- fingerprint: blm1:56f22928b5698ffa438e6b9ddcf3d998f3608d772bdd2e58af5623ab8a12595b
{{ config(materialized='table') }}

SELECT
  CAST(index AS BIGINT) AS line_no,
  CAST(CASE
    WHEN SUBSTRING(CAST(created_at AS VARCHAR) FROM 11) LIKE '%+%'
    OR SUBSTRING(CAST(created_at AS VARCHAR) FROM 11) LIKE '%-%'
    THEN NULL
    ELSE created_at
  END AS TIMESTAMP) AS order_date,
  CAST(order_id AS TEXT) AS order_id,
  CAST(qty AS BIGINT) AS quantity,
  CAST(price AS DECIMAL(12, 4)) AS unit_price,
  CAST(ARRAY[] AS TEXT[]) AS _quality_flags,
  TRUE AS _quality_ok
FROM {{ source('bronze', 'shop__order_lines') }}
