-- Generated by bloomery — do not edit.
-- fingerprint: blm1:79befb79cc1136b73bc5326ca93d0acdf7cf86b48171307b407775cf0ffc0111
{{ config(materialized='table') }}

SELECT
  CAST(customer_id AS TEXT) AS customer_id,
  CAST(id AS TEXT) AS order_id,
  CAST(ARRAY[] AS TEXT[]) AS _quality_flags,
  TRUE AS _quality_ok
FROM {{ source('bronze', 'shop__orders') }}
