-- Generated by bloomery — do not edit.
-- fingerprint: blm1:0f1cacfbce48b9897b7c2a9480e7e0688c86e725d1311728307754adaf469942
MODEL (
  name silver.order,
  kind FULL,
  owner 'commerce-platform@example.com',
  grain (order_id)
);

SELECT
  CAST(customer ->> 'id' AS TEXT) AS customer_id,
  CAST(id AS TEXT) AS order_id,
  CAST(ARRAY[] AS TEXT[]) AS _quality_flags,
  TRUE AS _quality_ok
FROM bronze.shopify__orders
