-- Generated by bloomery — do not edit.
-- fingerprint: blm1:8df03dd7c046468e09a96f18bce5f1ec72a035963976ffdd61c46cee4f69bc95
MODEL (
  name silver.order,
  kind FULL,
  owner 'commerce-platform@example.com',
  grain (order_id),
  audits (order_key_unique)
);

SELECT
  CAST(customer ->> 'id' AS TEXT) AS customer_id,
  CAST(id AS TEXT) AS order_id,
  CAST(ARRAY[] AS TEXT[]) AS _quality_flags,
  TRUE AS _quality_ok
FROM bronze.shopify__orders
