-- Generated by bloomery — do not edit.
-- fingerprint: blm1:9ab6be02fbdc8c44dc85b4acb03bfde7131aed81671d88c9e0ead7071f90020b
MODEL (
  name silver.order_item,
  kind INCREMENTAL_BY_TIME_RANGE (time_column order_date),
  grain (order_id, line_no),
  partitioned_by (days(order_date)),
  audits (not_null(columns := (order_date)))
);

SELECT
  CAST(index AS BIGINT) AS line_no,
  CAST(created_at AS TIMESTAMP) AT TIME ZONE 'Europe/Paris' AS order_date,
  CAST(order_id AS TEXT) AS order_id,
  CAST(qty AS BIGINT) AS quantity,
  CAST(CAST(total AS DOUBLE PRECISION) / qty AS DECIMAL(12, 4)) AS unit_price,
  CAST(ARRAY[] AS TEXT[]) AS _quality_flags,
  TRUE AS _quality_ok
FROM bronze.shopify__order_lines
