-- Generated by bloomery — do not edit.
-- fingerprint: blm1:83e3c9f49ba9d6f66ab566fdbc3e190e42da8d537a930eddd345f69e70be9804
MODEL (
  name silver.order,
  kind FULL,
  owner 'commerce-platform@example.com',
  grain (order_id)
);

SELECT
  CAST(customer ->> 'id' AS TEXT) AS customer_id,
  CAST(id AS TEXT) AS order_id,
  CAST(ARRAY[] AS TEXT[]) AS _quality_flags,
  TRUE AS _quality_ok
FROM bronze.shopify__orders
