-- Generated by bloomery — do not edit.
-- fingerprint: blm1:3b361d31b25c3e37bca38f4234664a5b05ac95f45921932fb8896208be5b2de6
MODEL (
  name gold.dim_date,
  kind FULL,
  grain (date_day)
);

SELECT
  CAST(date_day AS DATE) AS date_day,
  CAST(DATE_TRUNC('MONTH', date_day) AS DATE) AS date_month,
  CAST(DATE_TRUNC('QUARTER', date_day) AS DATE) AS date_quarter,
  CAST(DATE_TRUNC('WEEK', date_day) AS DATE) AS date_week,
  CAST(DATE_TRUNC('YEAR', date_day) AS DATE) AS date_year
FROM (
  SELECT
    DATEADD(DAY, ROW_NUMBER() OVER (ORDER BY SEQ4()) - 1, CAST('2020-01-01' AS DATE)) AS date_day
  FROM TABLE(GENERATOR(ROWCOUNT => 4018))
) AS date_day
