-- Generated by bloomery — do not edit.
-- fingerprint: blm1:bae1d63a2f6c90390eba56ad1c3551d56c783422f79e57c5584f81d03b3b8c74
MODEL (
  name gold.mart_orders,
  kind FULL,
  grain (order_id)
);

SELECT
  "ORDER".amount AS amount,
  "ORDER".order_date AS order_date,
  "ORDER".order_id AS order_id,
  CAST(DATE_TRUNC('DAY', "ORDER".order_date) AS DATE) AS ordered_day,
  CAST(DATE_TRUNC('MONTH', "ORDER".order_date) AS DATE) AS ordered_month,
  CAST(DATE_TRUNC('QUARTER', "ORDER".order_date) AS DATE) AS ordered_quarter,
  CAST(DATE_TRUNC('WEEK', "ORDER".order_date) AS DATE) AS ordered_week,
  CAST(DATE_TRUNC('YEAR', "ORDER".order_date) AS DATE) AS ordered_year,
  "ORDER".ship_date AS ship_date,
  CAST(DATE_TRUNC('DAY', "ORDER".ship_date) AS DATE) AS shipped_day,
  CAST(DATE_TRUNC('MONTH', "ORDER".ship_date) AS DATE) AS shipped_month,
  CAST(DATE_TRUNC('QUARTER', "ORDER".ship_date) AS DATE) AS shipped_quarter,
  CAST(DATE_TRUNC('WEEK', "ORDER".ship_date) AS DATE) AS shipped_week,
  CAST(DATE_TRUNC('YEAR', "ORDER".ship_date) AS DATE) AS shipped_year
FROM silver."ORDER" AS "ORDER"
