-- Generated by bloomery — do not edit.
-- fingerprint: blm1:82485659bde4bd2ce11ef7d452090ea3269f503620972fcf89d227265785ef1f
MODEL (
  name gold.mart_inventory,
  kind FULL,
  grain (warehouse_id, stock_date)
);

SELECT
  NOT inventory_level._quality_ok AS has_quality_flags,
  CAST(DATE_TRUNC('DAY', inventory_level.stock_date) AS DATE) AS snapshot_day,
  CAST(DATE_TRUNC('MONTH', inventory_level.stock_date) AS DATE) AS snapshot_month,
  CAST(DATE_TRUNC('QUARTER', inventory_level.stock_date) AS DATE) AS snapshot_quarter,
  CAST(DATE_TRUNC('WEEK', inventory_level.stock_date) AS DATE) AS snapshot_week,
  CAST(DATE_TRUNC('YEAR', inventory_level.stock_date) AS DATE) AS snapshot_year,
  inventory_level.stock_date AS stock_date,
  inventory_level.stock_level AS stock_level,
  inventory_level.warehouse_id AS warehouse_id
FROM silver.inventory_level AS inventory_level
