-- Generated by bloomery — do not edit.
-- fingerprint: blm1:3eb366ae79362c0c34325f2c7848f68609759f8b01a9b8749aee5509a060f7c5
MODEL (
  name gold.mart_inventory,
  kind FULL,
  grain (warehouse_id, stock_date)
);

SELECT
  NOT inventory_level._quality_ok AS has_quality_flags,
  CAST(DATE_TRUNC('DAY', inventory_level.stock_date) AS DATE) AS snapshot_day,
  CAST(DATE_TRUNC('MONTH', inventory_level.stock_date) AS DATE) AS snapshot_month,
  CAST(DATE_TRUNC('QUARTER', inventory_level.stock_date) AS DATE) AS snapshot_quarter,
  CAST(DATE_TRUNC('WEEK', inventory_level.stock_date) AS DATE) AS snapshot_week,
  CAST(DATE_TRUNC('YEAR', inventory_level.stock_date) AS DATE) AS snapshot_year,
  inventory_level.stock_date AS stock_date,
  inventory_level.stock_level AS stock_level,
  inventory_level.warehouse_id AS warehouse_id
FROM silver.inventory_level AS inventory_level
