-- Generated by bloomery — do not edit.
-- fingerprint: blm1:05e5341378624d6a628db11416ecd67485bfb0aae9cc364281a0c6c306585196
MODEL (
  name gold.mart_data_quality,
  kind FULL,
  grain (entity, rule)
);

WITH _quality_rows_inventory_level AS (
  SELECT
    _quality_flags AS _flags,
    FALSE AS _quarantined
  FROM silver.inventory_level
  UNION ALL
  SELECT
    failed_rules AS _flags,
    TRUE AS _quarantined
  FROM silver.inventory_level__reject
  WHERE
    resolved_at IS NULL
)
SELECT
  _stamped.disposition,
  _stamped.entity,
  _stamped.mapping,
  _stamped.rows_deduped,
  _stamped.rows_evaluated,
  _stamped.rows_failed,
  _stamped.rows_quarantined,
  _stamped.rule,
  _stamped.run_date,
  CAST(DATE_TRUNC('DAY', _stamped.run_date) AS DATE) AS run_day,
  _stamped.run_id,
  CAST(DATE_TRUNC('MONTH', _stamped.run_date) AS DATE) AS run_month,
  CAST(DATE_TRUNC('QUARTER', _stamped.run_date) AS DATE) AS run_quarter,
  CAST(DATE_TRUNC('WEEK', _stamped.run_date) AS DATE) AS run_week,
  CAST(DATE_TRUNC('YEAR', _stamped.run_date) AS DATE) AS run_year
FROM (
  SELECT
    _evaluations.entity,
    _evaluations.mapping,
    _evaluations.rule,
    _evaluations.disposition,
    _evaluations.rows_evaluated,
    _evaluations.rows_failed,
    _evaluations.rows_quarantined,
    _evaluations.rows_deduped,
    CAST(NULL AS TEXT) AS run_id, /* run_id: supplied by the executing engine's run context (RFC 0016 §5.8); the pinned target exposes no macro for it — fill this column in your runner */
    CAST(@execution_ds AS DATE) AS run_date
  FROM (
    SELECT
      'inventory_level' AS entity,
      'wms__stock_levels->inventory_level' AS mapping,
      '(entity)' AS rule,
      '(entity)' AS disposition,
      COUNT(*) AS rows_evaluated,
      0 AS rows_failed,
      COALESCE(SUM(CASE WHEN _quarantined THEN 1 ELSE 0 END), 0) AS rows_quarantined,
      (
        SELECT
          COUNT(*)
        FROM bronze.wms__stock_levels
      ) - (
        SELECT
          COUNT(*)
        FROM (
          SELECT
            TRY_CAST(day AS DATE) AS stock_date,
            TRY_CAST(on_hand AS BIGINT) AS stock_level,
            TRY_CAST(warehouse AS TEXT) AS warehouse_id,
            _ingested_at,
            _load_id,
            _source_row_id,
            day AS _src_stock_date_coercible_0000,
            on_hand AS _src_stock_level_coercible_0000,
            warehouse AS _src_warehouse_id_coercible_0000
          FROM bronze.wms__stock_levels
          QUALIFY
            ROW_NUMBER() OVER (
              PARTITION BY warehouse_id, stock_date
              ORDER BY _ingested_at DESC, _load_id DESC, _source_row_id DESC
            ) = 1
        ) AS _extract
      ) AS rows_deduped
    FROM _quality_rows_inventory_level
    UNION ALL
    SELECT
      'inventory_level' AS entity,
      'wms__stock_levels->inventory_level' AS mapping,
      'stock_date_coercible' AS rule,
      'quarantine' AS disposition,
      0 AS rows_evaluated,
      COALESCE(SUM(CASE WHEN ARRAY_CONTAINS(_flags, 'stock_date_coercible') THEN 1 ELSE 0 END), 0) AS rows_failed,
      0 AS rows_quarantined,
      0 AS rows_deduped
    FROM _quality_rows_inventory_level
    UNION ALL
    SELECT
      'inventory_level' AS entity,
      'wms__stock_levels->inventory_level' AS mapping,
      'stock_level_coercible' AS rule,
      'quarantine' AS disposition,
      0 AS rows_evaluated,
      COALESCE(
        SUM(CASE WHEN ARRAY_CONTAINS(_flags, 'stock_level_coercible') THEN 1 ELSE 0 END),
        0
      ) AS rows_failed,
      0 AS rows_quarantined,
      0 AS rows_deduped
    FROM _quality_rows_inventory_level
    UNION ALL
    SELECT
      'inventory_level' AS entity,
      'wms__stock_levels->inventory_level' AS mapping,
      'warehouse_id_coercible' AS rule,
      'quarantine' AS disposition,
      0 AS rows_evaluated,
      COALESCE(
        SUM(CASE WHEN ARRAY_CONTAINS(_flags, 'warehouse_id_coercible') THEN 1 ELSE 0 END),
        0
      ) AS rows_failed,
      0 AS rows_quarantined,
      0 AS rows_deduped
    FROM _quality_rows_inventory_level
    UNION ALL
    SELECT
      'inventory_level' AS entity,
      'wms__stock_levels->inventory_level' AS mapping,
      'stock_level_not_negative' AS rule,
      'flag' AS disposition,
      0 AS rows_evaluated,
      COALESCE(
        SUM(CASE WHEN ARRAY_CONTAINS(_flags, 'stock_level_not_negative') THEN 1 ELSE 0 END),
        0
      ) AS rows_failed,
      0 AS rows_quarantined,
      0 AS rows_deduped
    FROM _quality_rows_inventory_level
    UNION ALL
    SELECT
      'inventory_level' AS entity,
      'wms__stock_levels->inventory_level' AS mapping,
      'stock_level_not_null' AS rule,
      'fail' AS disposition,
      0 AS rows_evaluated,
      COALESCE(SUM(CASE WHEN ARRAY_CONTAINS(_flags, 'stock_level_not_null') THEN 1 ELSE 0 END), 0) AS rows_failed,
      0 AS rows_quarantined,
      0 AS rows_deduped
    FROM _quality_rows_inventory_level
    UNION ALL
    SELECT
      'inventory_level' AS entity,
      'wms__stock_levels->inventory_level' AS mapping,
      'stock_level_range_min' AS rule,
      'quarantine' AS disposition,
      0 AS rows_evaluated,
      COALESCE(
        SUM(CASE WHEN ARRAY_CONTAINS(_flags, 'stock_level_range_min') THEN 1 ELSE 0 END),
        0
      ) AS rows_failed,
      0 AS rows_quarantined,
      0 AS rows_deduped
    FROM _quality_rows_inventory_level
    UNION ALL
    SELECT
      'inventory_level' AS entity,
      'wms__stock_levels->inventory_level' AS mapping,
      'stock_level_matches_snapshot' AS rule,
      'flag' AS disposition,
      0 AS rows_evaluated,
      COALESCE(SUM(CASE WHEN NOT within_tolerance THEN 1 ELSE 0 END), 0) AS rows_failed,
      0 AS rows_quarantined,
      0 AS rows_deduped
    FROM silver.stock_level_matches_snapshot__reconcile
  ) AS _evaluations
) AS _stamped
