-- Generated by bloomery — do not edit.
-- fingerprint: blm1:973001eb3fe549f56e7467921a8555e0d2c4a3d2b24c5138e48cb6a99b80992e
{% snapshot customer_snapshot %}
{{ config(target_schema='silver', unique_key='customer_id', strategy='check', check_cols='all') }}

SELECT
  CAST(id AS TEXT) AS customer_id,
  CAST(email AS TEXT) AS email,
  CAST(segment AS TEXT) AS segment,
  CAST(ARRAY[] AS TEXT[]) AS _quality_flags,
  TRUE AS _quality_ok
FROM bronze.crm__customers

{% endsnapshot %}
