-- Generated by bloomery — do not edit.
-- fingerprint: blm1:55a3442e1f1ef8cf72ff224c7fd21978300926fcbe8032abb7302dcf1949b85f
-- The disjointness law (RFC 0024 §5.4) as a runtime audit: a union merge
-- requires the sources' key sets to be disjoint, and the compiler has no data
-- to establish it with. Blocking, and not configurable to a weaker
-- disposition (D5) — a key in two sources is either genuine duplication or a
-- shared key space by accident, and both are refusals. Flagging it would let a
-- double-counted entity into the warehouse marked merely suspect.
AUDIT (
  name order_line_source_collision
);

SELECT
  order_id,
  line_no,
  COUNT(DISTINCT _source) AS sources
FROM @this_model AS _entity
GROUP BY
  order_id,
  line_no
HAVING
  COUNT(DISTINCT _source) > 1
