-- Generated by bloomery — do not edit.
-- fingerprint: blm1:27d74d9ec84f7fb3275d59be3456f34dc78125a2575ea14766ecbdce0ba9805f
MODEL (
  name silver.order_item,
  kind INCREMENTAL_BY_TIME_RANGE (time_column order_date),
  grain (order_id, line_no),
  partitioned_by (days(order_date)),
  audits (order_item_key_unique, not_null(columns := (order_date)))
);

SELECT
  CAST(index AS BIGINT) AS line_no,
  CAST(TO_UTC_TIMESTAMP(
    CAST(CASE
      WHEN (
        SUBSTRING(CAST(created_at AS STRING), 11) LIKE '%+%'
        OR SUBSTRING(CAST(created_at AS STRING), 11) LIKE '%-%'
      )
      OR UPPER(SUBSTRING(CAST(created_at AS STRING), 11)) LIKE '%Z%'
      THEN NULL
      ELSE REPLACE(REPLACE(CAST(created_at AS STRING), 'T', ' '), 't', ' ')
    END AS TIMESTAMP_NTZ),
    'Europe/Paris'
  ) AS TIMESTAMP_NTZ) AS order_date,
  CAST(order_id AS STRING) AS order_id,
  CAST(qty AS BIGINT) AS quantity,
  CAST(total / qty AS DECIMAL(12, 4)) AS unit_price,
  CAST(ARRAY() AS ARRAY<STRING>) AS _quality_flags,
  TRUE AS _quality_ok
FROM bronze.shopify__order_lines
