-- Generated by bloomery — do not edit.
-- fingerprint: blm1:85868b90fb2c8058fae372853f795640688a50f36856ecadca960e559cf20854
MODEL (
  name silver.order,
  kind FULL,
  owner 'commerce-platform@example.com',
  grain (order_id),
  audits (order_key_unique)
);

SELECT
  CAST(customer:id AS STRING) AS customer_id,
  CAST(id AS STRING) AS order_id,
  CAST(ARRAY() AS ARRAY<STRING>) AS _quality_flags,
  TRUE AS _quality_ok
FROM bronze.shopify__orders
