-- Generated by bloomery — do not edit.
-- fingerprint: blm1:2bdd9c81817df877d2c461de43efd384e90f1bc8a8e00658ab1d52883f8b11d3
MODEL (
  name silver.order,
  kind FULL,
  owner 'commerce-platform@example.com',
  grain (order_id)
);

SELECT
  CAST(customer:id AS STRING) AS customer_id,
  CAST(id AS STRING) AS order_id,
  CAST(ARRAY() AS ARRAY<STRING>) AS _quality_flags,
  TRUE AS _quality_ok
FROM bronze.shopify__orders
