-- Generated by bloomery — do not edit.
-- fingerprint: blm1:2b6372ca8b47ba0246a75ad73d731f63e525b4dd7b4879016523384377857a62
MODEL (
  name silver.order,
  kind FULL,
  owner 'commerce-platform@example.com',
  grain (order_id)
);

SELECT
  CAST(customer:id AS STRING) AS customer_id,
  CAST(id AS STRING) AS order_id,
  CAST(ARRAY() AS ARRAY<STRING>) AS _quality_flags,
  TRUE AS _quality_ok
FROM bronze.shopify__orders
