-- Generated by bloomery — do not edit.
-- fingerprint: blm1:3b361d31b25c3e37bca38f4234664a5b05ac95f45921932fb8896208be5b2de6
MODEL (
  name silver.order,
  kind FULL,
  grain (order_id)
);

SELECT
  CAST(amount AS DECIMAL(12, 4)) AS amount,
  CAST(order_date AS DATE) AS order_date,
  CAST(id AS TEXT) AS order_id,
  CAST(ship_date AS DATE) AS ship_date,
  CAST([] AS TEXT[]) AS _quality_flags,
  TRUE AS _quality_ok
FROM bronze.oms__orders
