-- Generated by bloomery — do not edit.
-- fingerprint: blm1:2453bb91f182d808f502e99091547c17b453574adf893f0c9a276a1e2dc7dba1
MODEL (
  name silver.order,
  kind FULL,
  grain (order_id)
);

SELECT
  CAST(amount AS DECIMAL(12, 4)) AS amount,
  CAST(order_date AS DATE) AS order_date,
  CAST(id AS TEXT) AS order_id,
  CAST(ship_date AS DATE) AS ship_date,
  CAST([] AS TEXT[]) AS _quality_flags,
  TRUE AS _quality_ok
FROM bronze.oms__orders
