-- Generated by bloomery — do not edit.
-- fingerprint: blm1:f556c3cca699746afe521f56bef111efbe75c1de61752eca679b69654ecfa4c8
MODEL (
  name silver.item,
  kind FULL,
  grain (order_id, line_no),
  audits (item_source_collision, item_key_unique, item_net_price_reconcile)
);

SELECT
  *,
  CAST([] AS TEXT[]) AS _quality_flags,
  TRUE AS _quality_ok
FROM (
  SELECT
    CAST(position AS BIGINT) AS line_no,
    CAST(CAST(total AS DECIMAL(12, 4)) / quantity AS DECIMAL(12, 4)) AS net_price,
    CAST(price AS DECIMAL(12, 4)) AS net_price__direct,
    CAST(order_ref AS TEXT) AS order_id,
    CAST(quantity AS BIGINT) AS quantity,
    'shopify__items' AS _source
  FROM bronze.shopify__items
  UNION ALL
  SELECT
    CAST(item_index AS BIGINT) AS line_no,
    CAST(CAST(line_gross AS DECIMAL(12, 4)) / qty AS DECIMAL(12, 4)) AS net_price,
    CAST(unit_amount AS DECIMAL(12, 4)) AS net_price__direct,
    CAST(order_number AS TEXT) AS order_id,
    CAST(qty AS BIGINT) AS quantity,
    'woo__items' AS _source
  FROM bronze.woo__items
) AS _extract
