-- Generated by bloomery — do not edit.
-- fingerprint: blm1:b7d599c796b7af9fd474bf5d73dfede2ffb4a729e04b93d8f57807a90ebbe060
MODEL (
  name silver.order_line,
  kind FULL,
  grain (order_id, line_no),
  audits (order_line_source_collision)
);

SELECT
  *,
  ARRAY<STRING>[] AS _quality_flags,
  TRUE AS _quality_ok
FROM (
  SELECT
    CAST(JSON_EXTRACT_SCALAR(properties, '$.gift_note') AS STRING) AS gift_note,
    CAST(position AS INT64) AS line_no,
    CAST(JSON_EXTRACT_SCALAR(`order`, '$.id') AS STRING) AS order_id,
    CAST(quantity AS INT64) AS quantity,
    CAST(JSON_EXTRACT_SCALAR(variant, '$.sku') AS STRING) AS sku,
    'shopify__order_lines' AS _source
  FROM bronze.shopify__order_lines
  UNION ALL
  SELECT
    CAST(NULL AS STRING) AS gift_note,
    CAST(item_index AS INT64) AS line_no,
    CAST(order_number AS STRING) AS order_id,
    CAST(qty AS INT64) AS quantity,
    CAST(product_sku AS STRING) AS sku,
    'woo__order_lines' AS _source
  FROM bronze.woo__order_lines
) AS _extract
