-- Generated by bloomery — do not edit.
-- fingerprint: blm1:868b3943fdf842667f94b52c1da1fd0c44142ff28d8e5f54691b9f4775ce1e91
MODEL (
  name silver.inventory_level__reject,
  kind INCREMENTAL_BY_UNIQUE_KEY (unique_key (reject_id), when_matched (WHEN MATCHED THEN UPDATE SET target.source_relation = source.source_relation, target.mapping = source.mapping, target.mapping_version = source.mapping_version, target.failed_rules = source.failed_rules, target.key_values = source.key_values, target.raw = source.raw, target._load_id = source._load_id, target._ingested_at = source._ingested_at, target._source_row_id = source._source_row_id, target.first_seen = COALESCE(target.first_seen, source.first_seen), target.last_seen = source.last_seen, target.resolved_at = source.resolved_at, target.last_evaluated_at = COALESCE(target.last_evaluated_at, source.last_evaluated_at))),
  grain (reject_id)
);

SELECT
  _extract.reject_id,
  _extract.source_relation,
  _extract.mapping,
  _extract.mapping_version,
  LIST_CONCAT(
    LIST_CONCAT(
      LIST_CONCAT(
        LIST_CONCAT(
          LIST_CONCAT(
            CASE
              WHEN _extract._branch_stock_date_coercible
              THEN ['stock_date_coercible']
              ELSE CAST([] AS TEXT[])
            END,
            CASE
              WHEN _extract._branch_stock_level_coercible
              THEN ['stock_level_coercible']
              ELSE CAST([] AS TEXT[])
            END
          ),
          CASE
            WHEN NOT (
              _extract.stock_level >= 0
            )
            THEN ['stock_level_not_negative']
            ELSE CAST([] AS TEXT[])
          END
        ),
        CASE
          WHEN _extract.stock_level IS NULL
          THEN ['stock_level_not_null']
          ELSE CAST([] AS TEXT[])
        END
      ),
      CASE
        WHEN _extract.stock_level < 0
        THEN ['stock_level_range_min']
        ELSE CAST([] AS TEXT[])
      END
    ),
    CASE
      WHEN _extract._branch_warehouse_id_coercible
      THEN ['warehouse_id_coercible']
      ELSE CAST([] AS TEXT[])
    END
  ) AS failed_rules,
  JSON_OBJECT('stock_date', _extract.stock_date, 'warehouse_id', _extract.warehouse_id) AS key_values,
  _extract._raw AS raw,
  _extract._load_id,
  _extract._ingested_at,
  _extract._source_row_id,
  _extract._ingested_at AS first_seen,
  _extract._ingested_at AS last_seen,
  CAST(NULL AS TIMESTAMP) AS resolved_at,
  CAST(NULL AS TIMESTAMP) AS last_evaluated_at
FROM (
  SELECT
    TRY_CAST(day AS DATE) AS stock_date,
    TRY_CAST(on_hand AS BIGINT) AS stock_level,
    TRY_CAST(warehouse AS TEXT) AS warehouse_id,
    _ingested_at,
    _load_id,
    _source_row_id,
    TRY_CAST(day AS DATE) IS NULL AND (
      NOT day IS NULL
    ) AS _branch_stock_date_coercible,
    TRY_CAST(on_hand AS BIGINT) IS NULL AND (
      NOT on_hand IS NULL
    ) AS _branch_stock_level_coercible,
    TRY_CAST(warehouse AS TEXT) IS NULL AND (
      NOT warehouse IS NULL
    ) AS _branch_warehouse_id_coercible,
    JSON_OBJECT(
      '_ingested_at',
      _ingested_at,
      '_load_id',
      _load_id,
      '_source_row_id',
      _source_row_id,
      'day',
      day,
      'on_hand',
      on_hand,
      'warehouse',
      warehouse
    ) AS _raw,
    SHA256(
      'S17:wms__stock_levels' || 'S' || CAST(LENGTH(_source_row_id) AS TEXT) || ':' || _source_row_id
    ) AS reject_id,
    'wms__stock_levels' AS source_relation,
    'wms__stock_levels->inventory_level' AS mapping,
    1 AS mapping_version
  FROM bronze.wms__stock_levels
  QUALIFY
    ROW_NUMBER() OVER (
      PARTITION BY warehouse_id, stock_date
      ORDER BY _ingested_at DESC, _load_id DESC, _source_row_id DESC
    ) = 1
) AS _extract
WHERE
  COALESCE(
    (
      _extract._branch_stock_date_coercible
      OR _extract._branch_stock_level_coercible
      OR _extract._branch_warehouse_id_coercible
      OR _extract.stock_level < 0
    ),
    FALSE
  )
