-- Generated by bloomery — do not edit.
-- fingerprint: blm1:868b3943fdf842667f94b52c1da1fd0c44142ff28d8e5f54691b9f4775ce1e91
MODEL (
  name silver.inventory_level,
  kind FULL,
  grain (warehouse_id, stock_date),
  audits (inventory_level_ingestion_metadata, inventory_level_conservation, inventory_level_stock_level_not_null)
);

SELECT
  _evaluated.stock_date,
  _evaluated.stock_level,
  _evaluated.warehouse_id,
  _evaluated._ingested_at,
  _evaluated._load_id,
  _evaluated._source_row_id,
  _evaluated._quality_flags,
  COALESCE(ARRAY_LENGTH(_evaluated._quality_flags), 0) = 0 AS _quality_ok
FROM (
  SELECT
    _extract.stock_date,
    _extract.stock_level,
    _extract.warehouse_id,
    _extract._ingested_at,
    _extract._load_id,
    _extract._source_row_id,
    LIST_CONCAT(
      CASE
        WHEN NOT (
          _extract.stock_level >= 0
        )
        THEN ['stock_level_not_negative']
        ELSE CAST([] AS TEXT[])
      END,
      CASE
        WHEN _extract.stock_level IS NULL
        THEN ['stock_level_not_null']
        ELSE CAST([] AS TEXT[])
      END
    ) AS _quality_flags
  FROM (
    SELECT
      TRY_CAST(day AS DATE) AS stock_date,
      TRY_CAST(on_hand AS BIGINT) AS stock_level,
      TRY_CAST(warehouse AS TEXT) AS warehouse_id,
      _ingested_at,
      _load_id,
      _source_row_id,
      TRY_CAST(day AS DATE) IS NULL AND (
        NOT day IS NULL
      ) AS _branch_stock_date_coercible,
      TRY_CAST(on_hand AS BIGINT) IS NULL AND (
        NOT on_hand IS NULL
      ) AS _branch_stock_level_coercible,
      TRY_CAST(warehouse AS TEXT) IS NULL AND (
        NOT warehouse IS NULL
      ) AS _branch_warehouse_id_coercible
    FROM bronze.wms__stock_levels
    QUALIFY
      ROW_NUMBER() OVER (
        PARTITION BY warehouse_id, stock_date
        ORDER BY _ingested_at DESC, _load_id DESC, _source_row_id DESC
      ) = 1
  ) AS _extract
  WHERE
    NOT COALESCE(
      (
        _extract._branch_stock_date_coercible
        OR _extract._branch_stock_level_coercible
        OR _extract._branch_warehouse_id_coercible
        OR _extract.stock_level < 0
      ),
      FALSE
    )
) AS _evaluated
