-- Generated by bloomery — do not edit.
-- fingerprint: blm1:63d177637573086fbe0483938679959fbd7d8ab2938e2ef04626d6bbc89f1157
MODEL (
  name silver.inventory_level,
  kind FULL,
  grain (warehouse_id, stock_date)
);

SELECT
  CAST(day AS DATE) AS stock_date,
  CAST(on_hand AS BIGINT) AS stock_level,
  CAST(warehouse AS TEXT) AS warehouse_id
FROM bronze.wms__stock_levels
