-- Generated by bloomery — do not edit.
-- fingerprint: blm1:92c004029d618a8893fb97cb111ded2c3771a3720d84a3c5d9f10dc88a41729b
MODEL (
  name silver.stock_level_matches_snapshot__reconcile,
  kind FULL,
  grain (warehouse_id, stock_date),
  audits (stock_level_matches_snapshot_reconcile)
);

WITH _left AS (
  SELECT
    warehouse_id,
    stock_date,
    SUM(stock_level) AS left_value
  FROM silver.inventory_level
  GROUP BY
    warehouse_id,
    stock_date
), _right AS (
  SELECT
    warehouse_id,
    stock_date,
    stock_level AS right_value
  FROM silver.inventory_level
), _keys AS (
  SELECT
    _left.stock_date,
    _left.warehouse_id
  FROM _left
  UNION
  SELECT
    _right.stock_date,
    _right.warehouse_id
  FROM _right
)
SELECT
  _keys.warehouse_id,
  _keys.stock_date,
  _left.left_value,
  _right.right_value,
  ABS(_left.left_value - _right.right_value) AS difference,
  COALESCE(ABS(_left.left_value - _right.right_value) <= 0.01, FALSE) AS within_tolerance
FROM _keys
LEFT JOIN _left
  ON _keys.stock_date IS NOT DISTINCT FROM _left.stock_date
  AND _keys.warehouse_id IS NOT DISTINCT FROM _left.warehouse_id
LEFT JOIN _right
  ON _keys.stock_date IS NOT DISTINCT FROM _right.stock_date
  AND _keys.warehouse_id IS NOT DISTINCT FROM _right.warehouse_id
