-- Generated by bloomery — do not edit.
-- fingerprint: blm1:05e5341378624d6a628db11416ecd67485bfb0aae9cc364281a0c6c306585196
MODEL (
  name silver.stock_level_matches_snapshot__reconcile,
  kind FULL,
  grain (warehouse_id, stock_date),
  audits (stock_level_matches_snapshot_reconcile)
);

SELECT
  COALESCE(_left.warehouse_id, _right.warehouse_id) AS warehouse_id,
  COALESCE(_left.stock_date, _right.stock_date) AS stock_date,
  _left.left_value,
  _right.right_value,
  ABS(_left.left_value - _right.right_value) AS difference,
  COALESCE(ABS(_left.left_value - _right.right_value) <= 0.01, FALSE) AS within_tolerance
FROM (
  SELECT
    warehouse_id,
    stock_date,
    SUM(stock_level) AS left_value
  FROM silver.inventory_level
  GROUP BY
    warehouse_id,
    stock_date
) AS _left
FULL OUTER JOIN (
  SELECT
    warehouse_id,
    stock_date,
    stock_level AS right_value
  FROM silver.inventory_level
) AS _right
  ON _left.stock_date = _right.stock_date AND _left.warehouse_id = _right.warehouse_id
