-- Generated by bloomery — do not edit.
-- fingerprint: blm1:fef80a0621b2e5de353196d283d42cf42a6140fac61052c18f665136dba2ec49
MODEL (
  name silver.event,
  kind FULL,
  grants ("select" = ('analyst', 'reverse_etl')),
  grain (event_id)
);

SELECT
  CAST(id AS STRING) AS event_id,
  CAST(kind AS STRING) AS kind,
  CAST(ts AS TIMESTAMP_NTZ) AS occurred_at,
  CAST(ARRAY() AS ARRAY<STRING>) AS _quality_flags,
  TRUE AS _quality_ok
FROM bronze.raw__events
