-- Generated by bloomery — do not edit.
-- fingerprint: blm1:58a6195ae0c81f71e97bb9f469bc9cbc1dfed8462b51297838ef5093af565158
-- The conservation law (RFC 0016 §6) as a runtime audit: every bronze row
-- lands in exactly one of the entity, an unresolved reject, or the deduped
-- count. Blocking — a row in neither side of the split has been silently
-- dropped, which is the failure this package exists to make impossible.
AUDIT (
  name order_line_conservation
);

WITH _survivors AS (
  SELECT
    *
  FROM (
    SELECT
      *,
      ROW_NUMBER() OVER (
        PARTITION BY order_id, line_no
        ORDER BY placed_at DESC NULLS LAST, line_no DESC NULLS LAST, _source DESC NULLS LAST, _source_row_id DESC NULLS LAST
      ) AS _w
    FROM (
      SELECT
        CASE
          WHEN PG_INPUT_IS_VALID(properties ->> 'gift_note', 'TEXT')
          THEN CAST(properties ->> 'gift_note' AS TEXT)
        END AS gift_note,
        CASE WHEN PG_INPUT_IS_VALID(position, 'BIGINT') THEN CAST(position AS BIGINT) END AS line_no,
        CASE
          WHEN PG_INPUT_IS_VALID("order" ->> 'id', 'TEXT')
          THEN CAST("order" ->> 'id' AS TEXT)
        END AS order_id,
        CASE
          WHEN PG_INPUT_IS_VALID(created_at, 'TIMESTAMP')
          AND NOT LOWER(created_at) ~ '^[[:space:]]*(now|today|tomorrow|yesterday)[[:space:]]*$'
          THEN CAST(created_at AS TIMESTAMP)
        END AS placed_at,
        CASE WHEN PG_INPUT_IS_VALID(quantity, 'BIGINT') THEN CAST(quantity AS BIGINT) END AS quantity,
        CASE
          WHEN PG_INPUT_IS_VALID(variant ->> 'sku', 'TEXT')
          THEN CAST(variant ->> 'sku' AS TEXT)
        END AS sku,
        CASE CASE
            WHEN PG_INPUT_IS_VALID(financial_status, 'TEXT')
            THEN CAST(financial_status AS TEXT)
          END
          WHEN 'pending'
          THEN 'open'
          WHEN 'paid'
          THEN 'closed'
          WHEN 'refunded'
          THEN 'reversed'
          ELSE CASE
            WHEN PG_INPUT_IS_VALID(financial_status, 'TEXT')
            THEN CAST(financial_status AS TEXT)
          END
        END AS status,
        _ingested_at,
        _load_id,
        _source_row_id,
        CASE
          WHEN PG_INPUT_IS_VALID(properties ->> 'gift_note', 'TEXT')
          THEN CAST(properties ->> 'gift_note' AS TEXT)
        END IS NULL
        AND (
          NOT properties ->> 'gift_note' IS NULL
        ) AS _branch_gift_note_coercible,
        CASE WHEN PG_INPUT_IS_VALID(position, 'BIGINT') THEN CAST(position AS BIGINT) END IS NULL
        AND (
          NOT position IS NULL
        ) AS _branch_line_no_coercible,
        CASE
          WHEN PG_INPUT_IS_VALID("order" ->> 'id', 'TEXT')
          THEN CAST("order" ->> 'id' AS TEXT)
        END IS NULL
        AND (
          NOT "order" ->> 'id' IS NULL
        ) AS _branch_order_id_coercible,
        CASE
          WHEN PG_INPUT_IS_VALID(created_at, 'TIMESTAMP')
          AND NOT LOWER(created_at) ~ '^[[:space:]]*(now|today|tomorrow|yesterday)[[:space:]]*$'
          THEN CAST(created_at AS TIMESTAMP)
        END IS NULL
        AND (
          NOT created_at IS NULL
        ) AS _branch_placed_at_coercible,
        CASE WHEN PG_INPUT_IS_VALID(quantity, 'BIGINT') THEN CAST(quantity AS BIGINT) END IS NULL
        AND (
          NOT quantity IS NULL
        ) AS _branch_quantity_coercible,
        CASE
          WHEN PG_INPUT_IS_VALID(variant ->> 'sku', 'TEXT')
          THEN CAST(variant ->> 'sku' AS TEXT)
        END IS NULL
        AND (
          NOT variant ->> 'sku' IS NULL
        ) AS _branch_sku_coercible,
        CASE CASE
            WHEN PG_INPUT_IS_VALID(financial_status, 'TEXT')
            THEN CAST(financial_status AS TEXT)
          END
          WHEN 'pending'
          THEN 'open'
          WHEN 'paid'
          THEN 'closed'
          WHEN 'refunded'
          THEN 'reversed'
          ELSE CASE
            WHEN PG_INPUT_IS_VALID(financial_status, 'TEXT')
            THEN CAST(financial_status AS TEXT)
          END
        END IS NULL
        AND (
          NOT financial_status IS NULL
        ) AS _branch_status_coercible,
        NOT CASE CASE
            WHEN PG_INPUT_IS_VALID(financial_status, 'TEXT')
            THEN CAST(financial_status AS TEXT)
          END
          WHEN 'pending'
          THEN 'open'
          WHEN 'paid'
          THEN 'closed'
          WHEN 'refunded'
          THEN 'reversed'
          ELSE CASE
            WHEN PG_INPUT_IS_VALID(financial_status, 'TEXT')
            THEN CAST(financial_status AS TEXT)
          END
        END IN ('closed', 'open', 'reversed') AS _branch_status_in_enum,
        'shopify__order_lines' AS _source
      FROM bronze.shopify__order_lines
      UNION ALL
      SELECT
        CAST(NULL AS TEXT) AS gift_note,
        CASE
          WHEN PG_INPUT_IS_VALID(item_index, 'BIGINT')
          THEN CAST(item_index AS BIGINT)
        END AS line_no,
        CASE
          WHEN PG_INPUT_IS_VALID(order_number, 'TEXT')
          THEN CAST(order_number AS TEXT)
        END AS order_id,
        CASE
          WHEN PG_INPUT_IS_VALID(created, 'TIMESTAMP')
          AND NOT LOWER(created) ~ '^[[:space:]]*(now|today|tomorrow|yesterday)[[:space:]]*$'
          THEN CAST(created AS TIMESTAMP)
        END AS placed_at,
        CASE WHEN PG_INPUT_IS_VALID(qty, 'BIGINT') THEN CAST(qty AS BIGINT) END AS quantity,
        CASE WHEN PG_INPUT_IS_VALID(product_sku, 'TEXT') THEN CAST(product_sku AS TEXT) END AS sku,
        CASE CASE WHEN PG_INPUT_IS_VALID(state, 'TEXT') THEN CAST(state AS TEXT) END
          WHEN 'PROCESSING'
          THEN 'open'
          WHEN 'COMPLETE'
          THEN 'closed'
          ELSE CASE WHEN PG_INPUT_IS_VALID(state, 'TEXT') THEN CAST(state AS TEXT) END
        END AS status,
        _ingested_at,
        _load_id,
        _source_row_id,
        FALSE AS _branch_gift_note_coercible,
        CASE
          WHEN PG_INPUT_IS_VALID(item_index, 'BIGINT')
          THEN CAST(item_index AS BIGINT)
        END IS NULL
        AND (
          NOT item_index IS NULL
        ) AS _branch_line_no_coercible,
        CASE
          WHEN PG_INPUT_IS_VALID(order_number, 'TEXT')
          THEN CAST(order_number AS TEXT)
        END IS NULL
        AND (
          NOT order_number IS NULL
        ) AS _branch_order_id_coercible,
        CASE
          WHEN PG_INPUT_IS_VALID(created, 'TIMESTAMP')
          AND NOT LOWER(created) ~ '^[[:space:]]*(now|today|tomorrow|yesterday)[[:space:]]*$'
          THEN CAST(created AS TIMESTAMP)
        END IS NULL
        AND (
          NOT created IS NULL
        ) AS _branch_placed_at_coercible,
        CASE WHEN PG_INPUT_IS_VALID(qty, 'BIGINT') THEN CAST(qty AS BIGINT) END IS NULL
        AND (
          NOT qty IS NULL
        ) AS _branch_quantity_coercible,
        CASE WHEN PG_INPUT_IS_VALID(product_sku, 'TEXT') THEN CAST(product_sku AS TEXT) END IS NULL
        AND (
          NOT product_sku IS NULL
        ) AS _branch_sku_coercible,
        CASE CASE WHEN PG_INPUT_IS_VALID(state, 'TEXT') THEN CAST(state AS TEXT) END
          WHEN 'PROCESSING'
          THEN 'open'
          WHEN 'COMPLETE'
          THEN 'closed'
          ELSE CASE WHEN PG_INPUT_IS_VALID(state, 'TEXT') THEN CAST(state AS TEXT) END
        END IS NULL
        AND (
          NOT state IS NULL
        ) AS _branch_status_coercible,
        NOT CASE CASE WHEN PG_INPUT_IS_VALID(state, 'TEXT') THEN CAST(state AS TEXT) END
          WHEN 'PROCESSING'
          THEN 'open'
          WHEN 'COMPLETE'
          THEN 'closed'
          ELSE CASE WHEN PG_INPUT_IS_VALID(state, 'TEXT') THEN CAST(state AS TEXT) END
        END IN ('closed', 'open') AS _branch_status_in_enum,
        'woo__order_lines' AS _source
      FROM bronze.woo__order_lines
    ) AS _extract
  ) AS _t
  WHERE
    _w = 1
)
SELECT
  *
FROM (
  SELECT
    COUNT(*) AS surviving_rows,
    SUM(
      CASE
        WHEN COALESCE(
          (
            _survivors._branch_gift_note_coercible
            OR _survivors._branch_order_id_coercible
            OR _survivors._branch_quantity_coercible
            OR _survivors._branch_sku_coercible
            OR _survivors._branch_status_coercible
            OR _survivors._branch_status_in_enum
          ),
          FALSE
        )
        THEN 1
        ELSE 0
      END
    ) AS diverted_rows,
    (
      SELECT
        COUNT(*)
      FROM bronze.shopify__order_lines
    ) + (
      SELECT
        COUNT(*)
      FROM bronze.woo__order_lines
    ) AS bronze_rows,
    (
      SELECT
        COUNT(*)
      FROM @this_model AS _entity
      WHERE
        _entity._source_row_id IN (
          SELECT
            _source_row_id
          FROM _survivors
        )
    ) AS entity_rows
  FROM _survivors
) AS _conservation
WHERE
  entity_rows + diverted_rows <> surviving_rows
