-- Generated by bloomery — do not edit.
-- fingerprint: blm1:b6e7b4d8c4829a9301255fe04a14f48145243040b2c07c59768de2f6be092d36
AUDIT (
  name order_line_ingestion_metadata
);

SELECT
  *
FROM (
  SELECT
    *,
    COUNT(*) OVER (PARTITION BY _source, _source_row_id) AS _row_id_count
  FROM @this_model
) AS _metadata
WHERE
  _ingested_at IS NULL
  OR _load_id IS NULL
  OR _source_row_id IS NULL
  OR _row_id_count > 1
  OR (
    (
      NOT _ingested_at IS NULL
    )
    AND CASE
      WHEN PG_INPUT_IS_VALID(
        CASE
          WHEN SUBSTRING(CAST(_ingested_at AS VARCHAR) FROM 11) LIKE '%+%'
          OR SUBSTRING(CAST(_ingested_at AS VARCHAR) FROM 11) LIKE '%-%'
          THEN NULL
          ELSE _ingested_at
        END,
        'TIMESTAMP'
      )
      AND NOT LOWER(
        CASE
          WHEN SUBSTRING(CAST(_ingested_at AS VARCHAR) FROM 11) LIKE '%+%'
          OR SUBSTRING(CAST(_ingested_at AS VARCHAR) FROM 11) LIKE '%-%'
          THEN NULL
          ELSE _ingested_at
        END
      ) ~ '^[[:space:]]*(now|today|tomorrow|yesterday)[[:space:]]*$'
      THEN CAST(CASE
        WHEN SUBSTRING(CAST(_ingested_at AS VARCHAR) FROM 11) LIKE '%+%'
        OR SUBSTRING(CAST(_ingested_at AS VARCHAR) FROM 11) LIKE '%-%'
        THEN NULL
        ELSE _ingested_at
      END AS TIMESTAMP)
    END IS NULL
  )
