-- Generated by bloomery — do not edit.
-- fingerprint: blm1:4bbad191a61dccb442835e67992d617af3d6077b80515a275a91481c92ba089c
-- The conservation law (S-0033/tests-rfc-0009-amendment) as a runtime audit: every bronze row
-- lands in exactly one of the entity, an unresolved reject, or the deduped
-- count. Blocking — a row in neither side of the split has been silently
-- dropped, which is the failure this package exists to make impossible.
AUDIT (
  name order_line_conservation
);

WITH _survivors AS (
  SELECT
    *
  FROM (
    SELECT
      TRY_CAST(CAST(JSON_EXTRACT_PATH_TEXT(properties, 'gift_note') AS VARCHAR) AS VARCHAR) AS gift_note,
      TRY_CAST(CAST(position AS VARCHAR) AS BIGINT) AS line_no,
      TRY_CAST(CAST(JSON_EXTRACT_PATH_TEXT("ORDER", 'id') AS VARCHAR) AS VARCHAR) AS order_id,
      TRY_CAST(CAST(CASE
        WHEN SUBSTRING(CAST(created_at AS VARCHAR), 11) LIKE '%+%'
        OR SUBSTRING(CAST(created_at AS VARCHAR), 11) LIKE '%-%'
        THEN NULL
        ELSE REPLACE(REPLACE(CAST(created_at AS VARCHAR), 'T', ' '), 't', ' ')
      END AS VARCHAR) AS TIMESTAMPNTZ) AS placed_at,
      TRY_CAST(CAST(quantity AS VARCHAR) AS BIGINT) AS quantity,
      TRY_CAST(CAST(JSON_EXTRACT_PATH_TEXT(variant, 'sku') AS VARCHAR) AS VARCHAR) AS sku,
      CASE TRY_CAST(CAST(financial_status AS VARCHAR) AS VARCHAR)
        WHEN 'pending'
        THEN 'open'
        WHEN 'paid'
        THEN 'closed'
        WHEN 'refunded'
        THEN 'reversed'
        ELSE TRY_CAST(CAST(financial_status AS VARCHAR) AS VARCHAR)
      END AS status,
      _ingested_at,
      _load_id,
      _source_row_id,
      TRY_CAST(CAST(JSON_EXTRACT_PATH_TEXT(properties, 'gift_note') AS VARCHAR) AS VARCHAR) IS NULL
      AND (
        NOT JSON_EXTRACT_PATH_TEXT(properties, 'gift_note') IS NULL
      ) AS _branch_gift_note_coercible,
      TRY_CAST(CAST(position AS VARCHAR) AS BIGINT) IS NULL
      AND (
        NOT position IS NULL
      ) AS _branch_line_no_coercible,
      TRY_CAST(CAST(JSON_EXTRACT_PATH_TEXT("ORDER", 'id') AS VARCHAR) AS VARCHAR) IS NULL
      AND (
        NOT JSON_EXTRACT_PATH_TEXT("ORDER", 'id') IS NULL
      ) AS _branch_order_id_coercible,
      TRY_CAST(CAST(CASE
        WHEN SUBSTRING(CAST(created_at AS VARCHAR), 11) LIKE '%+%'
        OR SUBSTRING(CAST(created_at AS VARCHAR), 11) LIKE '%-%'
        THEN NULL
        ELSE REPLACE(REPLACE(CAST(created_at AS VARCHAR), 'T', ' '), 't', ' ')
      END AS VARCHAR) AS TIMESTAMPNTZ) IS NULL
      AND (
        NOT created_at IS NULL
      ) AS _branch_placed_at_coercible,
      TRY_CAST(CAST(quantity AS VARCHAR) AS BIGINT) IS NULL
      AND (
        NOT quantity IS NULL
      ) AS _branch_quantity_coercible,
      TRY_CAST(CAST(JSON_EXTRACT_PATH_TEXT(variant, 'sku') AS VARCHAR) AS VARCHAR) IS NULL
      AND (
        NOT JSON_EXTRACT_PATH_TEXT(variant, 'sku') IS NULL
      ) AS _branch_sku_coercible,
      CASE TRY_CAST(CAST(financial_status AS VARCHAR) AS VARCHAR)
        WHEN 'pending'
        THEN 'open'
        WHEN 'paid'
        THEN 'closed'
        WHEN 'refunded'
        THEN 'reversed'
        ELSE TRY_CAST(CAST(financial_status AS VARCHAR) AS VARCHAR)
      END IS NULL
      AND (
        NOT financial_status IS NULL
      ) AS _branch_status_coercible,
      NOT CASE TRY_CAST(CAST(financial_status AS VARCHAR) AS VARCHAR)
        WHEN 'pending'
        THEN 'open'
        WHEN 'paid'
        THEN 'closed'
        WHEN 'refunded'
        THEN 'reversed'
        ELSE TRY_CAST(CAST(financial_status AS VARCHAR) AS VARCHAR)
      END IN ('closed', 'open', 'reversed') AS _branch_status_in_enum,
      'shopify__order_lines' AS _source
    FROM bronze.shopify__order_lines
    UNION ALL
    SELECT
      CAST(NULL AS VARCHAR) AS gift_note,
      TRY_CAST(CAST(item_index AS VARCHAR) AS BIGINT) AS line_no,
      TRY_CAST(CAST(order_number AS VARCHAR) AS VARCHAR) AS order_id,
      TRY_CAST(CAST(CASE
        WHEN SUBSTRING(CAST(created AS VARCHAR), 11) LIKE '%+%'
        OR SUBSTRING(CAST(created AS VARCHAR), 11) LIKE '%-%'
        THEN NULL
        ELSE REPLACE(REPLACE(CAST(created AS VARCHAR), 'T', ' '), 't', ' ')
      END AS VARCHAR) AS TIMESTAMPNTZ) AS placed_at,
      TRY_CAST(CAST(qty AS VARCHAR) AS BIGINT) AS quantity,
      TRY_CAST(CAST(product_sku AS VARCHAR) AS VARCHAR) AS sku,
      CASE TRY_CAST(CAST(state AS VARCHAR) AS VARCHAR)
        WHEN 'PROCESSING'
        THEN 'open'
        WHEN 'COMPLETE'
        THEN 'closed'
        ELSE TRY_CAST(CAST(state AS VARCHAR) AS VARCHAR)
      END AS status,
      _ingested_at,
      _load_id,
      _source_row_id,
      FALSE AS _branch_gift_note_coercible,
      TRY_CAST(CAST(item_index AS VARCHAR) AS BIGINT) IS NULL
      AND (
        NOT item_index IS NULL
      ) AS _branch_line_no_coercible,
      TRY_CAST(CAST(order_number AS VARCHAR) AS VARCHAR) IS NULL
      AND (
        NOT order_number IS NULL
      ) AS _branch_order_id_coercible,
      TRY_CAST(CAST(CASE
        WHEN SUBSTRING(CAST(created AS VARCHAR), 11) LIKE '%+%'
        OR SUBSTRING(CAST(created AS VARCHAR), 11) LIKE '%-%'
        THEN NULL
        ELSE REPLACE(REPLACE(CAST(created AS VARCHAR), 'T', ' '), 't', ' ')
      END AS VARCHAR) AS TIMESTAMPNTZ) IS NULL
      AND (
        NOT created IS NULL
      ) AS _branch_placed_at_coercible,
      TRY_CAST(CAST(qty AS VARCHAR) AS BIGINT) IS NULL AND (
        NOT qty IS NULL
      ) AS _branch_quantity_coercible,
      TRY_CAST(CAST(product_sku AS VARCHAR) AS VARCHAR) IS NULL
      AND (
        NOT product_sku IS NULL
      ) AS _branch_sku_coercible,
      CASE TRY_CAST(CAST(state AS VARCHAR) AS VARCHAR)
        WHEN 'PROCESSING'
        THEN 'open'
        WHEN 'COMPLETE'
        THEN 'closed'
        ELSE TRY_CAST(CAST(state AS VARCHAR) AS VARCHAR)
      END IS NULL
      AND (
        NOT state IS NULL
      ) AS _branch_status_coercible,
      NOT CASE TRY_CAST(CAST(state AS VARCHAR) AS VARCHAR)
        WHEN 'PROCESSING'
        THEN 'open'
        WHEN 'COMPLETE'
        THEN 'closed'
        ELSE TRY_CAST(CAST(state AS VARCHAR) AS VARCHAR)
      END IN ('closed', 'open') AS _branch_status_in_enum,
      'woo__order_lines' AS _source
    FROM bronze.woo__order_lines
  ) AS _extract
  QUALIFY
    ROW_NUMBER() OVER (
      PARTITION BY order_id, line_no
      ORDER BY placed_at DESC NULLS LAST, line_no DESC NULLS LAST, _source DESC NULLS LAST, _source_row_id DESC NULLS LAST
    ) = 1
)
SELECT
  *
FROM (
  SELECT
    COUNT(*) AS surviving_rows,
    SUM(
      CASE
        WHEN COALESCE(
          (
            _survivors._branch_gift_note_coercible
            OR _survivors._branch_order_id_coercible
            OR _survivors._branch_quantity_coercible
            OR _survivors._branch_sku_coercible
            OR _survivors._branch_status_coercible
            OR _survivors._branch_status_in_enum
          ),
          FALSE
        )
        THEN 1
        ELSE 0
      END
    ) AS diverted_rows,
    (
      SELECT
        COUNT(*)
      FROM bronze.shopify__order_lines
    ) + (
      SELECT
        COUNT(*)
      FROM bronze.woo__order_lines
    ) AS bronze_rows,
    (
      SELECT
        COUNT(*)
      FROM @this_model AS _entity
      WHERE
        (_entity._source, _entity._source_row_id) IN (
          SELECT
            _source,
            _source_row_id
          FROM _survivors
        )
    ) AS entity_rows
  FROM _survivors
) AS _conservation
WHERE
  entity_rows + diverted_rows <> surviving_rows
