"""The SQLMesh emitter (RFC 0008 §5.3) — the primary target.

One ``MODEL (...)`` block plus ``SELECT`` per entity at
``models/<namespace>/<relation>.sql``. The SELECT is built as a SQLGlot AST
by the shared lowering (:mod:`bloomery.emit.lowering` — the same AST dbt
renders) and rendered through the dialect port; Jinja renders only the
envelope, from a template that interpolates *pre-rendered strings*, never SQL
fragments (RFC 0008 D4). Every artifact carries a header comment with the
project fingerprint (RFC 0008 D9).

``kind`` maps from the IR's resolved materialization: ``full`` → ``FULL``,
``incremental_by_key`` → ``INCREMENTAL_BY_UNIQUE_KEY``,
``incremental_by_partition`` → ``INCREMENTAL_BY_TIME_RANGE`` over the first
partition column. SCD type 2 entities use the native kind first (RFC 0008
§5.3): ``SCD_TYPE_2_BY_COLUMN (unique_key (...), columns *)`` — ``BY_COLUMN``
over all columns, not ``BY_TIME``, because the IR declares no updated-at
marker and inventing one would be silent degradation (syntax verified against
the pinned sqlmesh).

Audits (RFC 0006 §5.6/D7 → RFC 0008 §5.3): ``not_null`` and ``enum`` lower
builtin-style into the MODEL block (``not_null(columns := (...))``,
``accepted_values(column := …, is_in := (...))``); ``min``/``max``/``regex``
and the path-conflict ``reconcile`` need a custom body, so each becomes an
``audits/<entity>_<column>_<kind>.sql`` artifact (``ArtifactKind.AUDIT``)
selecting the violating rows from ``@this_model``, referenced by name in the
MODEL block.

Marts (RFC 0010 / RFC 0008 D11): one gold-layer model per ``MartIR`` at
``NamingPolicy.relation(name, Layer.GOLD)`` — the base entity's silver
relation joined once per resolved ``MartJoinIR`` (LEFT, so flattening never
drops base rows) and date roles bucketed via ``DATE_TRUNC`` cast to ``DATE``,
projecting the full flattened column set. This is the **only** join-emitting
path. When the catalog declares a date dimension, a deterministic
``gold.dim_date`` model is emitted from its year bounds (RFC 0008 D13) — a
generate-series calendar, no clock involved.
"""

from __future__ import annotations

import jinja2

from bloomery.emit.base import (
    ArtifactKind,
    EmitContext,
    EmittedArtifact,
    Feature,
    TargetCapabilities,
)
from bloomery.emit.lowering import (
    audit_predicate,
    column_type,
    dim_date_select,
    entity_select,
    enum_literal,
    mart_select,
)
from bloomery.ir import (
    AuditIR,
    DateDimensionIR,
    EntityIR,
    Layer,
    MartIR,
    Materialization,
    PartitionSpec,
    ProjectIR,
    SCDKind,
)

__all__ = [
    "SQLMeshEmitter",
]

# The envelope sees pre-rendered strings only (RFC 0008 D4). SQL is not HTML:
# autoescaping would corrupt it, and no untrusted input reaches the template.
_ENVELOPE = jinja2.Template(  # nosec B701
    """\
-- Generated by bloomery — do not edit.
-- fingerprint: {{ fingerprint }}
MODEL (
  name {{ name }},
  kind {{ kind }},
  grain ({{ grain }}){% if partitioned_by %},
  partitioned_by ({{ partitioned_by }}){% endif %}{% if audits %},
  audits ({{ audits }}){% endif %}
);

{{ select }}
""",
    autoescape=False,
)

# Custom audit bodies select the violating rows from @this_model — an audit
# passes when the query returns none. The predicate arrives pre-rendered
# through the dialect port, same doctrine as the MODEL envelope (D4).
_AUDIT_ENVELOPE = jinja2.Template(  # nosec B701
    """\
-- Generated by bloomery — do not edit.
-- fingerprint: {{ fingerprint }}
AUDIT (
  name {{ name }}
);

SELECT * FROM @this_model WHERE {{ predicate }}
""",
    autoescape=False,
)


def _kind_clause(entity: EntityIR) -> str:
    if entity.scd is SCDKind.TYPE2:
        # Native SCD (RFC 0008 §5.3): the SCD kind *is* the materialization —
        # it supersedes the resolved incrementality strategy.
        return f"SCD_TYPE_2_BY_COLUMN (unique_key ({', '.join(entity.key)}), columns *)"
    if entity.materialization is Materialization.INCREMENTAL_BY_KEY:
        return f"INCREMENTAL_BY_UNIQUE_KEY (unique_key ({', '.join(entity.key)}))"
    if entity.materialization is Materialization.INCREMENTAL_BY_PARTITION:
        time_column = entity.partition_by[0].column
        return f"INCREMENTAL_BY_TIME_RANGE (time_column {time_column})"
    return "FULL"


def _partitioned_by(specs: tuple[PartitionSpec, ...]) -> str:
    return ", ".join(
        f"{spec.transform}({spec.column})" if spec.transform else spec.column for spec in specs
    )


def _mart_kind_clause(mart: MartIR, base: EntityIR) -> str:
    """A mart is at exactly its base grain (RFC 0010 D2), so the base entity's
    key is its unique key when incrementality-by-key is requested."""
    if mart.materialization is Materialization.INCREMENTAL_BY_KEY:
        return f"INCREMENTAL_BY_UNIQUE_KEY (unique_key ({', '.join(base.key)}))"
    if mart.materialization is Materialization.INCREMENTAL_BY_PARTITION:
        time_column = mart.partition_by[0].column
        return f"INCREMENTAL_BY_TIME_RANGE (time_column {time_column})"
    return "FULL"


def _mart_artifact(mart: MartIR, ir: ProjectIR, ctx: EmitContext) -> EmittedArtifact:
    namespace, relation = ctx.naming.relation(mart.name, Layer.GOLD)
    base = next(entity for entity in ir.entities if entity.name == mart.base)
    content = _ENVELOPE.render(
        fingerprint=ctx.fingerprint,
        name=f"{namespace}.{relation}",
        kind=_mart_kind_clause(mart, base),
        grain=", ".join(base.key),
        partitioned_by=_partitioned_by(mart.partition_by),
        audits="",
        select=ctx.dialect.render(mart_select(mart, ctx)),
    )
    return EmittedArtifact.create(
        path=f"models/{namespace}/{relation}.sql",
        content=content.rstrip("\n") + "\n",
        kind=ArtifactKind.MODEL,
    )


def _dim_date_artifact(dim: DateDimensionIR, ctx: EmitContext) -> EmittedArtifact:
    # The date dimension is bloomery-owned, not a mart: it keeps its declared
    # relation name; the naming policy still shapes the gold namespace.
    namespace, _mart_relation = ctx.naming.relation(dim.name, Layer.GOLD)
    content = _ENVELOPE.render(
        fingerprint=ctx.fingerprint,
        name=f"{namespace}.{dim.name}",
        kind="FULL",
        grain=f"date_{dim.grain}",
        partitioned_by="",
        audits="",
        select=ctx.dialect.render(dim_date_select(dim)),
    )
    return EmittedArtifact.create(
        path=f"models/{namespace}/{dim.name}.sql",
        content=content.rstrip("\n") + "\n",
        kind=ArtifactKind.MODEL,
    )


def _accepted_values(entity: EntityIR, audit: AuditIR, ctx: EmitContext) -> str:
    member_type = column_type(entity, audit.column)
    members = ", ".join(
        ctx.dialect.render(enum_literal(value, member_type)) for _name, value in audit.params
    )
    return f"accepted_values(column := {audit.column}, is_in := ({members}))"


def _entity_audits(entity: EntityIR, ctx: EmitContext) -> tuple[str, tuple[EmittedArtifact, ...]]:
    """The MODEL block's ``audits`` entry string plus the custom audit
    artifacts. ``EntityIR.audits`` is sorted by (kind, column), so both the
    entry order and the artifact set are deterministic."""
    entries: list[str] = []
    artifacts: list[EmittedArtifact] = []
    for audit in entity.audits:
        if audit.kind == "not_null":
            entries.append(f"not_null(columns := ({audit.column}))")
        elif audit.kind == "enum":
            entries.append(_accepted_values(entity, audit, ctx))
        else:
            name = f"{entity.name}_{audit.column}_{audit.kind}"
            entries.append(name)
            content = _AUDIT_ENVELOPE.render(
                fingerprint=ctx.fingerprint,
                name=name,
                predicate=ctx.dialect.render(audit_predicate(entity, audit, violations=True)),
            )
            artifacts.append(
                EmittedArtifact.create(
                    path=f"audits/{name}.sql",
                    content=content.rstrip("\n") + "\n",
                    kind=ArtifactKind.AUDIT,
                )
            )
    return ", ".join(entries), tuple(artifacts)


class SQLMeshEmitter:
    """RFC 0008 §5.3: one model artifact per silver entity, plus one custom
    audit artifact per non-builtin ``AuditIR``."""

    name = "sqlmesh"

    def capabilities(self) -> TargetCapabilities:
        """Declared support per RFC 0008 §5.1 (amended D6): SCD type 2,
        variant columns, incrementality, audits, and all additivity features."""
        return TargetCapabilities(
            supported=frozenset(
                {
                    Feature.SCD_TYPE_2,
                    Feature.VARIANT_COLUMN,
                    Feature.INCREMENTAL,
                    Feature.AUDITS,
                    Feature.SEMI_ADDITIVE,
                    Feature.NON_ADDITIVE,
                    Feature.CUMULATIVE,
                    Feature.DERIVED_METRIC,
                }
            )
        )

    def emit(self, ir: ProjectIR, ctx: EmitContext) -> tuple[EmittedArtifact, ...]:
        """Lower every entity to a model artifact (plus its custom audits),
        every mart to a gold-layer model (RFC 0008 D11), and the declared
        date dimension to ``gold.dim_date`` (RFC 0008 D13); artifacts sorted
        by path, content ending in exactly one newline (RFC 0003 §5.5 rule 5)."""
        artifacts: list[EmittedArtifact] = []
        for entity in ir.entities:
            namespace, relation = ctx.naming.relation(entity.name, Layer.SILVER)
            audits, audit_artifacts = _entity_audits(entity, ctx)
            content = _ENVELOPE.render(
                fingerprint=ctx.fingerprint,
                name=f"{namespace}.{relation}",
                kind=_kind_clause(entity),
                grain=", ".join(entity.key),
                partitioned_by=_partitioned_by(entity.partition_by),
                audits=audits,
                select=ctx.dialect.render(entity_select(entity, ctx)),
            )
            artifacts.append(
                EmittedArtifact.create(
                    path=f"models/{namespace}/{relation}.sql",
                    content=content.rstrip("\n") + "\n",
                    kind=ArtifactKind.MODEL,
                )
            )
            artifacts.extend(audit_artifacts)
        artifacts.extend(_mart_artifact(mart, ir, ctx) for mart in ir.marts)
        if ir.date_dimension is not None:
            artifacts.append(_dim_date_artifact(ir.date_dimension, ctx))
        return tuple(sorted(artifacts, key=lambda a: a.path))
