"""The SQLMesh emitter (RFC 0008 §5.3) — the primary target.

One ``MODEL (...)`` block plus ``SELECT`` per entity at
``models/<namespace>/<relation>.sql``. The SELECT is built as a SQLGlot AST
from ``EntityIR.source`` + columns and rendered through the dialect port;
Jinja renders only the envelope, from a template that interpolates
*pre-rendered strings*, never SQL fragments (RFC 0008 D4). Every artifact
carries a header comment with the project fingerprint (RFC 0008 D9).

``kind`` maps from the IR's resolved materialization: ``full`` → ``FULL``,
``incremental_by_key`` → ``INCREMENTAL_BY_UNIQUE_KEY``,
``incremental_by_partition`` → ``INCREMENTAL_BY_TIME_RANGE`` over the first
partition column. Audits stay minimal until M4 wires real audits (RFC 0006);
marts lower here from M5 (RFC 0010 / RFC 0008 D11).
"""

from __future__ import annotations

from typing import TYPE_CHECKING

import jinja2
from sqlglot import exp

from bloomery.emit.base import (
    ArtifactKind,
    EmitContext,
    EmittedArtifact,
    Feature,
    TargetCapabilities,
)
from bloomery.ir import EntityIR, Layer, Materialization, ProjectIR

if TYPE_CHECKING:
    pass

__all__ = [
    "SQLMeshEmitter",
]

# The envelope sees pre-rendered strings only (RFC 0008 D4). SQL is not HTML:
# autoescaping would corrupt it, and no untrusted input reaches the template.
_ENVELOPE = jinja2.Template(  # nosec B701
    """\
-- Generated by bloomery — do not edit.
-- fingerprint: {{ fingerprint }}
MODEL (
  name {{ name }},
  kind {{ kind }},
  grain ({{ grain }}){% if partitioned_by %},
  partitioned_by ({{ partitioned_by }}){% endif %}
);

{{ select }}
""",
    autoescape=False,
)


def _kind_clause(entity: EntityIR) -> str:
    if entity.materialization is Materialization.INCREMENTAL_BY_KEY:
        return f"INCREMENTAL_BY_UNIQUE_KEY (unique_key ({', '.join(entity.key)}))"
    if entity.materialization is Materialization.INCREMENTAL_BY_PARTITION:
        time_column = entity.partition_by[0].column
        return f"INCREMENTAL_BY_TIME_RANGE (time_column {time_column})"
    return "FULL"


def _partitioned_by(entity: EntityIR) -> str:
    return ", ".join(
        f"{spec.transform}({spec.column})" if spec.transform else spec.column
        for spec in entity.partition_by
    )


def _entity_select(entity: EntityIR, ctx: EmitContext) -> exp.Select:
    namespace, relation = ctx.naming.relation(entity.source.relation, Layer.BRONZE)
    projections = [exp.alias_(column.expr.ast(), column.name) for column in entity.columns]
    return exp.Select().select(*projections).from_(exp.table_(relation, db=namespace))


class SQLMeshEmitter:
    """RFC 0008 §5.3: one model artifact per silver entity."""

    name = "sqlmesh"

    def capabilities(self) -> TargetCapabilities:
        """Declared support per RFC 0008 §5.1 (amended D6): SCD type 2,
        variant columns, incrementality, audits, and all additivity features."""
        return TargetCapabilities(
            supported=frozenset(
                {
                    Feature.SCD_TYPE_2,
                    Feature.VARIANT_COLUMN,
                    Feature.INCREMENTAL,
                    Feature.AUDITS,
                    Feature.SEMI_ADDITIVE,
                    Feature.NON_ADDITIVE,
                    Feature.CUMULATIVE,
                    Feature.DERIVED_METRIC,
                }
            )
        )

    def emit(self, ir: ProjectIR, ctx: EmitContext) -> tuple[EmittedArtifact, ...]:
        """Lower every entity to a model artifact; artifacts sorted by path,
        content ending in exactly one newline (RFC 0003 §5.5 rule 5)."""
        artifacts: list[EmittedArtifact] = []
        for entity in ir.entities:
            namespace, relation = ctx.naming.relation(entity.name, Layer.SILVER)
            content = _ENVELOPE.render(
                fingerprint=ctx.fingerprint,
                name=f"{namespace}.{relation}",
                kind=_kind_clause(entity),
                grain=", ".join(entity.key),
                partitioned_by=_partitioned_by(entity),
                select=ctx.dialect.render(_entity_select(entity, ctx)),
            )
            artifacts.append(
                EmittedArtifact.create(
                    path=f"models/{namespace}/{relation}.sql",
                    content=content.rstrip("\n") + "\n",
                    kind=ArtifactKind.MODEL,
                )
            )
        return tuple(sorted(artifacts, key=lambda a: a.path))
