-- Generated by bloomery — do not edit.
-- fingerprint: blm1:7feef6f251da705205cdd078d3376e048a4fac5588d6dce4a3c1495a6763acb7
MODEL (
  name gold.dim_date,
  kind FULL,
  grain (date_day)
);

SELECT
  CAST(date_day AS DATE) AS date_day,
  CAST(DATE_TRUNC('MONTH', date_day) AS DATE) AS date_month,
  CAST(DATE_TRUNC('QUARTER', date_day) AS DATE) AS date_quarter,
  CAST(DATE_TRUNC('WEEK', date_day) AS DATE) AS date_week,
  CAST(DATE_TRUNC('YEAR', date_day) AS DATE) AS date_year
FROM GENERATE_SERIES(CAST('2020-01-01' AS DATE), CAST('2030-12-31' AS DATE), INTERVAL '1 DAY') AS date_day(date_day)
