-- Generated by bloomery — do not edit.
-- fingerprint: blm1:c418eb69054fe59e9854583719a1921b90685f43d5405b5455a5c8da570860d1
MODEL (
  name silver.order,
  kind FULL,
  grain (order_id)
);

SELECT
  CAST(JSON_EXTRACT_SCALAR(customer, '$.id') AS VARCHAR) AS customer_id,
  CAST(id AS VARCHAR) AS order_id,
  CAST(ARRAY[] AS ARRAY(VARCHAR)) AS _quality_flags,
  TRUE AS _quality_ok
FROM bronze.shopify__orders
