-- Generated by bloomery — do not edit.
-- fingerprint: blm1:1232e274f07d69510134d0473e7ce8bc055f07fe980bcbe334934d48f033793c
MODEL (
  name silver.order,
  kind FULL,
  grain (order_id)
);

SELECT
  CAST(JSON_EXTRACT_SCALAR(customer, '$.id') AS VARCHAR) AS customer_id,
  CAST(id AS VARCHAR) AS order_id,
  CAST(ARRAY[] AS ARRAY(VARCHAR)) AS _quality_flags,
  TRUE AS _quality_ok
FROM bronze.shopify__orders
