-- Generated by bloomery — do not edit.
-- fingerprint: blm1:f688a883156fd4f1d0f44cd31fcff236fca4685e609f314b201f5fd2668bf205
MODEL (
  name silver.order,
  kind FULL,
  grain (order_id)
);

SELECT
  CAST(JSON_EXTRACT_SCALAR(customer, '$.id') AS VARCHAR) AS customer_id,
  CAST(id AS VARCHAR) AS order_id,
  CAST(ARRAY[] AS ARRAY(VARCHAR)) AS _quality_flags,
  TRUE AS _quality_ok
FROM bronze.shopify__orders
