-- Generated by bloomery — do not edit.
-- fingerprint: blm1:ed93f3d10372fbe4435756beb358e88e3bfbea5d8a8d371053e949d6d9a3b2a7
MODEL (
  name silver.order_item,
  kind INCREMENTAL_BY_TIME_RANGE (time_column order_date),
  grain (order_id, line_no),
  partitioned_by (days(order_date)),
  audits (not_null(columns := (order_date)))
);

SELECT
  CAST(index AS BIGINT) AS line_no,
  CAST(AT_TIMEZONE(
    WITH_TIMEZONE(CAST(REPLACE(created_at, 'T', ' ') AS TIMESTAMP), 'Europe/Paris'),
    'UTC'
  ) AS TIMESTAMP) AS order_date,
  CAST(order_id AS VARCHAR) AS order_id,
  CAST(qty AS BIGINT) AS quantity,
  CAST(CAST(total AS DOUBLE) / qty AS DECIMAL(12, 4)) AS unit_price,
  CAST(ARRAY[] AS ARRAY(VARCHAR)) AS _quality_flags,
  TRUE AS _quality_ok
FROM bronze.shopify__order_lines
