-- Generated by bloomery — do not edit.
-- fingerprint: blm1:27d74d9ec84f7fb3275d59be3456f34dc78125a2575ea14766ecbdce0ba9805f
MODEL (
  name silver.order_item,
  kind INCREMENTAL_BY_TIME_RANGE (time_column order_date),
  grain (order_id, line_no),
  partitioned_by (day(order_date)),
  audits (order_item_key_unique, not_null(columns := (order_date)))
);

SELECT
  CAST(index AS BIGINT) AS line_no,
  CAST(AT_TIMEZONE(
    WITH_TIMEZONE(
      CAST(CASE
        WHEN (
          SUBSTR(CAST(created_at AS VARCHAR), 11) LIKE '%+%'
          OR SUBSTR(CAST(created_at AS VARCHAR), 11) LIKE '%-%'
        )
        OR UPPER(SUBSTR(CAST(created_at AS VARCHAR), 11)) LIKE '%Z%'
        THEN NULL
        ELSE REPLACE(REPLACE(CAST(created_at AS VARCHAR), 'T', ' '), 't', ' ')
      END AS TIMESTAMP),
      'Europe/Paris'
    ),
    'UTC'
  ) AS TIMESTAMP) AS order_date,
  CAST(order_id AS VARCHAR) AS order_id,
  CAST(qty AS BIGINT) AS quantity,
  CAST(CAST(total AS DOUBLE) / qty AS DECIMAL(12, 4)) AS unit_price,
  CAST(ARRAY[] AS ARRAY(VARCHAR)) AS _quality_flags,
  TRUE AS _quality_ok
FROM bronze.shopify__order_lines
