-- Generated by bloomery — do not edit.
-- fingerprint: blm1:4eef78a6fc50bed1084282bbc309bde8f6af4488d3136789a92e0c8a0c6f8d8b
{% macro generate_schema_name(custom_schema_name, node) -%}
{%- if custom_schema_name is none -%}
{{ target.schema }}
{%- else -%}
{{ custom_schema_name | trim }}
{%- endif -%}
{%- endmacro %}
