-- Generated by bloomery — do not edit.
-- fingerprint: blm1:24f1416de6768bcc5570d9b26bde59c137272e4c44af84b7dc3034e683f49c21
{% macro generate_schema_name(custom_schema_name, node) -%}
{%- if custom_schema_name is none -%}
{{ target.schema }}
{%- else -%}
{{ custom_schema_name | trim }}
{%- endif -%}
{%- endmacro %}
