-- Generated by bloomery — do not edit.
-- fingerprint: blm1:c5a47c89f5524efe557e1c860a3cd54b7ba8ca8dd51396796a547b15e7449c06
{% macro generate_schema_name(custom_schema_name, node) -%}
{%- if custom_schema_name is none -%}
{{ target.schema }}
{%- else -%}
{{ custom_schema_name | trim }}
{%- endif -%}
{%- endmacro %}
